### PR TITLE
chat: fix sizing on mobile

### PR DESCRIPTION
**Pull request by tylershuster**
fixes https://github.com/urbit/landscape/issues/230

uses code shamelessly swiped from https://codepen.io/shshaw/pen/c72208b279d750f1ab46b6a45bbd04d7 via https://css-tricks.com/auto-growing-inputs-textareas/

### CODE REVIEW

**Comment by matildepark** [comment]
Looks good, but the font size (and I think line height) doesn't match the chat above. Also the clickable area to start typing is about half the field horizontally.

**Comment by tylershuster** [comment]
Oh, duh. try this.

**Comment by matildepark** [comment]
Clickable area still too small. If you use, say, your right thumb, you won't know why it's unresponsive.

**Comment by tylershuster** [comment]
Ok, that's a grid layout weirdness. I added a listener to watch the parent element for focus

**Review by matildepark — APPROVED** [review]

**Pull request merged**
