### PR TITLE
hoon: refactor unnecessary parameter to bif:by

### PR DESCRIPTION
**Pull request by ashelkovnykov**
Has a corresponding [jet PR in Vere](https://github.com/urbit/vere/pull/439)

### CODE REVIEW

**Comment by ashelkovnykov** [comment]
Tests failing due to crash in `/tests/sys/hoon/map/test-map-bif` because `+bif:by` jet isn't updated in the version of Vere used for testing.

**Review by joemfb — COMMENTED** [review]
This looks right to me, no idea why the value was being checked/manipulated before. This PR needs to target `next/hoon/138` (and we need to sort out the CI situation for these mutual PR staging scenarios).

**Comment by ashelkovnykov** [comment]
@joemfb Rebased on `next/hoon/138`

**Review by belisarius222 — APPROVED** [review]

**Review by joemfb — APPROVED** [review]
this will do

**Comment by belisarius222** [comment]
CI failed, but that's a known issue.  Merging.

**Comment by joemfb** [comment]
I was curious if this interface had been changed at some point, but it was always like this. See e88a091e56e.

**Comment by joemfb** [comment]
And 65dd7cdc10a.

**Pull request merged**
