### PR TITLE
Ignore LICENSE.txt files.

### PR DESCRIPTION
**Pull request by cgyarvin**

### CODE REVIEW

**Comment by juped** [comment]
Is this required for legal reasons? It's a dangerous thing compared to just having the stupid license.txt in the desk.

**Comment by cgyarvin** [comment]
Ignoring it isn't required for legal reasons.  We should have a less hacky
ignoring mechanism.  But ignoring makes sense and having LICENSE.txt is
required.

**Comment by juped** [comment]
It does not make sense to me to ignore it, unless a lawyer said to. The change of distribution channel does not make it any less MIT licensed.

**Comment by cgyarvin** [comment]
But I'm not sure the root of the desk, with a convention-violating name, is
actually where I want it.  It needs to be in the root of the GH repo,
though.  So keeping it out of urbit is postponing a decision in a way.

**Comment by juped** [comment]
I just want to put LICENSE.txt in the repository without increasing the clay/unix hazard level. This is too cutesy.

**Pull request merged**
