### PR TITLE
zuse: kelvin 412

### PR DESCRIPTION
**Pull request by belisarius222**
Draft PR for kelvin 412.  We will merge PRs into this branch as they're ready.  Kelvins further down in the stack, such as Hoon, might change within this branch later in the development process.

### CODE REVIEW

**Comment by yosoyubik** [comment]
PRs merged so far:

- [x] ames: remove num-live from pump-metrics [#6609](https://github.com/urbit/urbit/pull/6609)
- [x] gall: implement local provenance [#6605](https://github.com/urbit/urbit/pull/6605)
- [x] ames: make +abet pure [#6518](https://github.com/urbit/urbit/pull/6518)
- [x] eyre: session identities for all [#6561](https://github.com/urbit/urbit/pull/6561)
- [ ] ?

**Comment by yosoyubik** [comment]
CI is showing an error in %ames (probably the latest state migration?) but I can't reproduce that locally—the migration succeeds. This is with the latest binary `[vere-v2.10-ed86acc-macos-aarch64](https://bootstrap.urbit.org/vere/next/kelvin/412/v2.10-ed86acc/vere-v2.10-ed86acc-macos-aarch64)`

**Comment by yosoyubik** [comment]
Some issue with github's UI right now (I think this get eventually resolved). 

This is missing some commits, but if you go here: https://github.com/urbit/urbit/tree/next/kelvin/412 you can see the latests ones (that finally pass CI; the solid pill had been updated with the conflicting state migration so it was hard to tell where the problem was)

**Comment by belisarius222** [comment]
Note to add to the release checklist for this release: make sure eauth sessions are distinguished from local sessions, especially to ensure that they can't perform reads or writes for which they shouldn't have permissions.

**Comment by yosoyubik** [comment]
I've tested all ames-state migrations to the latest one in this PR (`%16`). Early versions (%8 t %11 can be tried using pill's v17 to v22—some of then don't contain newer versions; v21 and v22 have both amew-state %11)

We don't have pills for later versions, but we can use tagged releases:

- urbit-os-v2.136 for ames-state %12
- urbit-os-v2.139 for ames-state %13 and %14
- urbit-os-v2.142 for ames-state %15

All of these (migrating from one ames-state directly to latest) work, except the migration from ames-state %13. This one is a bit special because it was released at the same time as %14 for urbit-os-v2.139, so chances are that if someone got stuck, they'll be on %14. In any case, I'm looking now at fixing the nest fail from %13 to %16.

**Pull request merged**
