### PR TITLE
Floating point

### LINKED ISSUE #301: Non-double floats are broken
Missing ++rh, ++rs, and ++rq cores, relevant jets, and usage in ++rylh and co. Should be very similar to @rd handling.

### PR DESCRIPTION
**Pull request by max19**
Here are all the changes:
### Basic floating point math
All located in ++fl, using the ++fn structure. Round-to-nearest (ties away from zero) is not implemented because MPFR does not support it, and MPFR may be used to jet in the future. It would be trivial to implement, though. Jets at the moment bail on massive exponents and precision, but at values that nobody reasonable would use.

### IEEE 754
All except half-precision jetted with SoftFloat. Half-precision does not include any math, as it is a storage format, so people are expected to convert to single-precision and do calculations there (also SoftFloat doesn't provide any functionality for it).

### Printing/parsing
Printing is done with the assistance of ++drg, the famous Dragon4 algorithm, which finds the best base 10 representation. ++drg could be changed to convert directly to a string, which would be a bit faster, but would fit less elegantly with the rest of the printing mechanisms. Parsing is just done with mathematical operations, doesn't seem too slow.

### More integer math
Square root, simultaneous divide/remainder, power. I heard hoon.hoon was getting reorganized in the near future, so just stuck them on the end of chapter 2c. Without this, square root is painfully slow.

### Elementary functions
need to be cleaned up, and some algorithms fixed; will be placed in a library.

### u3r_words and u3r_bytes
implemented using memcpy. I don't see any problems with them, but am not totally familiar with c3, so there may be something I missed.

This opens the door to vector, matrix, complex, ball arithmetic...

closes #301

### CODE REVIEW

**Comment by galenwp** [comment]
Wow.

**Comment by ault011** [comment]
Awesome!

**Comment by philipcmonk** [comment]
This looks seriously awesome. I'm on vacation at the moment, but I'll have
to check this stuff out as soon as I can. Floating point is something we've
wanted for a long time.

**Comment by juped** [comment]
Merged into test for some testing.

**Comment by galenwp** [comment]
I get

```
ld: 275 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/urbit] Error 1
```

when I try to build test now. Something I'm missing?

**Comment by galenwp** [comment]
Also get lots of

```
duplicate symbol _softfloat_shortShiftRightJam64 in:
    outside/softfloat-3/build/Linux-386-GCC/softfloat.a(f128M_add.o)
    outside/softfloat-3/build/Linux-386-GCC/softfloat.a(s_shiftLeftM.o)
```

and similar

**Comment by juped** [comment]
Galen's issues are fixed in 966adc3 - it's a C89 vs C99 thing, and clang defaults to C99.

**Comment by galenwp** [comment]
Yep: sorry. Should have updated this. Thanks to @juped for the fix. I'd defer to @philipcmonk or @cgyarvin for the merge to master. But test is on its way to master anyway...

**Comment by cgyarvin** [comment]
Thanks, Raymond.  Max, I apologize for not having looked over this patch
yet - it obviously demands serious attention!

**Comment by max19** [comment]
I'm undoubtedly going to notice stuff I missed earlier and make another pull request eventually, but can't find anything particularly bad right now. The ++drg and ++lug jets could probably be organized better, for instance, and ++frd isn't necessary any more for the square root...

**Comment by max19** [comment]
Something I totally forgot to mention: the stack traces on some of the arms, %rd-fail %rq-fail etc, are necessary because the jet bindings get very confused without them! I suppose because the batteries hash the same.

**Comment by cgyarvin** [comment]
That's exactly why.

BTW, while the code looks very nice, one thing I'd really like to see in a
patch of this magnitude (which has been merged into the test branch, so I'd
edit it there) is a level of documentation, internal, external or both,
vaguely consistent with the level of effort you've already put in :-)  For
instance, although this rule is violated by us in various places in
hoon.hoon and elsewhere, I really think the standard should be a :: for
every ++, and a decent little block comment for every |_.

**Comment by max19** [comment]
Pull requested

**Pull request merged**
