### PR TITLE
Fix +to-wain:format null byte handling

### LINKED ISSUE #1755: Null character in a file causes error during |commit
<details><summary>Stack trace:</summary>

```
> |commit %home
>=
worker_send_replace 1730782 crud
%into event failed:
bail: exit
%failed-jack
[%lal %c %f]
[%failed-take %c]
[%failed-swim %c %f [~ /commit/home/casts]]
[%swim-take-vane %c %made]
[%failed-slym-in %c]
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[4.421 3].[4.594 5]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[4.422 3].[4.594 5]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[4.423 5].[4.427 15]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[4.424 5].[4.427 15]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[4.425 7].[4.426 35]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[4.426 7].[4.426 35]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[4.426 12].[4.426 35]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[3.011 5].[3.024 7]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[3.012 5].[3.024 7]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[3.013 5].[3.024 7]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[3.015 5].[3.024 7]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[3.017 5].[3.024 7]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[3.018 7].[3.018 74]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[430 7].[465 9]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[433 7].[465 9]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[436 7].[465 9]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[444 7].[465 9]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[448 7].[465 9]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[454 7].[465 9]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[461 9].[464 11]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[430 7].[465 9]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[433 7].[465 9]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[433 20].[433 47]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[385 5].[394 7]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[386 7].[386 18]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[385 5].[394 7]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[386 7].[386 18]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[385 5].[394 7]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[386 7].[386 18]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[888 9].[912 11]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[888 13].[893 35]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[889 13].[893 35]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[889 23].[889 54]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[2.187 5].[2.188 57]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[2.188 5].[2.188 57]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[2.178 5].[2.178 40]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[2.178 27].[2.178 39]>
/~zod/home/0/mar/txt/hoon:<[14 42].[14 55]>
ford: %call execution failed:
ford: %cast failed to call +grab arm in /~zod/home/0/mar/txt/hoon:
ford: %cast failed while trying to cast from mime to txt:
ford: failed to %cast
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[2.171 44].[2.171 54]>
%ford-fail
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[2.171 30].[2.171 55]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[2.243 19].[2.243 53]>
/~zod/home/~2019.8.28..19.07.13..2d9b/sys/vane/clay:<[2.243 16].[2.243 53]>
```
</details>

To reproduce, just `|commit` a file containing a null character.
For example:

```
$ echo -e '\0000' > zod/home/null.txt
$ urbit zod
[...]
> |commit %home
[error]
```

### PR DESCRIPTION
**Pull request by pkova**
Fixes #1755

### CODE REVIEW

**Comment by joemfb** [comment]
@jtobin, I'm not sure that this change is correct. Null bytes are not valid in `@t`. If `+to-wain`/`+of-wain` is construed as `@t -> (list @t)` and vice versa, this change would be wrong. If they're more general transformation of arbitrary atoms, then it's more defensible.

@pkova, what was the original motivation for this?

**Comment by jtobin** [comment]
On Mon, Jan 27, 2020 at 10:24:46AM -0800, Joe Bryan wrote:
> If `+to-wain`/`+of-wain` is construed as `@t -> (list @t)` and vice
> versa, this change would be wrong. If they're more general
> transformation of arbitrary atoms, then it's more defensible.

Ah, apologies for missing that.  This is an instance of me looking
over the diff and thinking "ok, this looks correct," but missing that
crucial Urbit context.  Not the first time, probably not the last..

**Comment by pkova** [comment]
Just saw the issue and wanted to fix it. Too much coding not enough thinking I guess!

The behavior below made me think that `@t` supports null bytes, though.

```
=('hi' 'hi\00')
%.y
=('hi' 'hi\00\00')
%.y
=('hi' 'h\00i')
%.n
```

**Comment by joemfb** [comment]
@jtobin, this also should not have been a mere OTA update, is it includes changes to a jet. We've pushed a jet mismatch ...

@pkova, funny thing about little-endian atomic encoding: it's impossible to represent trailing null bytes. A byte array encoded atomically is arguably of infinite length:

```
> `@ux`'hi'
0x6968
> `@ux`'hi\00'
0x6968
> `@ux`'hi\00\00'
0x6968
> `@ux`'hi\00\00hi'
0x6968.0000.6968
```

What's more, atom auras are a kind of "soft" type system. They can be validated, but *cannot* be enforced:

```
> `@ux`31
0x1f
> '\01f'
'\01f'
> `@t`31
'\1f'
> ((sane %t) '\01f')
%.n
```

**Pull request merged**
