### PR TITLE
Exit on SIGTSTP.

### PR DESCRIPTION
**Pull request by cgyarvin**

### CODE REVIEW

**Comment by juped** [comment]
You can have it if you admit that it's a bespoke keybinding for exactly one (1) person. From best to worst:

1. Do the right thing (this can be accomplished, because we can take note that we're suspending from terminal, send ourself SIGSTOP, and then redraw the prompt line)
2. Do nothing
3. Bespoke keybindings for exactly one (1) person that don't cause bad states
4. Current behavior that causes bad states

So it's not exactly *worse*, but it's not *sub specie aeternitatis*.

**Comment by cgyarvin** [comment]
I admit that it's not sub specie aeternatis!  It's sub something though...

**Comment by juped** [comment]
I will also demand a personal keybinding of my own. It will be chosen more prosocially, of course. Perhaps the original ^D functionality (fixing #452). After all, we have all these multifarious other ways of killing vere directly from the keyboard.

**Comment by galenwp** [comment]
To make this easier I'll just adopt whatever keybinding we just implemented for one person.

**Comment by juped** [comment]
(Not merged yet, not because I hate it so much (the ^D/#452 thing is what I care about), but because I'm waiting for @ohAitch to say whether he actually wants his personal keybinding or not.)

**Comment by ohAitch** [comment]
I am fine with this solution, my main issue with IGN on SIGSTP was a
utilitarian "okay then how do I get to a prompt whence I can kill9 in quick
order", which this should neatly make redundant.

**Comment by juped** [comment]
That is incredibly unprincipled of you!

I'm hoping a contributor who knows a bit more about this stuff than I do will show up to make suspend actually work right. I will be making a help-wanted issue about it.

**Comment by ohAitch** [comment]
That would definitely also be my preferred outcome.

Until then tho, my support for Unix semantics extends only insofar as my
workflow relies on these semantics, if they were universally perfect we
wouldn't be building urbit in the first place :P

**Comment by juped** [comment]
Yeah, but this amounts to breaking something because of your muscle memory. It's only permissible at all because not running *is* our suspended state, thanks to the glories of repeatable computing.

Merge incoming!

**Comment by ohAitch** [comment]
Oh sure, it helps that it would be ~semantically~ equivalent(kind of, when
you ^Z a web server it doesn't usually break all connections).

Though I protest that it's not a matter of specifically muscle memory, but
rather expectation that "computer, drop everything" is a primitive
operation accessible /somehow/. As mentioned earlier, if ^C^U^D worked
reliably I'd be as unprincipled about the "benign" just-drop-it option, and
switch over to that.

**Comment by cgyarvin** [comment]
I agree.

**Comment by juped** [comment]
^\

**Comment by ohAitch** [comment]
Blocks prompt for multiple seconds, not good enough. You can likewise wait
for ^C to stop printing backtrace.

**Comment by juped** [comment]
Turn off or shrink your core dump size? I don't like that urbit doesn't make me a consolation coffee every time it bails, myself, but I don't make it a workflow requirement.

I mean, is it an urbit prompt you want to escape to, or a unix prompt? I'm getting mixed signals...

**Comment by ohAitch** [comment]
I want to escape to a Unix prompt; as a separate operation from "exit
slowly, saving debug information", which itself is a useful but distinct
operation.

For that matter, the common operation here is "restart urbit", because the
external-to-arvo parts of vere have entered a bad state; and the most
common example of /that/ is lines being printed at a snail's pace because
that subsystem is broken and uninterruptible. (Apparently unfiled whoops;
introduced by a4abd165, apparently something relies on ~+)

**Comment by juped** [comment]
Yeah, I can understand why one would want to suspend to get a free unix prompt. (Though I recommend saving up and buying a copy of tmux sometime.) I can't understand why your core dumps apparently take longer to save than it takes to suspend and `kill %1`. Perhaps that should also be an issue, though I think I already filed it for BSD.

**Comment by ohAitch** [comment]
I mean, I run with multiple terminal tabs, I could just switch between them, but I want my history and stuff to still be there. For the "restart urbit" case in particular, the command used to restart it previously with all relevant flags is relevant, and in this manner easily available by ^P; also, I want that to happen /after/ the current process exits, and for its scrollback history to remain roughly contiguous. (now-filed #625 relevant)

All of this is of course somewhat tangential to the ultimate concern that exiting a process should not take multiple seconds ^-^

**Comment by philipcmonk** [comment]
I should point out that core dumping on linux machines (or at least DO
droplets) takes less than half a second.  It's seems to be a mac-specific
thing where core dumps take forever.

**Comment by juped** [comment]
If it's anything like FreeBSD (which it is, as we all know...) it's dumping 2 gigs of core. (Linux memory management is infamously optimistic and is only lying that it's allocated 2 gigs, other kernels work differently.) That's what I'm referring to above, which I think I already made an issue (because I couldn't stop it from dumping 2 gigs of core every time it bailed, which made debugging the various BSD crashes somewhat difficult).

**Comment by philipcmonk** [comment]
@loves his 28M core files, even if he's confused how that even works

**Comment by ohAitch** [comment]
Request to revert until #703 is fixed.

**Comment by juped** [comment]
Nope, sorry, it's an integral part of my workflow now :)
All deliberate bugs become features!

(Request to revert permanently. Reverting instantly fixes #703, and we can't get into an infinite revert and re-revert loop, now can we? Better to just figure out how to ask dill.c or whatever to do a redraw.)

**Comment by cgyarvin** [comment]
Don't do anything, I'll have an actual fix for this shortly.

**Comment by juped** [comment]
An actual "actual fix"?

**Comment by cgyarvin** [comment]
There's a spinner mutex unlock that crashes for some reason when we're
trying to exit in u3_term_io_exit().  Not sure why this happens, but in
practice we're quitting the process anyway, so I just ifdefed out the
cleanup code.

**Pull request merged**
