### PR TITLE
Remove %indirect

### PR DESCRIPTION
**Pull request by cahiggins**
I don't know %clay very well, so I probably screwed up somewhere. If anything is wrong, point me in the right direction and I'll be more than happy to fix any of my mistakes.

### CODE REVIEW

**Comment by juped** [comment]
It's removed in Philip's clay work - is there a specific reason to make that change out of context?

**Comment by cahiggins** [comment]
No, I suppose not. I wasn't aware it was already fixed. I'll go ahead and
close the request.

**Comment by cgyarvin** [comment]
Sorry for the confusion!  I'm afraid these things happen, but we could be more transparent...

**Comment by juped** [comment]
Feel free to check his branch and see if you got it right... :)

**Comment by philipcmonk** [comment]
Yes, my change is essentially identical: 

https://github.com/philipcmonk/urbit/commit/0de881ae103df0d988c778f5f03edf6f477e7382

**Comment by cahiggins** [comment]
Well, happy to know that I did it correctly. Time to find something useful
to work on.

**Pull request closed without merging**
