### PR TITLE
graph-store: run update log in correct order

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
tapping an ordered map returns a list with the smallest keys first.
However, graph-store's update-log is defined backwards, such that the
list will have the most recent updates in the front of the list. We
therefore flop the update log before iterating over it, in order to
process the updates in the order they occurred. 

A partial mitigation for #4133 and probably a lower risk deployment that #4156

### CODE REVIEW

**Comment by tacryt-socryp** [comment]
What? We should just change ordered-map to use the comparator in the tap function. This is an ordered-map level change.

**Comment by tacryt-socryp** [comment]
If you add a TODO to switch out tap:ordered-map for a generic implementation, we can push this out as is.

**Comment by liam-fitzgerald** [comment]
It already does use the comparator which is the issue. I don't think it's valid to use any other comparator for ordering the list, maybe we should just add bap:orm ie backwards tap

**Comment by tacryt-socryp** [comment]
Oh, I understand now. Yes, I like the idea of making a backward order tap. It could be far more efficient than flopping. Could you just add a TODO comment here to revisit that, and we can merge as is?

**Review by tacryt-socryp — APPROVED** [review]

**Comment by matildepark** [comment]
Is this superseded by the #4156 merge?

**Comment by tacryt-socryp** [comment]
Not superceded, but the implementation of this (using +tap, then +flop) as opposed to using +bap should be updated. We should use +bap now.

**Comment by matildepark** [comment]
Which would mean this would target next-sys too.

**Comment by tacryt-socryp** [comment]
Nope, this can target master. The addition of +bap is already on livenet, it just isn't being used yet.

**Pull request merged**
