### PR TITLE
armhf/debian maintainer patchset

### PR DESCRIPTION
**Pull request by yebyen**
Discuss

### CODE REVIEW

**Comment by juped** [comment]
How on earth did -msse3 sneak back in there?

**Comment by juped** [comment]
Also, I don't think we're going to shrink the loom on all platforms, at least not until the Performance Crusade is at the gates of Jerusalem. The rest is fine, though.

**Comment by max19** [comment]
I never removed -msse3, just tried to make it unnecessary, though apparently missed an include

**Comment by juped** [comment]
It should be removable. Platform-independent correctness is the current goal.

**Comment by juped** [comment]
I humbly submit this diff:
```
diff --git a/Makefile b/Makefile
index 014516e..58a8ec3 100644
--- a/Makefile
+++ b/Makefile
@@ -73,7 +73,7 @@ MDEFINES=-DU3_OS_$(OS) -DU3_OS_ENDIAN_$(ENDIAN) -D U3_LIB=\"$(LIB)\"
 # NOTFORCHECKIN - restore -O3
 #      -DGHETTO \
 #   -DHUSH
-CFLAGS= $(COSFLAGS) -O3 -msse3 -ffast-math \
+CFLAGS= $(COSFLAGS) -O3 -ffast-math \
        -funsigned-char \
        -I/usr/local/include \
        -I/opt/local/include \
@@ -473,6 +473,7 @@ debinstall:

 clean:
        $(RM) $(VERE_OFILES) $(BIN)/urbit urbit.pkg $(VERE_DFILES)
+       $(RM) -r debian/files debian/urbit*

 # 'make distclean all -jn' ∀ n>1 still does not work because it is possible
 # Make will attempt to build urbit while it is also cleaning urbit..
diff --git a/outside/scrypt/crypto_scrypt.h b/outside/scrypt/crypto_scrypt.h
index e2638c5..39cad5c 100644
--- a/outside/scrypt/crypto_scrypt.h
+++ b/outside/scrypt/crypto_scrypt.h
@@ -30,7 +30,6 @@
 #define _CRYPTO_SCRYPT_H_

 #include <stdint.h>
-#include <emmintrin.h>

 void smix(uint8_t *, size_t, uint64_t, uint32_t *, uint32_t *);
 void PBKDF2_SHA256(const uint8_t *, size_t, const uint8_t *, size_t,
```
It doesn't seem to break scrypt, because scrypt doesn't seem to work at all for me...

**Comment by max19** [comment]
juped: what happens with (hsh:scr '' '' 16 1 1 64) ?

**Comment by juped** [comment]
That works - is there some requirement that the parameters be powers of 2? Waiting on yebyen's remarks, then. If there's some way to detect the architecture in gmake, I wouldn't be averse to defining the loom smaller on arm in our makefile.

**Comment by max19** [comment]
The parameter N (CPU/Memory cost) must be a power of two; I'll add a block comment at some point.

**Comment by juped** [comment]
It's actually commented, no worries. If it must be a power of two, presumably nonnegative, then I would have just made the exponent into the parameter...

**Comment by yebyen** [comment]
I think we have already documentation that says another way to make loom mappable on 32-bit platforms (other than changing loom bits).  That's just what I do myself, I don't personally use a lot of loom.  I just wanted to make this patchset a little more visible than hidden somewhere in my urbit-deb maintainer repo where probably nobody will ever find it.

Just removing the emmintrim include and other changes in @juped diff look good to me, I'd be fine with closing in favor of that patch.

**Comment by juped** [comment]
I've done a bit of packaging/porting myself, and it's definitely always best when upstream integrates as much as possible...

**Pull request closed without merging**
