### PR TITLE
observe-hook: add ability to warm static mark conversions

### PR DESCRIPTION
**Pull request by tacryt-socryp**
Simplified our other apps' caching strategies and consolidated them into a general purpose utility in `%observe-hook`.  The previous caching strategy was fragile when marks were changed. Performance is approximately the same.

### CODE REVIEW

**Review by liam-fitzgerald — APPROVED** [review]
LGTM! Aren't we reincurring the scry boundary by not saving the mark conversion in the state of the app?

**Comment by tacryt-socryp** [comment]
The scry boundary is 0.5ms now, whereas when we originally were trying to avoid the scry boundary, it was 7-10ms.

**Comment by tacryt-socryp** [comment]
I need to fix one thing in the `+on-load` of this, so please hold. Will merge when ready.

**Comment by tacryt-socryp** [comment]
Tested on-load. All good.

**Pull request merged**
