### PR TITLE
Runtime overflows

### PR DESCRIPTION
**Pull request by frodwith**
Resolves issue #936.

### CODE REVIEW

**Comment by belisarius222** [comment]
Looks good to me.

**Comment by cgyarvin** [comment]
This is a lot of delta.  I can haz explanation pls?

**Comment by frodwith** [comment]
There was a memory bug in the jam jet, and (probably unrelatedly) some problems running the profiler after the unifying equality change. After resolving these, performance returns to normal (slightly slower than the previous jam due to cap manipulation, but nothing wild).

**Comment by cgyarvin** [comment]
Are we totally convinced that this explains the behavior that made us have to revert? Just want a confirmation of faith :-)

**Comment by frodwith** [comment]
Totally? No. I was able to verify the bad performance with those bugs, and acceptable performance after fixing them. I don't have a good story for why the memory bug was making it slower, other than that messing up refcounts in vere causes all sorts of interesting behavior.

**Comment by belisarius222** [comment]
@keatondunsford is going to run some tests with this code right now.

**Comment by cgyarvin** [comment]
Great, I’m satisfied on both counts.

**Comment by keatondunsford** [comment]
Running a comet with this commit's Vere, then visiting `comet-name.urbit.org` in my browser -- which broke in #936 -- now seems to work. So, insofar as that works, looks like this code can be merged.

**Comment by joemfb** [comment]
For posterity, here's something close to the true delta: https://github.com/urbit/urbit/compare/3f782dc00d10731d23ff0817bfdec88b6dfbcc02...67d3460a910678fbb7b0e265774f5989ee767573

**Comment by ohAitch** [comment]
I was going with
https://github.com/urbit/urbit/pull/941/files/ac65967fa057ee38cd9cdc64c6324d3b9a4229f8,
the three commits before the "revert revert rebase merge" integration

**Comment by keatondunsford** [comment]
@frodwith Hm, actually, I'm having trouble about 50% of the time authenticating running this new code. I.e. even though this code works fast enough sometimes, it might still be _too_ slow to call issue #936 completely fixed.

To clarify the issue: on commit 67d3460a910678fbb7b0e265774f5989ee767573, when my ship takes too long to jam and encrypt data to send to ~marzod per our current `ship.urbit.org` proxying "system", my web session 504s. Sometimes, though, the computation completes just fast enough so that I can load my `tonlur-sarret.urbit.org` login/`+code` page to auth into the Fora ship. 

However, running the previous Vere binary that was working, 4db7eb4d609b04c5399e9c25a91f8f8b827ed7b2 per #936, fixes this issue, and authentication works as normal.

So, I'm going to reopen issue #936. We may want to consider reverting the latest merge 67d3460a910678fbb7b0e265774f5989ee767573.

cc @belisarius222 @cgyarvin

**Comment by keatondunsford** [comment]
_Additional note_: I saw some ships in `/urbit-meta` reporting Fora auth 504s earlier today. I originally thought they were referring to the "5-0-Fora" class of 504s. But now that I've hit this issue, they may have been referring to this class of auth 504s as a result of running this latest master Vere code.

So, the network is currently affected by this.

**Comment by cgyarvin** [comment]
I think Keaton is right and we should revert again.  I'll talk to Paul
about how we can test this more thoroughly.

**Pull request merged**
