### PR TITLE
btc-wallet: Port btc-wallet to typescript.

### PR DESCRIPTION
**Pull request by finned-palmer**
This is 99% done, still checking on a few things before I call it done.

cc @timlucmiptev @ixv @tacryt-socryp

### CODE REVIEW

**Comment by timlucmiptev** [comment]
I can't comment here too much--if it works, we're good.

**Comment by finned-palmer** [comment]
It's good to go on my end.

**Comment by finned-palmer** [comment]
Any chance that @ixv or someone could review this? It will be updated after my other PR (PSBTs) is merged, fyi.

**Comment by ixv** [comment]
conflicts might be due to merging the previous PR, or from merging master into release/bitcoin-wallet, you might need to rebase this on release/bitcoin-wallet

**Comment by finned-palmer** [comment]
> conflicts might be due to merging the previous PR, or from merging master into release/bitcoin-wallet, you might need to rebase this on release/bitcoin-wallet

yep, that's what I was referring to in my previous comment. will update accordingly.

**Comment by finned-palmer** [comment]
Fixed conflicts, @ixv.

**Review by ixv — APPROVED** [review]

**Pull request merged**
