### PR TITLE
chat: jimmy's visualfix omnibus

### PR DESCRIPTION
**Pull request by jamesacklin**
Some very fun visual updates to chat, courtesy of @jyng.

- Introduces click-to-copy a ship's name in the mini-profile overlay.
- Swaps to the new Messages icon in the status bar and in Leap.
- Switches the cursor to `pointer` for Attachments and Dojo in the Chat input field.
- Swaps the message loading placeholder background to `washedGray` and rounds the box corners by 4px.
- Presents external images in chat with no gray border or padding, and introduces a 4px border-radius.
- When hovering over an external image, surfaces a small visual cue in the upper-right of the image.
- When images are in a normal chat flow context, makes the entire image, but when an image is transcluded, limits interactivity to this small visual cue. (This is in anticipation of clicking the entire transuded block to jump to its context, but allowing some external actions.)

Non-transcluded image appearance, hovered:
image

Transcluded image appearance, hovered:
image

### CODE REVIEW

**Comment by matildepark** [comment]
@jyng @g-a-v-i-n note the target branch here is itself blocked on https://github.com/urbit/indigo-react/issues/101

**Review by urcades — APPROVED** [review]
Adding small clarification to the last bullet for anyone reading:

> When images are in a normal chat flow context, makes the entire image **clickable**, but when an image is transcluded, limits interactivity to this small visual cue. (This is in anticipation of clicking the entire transuded block to jump to its context, but allowing some external actions.)

This is feeling really good, but did catch the messed up spinner @matildepark mentioned, which is blocking this PR.

**Comment by urcades** [comment]
Actually, I take it back there's ONE MORE THING related to this item:

> Switches the cursor to pointer for Attachments and Dojo in the Chat input field.

Since this is already being tweaked, I'd like to humbly request that we perform a very simple restyling of how these icons are placed within the input field. Right now they are a bit cramped:

Screen Shot 2021-04-21 at 6 27 11 PM

And the placement of the "Execute Hoon" button is on the right edge, which confuses people often (because it vaguely looks like a "send" button).

Rather, I think we should move the "Attach" to the rightmost slot, and pad out the items as indicated in the following video:

https://user-images.githubusercontent.com/1195363/115629365-36ba2c00-a2d0-11eb-9318-8e8cbdd1550d.mp4

If we could make these small edits, I think chat would feel increasingly put together.

**Comment by matildepark** [comment]
See also https://github.com/urbit/landscape/issues/777

**Comment by matildepark** [comment]
@urcades We could probably slip in a send button on mobile devices, if you want

**Comment by urcades** [comment]
This would be excellent — we don't need to overthink this! It could be as simple as a text button added to the right side of the icons, given the same approximate amount of tap space.

Screen Shot 2021-04-22 at 5 38 24 PM

On the other hand, if y'all are OK with pushing this a bit, into a much better space, I have something of a more involved spec here:

Screen Shot 2021-04-22 at 5 39 23 PM

**Comment by g-a-v-i-n** [comment]
Should be resolved now

**Comment by matildepark** [comment]
Unblocked, thanks @g-a-v-i-n. I’ll review but @urcades has some feedback to address first I think.

**Comment by jamesacklin** [comment]
@urcades I was happy to push the send button in the ChatInput a bit, for your review. Forgive the Chrome device simulator here, but it only appears on mobile as desired, 

No input, not focused:
image

No input, field focused (cursor blinks here, you'll have to trust me):
image

Some input, field focused:
image

Some input, field blur:
image

**Review by matildepark — CHANGES_REQUESTED** [review]
We need to prevent the avatar shrinking.

image


Kinda loud — 
image

The arrow pops in and out in Chrome dev tools for me, presumably on hot reload, how is it being prompted?

**Comment by jamesacklin** [comment]
> We need to prevent the avatar shrinking.
Done.

> Kinda loud —
"I found it like that, I swear." Not sure how to fix this, since we save the input to local storage if you navigate away and come back to that channel, so the unmount function is kind of critical here. @liam-fitzgerald know how this works?

> The arrow pops in and out in Chrome dev tools for me, presumably on hot reload, how is it being prompted?
Currently shown and hidden in tandem with the `chat-editor` focus; there's no real good way to detect if the soft keyboard is visible or not, so I figured :focus was a good-enough proxy.

**Review by matildepark — APPROVED** [review]
Fair enough, out of scope.

**Comment by tacryt-socryp** [comment]
Feeling like my text input is really squeezed by these icons on iOS now

**Comment by matildepark** [comment]
https://github.com/urbit/landscape/issues/240 is probably exacerbated, it's likely calcing `100% - 25px` or whatever where 100% isn't the full viewport width.

**Pull request merged**
