### PR TITLE
adds AddressSanitizer to CI build

### PR DESCRIPTION
**Pull request by joemfb**
There's many other sanitizers, it'd probably be worth adding them as well (this is pretty loud `-fsanitize=address,undefined` ...)

### CODE REVIEW

**Comment by joemfb** [comment]
A debug build should give more info (`make SANITIZE=YES DEBUG=yes`), but I wasn't sure if that should be enabled by default.

I'm surprised to see this error, though -- I've been running this pretty heavily on OS X. I'll see if I can reproduce on an Ubuntu VM. Even though the sanitizer *should* be the same, clang vs gcc might be relevant too...

**Comment by ohAitch** [comment]
huh, *on OS X* I get `clang: error: unsupported argument 'address' to option 'fsanitize='`, do I need to update clang?

**Comment by ohAitch** [comment]
(Also the [debug travis build](https://travis-ci.org/urbit/urbit/builds/327962992) can't find `u3qfl_bunt`)

**Comment by joemfb** [comment]
Here's what I have:

```
$ clang --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I'm running 10.11 El Capitan, and haven't done anything special with llvm (as far as I know).

Per [wikipedia](https://en.wikipedia.org/wiki/AddressSanitizer), ASan was added to clang 3.1 and gcc 4.8. I'm not sure which OS X versions had which versions of clang -- or when gcc starting pointing to clang.

In defense of the travis debug build, *I* can't find u3qfl_bunt either. How is that working anywhere?

**Comment by ohAitch** [comment]
```
➤ clang -v
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```
this looks >3.1?

And I see it just fine in `include/jets/q.h`, idk what DEBUG is doing weirdly

**Comment by joemfb** [comment]
One more difference to note, I think clang is being used as the linker locally, while travis is using GNU ld.

**Comment by joemfb** [comment]
I've duplicated both issues on Ubuntu 16: debug builds can't find `u3qfl_bunt` (regardless of this PR), and running with `-fsanitize=address` immediately aborts with `SEGV on unknown address`.

I happened to try on an old branch (master on my clone), and did not have the same issue with debug builds. So the problem is in the Makefile changes since a05a42405333 (for whatever that's worth ...)

**Comment by joemfb** [comment]
As for the ASan stuff, I'm out of my depth. It works on my machine, dammit!

I'll keep poking at it.

**Comment by joemfb** [comment]
Here's some more details from my Ubuntu VM.

I switched to llvm (since I know the toolchain better), and that resolved the failed debug build issue.

I still get an immediate unknown-crash: 

```
ubuntu@ip-172-26-5-145:~/urbit-dev/urbit$ bin/urbit -FI zod zod
~
urbit 0.5.1
urbit: home is zod
core limit: Invalid argument
loom: mapped 2048MB
=================================================================
==10846==ERROR: AddressSanitizer: unknown-crash on address 0x0000b5ffc000 at pc 0x00000049224f bp 0x7ffe5e865920 sp 0x7ffe5e8650d0
WRITE of size 16384 at 0x0000b5ffc000 thread T0
    #0 0x49224e  (/home/ubuntu/urbit-dev/urbit/bin/urbit+0x49224e)
    #1 0x53df40  (/home/ubuntu/urbit-dev/urbit/bin/urbit+0x53df40)
    #2 0x53cbf1  (/home/ubuntu/urbit-dev/urbit/bin/urbit+0x53cbf1)
    #3 0x55f233  (/home/ubuntu/urbit-dev/urbit/bin/urbit+0x55f233)
    #4 0x61ab20  (/home/ubuntu/urbit-dev/urbit/bin/urbit+0x61ab20)
    #5 0x7f377a48382f  (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #6 0x41e0a8  (/home/ubuntu/urbit-dev/urbit/bin/urbit+0x41e0a8)

Address 0x0000b5ffc000 is located in the shadow gap area.
SUMMARY: AddressSanitizer: unknown-crash (/home/ubuntu/urbit-dev/urbit/bin/urbit+0x49224e) 
==10846==ABORTING
```

Running in lldb, I'm able to get these details and backtrace:

```
$ lldb-5.0 -- bin/urbit -FI zod zod                                                                                                                          
(lldb) target create "bin/urbit"
Current executable set to 'bin/urbit' (x86_64).
(lldb) settings set -- target.run-args  "-FI" "zod" "zod"
(lldb) process launch
Process 10858 launched: '/home/ubuntu/urbit-dev/urbit/bin/urbit' (x86_64)
~
urbit 0.5.1
urbit: home is zod
core limit: Invalid argument
loom: mapped 2048MB
=================================================================
==10858==ERROR: AddressSanitizer: unknown-crash on address 0x0000b5ffc000 at pc 0x00000049224f bp 0x7fffffffd540 sp 0x7fffffffccf0
WRITE of size 16384 at 0x0000b5ffc000 thread T0
    #0 0x49224e  (/home/ubuntu/urbit-dev/urbit/bin/urbit+0x49224e)
    #1 0x53df40  (/home/ubuntu/urbit-dev/urbit/bin/urbit+0x53df40)
    #2 0x53cbf1  (/home/ubuntu/urbit-dev/urbit/bin/urbit+0x53cbf1)
    #3 0x55f233  (/home/ubuntu/urbit-dev/urbit/bin/urbit+0x55f233)
    #4 0x61ab20  (/home/ubuntu/urbit-dev/urbit/bin/urbit+0x61ab20)
    #5 0x7ffff597a82f  (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #6 0x41e0a8  (/home/ubuntu/urbit-dev/urbit/bin/urbit+0x41e0a8)

Address 0x0000b5ffc000 is located in the shadow gap area.
SUMMARY: AddressSanitizer: unknown-crash (/home/ubuntu/urbit-dev/urbit/bin/urbit+0x49224e) 
==10858==ABORTING
(lldb) AddressSanitizer report breakpoint hit. Use 'thread info -s' to get extended information about the report.
Process 10858 stopped
* thread #1, name = 'urbit', stop reason = Invalid memory access
    frame #0: 0x00000000004e9090 urbit`__asan::AsanDie()
urbit`__asan::AsanDie:
->  0x4e9090 <+0>:  movl   $0x1, %eax
    0x4e9095 <+5>:  lock   
    0x4e9096 <+6>:  xaddl  %eax, 0x6cf777(%rip)      ; __asan::AsanDie()::num_calls
    0x4e909d <+13>: testl  %eax, %eax
(lldb) bt
* thread #1, name = 'urbit', stop reason = Invalid memory access
  * frame #0: 0x00000000004e9090 urbit`__asan::AsanDie()
    frame #1: 0x000000000050504d urbit`__sanitizer::Die() + 45
    frame #2: 0x00000000004e4a38 urbit`__asan::ReportGenericError(unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long, unsigned int, bool) (.part.11) + 1288
    frame #3: 0x000000000049226d urbit`__interceptor_read + 941
    frame #4: 0x000000000053df41 urbit`_ce_image_blit(img_u=0x0000000001697738, ptr_w=0x00000000b5ffc000, stp_ws=-4096) at events.c:697
    frame #5: 0x000000000053cbf2 urbit`u3e_live(nuu_o='\x01', dir_c="zod") at events.c:879
    frame #6: 0x000000000055f234 urbit`u3m_boot(nuu_o='\x01', bug_o='\x01', dir_c="zod", pil_c=0x0000000000000000, url_c=0x0000000000000000, arv_c=0x0000000000000000) at manage.c:1657
    frame #7: 0x000000000061ab21 urbit`main(argc=4, argv=0x00007fffffffe4a8) at main.c:591
    frame #8: 0x00007ffff597a830 libc.so.6`__libc_start_main + 240
    frame #9: 0x000000000041e0a9 urbit`_start + 41
(lldb) thread list
Process 10858 stopped
* thread #1: tid = 10858, 0x00000000004e9090 urbit`__asan::AsanDie(), name = 'urbit', stop reason = Invalid memory access
(lldb) thread info -s
thread #1: tid = 10858, 0x00000000004e9090 urbit`__asan::AsanDie(), name = 'urbit', stop reason = Invalid memory access

{
  "access_size" : 16384,
  "access_type" : 1,
  "address" : 3053436928,
  "description" : "unknown-crash",
  "instrumentation_class" : "AddressSanitizer",
  "pc" : 4792911,
  "stop_type" : "fatal_error"
}
(lldb) 
```

I don't know if these errors are being caught due to toolchain differences from my OS X, or only exist on this platform.

**Comment by joemfb** [comment]
As for the debug build, `u3qfl_bunt` was removed in fbaa88039fc117fe92da20c8e09e13d95232f4e4. Was that a mistake, or is `jets/f/ap.c` missing some changes?

/cc @cgyarvin

**Comment by cgyarvin** [comment]
The latter.  Nothing that calls it is getting called.  Some linkers figure
that out and don't propagate the error.

It needs 8fb09d2690db3c9f0d290fc7377046b1d754af17
of ap.c, I think...

**Comment by cgyarvin** [comment]
OK I pushed a fix.

**Comment by joemfb** [comment]
Much obliged!

**Comment by joemfb** [comment]
Update: this branch builds without issue in travis (with clang), but still fails to start (with the same shadow_gap error). I suspect that older versions of clang (and therefore ASan) are not respecting the ASAN_OPTIONS, but haven't been able to verify that yet.

**Comment by joemfb** [comment]
closing in favor of #962

**Pull request closed without merging**
