### PR TITLE
interface: better error boundary reporting tools and formatting

### PR DESCRIPTION
**Pull request by tylershuster**
This should provide slightly better stack traces, plus it updates the "submit an issue" link to link to Landscape with the stack trace and title already filled in.

### CODE REVIEW

**Comment by matildepark** [comment]
It seems to work fine enough, but why is its unpacked size 1.46mb? It seems potentially heavier than lodash.

**Comment by tylershuster** [comment]
That seems...wrong:

image

**Comment by matildepark** [comment]
Just going off npm — 

https://www.npmjs.com/package/stacktrace-js
https://www.npmjs.com/package/lodash

**Comment by tylershuster** [comment]
The `build:prod` version isn't significantly bigger than before, not sure what NPM is on about

**Comment by matildepark** [comment]
Oh, this actually didn't hit next-js. Well, fine

**Review by matildepark — APPROVED** [review]

**Pull request merged**
