### PR TITLE
Try removing a bunch of dependencies

### PR DESCRIPTION
**Pull request by mrdomino**
If my claim (in urbit/docs#326) is correct, then we can get rid of a lot of this and the CI will still pass.

### CODE REVIEW

**Comment by mrdomino** [comment]
Oh man, the glory days of -Werror.

**Comment by ohAitch** [comment]
Last I checked we *were* building under -Werror! Perhaps they're in in the
submoduled dependencies?

**Comment by mrdomino** [comment]
Nah, meson changed that if I'm not mistaken.

**Comment by ohAitch** [comment]
<s>Can we revert it yet?</s>

**Comment by mrdomino** [comment]
I so far feel kinda good about meson.

However I do have a strongly-entrenched heuristic that says "all projects should be monorepi and built with bazel," that's probably largely a holdout from working at Google once upon a time.

**Pull request merged**
