### PR TITLE
fix pojo to be even more tco

### PR DESCRIPTION
**Pull request by ohAitch**

### CODE REVIEW

**Comment by galenwp** [comment]
https://en.wikipedia.org/wiki/Total_cost_of_ownership ?

**Comment by ohAitch** [comment]
https://en.m.wikipedia.org/wiki/Transparent_conducting_oxide

**Comment by ohAitch** [comment]
Er https://en.m.wikipedia.org/wiki/Tail_call_optimization

**Comment by ohAitch** [comment]
(And tail-cons optimization, in this case)

**Pull request merged**
