### PR TITLE
hoon: add +succ gate

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Adds an +inc (increment) gate. Whilst .+ exists, it is impossible to use
in a point free style and doesn't compose functionally. 

Should this be in functional hacks instead of unsigned int math?

### CODE REVIEW

**Comment by ohAitch** [comment]
the `~/` is a bit on the nose

**Review by pilfer-pandex — APPROVED** [review]

**Review by joemfb — CHANGES_REQUESTED** [review]
As discussed out of band, I'm somewhat opposed to adding this. I think we should have a consistent story about when we're going to additionally expose runes as gates, and not just add them haphazardly. (If we wanted them all, we could codegen them in the compiler.)

People should use `.+` directly wherever they can -- if the gate is present, I expect it'll be used more than necessary. Putting it in "functional hacks" (maybe as `+succ`) might better convey that.

**Comment by tacryt-socryp** [comment]
@liam-fitzgerald please apply Joe's suggestion so we can get this merged

**Review by tacryt-socryp — APPROVED** [review]
@joemfb only waiting for a stamp from you now

**Comment by tacryt-socryp** [comment]
@philipcmonk all review suggestions were applied in this PR, should be good to go

**Pull request merged**
