### PR TITLE
Ga/qa fixes

### PR DESCRIPTION
**Pull request by g-a-v-i-n**
- Resolves inconsistent spacing between status bar and home / content
- Leap positioning improved on mobile
- Reconnecting button refactored to use <Button />. Spinner added.
- Home is now "DMs + Drafts". I need extra review on that one because I also altered metadata around the codebase that seemed to point to this.

### CODE REVIEW

**Review by matildepark — CHANGES_REQUESTED** [review]
We somehow lost the status bar sigil by using Button instead of Row? Next userspace still has it showing correctly.

image

The Home changes seem to be in the right places, though wherever you see `icon="Circle"` we should probably change it to `icon="Boot"` to match.

**Comment by g-a-v-i-n** [comment]
Who wrote this sigil component? I have no idea what this thing is doing.

**Comment by matildepark** [comment]
It dates back to Modulo Chat, it's just been hacked at a lot since then.

**Comment by g-a-v-i-n** [comment]
Why is mix-blend-mode used here?

**Comment by matildepark** [comment]
Please see discussion in #2319.

**Comment by g-a-v-i-n** [comment]
Ok, thanks. Think I found the issue.

**Review by matildepark — APPROVED** [review]

**Pull request merged**
