### PR TITLE
contacts-js: fix setting of avatar prop

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Passes an empty avatar prop through correctly.

### CODE REVIEW

**Comment by loganallenc** [comment]
What is your intention here, like what are you trying to fix? I’m not sure this will work the way you expect.

**Comment by liam-fitzgerald** [comment]
If an avatar is not set, then the avatar is sent as `{ url: null }` instead of just `null`. This causes a parsing error when JSON conversion is attempted

**Comment by loganallenc** [comment]
Gotcha, okay!

**Comment by ixv** [comment]
@liam-fitzgerald merge conflict

**Comment by matildepark** [comment]
@liam-fitzgerald Target feat/spa?

**Comment by loganallenc** [comment]
Ping, please clean up these pull requests

**Comment by liam-fitzgerald** [comment]
bug has already been fixed

**Pull request closed without merging**
