### PR TITLE
hoon: add doq, kel, ker, pal, pam, par, pat, sel, ser, soq, tic

### PR DESCRIPTION
**Pull request by jfranklin9000**
update "XX deprecated" comments to match:
      https://urbit.org/docs/tutorials/hoon/hoon-syntax/#reading-hoon-aloud

This link is easier to read than the diff:
https://github.com/jfranklin9000/urbit/blob/0002413e853597f56d818cd6d30b2c867141ed20/pkg/arvo/sys/hoon.hoon#L5564

Not sure what branch to PR this to.

I'm willing to start the bus->buc, etc conversions if they're wanted at this point. In any case I think we want this PR as it's up-to-date.

### CODE REVIEW

**Comment by ohAitch** [comment]
While we're at it, any love for [the mneumonics](https://github.com/ohAitch/arvo/blob/071ac7c4606a57999ae27e00a4ec2689242ae7f4/arvo/hoon.hoon#L2721-L2756), in docs if not necessarily the source? They should all apply again except SEMicolon which I'll leave as an exercise to the reviewer.

<details>

```
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::                section 2eF, parsing (ascii)          ::
::
++  ace  (just ' ')                                     ::  spACE
++  bar  (just '|')                                     ::  vertical BAR
++  bas  (just '\\')                                    ::  Back Slash (escaped)
++  buc  (just '$')                                     ::  dollars BUCks
++  cab  (just '_')                                     ::  CABoose
++  cen  (just '%')                                     ::  perCENt
++  col  (just ':')                                     ::  COLon
++  com  (just ',')                                     ::  COMma
++  doq  (just '"')                                     ::  Double Quote
++  dot  (just '.')                                     ::  dot dot dot ...
++  fas  (just '/')                                     ::  Forward Slash
++  gal  (just '<')                                     ::  Greater Left
++  gar  (just '>')                                     ::  Greater Right
++  hax  (just '#')                                     ::  Hash
++  kel  (just '{')                                     ::  Curly Left
++  ker  (just '}')                                     ::  Curly Right
++  ket  (just '^')                                     ::  CareT
++  lus  (just '+')                                     ::  pLUS
++  hep  (just '-')                                     ::  HyPhen
++  pel  (just '(')                                     ::  Paren Left
++  pam  (just '&')                                     ::  AMPersand pampersand
++  per  (just ')')                                     ::  Paren Right
++  pat  (just '@')                                     ::  AT pat
++  sel  (just '[')                                     ::  Square Left
++  sem  (just ';')                                     ::  SEMicolon
++  ser  (just ']')                                     ::  Square Right
++  sig  (just '~')                                     ::  SIGnature squiggle
++  soq  (just '\'')                                    ::  Single Quote
++  tar  (just '*')                                     ::  sTAR
++  tec  (just '`')                                     ::  backTiCk
++  tis  (just '=')                                     ::  'tis tis, it is
++  wut  (just '?')                                     ::  wut, what?
++  zap  (just '!')                                     ::  zap! bang! crash!!
```

</details>

**Comment by joemfb** [comment]
@ohAitch, I like the mnemonics, and would be happy to see them back in the source.

@jfranklin9000, it would be great to have `$hoon` and `$spec` tags corrected. And to stop using these deprecated parsers. Anything you're willing to do to move that forward would be great. I'd be happy to help too. The `+solid` pill generator and scripts should be enough to stage those changes.

Without significant adapters, that's a breaching change, so it should be based on the `na-release/next-vere` branch, which currently holds such things.

**Comment by jfranklin9000** [comment]
Will do, thx.
Moved to https://github.com/urbit/urbit/pull/2945.

**Comment by jfranklin9000** [comment]
I wrote this before seeing @philipcmonk comment.  What should I do?

**Comment by philipcmonk** [comment]
As it is, it's not a breaching change.  I'd merge this as-is to `release/next-hoon`, or ideally we could add back those column-57 comments.

Switching usage of the deprecated parsers to the new ones is also non-breaching.  If you want to try changing the tags in +hoon and +spec, that's a breaching change, so we'd just target that at `na-release/runes` or something and then either we breach eventually (in which case we merge that into the release branch) or we write adapters such that it can go out OTA.

**Comment by joemfb** [comment]
@jfranklin9000, sorry for my confusing comment. You can just re-open this PR (open PRs can be updated to target a different branch with the edit button at the top) and target `release/next-hoon`. Further parser changes could happen here or in a new PR. And #2945 can be the home of the AST-node changes (it should probably be a "draft" PR until it's ready).

**Comment by jfranklin9000** [comment]
OK, here's what I'll do:

Target this PR (adding the new parsers) to `release/next-hoon` (and I'll also add the column-57 comments).  Then, in a new PR to `release/next-hoon` (or just adding commits to this one) I will switch usage of the deprecated parsers to the new ones.  All of this work is non-breaching.

Later, in another PR on a different/new branch, I'll change the tags in +hoon and +spec.  This is a breaching change (unless @philipcmonk writes the state adapters).  I'll worry about this later.

**Comment by jfranklin9000** [comment]
I think I'll start with a fresh checkout from `release/next-hoon`, closing.

**Comment by joemfb** [comment]
@jfranklin9000, I don't think that's your fault.

@philipcmonk, `release/next-hoon` was added today, and points to `ford-fusion`. It should be the same as master, or slightly ahead, right?

**Comment by philipcmonk** [comment]
You're correct, not sure how that happened (I don't think I created it?).  I'll switch it to master right now.

**Comment by joemfb** [comment]
@jfranklin9000, this PR is still salvageable!

Cherry-pick will be easiest, I'd do something like this:

```
git checkout -b tmp upstream/release/next-hoon
git cherry-pick 4h-parsing
git branch -f 4h-parsing tmp
git checkout 4h-parsing
git branch -d tmp
git push -f origin 4h-parsing
```

**Comment by jfranklin9000** [comment]
Where do I run these commands?  I'm in the directory of my `4h-parser` branch (cloned from `master`):
```
$ git branch
* master

$ git log | head -8
commit 0002413e853597f56d818cd6d30b2c867141ed20
Author: John Franklin <jfranklin9000@gmail.com>
Date:   Sun May 24 02:37:17 2020 -0500

    hoon: add doq, kel, ker, pal, pam, par, pat, sel, ser, soq, tic
          update "XX deprecated" comments to match:
          https://urbit.org/docs/tutorials/hoon/hoon-syntax/#reading-hoon-aloud

$ git config --get remote.origin.url
https://github.com/jfranklin9000/urbit.git

$ git config --get remote.jfranklin9000.push
master:4h-parsing

$ git checkout -b tmp upstream/release/next-hoon
fatal: 'upstream/release/next-hoon' is not a commit and a branch 'tmp' cannot be created from it
```

**Comment by joemfb** [comment]
First, you'll want to add the upstream repository as a remote so you can refer to our branches:

```
git remote add upstream https://github.com/urbit/urbit.git
```

It looks like you're working locally on a "master" branch, and pushing that remotely to `4h-parsing`. My commands assumed that your local and remote branches had the same name. You can get to such a state with:

```
git checkout -b 4h-parsing
```

which will create a new, local 4h-parsing branch from your current HEAD commit and immediately switch to it. The other commands should work after that.

**Comment by jfranklin9000** [comment]
I didn't get it to work so I started fresh.
Replaced by https://github.com/urbit/urbit/pull/2949.

**Pull request closed without merging**
