### PR TITLE
Removed Hall references from DNS apps

### PR DESCRIPTION
**Pull request by loganallenc**
Added TODOs for adding a systems notification service to replace its notify functions.

### CODE REVIEW

**Comment by philipcmonk** [comment]
Maybe at least replace with `+slog` for now?

**Comment by joemfb** [comment]
Is there some reason :hall *needs* to be removed before all it's use-cases are replaced?

**Comment by joemfb** [comment]
Of course, that question is for both this and #1761.

**Comment by jtobin** [comment]
I won't merge this.  There simply isn't enough context in the PR, the change as it stands by itself is dubious (it basically just breaks stuff), etc.

If you have another PR or PRs in mind that would depend on this, you should just PR the lot of that work together, or at least in larger and more meaningful chunks.

**Pull request closed without merging**
