### PR TITLE
profile: add html color picker

### PR DESCRIPTION
**Pull request by tylershuster**
Fixes https://github.com/urbit/landscape/issues/118

### CODE REVIEW

**Comment by matildepark** [comment]
There's that @tylershuster magic

**Review by matildepark — CHANGES_REQUESTED** [review]
This breaks the previous style — 

image

I suggest perhaps `position: absolute`-ing it inside the input as `position: relative` and then applying the same border and border-radius to complete the input, as before.

**Comment by tylershuster** [comment]
Hm, this must be not Firefox. I'll do some browser testing

**Comment by matildepark** [comment]
That's Brave Dev on macOS

**Comment by tylershuster** [comment]
Ok, slightly different approach but it looks good (better) and works the same now

**Comment by tylershuster** [comment]
FYI Brave's color picker is superior

**Review by matildepark — APPROVED** [review]
lgtm!

**Pull request merged**
