### PR TITLE
WIP: json unit tests

### PR DESCRIPTION
**Pull request by courajs**
I'm working on the [json unit test bounty](https://grants.urbit.org/bounties/318521460-unit-tests-for-json-parsing).
I'm about to jump into tests for `+enjs`/`+dejs`, but just wanted to see if there was any feedback on my first-ever set of Urbit unit tests, in the meantime.
Also, I may have found some unintentional behavior in `of-wall:format`, it always appends an extra newline to the end, except when applied to the empty list, which doesn't match `of-wain:format`. Should I change that?

### CODE REVIEW

**Comment by philipcmonk** [comment]
I remember a lot of blood spilled over the question of whether `+of-wall`/`+of-wain` should include a trailing newline in a non-empty wall/wain.  The strongest argument for it is that in practice these are used primarily for text files, and text files are usually considered to be a list of lines, each ending in a newline.  Most editors will include that newline without showing it to you.  If you follow `+of-wain`, then that last newline results in another empty item in the list, which is weird.  The strongest argument against it is that `+of-wall` as written is not a bijection -- we don't happen to have a `+to-wall`, but if we did it would be a partial function on tapes.  There's no mapping for "hi\0athere", or at least none where `+of-wall` would give back the original tape.

I lean slightly toward the `+of-wain` way of doing things because it's more flexible, but I would also like a similar function that does it the `+of-wall` way.

**Comment by joemfb** [comment]
I think #1448 is the main EOL discussion issue.

**Comment by joemfb** [comment]
Also #1557

**Comment by philipcmonk** [comment]
and #241 and #466 and I think urbit/arvo#24

**Pull request closed without merging**
