### PR TITLE
contact-store: enforce timestamp ordering on %initial

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Will stop flickering due to an excess of `%kick`s but does nothing for the network load causing the kicks in the first place.

### CODE REVIEW

**Review by tacryt-socryp — APPROVED** [review]

**Comment by tacryt-socryp** [comment]
Note: should only send initial diff if we actually modify the rolodex.

**Comment by liam-fitzgerald** [comment]
we aren't sending %initial on ames other than on the first watch, so does it really matter?

**Comment by tacryt-socryp** [comment]
Not too much, no, but semantically it is preferable. Less noisy.

**Comment by liam-fitzgerald** [comment]
done!

**Comment by tacryt-socryp** [comment]
Perfect, good to go

**Pull request merged**
