### PR TITLE
UP ?: Peerlist: (manual) userspace peer discovery

### PR DESCRIPTION
**Pull request by Fang-**
Idk if this is any good, but I'm gonna need this myself, so might as well see if it's worth merging in. Some work pending, but discussion welcome!

```
+++
up = ?
title = "Peerlist: (manual) userspace peer discovery"
created = 2019-06-29
authors = [
  "~palfun-foslup Mark <mark@tlon.io>"
]
editor = ?
type = feature 
status = draft
implementation = https://github.com/urbit/urbit/pull/1309
+++
```

# Abstract

Urbit theoretically supports peer-to-peer applications, but doesn't currently offer any tools for peer discovery. Peerlist allows users to manually define a list of ships they would like to interact with. Peer-to-peer applications can make use of this data as a drop-in solution to peer discovery.

# Motivation

One of the first things that come to mind about Urbit is its network topology. The Azimuth address space pushes strongly towards a decentralized topology, with the well-known `galaxies > stars > planets` hierarchy.

The misconception sometimes arises that userspace apps need to operate within that hierarchy also. Luckily, userspace doesn't need to care about network topology at all, and is free to communicate across the network in any way it sees fit.

Lots of peer-oriented (or, "multiplayer") applications will want to go the peer-to-peer route for their connections. More concretely, these are the kinds of applications that care about engaging with specific ships on the network, as opposed to interacting with a pool of data shared across (a subset of) the network.

A problem shared by all such applications is discovering peers to interact with. Even if that's solved for, interacting with random ships is often less desirable than staying within the user's social circles.

Users know who their friends are. Their Urbit should too. Peerlist allows users to maintain a list of ships they want to interact with, which client applications can then use in place of other forms of peer discovery.

As far as name and terminology is concerned, this is still open to change. In place of "peers" and "files", this had initially used "friends" and "groups", but that felt too intimate. Not every peer is a friend per se. But you can certainly create a `%friends` file for just those.

# Specification

For more detail, see the provided implementation. The primary data store is as follows:

```hoon
+$  state
  $:  ::  peers: all relations
      ::
      =peers
      ::  groups: locally defined clusters
      ::
      =groups
      ::  ...
  ==
::
+$  peers   (map ship relation)
+$  tag     @ta
+$  group   (set ship)
+$  groups  (map tag group)
::
+$  relation
  $:  ::  we-since: when we added them as a peer
      ::
      we-since=(unit @da)
      ::  they-since: when they added us as a peer
      ::
      they-since=(unit @da)
      ::  public: visible to others
      ::
      public=_|
  ==
```

This implementation aims to stick close to the core problem, adding only minimal bells and whistles.

We allow the user to define groups of peers (`files`), so they can easily tell client applications to use a user-defined subset of their peers.

We notify peers when we add them to our peerlist. This allows us to track incoming peer relations in addition to outgoing ones. Useful for "followers"-like lists, and distinguishing between one-sided relations and mutuals.

Lastly, peers in the list can be made public for viewing by others, but are private by default.

Scries and subscriptions, yet to be implemented, should support querying both the `peers` and `files` structures, filtering on ship, group, and a relationship `filter` (as defined in the implementation).

# Implementation

Implementation provided in [urbit#1309](https://github.com/urbit/urbit/pull/1309), but at the time of writing still needs work:
- [x] split off /lib and /sur files
- [x] write marks
- [x] generators for interaction
- [x] add logic for scries
- [ ] add logic for subscriptions
- [x] support im/export of app data

### CODE REVIEW

**Comment by jtobin** [comment]
This seems very useful.  If I'm understanding the semantics correctly: a
'file' is a set of ships to associate with some arbitrary tag (e.g. one
could define %my-friends and %my-enemies lists)?  And 'peers' are
literally all relations known to exist by a given ship?

**Comment by Fang-** [comment]
> If I'm understanding the semantics correctly

Yep, that's exactly right, assuming "a given ship" is whatever ship the app runs on.

**Comment by Fang-** [comment]
I put "subscription logic" on the todo list because it's such a standard box to check, but now I'm not so sure that's even needed. There's a case to be made here that this data is only relevant when apps are trying to connect to peers (or similar), and that apps shouldn't be reacting to the peerlist changing.

Perhaps best to leave it out for now, and see what it's like using it with just scries. If it turns out subscriptions are sorely needed, we can always add them in.

Also [snuck in](https://github.com/urbit/urbit/pull/1309/commits/8d10f1c6d3c93c95cc37b35fd7e0d00c5b15fcaa) an stdlib function, which I had hoped to be able to write generically (like `+join`)... but I couldn't get it to behave right.

**Comment by joemfb** [comment]
Does it work if you `zing`?

```
> `tape`(zing (join ":foo:" `(list tape)`["bar" "baz" "bud" ~]))
"bar:foo:baz:foo:bud"
```

The casts are awkward, you may want to `bake`:

```
> `tape`(zing ((bake join ,[tape (list tape)]) ":foo:" ["bar" "baz" "bud" ~]))
"bar:foo:baz:foo:bud"
```

FYI, you'll need to update the pill to get CI to pass (given a stdlib addition). You'll also probably need to merge `v0.8.0.rc` back into your branch (it has CI fixes). You can run the full CI testsuite yourself with `make test` at the top level.

**Comment by Fang-** [comment]
>Does it work if you zing?

Ah, of course, that works. Doesn't even need extra casts. I'll remove `+fuse` from this PR.

I have never in my life gotten `head` or `tail` to work with `cork` and friend. I _should_ just be able to do this, right?

https://github.com/urbit/urbit/blob/98117ce28f6b9b0d09afab969ad6d027cb9633fc/pkg/arvo/app/peerlist.hoon#L151-L155

**Comment by Fang-** [comment]
Alright, this should be ready for full review now. Any volunteers?

As per [this comment](https://github.com/urbit/urbit/pull/1309#issuecomment-509041698), subscriptions logic is still not in. Fight me, if you must!

Aside from [the above](https://github.com/urbit/urbit/pull/1309#issuecomment-511211758), there's two `TODO` remaining in the code. Those would be stdlib additions, I'll make a separate PR for those at some point.

**Comment by joemfb** [comment]
This must've been an accidental close, I have no memory of doing this (or of having any intention to do this). My apologies!

**Comment by jtobin** [comment]
> This must've been an accidental close, I have no memory of doing this (or of having any intention to do this). My apologies!

[Terrible things, joemfb.  You've done terrible things.](https://www.youtube.com/watch?v=DWMPRwSXsJo)

**Comment by Fang-** [comment]
For the record: there's ongoing internal discussion on how to incorporate this into upcoming userspace work, so this PR (in its current form) may or may not end up getting closed anyway.

**Comment by loganallenc** [comment]
Is this deprecated based on the new services/hooks architecture? @Fang-

**Comment by Fang-** [comment]
Yeah, this'll end up being redone/cleaned up alongside the work there, so closing this for now.

**Pull request closed without merging**
