### PR TITLE
fix shar:ed jet mismatch, add luck:ed, scad:ed, scap:ed, scas:ed, sign-raw:ed, sign-octs-raw:ed

### PR DESCRIPTION
**Pull request by newxiphiness**
- luck:ed and sign-(octs-)raw go together
  - luck:ed generates a public private keypair where the private keypair is generated from SHA512(seed) and the usual EdDSA clamping procedure is done on the first 32 bytes.
  - sign-(octs-)raw allows one to sign from a keypair generated with luck (or, from sca(d/s))

- scad, scas, scap allows one to 'tweak' a public/private keypair with a scalar
  - scad tweaks public and private
  - scas tweaks private
  - scap tweaks public

this also fixes the jet mismatch mentioned in #7072, and potentially other jet mismatches due to sign:ed taking the bit rather than the byte length, whereas the jet uses u3r_bytes_fit to obtain the length to sign (the urcrypt library, moreover, doesn't allow signing at bit-level lengths). it also removes code deduplication generating pub/priv keys via use of luck:ed, and ensures that various length calculuations are derived from the parameters of the EdDSA curve.

a further change is recommended, as our curve parameters are merely in the subject, as opposed to arms, so theoretically, one could obtain a jet mismatch via manipulating the parameters which are hard coded to Ed25519 to some other curve, however that is out of the scope of this PR

### CODE REVIEW

**Comment by newxiphiness** [comment]
i would say, now, this is good to go, i've tested this test suite with the ice flag enabled (or rather, disabled... c3n activates the testing) in the corresponding vere PR. excepting the fact that i haven't added shar:ed to the test file. i haven't managed to find a test vector in an RFC for ed25519 -> curve25519 -> DH

**Comment by newxiphiness** [comment]
related PRs
https://github.com/urbit/vere/pull/748
https://github.com/urbit/urbit/pull/7094
https://github.com/urbit/urcrypt/pull/13

**Comment by newxiphiness** [comment]
on second thought: for scalarmul(-base), we should assure the last byte is less than 127, and rather than punt on the failure of urcrypt library. i’d have to think more about it but one could perhaps imagine a dos vector were the ring signature library used (which is the only place where these jets are ran in injected code) resulting in the very slow +scam:ed being used. previously, this check was not performed in the urcrypt library, resulting in a key mismatch and erroneous behavior beyond the function domain the urcrypt method is well defined under.

will fix as soon as i get a chance and in vere PR, so don’t merge quite yet

**Comment by newxiphiness** [comment]
Okay, just re-ran with ice mode on all the jets with the updated test i've pushed. it should all be good to go, along with the other related PR's.

**Review by joemfb — APPROVED** [review]

**Pull request merged**
