### PR TITLE
Monorepoize

### PR DESCRIPTION
**Pull request by jtobin**
This will simply merge the `monorepo-candidate` branch into master, leaving us with the `arvo` repo as a subtree (including its entire history), instead of a submodule.

Barring any last-minute objections, it can just be merged in as anyone sees fit.

### CODE REVIEW

**Comment by joemfb** [comment]
This ... is quite a PR!

The PR build failed in CI because the brass pill generation (orchestrated over HTTP via `herb` and `:lens`) hit the request timeout. This is included in CI as a sanity check to ensure that new changes don't break the pill staging, but only on merge/PR builds, because it's slow (see https://github.com/urbit/urbit/blob/ade1e59ce124a6204f300d7f17274eb614752032/sh/ci-tests). It's performed in parallel with the tests (also because it's slow), but takes longer than usual (presumably due to resource contention on the small VMs in CI). We've already bumped that request timeout a couple of times -- it currently stands at `~45s`. I've restarted the PR build to see if the failure is consistent. We can either bump that timeout again, or try performing the tests and pill staging in series.

Also, these changes can't be merged to master until we're ready to breach them onto the network (as we direct people to install master: https://urbit.org/docs/getting-started/installing-urbit/). I think it's fine to either hold this PR open until we're ready to release, or target it against a "next-breach" (or whatever) branch if we want to merge it sooner.

**Comment by jtobin** [comment]
On Thu, Jun 27, 2019 at 11:16:13PM -0700, Joe Bryan wrote:
> Also, these changes can't be merged to master until we're ready to
> breach them onto the network (as we direct people to install master:
> https://urbit.org/docs/getting-started/installing-urbit/). I think
> it's fine to either hold this PR open until we're ready to release, or
> target it against a "next-breach" (or whatever) branch if we want to
> merge it sooner.

Ahhh, « mais oui ».  I hadn't realised that the present install
instructions pointed people at master.  I've got a branch sitting on
docs with updated getting started instructions -- clearly I didn't read
the existing ones very well.

My inclination is to simply close this one and rename the
'monorepo-candidate' branch to 'v0.8.0.rc'.  We can just open a new PR
targeting master for the breaching release proper.

--
~nidsut-tomdun
https://urbit.org

**Comment by jtobin** [comment]
On Fri, Jun 28, 2019 at 02:35:41PM +0800, Jared Tobin wrote:
> My inclination is to simply close this one and rename the
> 'monorepo-candidate' branch to 'v0.8.0.rc'.  We can just open a new PR
> targeting master for the breaching release proper.

(Or just reopen this PR when the time is right.)

--
~nidsut-tomdun
https://urbit.org

**Comment by joemfb** [comment]
I have no objections either way. Not merging a PR at this time does have the "advantage" of not requiring us to find an immediate solution to these failing PR builds ... ;)

**Comment by jtobin** [comment]
On Thu, Jun 27, 2019 at 11:44:16PM -0700, Joe Bryan wrote:
> I have no objections either way. Not merging a PR at this time does
> have the "advantage" of not requiring us to find an immediate solution
> to these failing PR builds ... ;)

*expanding brain*

--
~nidsut-tomdun
https://urbit.org

**Pull request closed without merging**
