### PR TITLE
%yard, a developer commons

### PR DESCRIPTION
**Pull request by sigilante**
`%yard` is a proposed desk to offload some non-essential `%base` functionality and provide ready-to-hand duplicates of essential marks and libraries for developers.

`%yard` is not subject to kelvin versioning.

See discussion at [this gist](https://gist.github.com/sigilante/beddcdfdd9836ede6403d4bb0ac1d43c).

### CODE REVIEW

**Comment by sigilante** [comment]
UIP draft now available at https://github.com/urbit/UIPs/pull/16/files

**Comment by sigilante** [comment]
Status update:

- I have the marks and /lib/schooner in place.
- I need to fix a version of /lib/etch to not use Ziggurat stuff

**Comment by Fang-** [comment]
Unclear to me from either this or the UIP how this is intended to be used. Imagine this already exists, is on my ship, and I'm going to develop an application that may use some of the code provided herein. What do I do with the `%yard` desk, specifically?

**Comment by sigilante** [comment]
https://github.com/urbit/yard

**Pull request closed without merging**
