### PR TITLE
Add urlencoded %post support to %eyre hooks

### PR DESCRIPTION
**Pull request by zaphar**
This only supports urleencoded data as the payload for now.

### CODE REVIEW

**Comment by juped** [comment]
Highly anticipated! Would you mind doing a quick example hook somewhere (not on this branch, bin it or something) so we can eventually document it right?

**Comment by zaphar** [comment]
It works exactly like `%get `requests so `%posting` to any current hook that uses a `qix.gas` will work.

**Comment by juped** [comment]
Ah, got it - it's not marked yet

**Comment by zaphar** [comment]
No but I have some ideas now on how to introduce marked payloads.

**Comment by juped** [comment]
I mean, POST does have a content-type header. We have at least a partial mapping of mime types to marks somewhere, and everything else can be x-urb/whatever.

**Pull request merged**
