### PR TITLE
split %cy hash out into %cz

### PR DESCRIPTION
**Pull request by philipcmonk**
This should help with the performance of various things.  @ohAitch, do you remember a real-world example of the slow %cy problem that we can check?  The example in #648 gives about 1.7 seconds, of which 1.4 is spent running the code (i.e. the rest is dojo overhead).  That's about 14 ms per request, which is an improvement of a factor of 5.

This should be merged with care, since `++arch` has changed, which has repercussions with other vanes.  There's a variety of things that need to be sequenced, but the problem I haven't figured out a solution for is that:

- clay's compilation will fail unless the new hoon is loaded
- the new hoon will fail to reset unless the new clay is present

Thus, what we want is for both's code to be added at the same time.  The issue is that we can't guarantee if clay or hoon will try to compile first, and if clay does, the compilation will fail, so the sync event will fail.  I tested this, and it broke the sync from the parent to the child.  I believe the long term solution will be to make it so that a failed reload/reset doesn't crash the event.  Perhaps I should work  on that next?

### CODE REVIEW

**Comment by galenwp** [comment]
Let's take a moment to note the PR number.

**Comment by chc4** [comment]
Really, this should be closed without merged solely on principle. Satanists pls go.

**Comment by juped** [comment]
I can reproduce the failure on sync to children, but I don't get the rest. The bug is that resets aren't guaranteed to happen first - really, the bug is that the reset happening doesn't override the individual vane reloads, since it necessarily includes them.

**Comment by philipcmonk** [comment]
The problem could be fixed by either turning the autoreload/autoreset into a separate event or having autoreset override autoreloads.  Since I'm in clay anyways, and we want the updating pipeline to be as smooth as possible, I'll do both.

**Pull request merged**
