### PR TITLE
group-feed: threaded conversation finally comes to urbit

### PR DESCRIPTION
**Pull request by tacryt-socryp**
Opening a draft so that people can view my progress. Will update with checklists of things yet to be done, etc.

### TODO:
- [x] Backend migration for `%metadata-store` to have group-feed related data
- [x] Graph validator for Posts graph type
- [x] Thread for making a group feed
- [x] Thread for auto-joining a group feed if it is added to a group
- [x] Functionality in `%group-view` to automatically join a group feed when we join a group if one is present
- [x] Render banner to allow creation of a group feed based on `%metadata-store` properties
- [x] Modal for creating group feed with permissions
- [x] API action to dismiss banner and not create group feed
- [x] Render initial group feed view
- [x] Render text field and hook it up to allow posting to group feed
- [x] Render replies view
- [x] Upload images and code mode
- [x] Pagination on JS side
- [x] Render inline reply input
- [x] Display header state and sidebar navigation state
- [x] Group feed settings popover

### CODE REVIEW

**Comment by tacryt-socryp** [comment]
@liam-fitzgerald @matildepark This is ready for review.

**Comment by matildepark** [comment]
CI fails ... on Ubuntu but not macOS, for `+tally`, presumably due to our changes to metadata-store.

```
gall: read-at-aeon fail [care=%a case=[%da p=~2021.3.24..03.20.34..c554] path=/gen/tally/hoon]
2573
/gen/tally/hoon::[3 1].[134 3]>
2574
/gen/tally/hoon::[4 1].[134 3]>
2575
/gen/tally/hoon::[5 1].[134 3]>
2576
/gen/tally/hoon::[10 1].[134 3]>
2577
/gen/tally/hoon::[11 1].[134 3]>
2578
/gen/tally/hoon::[13 1].[134 3]>
2579
/gen/tally/hoon::[14 1].[117 3]>
2580
/gen/tally/hoon::[34 1].[117 3]>
2581
/gen/tally/hoon::[45 1].[117 3]>
2582
/gen/tally/hoon::[51 1].[117 3]>
2583
/gen/tally/hoon::[52 3].[63 33]>
2584
/gen/tally/hoon::[53 3].[63 33]>
2585
/gen/tally/hoon::[54 3].[63 33]>
2586
/gen/tally/hoon::[55 3].[63 33]>
2587
/gen/tally/hoon::[56 3].[63 33]>
2588
/gen/tally/hoon::[60 3].[63 33]>
2589
/gen/tally/hoon::[62 3].[63 33]>
2590
/gen/tally/hoon::[63 3].[63 33]>
2591
/gen/tally/hoon::[63 4].[63 33]>
2592
/gen/tally/hoon::[63 5].[63 21]>
2593
-find.module.metadatum
2594
[%error-building /gen/tally/hoon]
2595
FAILED  /gen/tally/hoon
```

**Comment by joemfb** [comment]
@matildepark the macos build doesn't run any arvo tests.

**Comment by matildepark** [comment]
> @matildepark the macos build doesn't run any arvo tests.

We had three engineers sitting in a meeting to test this on Ropsten directly afterward just idling as CI ran for 30+ minutes.

**Pull request merged**
