### PR TITLE
build: replace push-storage-object fixed output derivation with hercules ci effect

### PR DESCRIPTION
**Pull request by brendanhay**
This removes the need to calculate sha256/md5 hashes on the tarballs or pills which were used as part of the `gsutil` gymnastics to perform idempotent uploads.

The effects now run at the end of build, but unfortunately didn't have quite the positive performance impact I was hoping for - only a very small improvement. They do run inside a special sandbox though, so we get sandboxes inside sandboxes, life isn't all bad.

Depends on #3886

### CODE REVIEW

**Comment by brendanhay** [comment]
This required some out-of-band work on the agent machines to use newer versions of the `hercules-ci-agent` binary.

**Comment by joemfb** [comment]
@brendanhay, can you force-push or rebase now to clean up the history? It looks to me like the `:lens`/pill commits actually differ between this and #3886.

**Comment by brendanhay** [comment]
Noone ever had to ask me twice to force push!

**Review by joemfb — APPROVED** [review]
LGTM

**Comment by joemfb** [comment]
Due to the LFS issue in #3886, I rebased this branch (767a6f85a) and manually merged it into a reverted `release/next-vere` (86b59c67c).

**Pull request merged**
