### PR TITLE
Implement doccords in hoon [jet modification].

### PR DESCRIPTION
**Pull request by eglaysher**
This adds syntax to the language to embed documentation.

### CODE REVIEW

**Comment by juped** [comment]
Thanks!

**Comment by cgyarvin** [comment]
Thanks!  Gonna take a little bit to review this one but I should get it
done today...

**Comment by cgyarvin** [comment]
Wait, where is the matching hoon.hoon change?  Do we already have a PR for
it?

**Comment by juped** [comment]
Yes, it's there.

**Comment by eglaysher** [comment]
%docs -> %help, as requested in the arvo patch.

**Comment by juped** [comment]
Superseded by #837

**Pull request closed without merging**
