### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by max19**

### CODE REVIEW

**Comment by juped** [comment]
Do you mind if I squash these? There's two "oops"es and a merge bubble...

**Comment by juped** [comment]
Then again, at this point it's like closing the barn door in Mongolia after the Great Khan has nationalized all your horses and moved on to menace Constantinople.

**Comment by max19** [comment]
Henceforth I shall squash

**Comment by juped** [comment]
It is up to you - git is pretty nerve-wracking.

though I might write some contributor guidelines encouraging such things...

**Comment by cgyarvin** [comment]
@encourages such things!

**Pull request merged**
