### PR TITLE
interface: ensure that we display the correct ship name and do not retain stale state

### PR DESCRIPTION
**Pull request by tacryt-socryp**
Fixes https://github.com/urbit/landscape/issues/434

### CODE REVIEW

**Review by matildepark — CHANGES_REQUESTED** [review]
Still at large!

Try this repro:

1. Go to a direct message.
2. Refresh the page.

Your nickname will never appear. Also note that ChatInput also needs this fix too.

**Comment by tacryt-socryp** [comment]
Huh, I couldn't reproduce that on the DMs page in my testing. Will try again.

**Comment by tacryt-socryp** [comment]
Are you sure that this doesn't work? I've created a test case in which it takes an additional 5 seconds to set the "hasLoadedAllowed" boolean to true, and the contact information comes in properly.

**Comment by matildepark** [comment]
Will film and show. Standby

**Review by matildepark — APPROVED** [review]
This is good to go if you remove the console.logs!

**Pull request merged**
