### PR TITLE
collections: allow %reference as link

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Allows permalinks to be added to collections.

Capture d’écran 2021-03-29 à 12 41 49 PM

Fixes urbit/landscape#661

### CODE REVIEW

**Comment by matildepark** [comment]
Why does this require a validator change? You could just check for the URL like any other and convert it to a render. Collections are links. Let’s not change that.

**Comment by tacryt-socryp** [comment]
No, we absolutely must use the type system here.

**Comment by matildepark** [comment]
If you insist ... will this produce backwards incompatibility issues if someone adds a permalink and the subscriber doesn’t have this change? Presumably so. Not ideal

**Comment by tacryt-socryp** [comment]
Yes, it would produce backward incompatibility, but the worst case is just a missing link on someone's old / incompatible ship. The missing link issue could be resolved simply by incrementing the versions in graph-push/pull hook, which will prompt a resubscribe.

**Comment by matildepark** [comment]
Well as long as the version bump we're already doing for adding references is here, this is considered to be part of that new version, and then we're already covered.

**Review by matildepark — APPROVED** [review]
Reads sanely enough

**Pull request merged**
