### PR TITLE
interface: do not cache index.html and cache bust JS

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
- Strips index.html of all caching headers. 
- Webpack now outputs a hashed filename, .e.g. `index.11130a034c1b98f912ee.js`
- Updated glob to handle new bundle name.
- Updates MAINTAINERS.md to instruct the deployer to update the index.html to pull in the latest JS. (PR for janeway otw)
- Remove index.js being treated as both the entry point and a chunk, which was causing the bundle to be twice as large as it should be.

### CODE REVIEW

**Comment by matildepark** [comment]
Always flexin...

**Comment by tylershuster** [comment]
Fixes #3239

**Comment by matildepark** [comment]
Doesn't this break the dev server?

**Comment by liam-fitzgerald** [comment]
> Doesn't this break the dev server?

not anymore

**Comment by liam-fitzgerald** [comment]
fwiw this also opens the door to bundling our dependencies separately, which could be a nice perf improvement.

**Comment by matildepark** [comment]
pong @g-a-v-i-n also this has a conflict

**Comment by tacryt-socryp** [comment]
Have you tested the OTA case for this? I worry that it would break the webpage by unbinding 
/~landscape/index.js

**Comment by matildepark** [comment]
Aye, might be worth just doing a once-over on an -L ship; my guess is that it will certainly blank at first, because of a residually cached index.html, but work afterward (and for all subsequent updates).

—
~haddef-sigwen
https://urbit.org

**Comment by liam-fitzgerald** [comment]
OTA case tested. works fine

**Comment by matildepark** [comment]
And if we merge this we won't be able to run the dev server against livenet right? The proxy won't block the original landscape.

**Comment by liam-fitzgerald** [comment]
it does not break the dev server for livenet or for new ships.

**Comment by matildepark** [comment]
I meant “until we OTA this” heh

**Comment by liam-fitzgerald** [comment]
> I meant “until we OTA this” heh

No it still works.

**Comment by tacryt-socryp** [comment]
Good to go.

**Comment by matildepark** [comment]
> > I meant “until we OTA this” heh
> 
> No it still works.

Just a heads up that this is straight up not true; doing `npm run start` now against a livenet ship and it's serving old landscape instead of the dev server.

**Comment by matildepark** [comment]
Worked around this by changing L55 in webpack.dev.js back to this for the time being so we proxy against the actual location of the old index.js:

```
      '/~landscape/js/index.js': {
```

**Pull request merged**
