### PR TITLE
bytecode, hashboard, and nock 12 (4K)

### PR DESCRIPTION
**Pull request by joemfb**
This is the long-awaited integration of the inestimable @frodwith's long-running infrastructure projects:

- a new, faster nock interpreter with custom bytecode
- *hashboard*: a safer and more robust jet dashboard
- the addition of nock `12`, bringing nock to 4K.

Note that this PR currently lacks battery hashes in `tree.c`. The merge with release-candidate (and, transitively, research-final) was onerous enough that I mostly reconstructed these declarations. The correct hashes are printed as jets are registered, so adding them is a mostly straightforward manual operation. This should probably be deferred until `hoon.hoon` and %zuse are relatively stable (else it will need to be repeated).

### CODE REVIEW

**Comment by cgyarvin** [comment]
Have we checked this for memory leaks?

**Comment by joemfb** [comment]
I just tried with `-g`:

```
$ build/urbit -g -FI zod -A ./arvo/ -s -c zod
```

master, release-candidate, and this branch before and after the merge with release-candidate all bail with leaks.

**Comment by joemfb** [comment]
It was kindly pointed out to me that I have to first `#define U3_MEMORY_DEBUG`. Sorry!

Trying again ...

**Comment by joemfb** [comment]
Take two:

The "master" and "edit" (original) branches both boot fake-zods without leaking. The "release-candidate" and "edit" (merged) branches both leak right after bringing up the ames listener.

Is there any approach to debugging these that's better than a) bisecting or b) guessing?

**Comment by cgyarvin** [comment]
Not one that's much better.  However, bisecting is extremely difficult
due to the basically-informal vere/arvo synchronization.

The garbage collector will tell you what addresses are being leaked.
These may be stable across a run or they may not be.  The stable ones
are obviously easier, because you can put printfs and/or crashes at
points where that address is operated on.  But of course this data is
full of noise, because addresses are (duh) reused.

A memory leak is a memory leak in vere, by definition.  But we still
don't have a clean way of mapping from vere to arvo version to a pill
that works with that version of vere.  This is lame (and one
consequence of not being in a monorepo).

In the real world now, sounds like it's on me to fix the leaks it
sounds like I introduced (presumably somewhere in some compiler jet).
Of course, if you want to screw around with actually debugging this,
it might be more fun than changing diapers.  But it is my error and
it'll be much more efficient at fixing it.

Also, once fixed, this should go in our CI!  Again, lame.  Also
probably mostly my fault.

**Comment by joemfb** [comment]
I'm digging into this now. Bisecting has indeed proved to be as hard as you say. But I think I've tracked the leak to the absolutely horrifying "graceful" http server restart code I added when I implemented the proxy and dynamic server config effect. I'll post updates soon.

**Comment by cgyarvin** [comment]
Bisecting is a disaster and makes me cower in shame before my ancestors.

**Comment by ohAitch** [comment]
> we still don't have a clean way of mapping from vere to arvo version to a
pill that works with that version of vere.
We should have a clean way of mapping arvo version to a version of vere
that works with it — assuming people have been pushing the relevant
branches, and feeding CI when it breaks. From there it's hopefully fairly
straightforward to go "what non-broken arvo commit is closest to the tip of
rc vere", or to a bisect thereof.

**Comment by joemfb** [comment]
closing in deference to #1031. nock 4K will be staged separately.

**Pull request closed without merging**
