### PR TITLE
king: don't kill on C-d

### PR DESCRIPTION
**Pull request by ryjm**
Have mercy.

### CODE REVIEW

**Comment by pilfer-pandex** [comment]
Why is this desirable?

**Comment by ohAitch** [comment]
Yeah isn't this kinda the standard way to quit urbit on the C runtime? Or does "kill" mean something weird here

**Comment by ryjm** [comment]
C-d should only kill when the line is blank, otherwise it's delete forward
one character. I use C-d all the time so I would accidentally quit dojo all
the time.

**Comment by joemfb** [comment]
There's no reason to implement the behavior at this level, exiting is implemented inside `lib/hood/drum`. (Also, the current implementation is wrong...)

**Comment by ryjm** [comment]
Yeah after deleting this line the behavior is correct - it quits on C-d only when the dojo is blank.

**Comment by pilfer-pandex** [comment]
Okay in that case I do want to push back against the proposed behavior change. I don't like that my line has to be empty in order for me to quit. I know that this is a difference from vere, but I prefer our way better. A large man once said that "wrong" is always and everywhere a matter of taste.

Bikeshedding: Arguably, ^D also sucks in that if you press it twice (for example, because there is lag and you forgot that you pressed it), you wind up losing your shell. This happens to me on a regular basis. The best of all worlds would then be to come up with a different control character which would take the place of ^D in the haskell line which @ryjm proposes to delete. Then ^D can proceed to work only on empty lines, "deleting" otherwise, and everyone can be happy. Is there a standard alternative character for this? I don't know one off of the top of my head.

**Comment by ohAitch** [comment]
`^Z` and `^\` should both quit instantly regardless of line state right? (The latter recording a core dump for inspection)

**Comment by pilfer-pandex** [comment]
[You're wrong.](https://www.youtube.com/watch?v=GM-e46xdcUo) I just tried it on macOS and:
- ^Z did nothing
- ^\ caused the terminal/king to become completely unresponsive

**Comment by philipcmonk** [comment]
Well those two should be fixed to work like in vere, they're the normal ways to exit without going through event loop.  Note that they're handled as SIGTSTP and SIGQUIT rather than keystrokes directly.  ^D has the same "only exit if the line is empty" behavior in bash, fish, etc, so it'd be nice to preserve that behavior.

**Comment by ohAitch** [comment]
Can one really be "right" or "wrong" on matters of "should"? ;)
(But yes, I was referring to the reference implementation behavior)

**Comment by ohAitch** [comment]
I suppose I *can* confidently claim "caused the terminal/king to become completely unresponsive" is not what any button should do, UI considerations aside. (`^S` maybe? I think that one's built in.)
Is this a Haskell core dump difference, something about the connection to the worker and/or terminal not being cleaned up, some performance edge case?

**Comment by joemfb** [comment]
Merging to ensure this is not lost.

**Pull request merged**
