### PR TITLE
interface: remove share profile chat button

### PR DESCRIPTION
**Pull request by dnmfarrell**
Removes the "Share private profile?" text and button that appear
at the top of the chat window when the ship has not opted in to sharing
their profile.

fixes [urbit/landscape#1195]([1195](https://github.com/urbit/landscape/issues/1195))

cc @nerveharp @urcades

### CODE REVIEW

**Comment by dnmfarrell** [comment]
Maybe I should branch off next/landscape instead of master?

**Review by patosullivan — APPROVED** [review]
LGTM

**Comment by patosullivan** [comment]
Thanks for the contribution!

**Comment by arthyn** [comment]
For future reference this goes in next/groups confusingly enough, we hope to have this sorted better in the future.

**Pull request merged**
