### PR TITLE
Images should use -webkit-optimize-contrast.

### PR DESCRIPTION
**Pull request by 0x70b1a5**
The gains from this unobtrusive change are fairly straightforward.

before

after

### CODE REVIEW

**Comment by nerveharp** [comment]
@0x70b1a5 Looks good, thank you. Can you target `next/groups` with your PR?

**Comment by 0x70b1a5** [comment]
@nerveharp Sure.

**Comment by 0x70b1a5** [comment]
@nerveharp  Did I do that correctly?

**Comment by nerveharp** [comment]
@0x70b1a5 Not really -- if you look here, you're including a couple changes from your fork of `master` in your PR. https://github.com/urbit/urbit/pull/5712/files

**Comment by 0x70b1a5** [comment]
Ah, so I am. I will submit a new PR.

**Pull request closed without merging**
