### PR TITLE
Eyre serve /=home=/web, set with |serve

### PR DESCRIPTION
**Pull request by ohAitch**
Also contains userspace changes, redirect mechanism.
Deployment notes:
- this branch is **undergoing review** and should not be merged yet. This is a list of things to watch when that does happen.
- most things in /===pub have been moved to /===web.
  + the movement of things from /pub to /web and urls from /home/pub/foo to /foo should be posted on urbit-dev
- this pr containst eyre changes and a zuse change, the zuse change needs to happen first
- see https://github.com/urbit/examples/tree/eyre-root-beam for parallel changes to sample app frontends, to be deployed on ~wactex-ribmex simultaneously with this update
- ships not synced to /(sein our)/home=, such as the one serving urbit.org, may find their web pressence affected by the changed eyre being reloaded in from their subs. Nginx rewrite rules should be updated accordingly.

### CODE REVIEW

**Comment by galenwp** [comment]
We want to wait to merge this, right?

**Comment by ohAitch** [comment]
Correct, edited. (Also it apparently has conflicts)

**Comment by philipcmonk** [comment]
Why are we not moving everything from `pub` to `web`?

**Comment by ohAitch** [comment]
Namespace conflict: /web/docs is an alias for /web/tree/.../docs, /pub/docs are the actual source files being pointed at by the alias.

**Comment by philipcmonk** [comment]
Seems like it'd be cleaner to just put the source files in a subdirectory
of /web and point there.

**Comment by ohAitch** [comment]
/web/src/docs, perhaps.

**Comment by philipcmonk** [comment]
Whenever this gets merged, the examples repo should be updated as well.

**Comment by ohAitch** [comment]
see point four :3

**Comment by philipcmonk** [comment]
Indeed.

Re: point five, the ~fotlev-datben, the current urbit.org ship, is currently fully synced with ~doznec.  Whether this is advisable is another question.

**Comment by chc4** [comment]
will this allow adding an index.html to /web and having it served at the root domain, instead of erroring?

**Comment by ohAitch** [comment]
a web.html or web/hymn.hook (or web/elem.hook), yes. Alternately a
`*web/red/quri.hook '/$ fuel ?^(but !! [%| `/index ~])'` will redirect /,
in which case it can be called web/index.html sure.

**Comment by philipcmonk** [comment]
It will!

**Comment by philipcmonk** [comment]
Whoops, lost connection between the two messages; didn't see anton's repsonse

**Comment by juped** [comment]
RIP

**Comment by ohAitch** [comment]
Has been subsumed by ford-ren, soon to enter @galenwp/factor

**Pull request closed without merging**
