### PR TITLE
Add a GitHub workflow that auto-merges master to release/next-js on push

### PR DESCRIPTION
**Pull request by jtobin**
Adds a workflow that, on any push to master, merges master to release/next-js.

### CODE REVIEW

**Comment by matildepark** [comment]
So what happens if we merge next-js into master?

**Comment by jtobin** [comment]
grey goo? :-)

Not really.  I haven't tested that behaviour, but it will just try to merge master back into next-js as per usual, creating a new merge commit on release/next-js if there's a material one to make.  And if not, it won't do anything ('already up to date').

**Review by matildepark — APPROVED** [review]

**Comment by matildepark** [comment]
@jtobin The automated merge commit doesn't seem to initiate a glob action? Any ideas?

**Comment by jtobin** [comment]
Hmm, apparently a workflow that's run using `GITHUB_TOKEN` [can't trigger other workflows](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token).

The solution seems to be to use a personal access token instead.  So, I'll probably create a custom bot account for this type of thing, assign it the required write permissions, and generate / use a token for that.

**Pull request merged**
