### PR TITLE
Chat: Standardise sigil size and input line height

### PR DESCRIPTION
**Pull request by matildepark**
Read-only chats had a slightly bigger sigil box, looking skewed to
the left. Its copy also had a different line height than the
chat input itself, which was vertically aligned slightly higher.

This commit standardises the sigil box to 32px across both
and brings both to the same, centered vertical alignment
for the chat input and read-only notice.

For comparison (before and after, each time):

**Read-only**
Screen Shot 2019-08-22 at 5 45 44 PM

Screen Shot 2019-08-22 at 5 40 59 PM

**Chat input**
Screen Shot 2019-08-22 at 5 46 48 PM

Screen Shot 2019-08-22 at 5 41 18 PM

### CODE REVIEW

**Comment by loganallenc** [comment]
Have you tested this on Safari and Chrome?

**Comment by matildepark** [comment]
Tested on Brave (and, I think, Firefox for ~marzod’s client). I can double check if you want me to be triply sure.

**Comment by alexmatz** [comment]
> Tested on Brave (and, I think, Firefox for ~marzod’s client). I can double check if you want me to be triply sure.
> […](#)
> On Aug 23, 2019, at 1:56 PM, Logan ***@***.***> wrote: Have you tested this on Safari and Chrome? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

yes, please check, thank you!

**Comment by matildepark** [comment]
Seems clear.

Screen Shot 2019-08-23 at 8 21 27 PM

Screen Shot 2019-08-23 at 8 22 13 PM

**Pull request merged**
