### PR TITLE
graph: Permalinks

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
- Changes graph-store %reference type to accomodate groups
- Allows links, notes, comments and messages to be copied as permalinks
- Allows permalinks to be sent in comments and messages, where they'll be transcluded if the ship has the referenced node
- Registers a protocol handler for permalinks such that they can be navigated to by entering the link in the address bar on Chrome and Firefox (desktop only)
- If a permalink is clicked, but the user has not joined either the group or the graph, the group and graphs will be joined automatically.
- Leverages the new versioned subscriptions, declaring incompatibility with `graph-update-0`.

Notes:
- This needs an aggressive rebase, given that the versioning stuff has been rebased onto master. I'm unsure what I should rebase onto however.

### CODE REVIEW

**Comment by matildepark** [comment]
> This needs an aggressive rebase, given that the versioning stuff has been rebased onto master. I'm unsure what I should rebase onto however.

Versioning stuff will be merged into an intermediate branch and then into next-userspace where this can then still be based off that next-userspace branch. However the versioning stuff needs to be merged first before we can stage these integrations!

**Comment by joemfb** [comment]
What's the permalink format? Given the "perma" requirement, it'd be good to have that specifically reviewed for long-term compatibility, relationship to the namespace, &c.

**Comment by matildepark** [comment]
> What's the permalink format? Given the "perma" requirement, it'd be good to have that specifically reviewed for long-term compatibility, relationship to the namespace, &c.

I believe it's `group/graph/index` as per https://github.com/urbit/urbit/pull/4630/files#diff-435a247d0dd6deecc86f3cd32fe407acf557b6846123da809d2103c9f3500940R77

Decision was to amend the graph nodes to include a reference to the group in question so that we don't have Landscape FE-specific content in our graph-store, but something Urbit-parseable and at least _possibly_ agnostic for other clients; decision was also made to have a "general permalink handler" route in Landscape to process the permalinks in a way that could be ported if we move to, eg., remote scries later. I'm sure @liam-fitzgerald and @tacryt-socryp can opine further.

**Comment by matildepark** [comment]
@liam-fitzgerald Noting the reply / delete stubbed still, do you expect it an easy add?

**Comment by liam-fitzgerald** [comment]
Right now it's just 
```
web+urbit://groups/~host/name
web+urbit://groups/~host/name/graph/~graph-host/graph-name
web+urbit://groups/~host/name/graph/~graph-host/graph-name/index
::  e.g.
web+urbit://groups/~bitbet-bolbel/urbit-community/graph/~dopzod/urbit-help/1237895432034
```
The intention here is for these permalinks to form some kind of '''semantic scry''', that preserves most of the properties of an actual Arvo scry, but is optimised for user experience and readability.

**Comment by liam-fitzgerald** [comment]
Replying is not stubbed. Deleting messages is indeed stubbed, pending tyler's api changes so we don't have to drill the api prop everywhere.

**Comment by liam-fitzgerald** [comment]
Capture d’écran 2021-03-22 à 12 44 47 PM

for design cc: @urcades 

Note that the unjoined groups and graphs work as one would expect, joining the group and/or graph if necessary.

**Comment by urcades** [comment]
These are looking so, so, so good Liam.

A question regarding the “link to a comment on a collection item, with nested content”:

This is essentially pointing out that referencing other nodes/channel embedding is also supported in comments themselves?

**Comment by tacryt-socryp** [comment]
I think it may be best for the link to be `web+urbit-graph://` so that more general scries in the future don't share the namespace. https://github.com/urbit/urbit/pull/4630#issuecomment-803685368

**Comment by matildepark** [comment]
This still needs a merge/rebase of next-userspace before we can review.

**Review by matildepark — APPROVED** [review]
Did basic sift through the code, confirmed it compiles, added the namespacing to the schema, the rest we'll catch on Ropsten ...

**Comment by urcades** [comment]
@matildepark do we expect ropsten to be updated with this work in the next few minutes now that this is merged? or is the process more involved?

**Comment by urcades** [comment]
I'm simply very hyped to Quality Assurance this work

**Comment by matildepark** [comment]
No ✔️

Because Ropsten is a manually merge and deploy process. We’re doing an integration push right now.

—
~haddef-sigwen
https://urbit.org

**Comment by urcades** [comment]
Rad, sounds good, ty for enlightening me

**Pull request merged**
