### PR TITLE
interface: pass api object to Mention component

### PR DESCRIPTION
**Pull request by finned-palmer**
fixes https://github.com/urbit/landscape/issues/955

### CODE REVIEW

**Review by jamesacklin — COMMENTED** [review]
Looks good to me, just need to test in situ.

**Comment by finned-palmer** [comment]
> Looks good to me, just need to test in situ.

Cool, is that something I need to do?

**Review by jamesacklin — APPROVED** [review]
Confirmed works in the UI! Thank you for the help.

**Comment by finned-palmer** [comment]
No problem!

**Review by liam-fitzgerald — APPROVED** [review]

**Pull request merged**
