### PR TITLE
interface: adds serviceworker

### PR DESCRIPTION
**Pull request by tylershuster**
This adds a serviceworker with the boilerplate from https://developers.google.com/web/tools/workbox/guides/get-started and starts to cache images. Seems...faster?

Preliminary work to out-of-tab browser notifications and other wondrous splendiferousnesses

@liam-fitzgerald RFC

### CODE REVIEW

**Review by jamesacklin — APPROVED** [review]
I'm not super-familiar with workbox, but this behaves as expected. It appears to properly cache images and display them when the browser is offline.

**Review by liam-fitzgerald — CHANGES_REQUESTED** [review]
Looks ok, will have to add this to the glob so that it'll work in production. Will PR such a change myself.

**Comment by tylershuster** [comment]
Great, I'll clean up the boilerplate

**Comment by tylershuster** [comment]
Obviously this is just a start to get the fiddly bits out of the way to do the real work

**Pull request merged**
