### PR TITLE
various: correctly validate @p

### LINKED ISSUE #2556: invite search: non-hyphenated ships register as valid
Screen Shot 2020-03-19 at 11 07 03 AM

Screen Shot 2020-03-19 at 11 07 06 AM

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Checks that the @p is correctly formatted with hep. 
Fixes #2556

### CODE REVIEW

**Comment by matildepark** [comment]
image

Except not so legit in practice. Sorry. -_-;

**Comment by liam-fitzgerald** [comment]
> image
> 
> Except not so legit in practice. Sorry. -_-;

Which app is this? I'm unable to repro this

**Comment by jtobin** [comment]
Hmm.  I think it'd be better to fix this properly in urbit-ob (and resolve the long-standing urbit/urbit-ob#17).

**Comment by liam-fitzgerald** [comment]
will do!

**Pull request closed without merging**
