### PR TITLE
Dane.bettis/meme hint next

### PR DESCRIPTION
**Pull request by DaneBettis**
This is the development branch for the %meme hint.

The meme hint will have two verbosity modes:
0: slog the arena graph
1: slog all memory info and the graph

### CODE REVIEW

**Review by joemfb — CHANGES_REQUESTED** [review]
I've noted some stylistic issues below.

The only real problem I see is that the string concatenation pattern in this PR leaks memory. `u3i_string()` allocates an atom (on the loom) from a `C` string, while `u3r_string()` allocates a string (on the heap) from an atom. This pattern of combining them leaks both allocations. Let's talk through some alternatives.

**Comment by DaneBettis** [comment]
@joemfb @mcevoypeter should I migrate this MR to be a MR against the `urbit/vere` repo?

**Comment by mcevoypeter** [comment]
Yes, that'd be great. When you do, please read and follow the [updated contributing guidelines](https://github.com/urbit/vere/blob/i/97/md-docs/CONTRIBUTING.md). If you have any questions, let me know.

**Comment by DaneBettis** [comment]
thanks @mcevoypeter! - I am proceeding with this process and will reach out as I find issues or questions

**Comment by DaneBettis** [comment]
@mcevoypeter I am having problems with `bazel build :urbit`.

I am still trying to get to the root problem, but my build machine (on which I have developed all my previous vere hints) is Ubuntu 20.04.4 LTS. 

Here's what I've tried:
1. I installed bazel, autobuild and libtool
2. I tried installing uninstalling musl several ways and finally got the way recommended in your docs working
3. I tried to run `bazel build :urbit` and got errors to the effect of `some c file refers to linux/mman.h`
4. I installed clang using apt, and continued to get these errors, so I added the clang/musl/sys header paths to the the bazel build command via copts. here's the command that got \@openssl:openssl to compile correctly: `~/code/new_vere/vere$ bazel build @openssl//:openssl --copt="-nostdinc" --copt="-isystem /usr/include/x86_64-linux-musl" --copt="-isystem /usr/include" --copt="-isystem /usr/include/x86_64-linux-gnu"`
5. The above command succeeds against a fresh download of `urbit/vere` however, I cannot get `bazel build :urbit` to succeed with these same arguments, which makes sense, as they are getting applied to **every** build dependency and not just openssl.
6. when running `bazel build :urbit` with the same copt flags as above, I have gotten various errors on different runs. I use the `--jobs=1` flag to add determinism to the build process so I can face any one error at a time.
7. Error: `The include path '/usr/include/x86_64-linux-musl' references a path outside of the execution root`: suggested solution: a local bazel repository.
8. I tried to create local repos for the paths needed, per this [issue](https://github.com/bazelbuild/bazel/issues/8846), but so far this has not worked for me, which I suspect has something to do with how openssl is itself configured

I'd really appreciate any advice you can give, as I need to build, migrate my changes, rebuild and test before I feel safe uploading a new PR. 

-Dane

**Comment by mcevoypeter** [comment]
@DaneBettis can you run the following commands and attach the full output as a log file? Doing so will help give me an idea of what's going wrong.
```console
$ bazel run //bazel/toolchain:x86_64-linux-musl-gcc
$ ls -l //usr/local/x86_64-linux-musl/**
$ bazel build --subcommands :urbit
```

**Comment by DaneBettis** [comment]
well.... that just **_worked_**. Thank you!

**Comment by mcevoypeter** [comment]
It looks like it built successfully. Is that because you added hacks to get it to build before, and it's not building again because everything's up-to-date? If so, can you run `bazel clean && bazel build --subcommands :urbit`?

**Comment by DaneBettis** [comment]
To clarify, following your instructions led to the print out I sent you.
after which, I ran `bazel build :urbit` and it worked correctly and yielded a working urbit bin file.
I'm now rerunning your most recent commands for completeness sake, but I think everything is now working...

Yup, urbit is compiling. I can now add and test my changes.

**Comment by DaneBettis** [comment]
@joemfb @mcevoypeter should this most recent force pushed commit of mine have run any CI against my arvo tests?

**Comment by DaneBettis** [comment]
@joemfb any other thoughts on this PR?
It is now just the addition of `%meme` tests to `hints.hoon` based upon the `develop` branch.

**Review by joemfb — APPROVED** [review]
this will do

**Pull request merged**
