### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vvisigoth**

### CODE REVIEW

**Comment by joemfb** [comment]
@vvisigoth, fine to merge this into release-candidate instead? That way it can go to master with everything else.

**Comment by vvisigoth** [comment]
ah yeah! I'll put it there.

**Comment by joemfb** [comment]
I re-pointed this PR, you can just force-push to your branch.

**Comment by Fang-** [comment]
The Etherscan should be changed to be `https://etherscan.io/address/azimuth.eth`, now that we've set the ENS domains. We might also want to replace the long ugly addresses for Azimuth and Ecliptic with their .eth equivalents everywhere.

**Comment by joemfb** [comment]
I added `azimuth.eth` after the address, just as the launch post does.

**Pull request merged**
