### PR TITLE
interface: bring npm packages inline with userspace

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Also makes them typecheck. I can't work out how the hell i can pr against a foreign branch so here we are. The last three commits are the changes i've made.

### CODE REVIEW

**Comment by liam-fitzgerald** [comment]
cc: @tylershuster

**Comment by tylershuster** [comment]
nice

**Comment by matildepark** [comment]
You should be able to just check out Tyler’s fork and push straight to the PR’d branch.

**Comment by matildepark** [comment]
So @tylershuster should I just merge? Seems like nothing left.

**Comment by tylershuster** [comment]
I'm fine with it

**Comment by tylershuster** [comment]
> What is next-js for?

**Comment by matildepark** [comment]
It's for catching stuff before hitting livenet

**Comment by tylershuster** [comment]
Shall we catch some stuff?

**Comment by matildepark** [comment]
Your npm PR, if we just merged it, would’ve broken everything on devnet because old api... so I’m glad I made Liam test. Can you run this locally and do a run through?

**Comment by tylershuster** [comment]
I was able to clone and run this branch. In order to compile it I had to publish the two NPM packages that weren't already in the repository.

**Comment by tylershuster** [comment]
We'll want to bump `http-api` as well due to liam's changes

**Review by matildepark — APPROVED** [review]
Can also confirm basic functionality preserved. Let's do this.

**Comment by tylershuster** [comment]
so it begins

**Comment by matildepark** [comment]
I sort of feel like we can't publish these packages until they hit master, but we can confirm it's stable before a merge early next week and I think you are unblocked for state hooks, etc? @tylershuster

**Comment by tylershuster** [comment]
I already published them just to get them to compile. They're usable, I have no problem with people using them. But they're not exactly *polished*, which I will do before it hits master and we can announce it or whatever.

**Pull request merged**
