### PR TITLE
Chat: Clarify "Leave" message, add "Home" screen content

### PR DESCRIPTION
**Pull request by matildepark**
UX tweak. 

- Changes "Leave this chat." to "You will no longer have access to this chat."
- Adds some basic home page copy so that the /~chat route is not blank.

This was presenting confusing UX when leaving or deleting chats and being pushed to the /~chat route.

Screen Shot 2019-08-21 at 12 45 32 AM

- Also removes the underline from the "Leave" (or "Delete") button. This fits the most recent mockups, as far as I can tell — though it leaves our buttons inconsistent in style. Specifically, "Create" still uses underlines — as does accepting or rejecting an invitation, as well as removing ships from a chat.  

Tagging @g-a-v-i-n for opinion (though I've asked out of band, too).

Screen Shot 2019-08-21 at 1 02 02 AM

### CODE REVIEW

**Comment by loganallenc** [comment]
I think we should generally take a policy of being consistent over being up to date with mocks. @g-a-v-i-n Feel free to correct me here

**Comment by matildepark** [comment]
Then I would suggest I also put it back on "-> Invite" as well, since it doesn't have an underline and would be the only thing that does not.

**Comment by matildepark** [comment]
This is good to go now, I just have to rebase it before it can be merged. Also it needs an approval.

**Comment by loganallenc** [comment]
Great, thanks Matilde.

**Pull request merged**
