### PR TITLE
switch stars

### PR DESCRIPTION
**Pull request by galenwp**

### CODE REVIEW

**Comment by juped** [comment]
This should be /urbit-meta because of federation, right?

**Comment by galenwp** [comment]
Comets don’t see the federation.  Could give both options.

**Comment by philipcmonk** [comment]
We definitely want planets to use their own parent.  Ideally we'd divide the comets up, but putting them on one is probably fine for now.

**Comment by juped** [comment]
It's not federated to ~zod? Seems like a simple fix.

**Comment by galenwp** [comment]
But risky since ~zod carries all the load of starting comets?

**Comment by philipcmonk** [comment]
I'd argue strongly against putting talk stuff on ~zod

On Mon, Aug 15, 2016 at 2:38 PM, Galen Wolfe-Pauly <notifications@github.com

**Comment by cgyarvin** [comment]
Blacking up Philip

**Comment by cgyarvin** [comment]
I mean, backing up Philip

**Comment by galenwp** [comment]
Can we merge this?  Someone just emailed being confused.

**Pull request merged**
