### PR TITLE
btc-wallet: Fix various issues in prod release last night

### PR DESCRIPTION
**Pull request by finned-palmer**
@ixv there were a few issues in the bitcoin wallet release branch that got merged into master, all fixed here. Can we get this into master out as an OTA today?

@timlucmiptev

### CODE REVIEW

**Comment by finned-palmer** [comment]
This fixes issues in prod, @jalehman @belisarius222

**Comment by ixv** [comment]
There's an issue with the fee payment drop down, it behaves erratically with buttons sometimes requiring several clicks to work. It also no longer lets you click outside the modal to dismiss it.

I also noticed you can't click outside the central panel on the signing pages to cancel the transaction. I don't know if this was done deliberately, but if it was we need at least some way to cancel transactions that isn't just refreshing the page.

**Comment by finned-palmer** [comment]
On this branch? Taking a look now.

**Comment by ixv** [comment]
yeah this branch

**Comment by finned-palmer** [comment]
@ixv just fixed the issues you noted.

**Review by ixv — APPROVED** [review]
Thanks, looks good

**Pull request merged**
