### PR TITLE
Publish: various fixes and improvements

### PR DESCRIPTION
**Pull request by ixv**
- Properly handle edge cases in blog/post naming.
- Fixed auto-resizing of blog title input field
- Changed some spacing on next/prev components
- Fixed header bar path state transition when clicking next/prev
- Added launch, chat, publish, clock, and weather to comet default apps
- Fixed \<hr\> tag rendering in blog posts
- Fixed unread notification logic and added unread badges to post previews

### CODE REVIEW

**Comment by joemfb** [comment]
Is there a more general solution to this problem that manifested with `<hr/>`? Can we at least put a try/catch around the udon-html rendering and render errors to the user? That way they could at least edit blindly -- that's painful, but better than console errors.

**Comment by ixv** [comment]
Fair criticism, I'll add that to my task list.

**Comment by jfranklin9000** [comment]
Would it be possible/desirable to make the udon parser just pass the rest of the unparsed udon straight through after it detects a problem?  I'm working on the udon syntax highlighter and need to know how to handle parser errors.  This is what I'm doing now:
buchax
hax
If you see red in the highlighter you'll know you won't get any output.

**Comment by ixv** [comment]
Like pass through as plain text? I think partial rendering like that would be difficult, we could potentially just pass through the whole file as plain text in the case of an error though.

I think the real benefit of having a syntax highlighter than can detect errors is being able to just prevent the user from posting broken udon at all.

**Comment by jfranklin9000** [comment]
Yes, that's the approach I'm going to take: flag errors in the highlighter and not touch the parser.

**Pull request merged**
