### PR TITLE
all: fixes error stack trace in dark mode

### LINKED ISSUE #3530: all: error messages don't respect dark mode
All browsers in dark mode:
image

### PR DESCRIPTION
**Pull request by tylershuster**
fixes #3530

image

### CODE REVIEW

**Comment by matildepark** [comment]
What's the white block thing at the bottom there?

**Comment by tylershuster** [comment]
horizontal scrollbar

**Comment by tylershuster** [comment]
new pr?
image

**Comment by matildepark** [comment]
O:

**Comment by matildepark** [comment]
image

୧((#Φ益Φ#))୨

**Comment by matildepark** [comment]
I think you can probably get around this by making `styled.summary` or whatev and passing it `color="black"`

**Comment by tylershuster** [comment]
Indigo 1.2 has `DisclosureBox` and `DisclosureButton` but it seems like the naming has changed since the current version, which just has `DisclosurePanel` and `DisclosureButton`. @g-a-v-i-n should I implement those now or wait for 1.2?

**Comment by matildepark** [comment]
1.2 is out, we just need to migrate and I need to talk to Liam about the stuff to cover (a bunch of renaming and removing of code editor stuff, tabs, etc. makes it a bigger task than one would think). I'd just do the styled element here to unblock and we can refactor it into the disclosure after.

**Comment by tylershuster** [comment]
This doesn't work; the arrow totally disappears

**Comment by tylershuster** [comment]
Wait no never mind. The arrow thing was my problem. This works.

**Review by matildepark — APPROVED** [review]
lgtm

**Comment by matildepark** [comment]
CI fail unrelated

**Pull request merged**
