### PR TITLE
publish group paths

### PR DESCRIPTION
**Pull request by ixv**
Changed the publish api so that group paths are passed through from the frontend rather than generated on the backend (except in cases where they must be generated on the backend).

also included a minor bugfix in this PR.

### CODE REVIEW

**Comment by vvisigoth** [comment]
This looks good. Question, though, under what circumstances does the path need to be mad on the backend?

**Comment by ixv** [comment]
When you import a notebook with clay and the paths are nulled, or you have an old version of the publish-info mark. It defaults to /~/publish/<ship>/<notebook>/write or /read

**Comment by vvisigoth** [comment]
ah got it.

**Comment by vvisigoth** [comment]
Go ahead and merge.

**Pull request merged**
