### PR TITLE
dojo: support running other-desk generators

### PR DESCRIPTION
**Pull request by Fang-**
Syntax is `+desk#gen`. The `#` is just a placeholder (as is tradition), and I'd be happy to take suggestions/votes on the real thing. I was thinking `+desk>gen` maybe?

`:app|gen` de-sugars to `:app +desk#gen`, where the desk is the desk the app is running on.

`:app|desk#gen` is currently broken, in the sense that the above de-sugaring takes precedence, overwriting the manually specified desk with the desk where the app is running.

The `+on-load` here just aborts any running user action to avoid having a monstrously large state adapter.

### CODE REVIEW

**Comment by ohAitch** [comment]
What does +term/gen currently do?

**Comment by ohAitch** [comment]
(For example `+/=desk==name` would be more compositional, but kind of a mouthful)

**Comment by Fang-** [comment]
> What does +term/gen currently do?

It runs the generator in `/gen/term/gen.hoon`.

**Comment by ohAitch** [comment]
Actually hm, `+desk%foo` as a shortening of `/=desk%/foo`(again wrt `/===gen` as %) would be not completely terrible

**Comment by ryjm** [comment]
`+desk!gen` ala `Dark!Harry`

desks are just urbit fanfics

**Comment by joemfb** [comment]
Is there a need for this separate from changing the working directory? Ie, would the following be sufficient?

```
=dir /=desk=
+gen
```

**Comment by belisarius222** [comment]
maybe we could do like %= syntax?

+gen(dir /=desk) arg

—
~rovnys-ricfer
https://urbit.org

**Comment by Fang-** [comment]
> Is there a need for this separate from changing the working directory?

@joemfb This is precisely so you don't _have_ to continuously change the working directory. Certainly needing to do so for the `:app|gen` case is dumb.

**Comment by belisarius222** [comment]
I'll confirm that needing to change dir to run generators for agents on other desks is annoying and error-prone.

—
~rovnys-ricfer
https://urbit.org

**Comment by Fang-** [comment]
CI errors should be fixed by pills on latest dist. @belisarius222 gave his approval out of band.

**Pull request merged**
