### PR TITLE
invites: don't pin to top

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
- Removes pinning of invites to top
- Adds ability to hide join requests

### CODE REVIEW

**Comment by matildepark** [comment]
We can probably squeeze this into the la/release-2021-3-5 branch if @tacryt-socryp reviews and finds it innocent enough to test alongside the graph work.

**Comment by tacryt-socryp** [comment]
Plz no

**Comment by matildepark** [comment]
These are pretty innocent changes that we’d be testing on ropsten anyway.

**Comment by matildepark** [comment]
Targetting next-userspace, we'll just test in the QA period.

**Review by tacryt-socryp — APPROVED** [review]
LGTM

**Pull request merged**
