### PR TITLE
eyre + interface: use font-display: swap; to reduce time to paint text

### PR DESCRIPTION
**Pull request by tacryt-socryp**
https://web.dev/font-display/?utm_source=lighthouse&utm_medium=unknown

Fixes https://github.com/urbit/landscape/issues/762

### CODE REVIEW

**Comment by tylershuster** [comment]
Why are we still serving from media.urbit.org? I thought we moved these to local host

**Comment by matildepark** [comment]
> Why are we still serving from media.urbit.org? I thought we moved these to local host

Those two fonts don't actually exist on localhost, so they were constantly hitting 404 in console, so I removed the localhost lines. The others do exist. Note that we should serve from urbit.org as a fallback.

**Review by matildepark — APPROVED** [review]
lgtm, can probably just go out with https://github.com/urbit/urbit/pull/4748 since it changes eyre (however trivially).

**Review by liam-fitzgerald — APPROVED** [review]
LGTM! Wondering if this should be split into two commits and deployed seperately, given that the majority of the improvement here is on userspace side

**Comment by tacryt-socryp** [comment]
Seems safe to me regardless. We primarily care about separating sys and userspace deploys so that things affecting vane logic can be properly debugged etc

**Comment by tacryt-socryp** [comment]
is this ready?

**Pull request merged**
