### PR TITLE
fix ++lore and ++role

### PR DESCRIPTION
**Pull request by juped**
@chc4 pull request, wrongfully deleted by GH. Unfinished (sorry, will get to it asap!).

### CODE REVIEW

**Comment by chc4** [comment]
No problem, I know the merging of this is pretty involved. It's not a high priority thing.

**Comment by juped** [comment]
It's not really that tough, I've just been slacking on it. Though, now that I think of it, we do have that thing where event logs randomly get corrupted when you rebuild and reload...

**Comment by philipcmonk** [comment]
Since we're breaching, this can just go in, right?

**Comment by juped** [comment]
The marks will be wrong.

**Comment by philipcmonk** [comment]
i'll fix those real quick

**Comment by juped** [comment]
:+1:

**Pull request merged**
