### PR TITLE
handle ._~~__ many/~[`n/0] compilation properly

### PR DESCRIPTION
**Pull request by ohAitch**
Type was atom/%n, whould be cube/[0 atom/%n]
Cherry-pick of hoon164 005903

Jet of urbit/arvo@8540e1c, impure push signed off by @cgyarvin

### CODE REVIEW

**Comment by juped** [comment]
Did that (the arvo one) get undone in the Curtis 151 merge? I tried to keep a careful lookout for things like that...

**Comment by ohAitch** [comment]
Yes, as did the C one. The relevant part of the compiler was restructured,
dtzy changed to sand, etc., so I wasn't too surprised, but
whatever-005903-is-now-called definitely didn't survive the merge.

**Comment by juped** [comment]
The whole idea of merging is that everything *does* survive...

Seminars incoming

Yours,
r

**Comment by ohAitch** [comment]
Yes please.

I'm guessing the conflict showed up among a bunch of other changed/deleted
markers in jets/?/ut*.c, most of which were in fact obsolete.

**Comment by juped** [comment]
It should have been the only conflict in the file.

Yours,
r

**Comment by ohAitch** [comment]
Okay yeah, rerunning `git checkout fd001d5; git merge 10ff0c8` gets that as the _only conflict in the merge_, though of course there would have also been urb/zod ones.

**Pull request merged**
