### PR TITLE
ci: add ota-on-merge flow for next/arvo

### PR DESCRIPTION
**Pull request by jtobin**
#6111 

Adds a GitHub action & workflow for making OTA updates to arvo on a remote ship.  The workflow is configured to deploy an OTA to the kernel canary moon (~binnec) on every push to next/arvo, and will go live as soon as this PR is merged.

(Also guts a bunch of deprecated workflows.)

### CODE REVIEW

**Comment by jtobin** [comment]
Yeah, I tested the flow by initially having it run on pushes to this branch (instead of next/arvo), and when it did run it would only sync the files to %base (without committing them).  I then retargeted things to run on pushes to next/arvo and removed the `--no-commit` flag when everything seemed ship-shape.

It should be ok, and at minimum nothing should outright explode when it starts running.

**Review by zalberico — APPROVED** [review]

**Comment by joemfb** [comment]
Should this deployment be gated on CI success?

**Comment by zalberico** [comment]
Yeah, stuff shouldn't merge with broken CI.

**Comment by jtobin** [comment]
There's no *formal* mechanism here checking for CI success, the working assumption being that stuff just doesn't get merged if it breaks CI.  But it's possible to add some stuff to execute conditionally on the success of another jobs.

Thoughts?

**Comment by matildepark** [comment]
It might introduce a case where it invisibly doesn't deploy something people in the future expect it to because, well, say there's nebulous long-lasting false negative CI results. It would lead people to merge anyway, but then because of lack of institutional knowledge it doesn't go out and models of "what's on canary" diverge between people.

**Comment by jtobin** [comment]
Yeah I'm inclined to agree that gating merges should be sufficient, but don't have terribly strong feelings either way.

**Comment by zalberico** [comment]
Yeah, deploy should happen on merge no matter what. People shouldn't merge if CI is broken. If people merge when CI is broken and it kills the canary (or breaks CI on all figure commits blocking merge) the person that merged that is responsible for fixing.

**Comment by zalberico** [comment]
@jtobin - I’ll send a company wide email today about this (just to make sure non-core devs don’t have binnec unexpectedly set for OTAs), but after that I think we’re good to merge. Once I send that, can you merge this and then keep an eye on it to make sure deploys work as expected?

**Comment by jtobin** [comment]
Sure thing.

**Comment by zalberico** [comment]
Email went out - you're good to merge when ready.

**Pull request merged**
