### PR TITLE
Don't unlock mutex when exiting; it crashes for some reason.

### PR DESCRIPTION
**Pull request by cgyarvin**

### CODE REVIEW

**Comment by juped** [comment]
Rejected, you committed DEBUG=yes. How did you even do that?

**Comment by cgyarvin** [comment]
Terrible!

**Comment by cgyarvin** [comment]
I fixed it, but "a pull request already exists."

**Comment by juped** [comment]
Seminars.

**Comment by juped** [comment]
Merged in eea4758

**Pull request closed without merging**
