### PR TITLE
Interface monorepo

### PR DESCRIPTION
**Pull request by loganallenc**
Add all interface files to monorepo for easier integration and builds.

For the past 3 months, the process for app development on top of Urbit has been relatively heavy-weight and has required keeping track of two copies of the same Hoon files.

The urbit/interface repository has contained all of the JS files served in the interfaces, and the most upstream versions of all app files, mark files, and lib files needed for the userspace applications to run.

This led to inconsistencies in code versions between the urbit/arvo repository and the urbit/interface repository. This seems unnecessary and detrimental to both @ixv and me.

The included PR changes the build system of the interface files to the most minimal extent possible to allow them to use the Hoon files in pkg/arvo as the main source of truth for doing application development. It also adds a `make interface` command to the high-level Makefile in urbit/urbit so that we can make the first step towards unifying the build process of the entirety of Urbit.

### CODE REVIEW

**Comment by ixv** [comment]
Does anyone have any objections to mono-repoing this? I would like to do it sooner rather than later to avoid messy integration with the interface repo.

**Comment by eglaysher** [comment]
I think monorepoing so we have one build process is pretty neato.

**Comment by eglaysher** [comment]
If I may recommend one thing: you should use git-subtree to maintain the history of the interface repo instead of just copying the files over.

**Comment by loganallenc** [comment]
Thanks @jtobin. I updated the rationale for the PR. I believe @ixv is using git-subtree to include the interface history.

Thanks!

**Comment by ixv** [comment]
Alright, I just added the git-subtree stuff, and some minor changes to the build process.

I think it'll take a little more work to get the build process to be exactly what we want, but I think this is probably okay for our present purposes.

**Pull request merged**
