### PR TITLE
publish: amend snippets, add images to snippets

### PR DESCRIPTION
**Pull request by matildepark**
After #3989 I noticed our `md` class didn't have styling for non-`<p>` characters, which our body content used for stripping headers and the like, leading the layout to look quite uneven.

This PR makes `getSnippet` take up until the first `\n` character as of index `2` to get the first line; wraps the snippet in indigo-react, sidestepping the CSS styling with its "sometimes 14px margin-bottom, sometimes 2px" due to not every snippet having a paragraph element.

I also went ahead and rendered image previews if the first line is an image, containing it in a 300px block.

Before / after (note "On Odyssey" being smaller even though it's header copy, because we're escaping headers in the snippet):

Screen Shot 2020-11-25 at 12 19 42 AM

Screen Shot 2020-11-25 at 12 18 53 AM

### CODE REVIEW

**Review by liam-fitzgerald — APPROVED** [review]
nice!

**Comment by matildepark** [comment]
@urcades I'm struck that we could just ape the new Links layout here anyway.

**Comment by urcades** [comment]
Yeah, for some context into how we've been thinking about evolving these interfaces, refer to the Big Model for Landscape in figma here:

https://www.figma.com/file/ovD1mlsYDa0agyYTdvCmGr/Landscape?node-id=2030%3A43755

Here are comparison images too:

Collections:

Screen Shot 2020-11-25 at 1 37 04 PM

Notebooks:

Screen Shot 2020-11-25 at 1 37 52 PM

Would it make sense to perform the same styling updates in this PR?

**Comment by matildepark** [comment]
I can see what I can do today but this MVP PR is still an improvement over what's in next-userspace

**Comment by urcades** [comment]
Yeah, totally Agree – initially spec'd changes are more than fine for now.

**Comment by vvisigoth** [comment]
thank god
—
~poldec-tonteg
http://urbit.org

**Comment by matildepark** [comment]
Screenshot 2020-11-25 at 3 37 31 PM

**Pull request merged**
