### PR TITLE
webterm: migrate to indigo-react

### PR DESCRIPTION
**Pull request by matildepark**
I thought this was already done in the Term work, but it wasn't, so I just do it here. Tested on desktop and on iOS, works normally. Matches code styling in chat.

cc @urcades

### CODE REVIEW

**Comment by urcades** [comment]
Stamp from me

**Review by Fang- — CHANGES_REQUESTED** [review]
Neat, thanks for cleaning up my mess. That screenshot doesn't look quite right though, the output from `azimuth` should look like so:

image

Guessing something got lost in the classname->prop translation, but it's not immediately obvious to me what.

**Comment by matildepark** [comment]
Cracked the dev environment open again and looks fine?

EBB399BB-D980-48E8-AB82-F57B5486A64B

**Review by Fang- — APPROVED** [review]
Ok, looks all good then! Thank you.

**Pull request merged**
