### PR TITLE
App: filtering props from html

### PR DESCRIPTION
**Pull request by arthyn**
Fixes urbit/landscape#975

### CODE REVIEW

**Review by liam-fitzgerald — COMMENTED** [review]
Does this fix it globally, or just for this component?

**Comment by arthyn** [comment]
Does not fix globally, we'd have to probably make our own wrapper for `styled` and change all instances of styled or maybe switch to using "transient" props as they describe here: https://github.com/styled-components/styled-components/releases/tag/v5.1.0

**Comment by matildepark** [comment]
> Does this fix it globally, or just for this component?

Do we even see this in other components?

**Comment by zalberico** [comment]
@arthyn same question here - is this little change good to clean up and merge or should we close it?

**Pull request closed without merging**
