### PR TITLE
all: added fullscreen button

### PR DESCRIPTION
**Pull request by tylershuster**
RFC. I always have urbit open and on a mac it's nice to have something take up the full 'space' or whatever they're called. Feels nice.

### CODE REVIEW

**Comment by matildepark** [comment]
I don't think it's really necessary to have in the status bar, honestly?

**Comment by tylershuster** [comment]
Think a hotkey would be better?

**Comment by galenwp** [comment]
Isn't this normally done by making the browser fullscreen?

**Comment by tylershuster** [comment]
You still get browser chrome, at least in Firefox

**Comment by matildepark** [comment]
That's all this does — it's a button in the header bar to tell the browser to full screen.

**Comment by tylershuster** [comment]
Not quite...make your browser full screen versus pasting this in:
`document.addEventListener('click', () => document.documentElement.requestFullscreen())`
and then clicking on the page.

**Comment by tylershuster** [comment]
(I am not attached to this, but I do think it's neat)

**Comment by galenwp** [comment]
In chrome there's no chrome. I guess I'd have to see it. I'm always trying to remove as many buttons as possible. @urcades can also weigh in.

**Comment by matildepark** [comment]
pinging @urcades who just got back

**Comment by urcades** [comment]
I did some digging and it turns out this is a specifically annoying firefox trait while full-screening the browser. I still need to test Edge browser, but currently i'm witnessing Safari and Chrome both initialize chrome-less fullscreen as desired. 

I'd be cautious to introduce another non-visual (keyboard shortcut triggered)  feature specifically tailored to one browser, but I'd prefer we resist implementing new buttons/interface for a feature that should really be handled by the browser/OS.

**Comment by tylershuster** [comment]
Alright, Firefox maximalists strike out again

**Pull request closed without merging**
