### PR TITLE
hoon: remove legacy syntax support

### PR DESCRIPTION
**Pull request by Fang-**
Happy thanksgiving, and merry merge conflicts to all! I hope you're hungry, because this thing's _big_.

This PR removes deprecated type syntax (the `{a/@ b/?($x $y)}` kind) from all source code, and removes support for it from the compiler. Additionally:

- removes `+=` and `+-` arm syntax,
- removes deprecated names for the character parsers,
- updates test running to not fall over on non-test files (so you can just run `-test %` to test-build the entire desk, maybe we want that in CI too?),
- removes an unused, broken group library,
- fixes broken thread files,
- updates vane tests to account for the new shape of the scry gate.

Based off of @joemfb's `jb/candidate` to avoid conflicts with that.

I've gone over the changes best I could, and am fairly confident nothing was changed in error. I'd ask you, dear reader, for a scroll through the changelist, but the effort:value ratio seems dubious. If boredom strikes you though, do feel free!

### CODE REVIEW

**Comment by jfranklin9000** [comment]
The diff of `pkg/arvo/gen/deco.hoon` looks incomplete, or maybe shouldn't be there at all?

**Comment by jfranklin9000** [comment]
`pkg/arvo/lib/group-store.hoon` line `312`

**Comment by ohAitch** [comment]
Has every single .hoon file on this branch been successfully compiled under
the resulting hoon.hoon?
:test [%cores /]
Should run through that iirc

**Comment by jfranklin9000** [comment]
`pkg/arvo/lib/pprint.hoon` line `160`, extra space in tuple

**Comment by jfranklin9000** [comment]
`pkg/arvo/lib/generators.hoon` line `30`, comment indent

**Comment by jfranklin9000** [comment]
`pkg/arvo/mar/dill/belt.hoon` line `27`, incomplete conversion

**Comment by jfranklin9000** [comment]
`pkg/arvo/mar/snip.hoon` line `60`
Should this be `++  noun  ,[marl marl]` or `+$  noun  [marl marl]`?
Sorry for the noise if not.

**Comment by jfranklin9000** [comment]
`pkg/arvo/sys/vane/clay.hoon` line `1725`
I think the comment meant "Add and/or change" and shouldn't have been converted.

**Comment by jfranklin9000** [comment]
`pkg/arvo/sys/zuse.hoon` lines `5632`, `5686`, `5705` and `5722`, incomplete conversion
lines `6930` and `6931`, incomplete conversion?

**Comment by Fang-** [comment]
@jfranklin9000 looks like most of these are comments, but good catches regardless. Thank you, I'll clean them up!

> Has every single .hoon file on this branch been successfully compiled under the resulting hoon.hoon?

@ohAitch Yes, I did so using `-test %`.

**Comment by jfranklin9000** [comment]
`pkg/arvo/sys/hoon.hoon` line `8469`, incomplete conversion (comment)

**Comment by jfranklin9000** [comment]
`pkg/arvo/app/dojo.hoon` line `57`, comment shouldn't have been converted?

This concludes my review.

I do have one question:  In `pkg/arvo/sys/vane/jael.hoon` line `275` you deleted up a stray `}`, but how did it compile before you cleaned it up?

**Comment by Fang-** [comment]
Thanks @jfranklin9000, appreciate it. The reason it compiled before (and the reason everything else compiled despite these partial conversions) is that this is commented-out code!

Very nice catch on the `/mar/snip`. I'm a bit confused by it though. `,[marl marl]` seems like it should be correct, and indeed when we test a minimal case:

```hoon
> =>  |%  ++  x  ,[marl marl]  --
  (x [*marl *marl])
[~ ~]
```

But when we try to use it within the mark:

```hoon
> &snip [*marl *marl]
[%grab %snip %noun]
mull-nice
- need
[ ?(i=%~ i=[i=#3 t=it(#3)])
  ?(
    t=%~
      t
    [ i=[g=[n=?(@tas [@tas @tas]) a=it([n=?(@tas [@tas @tas]) v=""])] c=it(#3)]
      t=it(^#3.[g=[n=?(@tas [@tas @tas]) a=it([n=?(@tas [@tas @tas]) v=""])] c=it(#3)])
    ]
  )
]
-have.%~
nest-fail
```

**Review by joemfb — APPROVED** [review]
LGTM. And thank you!

**Pull request merged**
