### PR TITLE
publish: add more join spacing

### PR DESCRIPTION
**Pull request by matildepark**
Addresses #3518.

@urcades This still feels a little odd?

Screenshot 2020-09-18 at 9 53 32 PM

### CODE REVIEW

**Comment by urcades** [comment]
I'll have a design available for this soon. Right now, we have about 2/3s of the module's "joining/loading" interfaces normalized, and publish/notebooks happens to be the one third that is lagging here.

**Review by liam-fitzgerald — APPROVED** [review]
LGTM!

**Comment by urcades** [comment]
Some general sketches around how these loading states should be associated with the surrounding interface in chat, links/collections, and publish respectively:

Screen Shot 2020-09-21 at 7 18 51 PM

Screen Shot 2020-09-21 at 7 19 19 PM

Screen Shot 2020-09-21 at 7 19 41 PM

Each of the listed interfaces make their appearance in the latest groups specification, and essentially reconfigure the 'top bar' of each module to incorporate the channel name, description, and some additional information + settings aligned right in the bar. These loading interfaces populate another bar situated directly underneath these headers.

**Comment by matildepark** [comment]
Closing this in favour of a renovation in the new group layout.

**Pull request closed without merging**
