### PR TITLE
Write http ports to .urb/ports.json

### PR DESCRIPTION
**Pull request by ohAitch**
Review requested from @cgyarvin

### CODE REVIEW

**Comment by juped** [comment]
This should follow the same discipline as `.vere.lock` and only exist while running (and it would be great if it were text not JSON)

**Comment by ohAitch** [comment]
Disappearing on graceful exit sounds reasonable, I'm at phrasebook
proficiency level in C and was trying to do the most straightforward "write
a file" possible.

It would not be great if this were text not JSON, this is a scripting
interface and I don't want to write ad-hoc TSV parsers in 20 different
languages <3 (I could see an argument for it being a directory full of
files, but the setup / teardown would be a bit involved. Also, JSON has the
virtue that if you suffer ^Z or other interrupt and end up only writing
'{"loopback":31337,"localhost":808', this is obvious to the consumer in a
way that e.g. "loopback 31337\nlocalhost 808" isn't, nor the "files in a
directory" equivalent)

**Comment by ohAitch** [comment]
I am somewhat leery about  c3_c ful_c[2048], but see: attempting to avoid
doing anything too clever.

**Comment by juped** [comment]
Because of this, you wrote shell scripts that depend on someone's JSON parser off the web when you could have used the shell; I was not amused to discover this. (Not to mention the ad-hoc JSON generator here.) JSON has no place in Unix glue.

My preferred patch (as a C and Unix literate):

```
diff --git a/vere/http.c b/vere/http.c
index 02379c7..ebeb08f 100644
--- a/vere/http.c
+++ b/vere/http.c
@@ -1088,6 +1088,50 @@ _http_start(u3_http* htp_u)
   }
 }
 
+/* _http_write_ports_file(): update .http.ports
+*/
+void
+_http_write_ports_file(c3_c *pax_c)
+{
+  c3_c paf_c[2048];
+  FILE *por_u;
+  u3_http *htp_u;
+
+  snprintf(paf_c, 2048, "%s/%s", pax_c, ".http.ports");
+  fprintf(uH, "snprintfed\n");
+
+  if ( NULL != (por_u = fopen(paf_c, "r")) ) {
+    fprintf(uH, ".http.ports already existed - clearing it\n");
+  }
+
+  fclose(por_u);
+
+  por_u = fopen(paf_c, "w");
+  for ( htp_u = u3_Host.htp_u; htp_u; htp_u = htp_u->nex_u ) {
+    fprintf(por_u, "%u %s %s\n", htp_u->por_w,
+                   (c3y == htp_u->sec) ? "secure" : "insecure",
+                   (c3y == htp_u->lop) ? "loopback" : "public");
+ }
+
+ {
+   c3_i fid_i = fileno(por_u);
+   c3_sync(fid_i);
+ }
+ fclose(por_u);
+}
+
+/* _http_release_ports_file(): update .http.ports
+*/
+void
+_http_release_ports_file(c3_c *pax_c)
+{
+  c3_c paf_c[2048];
+
+  snprintf(paf_c, 2048, "%s/%s", pax_c, ".http.ports");
+
+  unlink(paf_c);
+}
+
 /* u3_http_io_init(): initialize http I/O.
 */
 void
@@ -1159,6 +1203,8 @@ u3_http_io_talk()
   for ( htp_u = u3_Host.htp_u; htp_u; htp_u = htp_u->nex_u ) {
     _http_start(htp_u);
   }
+
+  _http_write_ports_file(u3_Host.dir_c);
 }
 
 /* u3_http_io_poll(): poll kernel for http I/O.
@@ -1173,4 +1219,5 @@ u3_http_io_poll(void)
 void
 u3_http_io_exit(void)
 {
+  _http_release_ports_file(u3_Host.dir_c);
 }
```

**Comment by ohAitch** [comment]
I pulled in a fairly popular piece of json<->shell glue, yes, because I was attempting to interact with an interface primarily designed for urb.py; I could trivially replace `jq .localhost $ship/.urb/ports.json` with `node -p  "require('$ship/.urb.ports.json').localhost"` if that would be better, but I get the impression that's not where your disagreement lies. (I suppose node is also "someone's JSON parser off the web", but by that definition so is sed in the `sed -n '/^loopback/ s/[^0-9]//gp` case.)

I would in fact have significantly preferred to use e.g. hoon JSON facilities, but doing that from C would probably have been way less readable; "plain text" generators and parsers are however always ad hoc, in the "lack a formal specification" sense.

**Comment by juped** [comment]
Here's a formal specification:

```
.http.ports ABNF Format Specifiation
Version 0.1, 12 December 2016

http-ports-file = *(http-ports-line LF)

http-ports-line = port-num secure-val loopback-val

; number of a port being listened on
port-num = *DIGIT
; whether the http subsystem has the port marked as "secure"
secure-val = ("secure" / "insecure")
; whether the port is bound only on loopback or on all interfaces
loopback-val = ("loopback" / "public")
```

Will add to spec directory.

**Comment by ohAitch** [comment]
...just noticed that the patch wasn't you quoting my ad-hoc generator, my bad. (Emailing raw patches around is The Git Way, and I have sinned). That is what I meant by "TSV" yes, though I suppose WSSV as is more correct/unixy; you did mean `port-num secure-val loopback-val` to be `port-num SP secure-val SP loopback-val` right?

If sed is the official way to collapse `.http.ports` down into a single `port-num` value, or regex for python, I am still slightly worried about free-formedness, but not going to press the point. Having a grammar for something of this scale feels twee but is still appreciated, esp if you can plausibly keep out any future PRs that would violate it; the whole reason I went with json and not just like "$insecure-port $vouched-secure-port $loopback-port" was extensibility wrt urbit having future interesting ports, but presumably those could just be added backwards-compatibly to the grammar.

**Comment by juped** [comment]
The excessive formality of ABNF is tongue in cheek (and yeah, I forgot the SPs), but there's no reason not to write down the specification.

`for p in `grep loopback .http.ports | cut -d ' ' -n 1`; do something $p; done` btw

**Comment by ohAitch** [comment]
I do object to `"secure"` instead of `"\"secure\""`, the whole point is the port is completely unencrypted but is trusted by urbit to represent an https connection.

**Comment by juped** [comment]
Backslash hell is real, I'll go with trusted

**Comment by ohAitch** [comment]
The `for p in` seems very unlikely to be actually the behavior you want on multiple/no loopback ports found, but otherwise seems reasonable. Python equivalent
```python
with open(args.pier + '/.urb/.http.json', 'r') as file:
     for port, _, loop in csv.reader(file,delimiter=' '):
         if loop is "loopback"
           PORT = port
```

**Comment by ohAitch** [comment]
Trusted sounds more like what loopback is doing tbh, "as-https" maybe?

**Comment by ohAitch** [comment]
(Also honestly just `.loopback.port` containing `12321` wouldn't be terrible, writing all of them down was just easier / maybe cleaner than trying to figure out which was which)

**Comment by ohAitch** [comment]
Like I can totally see auto-configuring nginx or whatever based on the current version, but this is unlikely to happen within idk the next 6 months

**Pull request closed without merging**
