### PR TITLE
chat-js: fix scroll slam

### LINKED ISSUE #2864: Chat slams to bottom on getting a new message
We only want Chat to slam to bottom when *we* send a message, not when we get one, as per @urcades.

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Locks the scroll upon scrolling half a screenful or 200px from the
bottom, whichever comes first. Correspondingly unlocks the scroll upon
scrolling inside this distance. 

fixes #2864 

cc: @urcades

### CODE REVIEW

**Comment by matildepark** [comment]
This really should just be one commit.

**Comment by matildepark** [comment]
In testing, what it does is slam to bottom unless I'm scrolled all the way to the very top of a chat (with something like 50 messages). If I'm even a little bit away from the top of the chat, it still slams.

**Comment by matildepark** [comment]
ping @liam-fitzgerald

**Comment by matildepark** [comment]
@liam-fitzgerald Can you resolve the conflict? I'll test this again tn.

**Comment by matildepark** [comment]
Still borked! Slams no matter where I am.

**Comment by urcades** [comment]
Same, slamming is perceived
—
~fabled-faster
https://urbit.org/

**Comment by matildepark** [comment]
Are you talking about on master? I'm talking about in this branch, ha. Of course livenet slams like a mofo. It's actually surprising this PR dates to May 8, time flies by.

**Comment by urcades** [comment]
Ah, yeah I'm speaking to prod/master/what the public is using, my
mistake/bad ha.

—
~fabled-faster
https://urbit.org/

**Comment by matildepark** [comment]
Superseded by #3242, which rewrote the scroll functionality from scratch.

**Pull request closed without merging**
