### PR TITLE
jets: hook up preexisting +repn jet.

### PR DESCRIPTION
**Pull request by eglaysher**
The C code for +repn was written, but never hooked up.

### CODE REVIEW

**Comment by philipcmonk** [comment]
@benjamin-tlon You wrote this, right?  Was there a reason it wasn't turned on?

**Comment by joemfb** [comment]
It was added (and turned on) in #2066, as part of the OS1 work. There were issues with the management of the relevant branches -- that and OTA questions lead to #2254 and #2306. The tree.c parts of #2066 are notably missing from from the final OS1 PR: #2365.

**Comment by joemfb** [comment]
The CI failure here was strange and presumably spurious; the test app just didn't start for some reason. Re-running the build to check.

**Comment by joemfb** [comment]
Welp, the same CI failure occurred. Hard for me to imagine how improved base64 performance could impact start of the `:test` app. @philipcmonk, any ideas about what might've go wrong in app initialization?

**Comment by matildepark** [comment]
Does this branch have 54969afdd25d0843f16797b0302e1f0179122daf in it? If it precedes that commit then apps won't `|start`.

**Comment by eglaysher** [comment]
Rebased this on top of current master, which has the `|start` fix, and made stub hash declarations.

**Pull request merged**
