### PR TITLE
helm: fix |rekey to work with multikey files

### PR DESCRIPTION
**Pull request by drbeefsupreme**
This is identical to #5522, I was just asked to merge it into `next/arvo` instead of `release/next-userspace`

### CODE REVIEW

**Comment by Fang-** [comment]
I actually like the code as it exists in #5522 a little bit better. This does an unnecessary assignment to `sed` and does repeated `+snoc`s instead of a single `+flop`.

Any particular reason for these changes? (Seems functionally equivalent though.)

**Comment by drbeefsupreme** [comment]
Whoops, that's what I get for copying and pasting on a new branch without double checking instead of doing things the right way. Thanks for catching that. It was supposed to be identical to #5522.

**Comment by drbeefsupreme** [comment]
@Fang- OK now it should actually be identical.

**Review by Fang- — APPROVED** [review]
> copying and pasting on a new branch

Just `git cherry-pick` the commit over. (;

This looks good, thanks!

**Pull request merged**
