### PR TITLE
`urbit-atom` 32 bit and GHCJS support.

### PR DESCRIPTION
**Pull request by benjamin-tlon**

### CODE REVIEW

**Comment by benjamin-tlon** [comment]
This seems right, but still doesn't work correctly on GHCJS. Need to bring back the tests.

**Comment by benjamin-tlon** [comment]
Maybe GHCJS `Natural`'s are broken? https://github.com/ghcjs/ghcjs/commit/c3922ede190a7dda6c0b673a3b7441cf41afcc9c

**Comment by benjamin-tlon** [comment]
Alpine Linux build works just fine. Basically the same `--host` option, same source URL, also using `musl`. What's the difference?

https://pkgs.alpinelinux.org/package/edge/testing/armv7/libsigsegv

**Comment by benjamin-tlon** [comment]
Happy to take review on this, but mostly just want to get it merged.

**Comment by benjamin-tlon** [comment]
Who can merge this? @eglaysher @jtobin @ixv

**Comment by eglaysher** [comment]
(I can't, otherwise I would.)

**Pull request merged**
