### PR TITLE
Comet sigil size uses props.size, member list spacing tweak

### PR DESCRIPTION
**Pull request by matildepark**
Instead of hard-coding the `bg-black` 'comet sigil' size, take props.size as the input as everything else does. In order for comet names to not break through the 'host' and 'remove' links, I had to respace the members list a bit. Screenshots attached.

Screen Shot 2019-08-08 at 6 09 21 PM

Screen Shot 2019-08-08 at 6 09 46 PM

### CODE REVIEW

**Comment by matildepark** [comment]
Still breaks on less wide aspect ratios, though. 
image

**Comment by loganallenc** [comment]
beast mode, LGTM

**Comment by matildepark** [comment]
Check out this merge conflict on the compiled binary! Time to learn how to resolve merge conflicts. 

I've heard @jtobin is supposed to be the one to just merge into urbit/urbit? Trying to figure out how we handle this when merging compiled stuff with multiple changes.

**Comment by Fang-** [comment]
We should make arvo compile the javascript so we can just ship raw source instead. (^:

**Comment by matildepark** [comment]
Yes.

**Comment by jtobin** [comment]
On Fri, Aug 09, 2019 at 11:12:07AM -0700, Matilde Park wrote:
> Yes.

Double yes.  Or just a build of some kind, in any case.  This is
actually the first I've seen of these non-diffable/compiled JS files; I
don't immediately see why they should be tracked in version control.

We don't literally need to deploy straight from git, after all.  Off the
top of my head: it seems like OTA updates could be done by grabbing the
source associated with a tag, running a build on it, and then handing
~zod the produced files.  Non?

**Comment by Fang-** [comment]
Having a `./sh/build-release-arvo` that just runs `gulp bundle-prod` or whatever for everything in `/pkg/interface` seems much better, yes.

This is kind of similar to the whole pill situation...

**Comment by jtobin** [comment]
On Fri, Aug 09, 2019 at 11:41:29AM -0700, Fang wrote:
> This is kind of similar to the whole pill situation...

'Tis!  I have actually been devoting some of my limited brain capacity
to that problem today.  Needs slightly more devotion..

**Comment by matildepark** [comment]
> Having a `./sh/build-release-arvo` that just runs `gulp bundle-prod` or whatever for everything in `/pkg/interface` seems much better, yes.

It may need its own command — bundle-prod wants an urbitrc with a dev ship pier IIRC.

As for this — should I merge master back into this, recompile and let @jtobin merge it? Or leave this as it is? What do you think?

**Comment by Fang-** [comment]
@jtobin's being paid to wrestle with this mess. Let him take care of master-merging etc. The more he suffers, the faster he comes up with a good solution. (;

**Comment by jtobin** [comment]
@matildepark Yeah, for this one please rebase onto or merge master & recompile in order to get rid of the merge conflict.  We can worry about adding a proper build elsewhere.

**Comment by matildepark** [comment]
I appear to have just created more merge conflicts.

**Comment by matildepark** [comment]
OK, I think I resolved this properly; that is, I just accepted all the incoming changes from urbit/master except the compiled which I took from the comet-sizing branch here.

**Comment by matildepark** [comment]
OK! OK! We're good now. I was doing timer work and was in that working directory when I compiled instead of chat. I should not be doing Git surgery before coffee, clearly.

**Pull request merged**
