### PR TITLE
Moved tutorial to principles; added 3 and 4.

### PR DESCRIPTION
**Pull request by cgyarvin**

### CODE REVIEW

**Comment by philipcmonk** [comment]
I'll merge this, but for posterity the correct git flow would have been:

- starting from master, create branch 'url-fix'
- make changes on url-fix
- submit pr for url-fix
- starting from master, create branch 'tutorial-3-4'
- make changes on 'tutorial-3-4'
- submit pr for 'tutorial-3-4'

There's no way the tutorial changes depend on the url changes.

**Comment by philipcmonk** [comment]
In case it wasn't obvious, the problems here are:  duplicated commit, two trollmerges, and #563 is all messed up.

**Comment by cgyarvin** [comment]
Thanks!

**Comment by philipcmonk** [comment]
```
fatal: merge program failed
Automated merge did not work.
Should not be doing an Octopus.
```

I'll take that as a challenge.

**Comment by cgyarvin** [comment]
Ha!

**Comment by juped** [comment]
I generally prefer unraveling the graph myself and then complaining that I had to do it. This works on everyone but Curtis, who will obliviously continue comitting to his dead branch and cause more madness.
Yours,
r

**Pull request closed without merging**
