### PR TITLE
publish-fe: Adds deletion and editing of comments

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Adds interface affordances for the addition and removal of comments.

drafted rn because clay doesn't appear to like the publish-comment mark for whatever reason. Have filed a bug in #2731  .   Deletion works fine, but updates are a no go (may actually bork your entire fakezod). 

cc: @matildepark @urcades 

Demo: 
Screen Shot 2020-04-14 at 8 29 43 pm
Screen Shot 2020-04-14 at 8 22 16 pm

### CODE REVIEW

**Comment by liam-fitzgerald** [comment]
cc: @ixv

**Comment by matildepark** [comment]
Cancel should definitely be beside the "Submit" button as a `b--black black` button. 

Edit as green text looks odd, but I did that the first time (with the Publish header matter, ha) and I have no counter-suggestions.

**Comment by liam-fitzgerald** [comment]
Screen Shot 2020-04-15 at 11 00 14 am

**Comment by matildepark** [comment]
Are there dark mode styles on that?

**Comment by liam-fitzgerald** [comment]
yuh
Screen Shot 2020-04-15 at 12 52 23 pm

**Comment by urcades** [comment]
Matilde caught everything here, final results are looking good.

**Comment by matildepark** [comment]
ping @ixv

**Comment by ixv** [comment]
I hit a bug where after editing one comment, another comment was deleted. Trying to get a repro now.

**Comment by belisarius222** [comment]
@ixv I hit a bug last night where after attempting to edit a post (which resulted in a silent failure), I tried to add a comment.  When I clicked the button to submit the comment, it took me back to a different page, but it seems to have swallowed the comment.  It did this twice in a row.

**Pull request merged**
