### PR TITLE
Removing chat clutter

### PR DESCRIPTION
**Pull request by othercriteria**
Since we have a working `:talk` superseding a non-working `:chat`/`radio`, it seems reasonable to remove `:chat` and related unused infrastructure. I also made small related documentation tweaks without trying to catch up to where the bleeding-edge.

I tested this PR to the point that a fake `~zod` with it will start up fine, but I wasn't able to get a fleet going (due to a `%no-ali-desk` problem) to confirm that I've left `:talk` or anything else unharmed.

I didn't touch code related to `%mensajes` or `%zongs` out of caution, but they seem `:chat`-specific and could go as well?

### CODE REVIEW

**Comment by chc4** [comment]
In the `test` branch, all of the old /app programs have been more or less depreciated. Nearly all of them should eventually be removed and/or rewritten, I imagine, not just `:chat`.

Rewriting the docs so they use `:talk` over `:chat` is a pretty good idea though! I only updated the readme, didn't think of looking elsewhere.

Did you create a `%kids` deck before trying to start a fleet?

**Comment by othercriteria** [comment]
@chc4: I didn't create a `%kids` deck. Is that documented anywhere outside of the `:talk` logs?

**Comment by galenwp** [comment]
i think he means 'desk'. 

it's (woefully) not documented anywhere. on your fake `~zod` you should be able to run `:+merge %kids ~zod %base` to create the desk. you'll need to do the same on `~doznec` if you want to ticket all the way down to destroyers.

this looks good to me though. i'd defer to phil on merging it — but thanks for doing this!

**Comment by philipcmonk** [comment]
These are excellent changes.  You are correct that %mensajes, %zongs, etc can all disappear.  All the old gall apps can disppear too.  I'll go get rid of those.

**Pull request merged**
