### PR TITLE
cc-release: finish event replacement

### PR DESCRIPTION
**Pull request by joemfb**
This PR restores %ames negative acknowledgements and generally fleshes out the event replacement logic, adding hard limits to prevent endless replacement looping (as was previously possible). If this approach seems reasonable, I'll add a generic `%warn` handler to Arvo proper.

To expand on the logic a little bit:

- a deterministic crash while processing an ames packet (`%hear`) is optimistically converted into a negative acknowledgement (`%hole`)
- all other failures, deterministic or otherwise (including the aforementioned attempt) turn into a `[%crud original-event-tag stack-trace]` and are routed along the original event wire, except for
- a failure in processing the self-same `%crud`, which is turned into a generic arvo-level error notification (`%warn`)

That %warn is currently designed to be a print and otherwise no-op (for obvious reasons it should certainly never crash). But maybe it should include the original stacktrace, the failure stacktrace, or even both -- it could `+slog` them in a `+mule`, for instance, perhaps gated by `|verb`. Thoughts?

### CODE REVIEW

**Comment by ohAitch** [comment]
In general, it seems fairly likely that a maliciously-crafted `~|` would be able to cause a deterministic or non-deterministic error(or hang) - possibly warranting a fourth layer with a sandbox process that prints as much as it can and is killed after a few seconds?

In particular the `mule` does not help with oom or (timeout-interrupted) infinite loops - and ++slog in particular is just `~> %slog.`, it should drop directly into the `win:re` jet, which in that mode I think already `####`s out lines that fail even non-deterministically.

**Comment by joemfb** [comment]
Unfortunately, neither `+re` nor `+win:re` is jetted. (And the whole thing is horribly inefficient. And the entire approach to output should be reconsidered.) But the rest is well said -- my approach here still seems incomplete.

**Comment by ohAitch** [comment]
Ah yup that would make you want roads!

Out of curiosity, could I trouble you to collect CI timings for if `%slog` and `dill` printing is just completely NOP'd out?

**Comment by ohAitch** [comment]
(Unless I misremember that cc-release CI sequencing uses `urb.py` instead of the original print-based system, in which case ignore me)

**Comment by joemfb** [comment]
Indeed, we are using `urb.py` here. It'd still be a good exercise in one form or another. The entire output pathway really needs a comprehensive revision.

**Comment by ohAitch** [comment]
No I mean if the prints _aren't_ structurally necessary, then the comparison can be made wrt how much of the total test time they're taking :P

(I guess if they were we could still use the profiling systems, but this sounds like it is just a ~~$1 chalk mark~~ single `return` in the right place)

**Comment by joemfb** [comment]
I've tweaked these events further, and implemented the `%warn` handler in urbit/arvo#1154. Once both that and this are approved, I'll merge the arvo PR and update the arvo submodule here.

/cc @jtobin

**Pull request merged**
