### PR TITLE
strandio: fix await-thread and thread-result

### PR DESCRIPTION
**Pull request by tinnus-napbus**
`++  await-thread` generated the `tid` twice and didn't take the kick caused by
the child thread closing. Additionally, `++  await-thread` and `+$  thread-result`
expect a `%thread-fail` to produce `[term (list tang)]` rather than the
actual `[term tang]`.

This adds a `take-kick`, removes the duplicate tid line, and fixes the
expected `%thread-fail` type.

@philipcmonk

### CODE REVIEW

**Review by philipcmonk — APPROVED** [review]
Looks good!

**Comment by philipcmonk** [comment]
This should probably be merged into release/next-userspace, but it looks like that's not up-to-date with master yet.  I'd update it myself but I don't want to step on toes.  This is ready to merge, though.

**Comment by matildepark** [comment]
> This should probably be merged into release/next-userspace, but it looks like that's not up-to-date with master yet. I'd update it myself but I don't want to step on toes. This is ready to merge, though.

Shortly, shortly — I asked @liam-fitzgerald to do so because of the horizontal work in next-js he knows best.

**Comment by matildepark** [comment]
Next-userspace is up to date, merging.

**Pull request merged**
