### PR TITLE
hark: pass remotecontentpolicy to chat notifications

### PR DESCRIPTION
**Pull request by matildepark**
Fixes an interface crash when receiving rich media in notifications.

image

### CODE REVIEW

**Comment by matildepark** [comment]
Actually would this need to be passed to Archive too or archived rich media notifications would crash?

**Comment by tylershuster** [comment]
@liam-fitzgerald we really have to make the useRemoteContentPolicy hooks; this prop stuff is insane

**Comment by matildepark** [comment]
> Actually would this need to be passed to Archive too or archived rich media notifications would crash?

Just checked, archive works fine. OK this is good to go. Needs a stamp from anybody. I asked @philipcmonk a few hours ago about a potential next-sys deploy; if there isn't one this can go out basically asap but otherwise it's better to just ship with that.

**Review by Fang- — APPROVED** [review]
Not the one you asked, but you seem antsy to get this out. It looks Fine!

**Pull request merged**
