### PR TITLE
contacts-js: set react keys correctly

### LINKED ISSUE #2567: Groups Rendering Issue
**Describe the bug**
For some groups managed by the user, switching from Group A to Group B results in a channel from Group A being rendered as a channel in Group B. Subsequent switches back from Group A to Group B produce additional instances of the channel.

**To Reproduce**
1. Go to ~groups/
2. Click on a group managed by the user
3. Click on another group managed by the same user
4. Observe the rendering bug

**Expected behavior**

**Screenshots**
[Screencast of issue.](https://imgur.com/a/uLTgOXN)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Brave
 - Base hash of your urbit ship: 0v19.ibduh.62jie.3rk7j.ojsiq.4bmhv.m7cus.c8cu5.rhoq7.rs3pp.f0eri

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
If two items from different apps had the same name, we ended up with a
duplicate key, causing a rendering issue. Prepends the app name to the
key to prevent this.

Fixes #2567

### CODE REVIEW

**Comment by matildepark** [comment]
oh my GOD you found it

**Comment by matildepark** [comment]
@liam-fitzgerald Target feat/spa?

**Comment by loganallenc** [comment]
Ping, please clean up these pull requests

**Comment by liam-fitzgerald** [comment]
rendered redundant by changes in feat/spa

**Pull request closed without merging**
