### PR TITLE
dojo: restore `??` and `???` syntax

### PR DESCRIPTION
**Pull request by ohAitch**
Unsure what happened here, we appears to have ended up at a `?` and a `?????` and nothing in between, documented as "val/type/hoon/xray".

Grabbed original implementations out of git history, there was an ominous warning about "filtering" but I don't have the context for what it means - these operations cannot have side effects, so worst case you can just not run them. (Possibly after rebooting a hung pier?)

Contains some questionable type hackery around the 79aa1cb redefinition of `$?` to disallow multiple "complex" types, if anyone can come up with a real solution here I'll be overjoyed if you push commits to that effect.

### CODE REVIEW

**Comment by ohAitch** [comment]
Should I also be reformatting this to have commit message bodies cf #2928? This is mostly a glorified "uncomment some code" PR.

**Comment by Fang-** [comment]
> Should I also be reformatting this to have commit message bodies

If you want to give more details, explanation or references (ie historical commits etc), that's always nice, but I wouldn't say they're mandatory.

**Comment by ohAitch** [comment]
Makes sense, I think for historical record I'll just leave a note \~here on this PR~: most of the code reintroduced was either [commented out by](https://github.com/urbit/urbit/commit/79aa1cb#diff-95e3157683c97ac8eaa6db465e5c352fR1157-R1189) or otherwise [present as of](https://github.com/urbit/urbit/blob/79aa1cb/app/dojo.hoon#L1133-L1153) aforementioned `$?` commit 79aa1cb. (And got cleaned out in a separate later one.) There's also a small [patch](https://github.com/urbit/urbit/pull/3311/commits/dda3864) to account for thread syntax.

The part that could use eyes is a three-line [creative shim](https://github.com/urbit/urbit/pull/3311/files#diff-efaa874d5295aa406381fc8493f63577R663-R665) of bunting old $?, as (to simplify) `?(hoon @ta)` is no longer a valid mold.

**Comment by philipcmonk** [comment]
I don't know why that fishes, but I confirm your code works and that `$?` fails as you say.  Good enough for this PR.

**Pull request merged**
