### PR TITLE
interface: div is not a self-closing tag

### PR DESCRIPTION
**Pull request by tylershuster**
a bit pedantic but

### CODE REVIEW

**Comment by ohAitch** [comment]
Really taking the X out of XHTML

**Comment by matildepark** [comment]
I don't know what this means but I can't win here

**Comment by tylershuster** [comment]
inde.xhtml

**Comment by ohAitch** [comment]
Aight to be less cryptic: A+ correct change to achieve nonbroken behavior in the broken web ecosystem ^-^

**Pull request merged**
