### PR TITLE
bitcoin-utils: Fix parsing of of CompactSize integers

### PR DESCRIPTION
**Pull request by dasrun-fadben**
When the first byte is greater or equal to 0xfd, (bex len) bytes are consumed to
form the csiz atom, but only one byte is dropped from the 'rest' of the input.

The parser should consume all bytes of the CompactSize.

### CODE REVIEW

**Comment by zalberico** [comment]
@belisarius222 assigning this one to you for next steps, either way we should not be merging it directly into master

**Comment by cyclomancer** [comment]
@belisarius222 asked me to take a look at this and I think it's good to merge. The first commit covers the missing 0-value case for encoding, and the second fixes a straightforward bug in parsing that treated a `bloq`/exponent "length" value as the actual bytewidth.

Something else to fix in the future here (and elsewhere in the bitcoin libraries?) is the use of `bloq` as a bytewidth value rather than strictly bitwidth. That doesn't impact this PR's fix however.

**Comment by belisarius222** [comment]
Thanks @cyclomancer.  Let's get this merged, then.  @zalberico should this go into next/arvo?  Please advise.

**Comment by zalberico** [comment]
Yep - just needs approval first and be up to date with next/arvo prior to merge. Then if things look good and tests are passing you can merge it.

We're not deploying next/arvo to the canary moon on merge yet because Philip is testing his upgrade work there, but his upgrade work is moving to the tlon internal moon shortly at which point the tip of next/arvo will move to the canary.

**Review by belisarius222 — APPROVED** [review]
rubber stamp lgtm

**Pull request merged**
