### PR TITLE
chat: serialize %keys to JSON for chat update

### PR DESCRIPTION
**Pull request by cmarcelo**
This was missing from the serialization, resulting in the value of keys being null in the JSON produced.

And an extra patch to use `?-` in the serialization instead of a sequence of `?:  ?=`.

### CODE REVIEW

**Comment by cmarcelo** [comment]
@matildepark once the base branch was changed I noticed there are other unrelated commits in this PR, should I force push to rebase just the two commits onto `next-userpace`?

**Comment by matildepark** [comment]
I'll merge master back in.

**Comment by matildepark** [comment]
OK, looks fine now.

**Comment by matildepark** [comment]
ping @tacryt-socryp mind looking at this today?

**Pull request merged**
