### PR TITLE
Misc KH Cleanup

### PR DESCRIPTION
**Pull request by benjamin-tlon**
- Behn Cleanup (eventually, I want Behn to be very polished code and to use that as a starting point for people reading this codebase)
- Behn Tests
- Disables an Ames tests that doesn't work
- Initial work towards pulling config and pier data from RIO environment, instead of passing tons of arguments to everything.
- Some other misc cleanup.

### CODE REVIEW

**Comment by eglaysher** [comment]
Does this apply cleanly on top of https://github.com/urbit/urbit/pull/1845?

**Comment by benjamin-tlon** [comment]
> Does this apply cleanly on top of #1845?

Yeah.

**Comment by benjamin-tlon** [comment]
:+1:

**Comment by jtobin** [comment]
Going to close this one as I'm pretty sure it's out-of-date.

**Pull request closed without merging**
