### PR TITLE
Revert "meta: remove herb, urbit .gitignore files [ci skip]"

### PR DESCRIPTION
**Pull request by joemfb**
I can't speak to `herb`, but the `pkg/urbit/.gitignore` was specifically added during the "monorepoization", and is very much necessary for working on vere.

And a process note, I really think these kinds of changes should not be being pushed straight to master. It seems like anything other than merge commits should probably go through review.

### CODE REVIEW

**Comment by belisarius222** [comment]
Yes, this has been pretty annoying, with .o files strewn everywhere each time I switch branches nd need to rebuild Vere.  I've been wondering what happened to our .gitignore ...

**Comment by jtobin** [comment]
Sorry boys.  Collateral damage.  I must have falsely assumed the Vere .gitignore was lingering gunk when cleaning up some other lingering gunk (deprecated Travis config, junk .gitignore from pkg/arvo, junk .gitignore for herb).

I did a spree of this while putting in some support for better git-archive use -- the motivation being to avoid packaging up spurious files in release archives.  I've started making internal use of this git-archive stuff, but it has yet to reach its final form.

> And a process note, I really think these kinds of changes should not be being pushed straight to master. It seems like anything other than merge commits should probably go through review.

There are many random tweaks that could stand to be done around the repository at any given time that, as far as I'm concerned, simply don't need review.  Check out this list, for example:

```
618cfa862 MAINTAINERS: several updates [ci skip]
915bf1332 sh/release-archive: 'set -e' in header [ci skip]
6acb75156 sh/merge-with-custom-msg: add checks [ci skip]
696a1314f sh/merge-with-custom-msg: 'origin' handling fix [ci skip]
7be9ed95a sh/merge-with-custom-msg: add pill update check [ci skip]
171fcbd26 gitattributes: export-ignore additions [ci skip]
7fab8be0d meta: remove herb, urbit .gitignore files [ci skip]
ead17841b gitattributes: export-ignore default.nix in herb [ci skip]
9c644c433 sh: add release-archive script [ci skip]
eb27d67cc gitattributes: export-ignore test directories [ci skip]
769252f4e gitattributes: export-ignore hashtable_tests [ci skip]
b8ce433e0 meta: remove deprecated files [ci skip]
7e3b9411d mailmap: add pkova [ci skip]
2896386ec vere: patch version bump (v0.10.3) [ci skip]
f1c9f54c2 readme: update bridge URL [ci skip]
ccb27b1e6 test-arvo-upgrade-path: don't install vere [ci skip]
de9bd593d ci: remove whitespace test [ci skip]
ce6f82a58 chat: trim whitespace [ci skip]
0c4544a6f meta: add a basic maintainers' guide [ci skip]
5591987ea meta: update .mailmap [ci skip]
0fadd8898 contributing: use alternative rebase tutorial [ci skip]
baedc5056 sh: replace merge helper [ci skip]
ea8e331d9 vere: patch version bump [ci skip]
7ef702842 build: add :soto, always install dependencies [ci skip]
78a2dfcf8 sh: fix merge-and-update-solid name [ci skip]
c7fe6f408 sh: add OTA test helper script [ci skip]
7ca71fb31 sh: add merge helper script [ci skip]
f183a5f66 contributing: update git practice section [ci skip]
7ceff5be8 vere: update patch version (0.9.1 -> 0.9.2) [ci skip]
3210acd4d vere: patch version bump (0.9.0 -> 0.9.1)
9068188e4 build: fix 'solid' derivation [ci skip]
8a4a3335d build: fix typo [ci skip]
3a540371a vere: rc version bump (-> 0.9.0.rc-4)
8b64b3de4 vere: rc version bump (-> 0.9.0.rc-3)
32052396d vere: version bump (0.8.0 -> 0.9.0)
f9fc56a22 mailmap: add .mailmap file [ci skip]
9e3b96019 contributing: fix awkward language [ci skip]
64a20fd70 contributing: add notes on describing contributions [ci skip]
8920bf0dc meta: update contributing section in arvo readme [ci skip]
2694d04a5 contributing: add note on hotfixes [ci skip]
6b2c2d621 readme: point arvo URL at subtree [ci skip]
```

IMO PRs and review for "this kind of stuff" would make tedious administrative work even more tedious, with little benefit, and would slow things down unnecessarily.  I'm afraid I don't plan to start asking for permission for this kind of thing.

I may have gotten one of the two `.gitignore` deletions wrong here (the herb one clearly just refers to the `result` from `nix-build` when `--no-out-link` is omitted, and is pretty superfluous), and I do apologize for that, but I consider it a pretty minor oversight.  We can just put the file back.

As an aside: this is a good excuse to clean up the .gitignore contents (i.e. both Vere's and the root one).  Hardly the most thrilling or important task, but some occasional janitorial work doesn't hurt..

**Comment by joemfb** [comment]
Over half of those commits are build changes, new scripts, documentation updates, and the like -- all things that could use review, or just the visibility and shared context that comes with PRs. (Note that `[ci skip]` works in PRs as well.)

**Comment by joemfb** [comment]
Bump -- this remains a real pain.

**Comment by jtobin** [comment]
On Fri, Feb 28, 2020 at 03:40:01PM -0800, Joe Bryan wrote:
> Bump -- this remains a real pain.

Apologies, didn't manage to get around to it yesterday.  I'll sort it
out today.  I'll probably just tack on a commit to get rid of the herb
.gitignore, which I don't think is necessary.

**Comment by jtobin** [comment]
@joemfb -- PTAL.  I just did some minor cleaning here.  I ran a basic sanity test -- a `configurePhase` and `buildPhase` for Vere in a nix-shell -- and didn't see observe git trying to track anything, but that might not have hit your use case.

Also, in cleaning up the global .gitignore: I have no idea what was supposed to be matched by these things, but they don't look relevant anymore:

```
\#*\#
s/*
```

I've axed them, but let me know if you recognize them.

**Comment by ohAitch** [comment]
the first one looks like an editor backup thing, emacs maybe? if so seems
like a thing people can individually put in their .git/info/exclude, since
it's not the same category of "files developing the repo definitely will
generate and want to not be checked in"; otoh I don't see how keeping it
would hurt exactly

**Comment by jtobin** [comment]
> otoh I don't see how keeping it would hurt exactly

I know, making any sort of cleanup effort on .gitignore files reeks of misplaced effort.  That said, tidiness is generally better than messiness, so if we're looking at it now anyway..

In general I agree that these files should only contain build artifacts and similar things related to the project itself, rather than .swo and .swp and .DS_Store files and such.  But I'm not picky.

**Comment by ohAitch** [comment]
Well the thing is "random shit gets checked in" is the ground-level
messiness, so there's a degree to which this whole effort smells like
removing the handle fo the broom because people should never get crumbs on
the floor in the first place

tho insofar as we _do_ know why a line is there, and that the cause no
longer applies, removing it seems good. (git blame may be instructive in
remaining cases)

**Comment by ohAitch** [comment]
((Previous disagreements I believe we've had on vaguely this topic: closing
github issues because you personally don't expect to ever run into them,
removing example generators because discoverability is indistinguishable
from clutter, removing parts of the type system now that the standard
library functions using them have been commented out because the apps
calling those have been "cleaned out"…))

**Comment by jtobin** [comment]
> tho insofar as we _do_ know why a line is there, and that the cause no longer applies, removing it seems good. (git blame may be instructive in remaining cases)

Yeah, I've re-added them back in.  You're right that they don't fit the "known superfluous" case, so best not tempt fate here.

Re: tidiness philosophy -- there's Chesterton's fence, and then there's the pristine, unspoiled landscape one reclaims by bulldozing Chesterton's fence.  One hopes to be able to judge when to take either approach and get things *mostly* right. 😄 

(In the meantime, I wound up tweaking and building Vere again on another branch and am now more assured that everything @joemfb wanted ignored is, once again, sufficiently ignored.  I'll merge this.)

**Pull request merged**
