### PR TITLE
URL printing; doc and usability fixes.

### PR DESCRIPTION
**Pull request by cgyarvin**

### CODE REVIEW

**Comment by philipcmonk** [comment]
Word on the street is "merge with care".  I believe the flow should be:

- reload %zuse
- reload %ford
- rest of changes
- make vere

The upgrade process isn't yet tested.

**Comment by juped** [comment]
vere should be first, right? Either version can handle not having any `%url`s just fine.

**Comment by juped** [comment]
Also, no urbit.pill fwiw

**Comment by philipcmonk** [comment]
Neither order is catastrophic, but vere first would be better, yes.

**Comment by juped** [comment]
Test sequence:

- start up fake `~zod` and fake comet on master's version of vere
- rebuild on branch's version of vere, restart `~zod` (not comet)
- copy over `%zuse`
- copy over `%ford` and `%gall`
- copy over the rest
- restart comet with updated vere

I don't know how to trigger the url printing functionality or I would have included that, but the fake network does not crash and burn on this sequence.

**Pull request closed without merging**
