### PR TITLE
btc-provider: refactor and improve performance

### PR DESCRIPTION
**Pull request by tacryt-socryp**
Big props to @ixv for helping track through all of this. Used to take 40s, now takes 0.5s to process a `%block-info` request.

### CODE REVIEW

**Comment by ixv** [comment]
You want to keep all those jet hints in there?

**Comment by tacryt-socryp** [comment]
Yes, jet hints are good to have to track any performance regressions over time.

**Review by ixv — APPROVED** [review]

**Comment by timlucmiptev** [comment]
What's the rationale for not exposing `bitcoin-utils` via `bitcoin`? Those are pieces of logic that really should just be part of the `bitcoin` lib, but had to be put in their own so that the BIP libs could depend on them too without creating a circular dependency.

**Comment by tacryt-socryp** [comment]
Easier to do jet hints / profiling when there isn't as much subject modification going on. ie =, multiple =< of other libraries, etc

**Comment by timlucmiptev** [comment]
Gotcha--is there another simple way to keep the semantics of exposing via
bitcoin.hoon?

Пт, 25 июня 2021 г. в 08:45, L ***@***.***>:

**Comment by tacryt-socryp** [comment]
We could just access them through bcu:bc within agents. In other words, there isn't really an obvious way

**Pull request merged**
