### PR TITLE
graph-js: normalize keys in reducer

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Pre-graph-store links that were brought over use @da as their index,
however new links use a unix timestamp as their index. Pending a proper
fix, we instead just normalize all the indexes to be unix timestamps
inside the reducer.

### CODE REVIEW

**Comment by joemfb** [comment]
Why aren't we using `@da` anymore? Seems fairly hostile to the rest of the system.

**Comment by matildepark** [comment]
/me shrugs — outside the scope of this PR, which is a FE shim fix to fix Links before making a call on a back-end fix to standardise these times.

**Review by matildepark — APPROVED** [review]

**Comment by liam-fitzgerald** [comment]
@joemfb We can't reliably do any manipulation of @da on the frontend, because even discarding the 64bits of subsecond timestamp, we don't have enough room in the JS number type (double, so 53 bits) to accurately manipulate and display timestamps. BigInt support just dropped in iOS 14, so we might be able to use `@da` in the future, but I don't think iOS 14 has sufficient traction yet to warrant a change. We usually do `@da` to timestamp conversion during the conversion to JSON, but we can't do this with graph-store, because it's not guaranteed that indexes are necessarily dates. (.e.g. publish uses the revision number as the index)

**Comment by ohAitch** [comment]
Are there BigInt polyfills? Would it make any sense to pass da around as
{seconds,subseconds} objects?

**Comment by matildepark** [comment]
image

Maybe [this Babel plugin](https://www.npmjs.com/package/@babel/plugin-syntax-bigint)?

**Comment by liam-fitzgerald** [comment]
Well, looks like I'm gonna have to fix this in order to ship notifications. Will pull in a polyfill for bigint and add some utility functions for formatting and parsing @da

**Comment by matildepark** [comment]
:/ OK ganbatte

**Pull request merged**
