### PR TITLE
gall %doff to kill subscriptions

### PR DESCRIPTION
**Pull request by belisarius222**
Adds a `%doff` task to Gall to kill all outgoing subscriptions.  Agents will generally restart these when they get the `%kick`.  This is intended for use as a manual workaround for the gall request queue bug, to try to clear inconsistent subscription state.

User can now run `|doff` to kill all subscriptions.  This causes dojo to relink, with a benign stack trace.

### CODE REVIEW

**Review by Fang- — APPROVED** [review]
As discussed on call, this looks good to me.

**Comment by zalberico** [comment]
Ok - I installed this on the ship that was having the connection issues.

It installed successfully and I was able to run `|doff`, but then dojo outputs this every time I hit enter (it also did not solve the joining channels issue).

```%hood: stale %fact [expected=4 got=3] ok=%.y
[p=~panhec-moslet q=%dojo]: /drum/phat/~panhec-moslet/dojo
wire=[i=%~.out t=[i=~.~panhec-moslet t=[i=~.dojo t=/3/drum/phat/~panhec-moslet/dojo]]]
%hood: stale %fact [expected=4 got=2] ok=%.y
[p=~panhec-moslet q=%dojo]: /drum/phat/~panhec-moslet/dojo
wire=[i=%~.out t=[i=~.~panhec-moslet t=[i=~.dojo t=/2/drum/phat/~panhec-moslet/dojo]]]
%hood: stale %fact [expected=4 got=0] ok=%.y
[p=~panhec-moslet q=%dojo]: /drum/phat/~panhec-moslet/dojo
wire=[i=%~.out t=[i=~.~panhec-moslet t=[i=~.dojo t=/0/drum/phat/~panhec-moslet/dojo]]]
%hood: stale %fact [expected=4 got=3] ok=%.y
[p=~panhec-moslet q=%dojo]: /drum/phat/~panhec-moslet/dojo
wire=[i=%~.out t=[i=~.~panhec-moslet t=[i=~.dojo t=/3/drum/phat/~panhec-moslet/dojo]]]
%hood: stale %fact [expected=4 got=2] ok=%.y
[p=~panhec-moslet q=%dojo]: /drum/phat/~panhec-moslet/dojo
wire=[i=%~.out t=[i=~.~panhec-moslet t=[i=~.dojo t=/2/drum/phat/~panhec-moslet/dojo]]]
%hood: stale %fact [expected=4 got=0] ok=%.y
[p=~panhec-moslet q=%dojo]: /drum/phat/~panhec-moslet/dojo
wire=[i=%~.out t=[i=~.~panhec-moslet t=[i=~.dojo t=/0/drum/phat/~panhec-moslet/dojo]]]```

Mark and I took a look at this initially, but we're not sure what the cause of the failure is yet.

**Comment by zalberico** [comment]
I updated to v1.10 and on boot started seeing a lot more output:
```
oup-pull-hook: stale %fact [expected=159 got=144] ok=%.y
[p=~rondev q=%group-push-hook]: /helper/pull-hook/pull/resource/ship/~rondev/group-discovery
wire=[i=%~.out t=[i=~.~rondev t=[i=~.group-push-hook t=/144/helper/pull-hook/pull/resource/ship/~rondev/group-discovery]]]
%graph-pull-hook: stale %kick [expected=309 got=262] ok=%.y
[p=~hiddev-dannut q=%graph-push-hook]: /helper/pull-hook/pull/resource/ship/~hiddev-dannut/hooniverse-banter-4174
wire=[i=%~.out t=[i=~.~hiddev-dannut t=[i=~.graph-push-hook t=/262/helper/pull-hook/pull/resource/ship/~hiddev-dannut/hooniverse-banter-4174]]]
%metadata-pull-hook: stale %fact [expected=165 got=158] ok=%.y
[p=~panhec-moslet q=%metadata-store]: /store
wire=[i=%~.out t=[i=~.~panhec-moslet t=[i=~.metadata-store t=/158/store]]]
%metadata-push-hook: stale %fact [expected=4 got=0] ok=%.y
[p=~panhec-moslet q=%metadata-store]: /helper/push-hook/store
wire=[i=%~.out t=[i=~.~panhec-moslet t=[i=~.metadata-store t=/0/helper/push-hook/store]]]
%metadata-pull-hook: stale %fact [expected=165 got=150] ok=%.y
[p=~panhec-moslet q=%metadata-store]: /store
wire=[i=%~.out t=[i=~.~panhec-moslet t=[i=~.metadata-store t=/150/store]]]
%metadata-push-hook: stale %fact [expected=4 got=2] ok=%.y
[p=~panhec-moslet q=%metadata-store]: /helper/push-hook/store
wire=[i=%~.out t=[i=~.~panhec-moslet t=[i=~.metadata-store t=/2/helper/push-hook/store]]]
%hark-group-hook: stale %fact [expected=4 got=2] ok=%.y
[p=~panhec-moslet q=%metadata-store]: /metadata
wire=[i=%~.out t=[i=~.~panhec-moslet t=[i=~.metadata-store t=/2/metadata]]]
%observe-hook: stale %fact [expected=732 got=675] ok=%.y
[p=~panhec-moslet q=%metadata-store]: /observer/0vtnmnr.av565.j572o.rbf3k.scv73
wire=[i=%~.out t=[i=~.~panhec-moslet t=[i=~.metadata-store t=/675/observer/0vtnmnr.av565.j572o.rbf3k.scv73]]]
%observe-hook: stale %fact [expected=732 got=713] ok=%.y
[p=~panhec-moslet q=%metadata-store]: /observer/0vtnmnr.av565.j572o.rbf3k.scv73
wire=[i=%~.out t=[i=~.~panhec-moslet t=[i=~.metadata-store t=/713/observer/0vtnmnr.av565.j572o.rbf3k.scv73]]]
%hark-group-hook: stale %fact [expected=4 got=0] ok=%.y
[p=~panhec-moslet q=%metadata-store]: /metadata
wire=[i=%~.out t=[i=~.~panhec-moslet t=[i=~.metadata-store t=/0/metadata]]]
%metadata-pull-hook: stale %kick [expected=168 got=152] ok=%.y
[p=~rondev q=%metadata-push-hook]: /helper/pull-hook/pull/resource/ship/~rondev/group-discovery
wire=[i=%~.out t=[i=~.~rondev t=[i=~.metadata-push-hook t=/152/helper/pull-hook/pull/resource/ship/~rondev/group-discovery]]]
%metadata-pull-hook: stale %kick [expected=168 got=157] ok=%.y
[p=~rondev q=%metadata-push-hook]: /helper/pull-hook/pull/resource/ship/~rondev/group-discovery
wire=[i=%~.out t=[i=~.~rondev t=[i=~.metadata-push-hook t=/157/helper/pull-hook/pull/resource/ship/~rondev/group-discovery]]]
; ~dister-nocsyx-lassul not responding still trying
%contact-pull-hook: stale %kick [expected=161 got=152] ok=%.y
[p=~rondev q=%contact-push-hook]: /helper/pull-hook/pull/resource/ship/~rondev/group-discovery
wire=[i=%~.out t=[i=~.~rondev t=[i=~.contact-push-hook t=/152/helper/pull-hook/pull/resource/ship/~rondev/group-discovery]]]
~panhec-moslet:dojo> 
```

**Comment by belisarius222** [comment]
Hm, the [expected=x got=y] prints look like the subscription-killing code isn’t using the right subscription nonce — this should only happen in a post-request-queue-fix world.

—
~rovnys-ricfer
https://urbit.org

**Comment by belisarius222** [comment]
The strangest thing about this is that while the `actual` subscription nonces are stale, they're not zero.  I don't know where those stale numbers are coming from.

**Comment by belisarius222** [comment]
Some lemmas, as I look into this:
- many agents are affected, so the issue does not seem agent-specific (e.g. resulting from one agent crashing)
- both local and remote subscriptions are affected, implying:
  - this issue can arise purely in Gall without any Ames interaction, and
  - the issue is not specific to local subscription handling
- each time `|doff` is run, a new stale `%fact` gets emitted, with a new stale wire at a different nonce
  - since this happens for local subscriptions too, it's not just a matter of Ames packets being sent on old flows
  - somehow, Gall is allowing agents to emit `%fact`s on multiple subscription wires that differ only in nonce
  - somehow, `%fact`s are being delivered on wires whose nonces are far behind, e.g. `[expected=732 got=675]` -- this difference is much higher than the number of times `|doff` has been run, implying the existence of some other mechanism for falling behind, not just the `|doff` command itself, although maybe running `|doff` once could switch the system into a mode where `%fact`s lag further and further behind over time
  - I wonder if publishing agents are somehow not having this subscription deleted from their bowl properly, so they just keep adding new wires as clients resubscribe -- I'll try to check that, since if so, digging into why it's not being deleted might be the key to understanding this bug

**Comment by belisarius222** [comment]
- This bug occurs with just %base running
- This bug occurs on a fakezod booted off gall-request-queue-fix, with no old subscriptions present -- so it's not caused by trying to upgrade old subscriptions

**Comment by belisarius222** [comment]
https://github.com/urbit/urbit/blob/731e27d5a11feb313ec8235fbc90db5da75cd411/pkg/arvo/sys/vane/gall.hoon#L1708

The `~` case is being hit here when `|doff` runs.  I think we're deleting the wrong wire (missing the nonce), and also the wrong rest of the duct (possibly an artifact of this move being `%huck`ed from Gall to Behn back to itself).  `duct` in this printf is the `agent-duct` in the `+ap` core, which Gall uses as a key for managing subscriptions, and its tail looks wrong.  The head (the top wire) also looks wrong because it should have the latest nonce in it (and for recovery, we might want to try it with all the older nonces for this wire too).

```
["||||||" %pass [%gall %g] [%doff /use/hood/0w1.FFb7X/~nec/helm/doff] ~[/dill //term/1]]
gall: +ap-kill-down %hood [wire=/drum/phat/~nec/dojo ship=~nec term=%dojo]
["|||||||" %pass [%gall %g] [[%deal [~nec ~nec] %dojo %leave] /use/hood/0w1.FFb7X/out/~nec/dojo/drum/phat/~nec/dojo] ~[/dill //term/1]]
[ %dojo
  had=%.n
    bitt
  { [p=~[/gall/use/hood/0w1.FFb7X/out/~nec/dojo/3/drum/phat/~nec/dojo /dill //term/1] q=[p=~nec q=/sole/drum_~nec]]
    [p=~[/gall/use/hood/0w1.FFb7X/out/~nec/dojo/5/drum/phat/~nec/dojo /dill //term/1] q=[p=~nec q=/sole/drum_~nec]]
    [p=~[/gall/use/hood/0w1.FFb7X/out/~nec/dojo/4/drum/phat/~nec/dojo /dill //term/1] q=[p=~nec q=/sole/drum_~nec]]
    [p=~[/gall/use/hood/0w1.FFb7X/out/~nec/dojo/2/drum/phat/~nec/dojo /dill //term/1] q=[p=~nec q=/sole/drum_~nec]]
    [p=~[/gall/use/hood/0w1.FFb7X/out/~nec/dojo/1/drum/phat/~nec/dojo /dill //term/1] q=[p=~nec q=/sole/drum_~nec]]
  }
  duct=~[/gall/use/hood/0w1.FFb7X/out/~nec/dojo/drum/phat/~nec/dojo /dill //term/1]
]
["|||||||" %pass [%gall %b] [%huck /use/hood/0w1.FFb7X/out/~nec/dojo/drum/phat/~nec/dojo] ~[/dill //term/1]]
["||||||||" %give %behn %heck i=/gall/use/hood/0w1.FFb7X/out/~nec/dojo/drum/phat/~nec/dojo t=~[/dill //term/1]]
[%drum-quit ~nec p=~nec q=%dojo]
drum: link [~nec %dojo]
["|||||||||" %give %gall [%unto %fact] i=/dill t=~[//term/1]]
["||||||||||" %give %dill %blit i=/gall/use/herm/0w1.FFb7X/~nec/view/ t=~[/dill //term/1]]
["|||||||||" %pass [%gall %g] [[%deal [~nec ~nec] %dojo %watch] /use/hood/0w1.FFb7X/out/~nec/dojo/6/drum/phat/~nec/dojo] ~[/dill //term/1]]
[%dojo-peer-replaced ~.drum_~nec]
["||||||||||" %give %gall [%unto %watch-ack] i=/gall/use/hood/0w1.FFb7X/out/~nec/dojo/6/drum/phat/~nec/dojo t=~[/dill //term/1]]
["|||||||||||" %give %gall [%unto %fact] i=/dill t=~[//term/1]]
["||||||||||||" %give %dill %blit i=/gall/use/herm/0w1.FFb7X/~nec/view/ t=~[/dill //term/1]]
["||||||||||||" %give %dill %blit i=/gall/use/herm/0w1.FFb7X/~nec/view/ t=~[/dill //term/1]]
["||||||||||||" %give %dill %blit i=/gall/use/herm/0w1.FFb7X/~nec/view/ t=~[/dill //term/1]]
["||||||||||" %give %gall [%unto %fact] i=/gall/use/hood/0w1.FFb7X/out/~nec/dojo/1/drum/phat/~nec/dojo t=~[/dill //term/1]]
%hood: stale %fact [expected=6 got=1] ok=%.y
```

**Comment by belisarius222** [comment]
closing in favor of https://github.com/urbit/urbit/pull/5934

**Pull request closed without merging**
