### PR TITLE
See #460

### PR DESCRIPTION
**Pull request by ohAitch**

### CODE REVIEW

**Comment by philipcmonk** [comment]
I don't know how this has been working in my absence -- is it still my role to merge these and push to ~zod?

**Comment by ohAitch** [comment]
It is your role now that no longer absence ^-^

*is trying out ramtev's "make a branch for everything" flow, comments
solicited*

**Comment by juped** [comment]
Anton and I have been doing these things, and I've been complaining lots about lack of meaningful branches... :)

**Comment by philipcmonk** [comment]
@approves of meaningful branches

@will push this in a bit after I get back on the network

**Comment by philipcmonk** [comment]
I hope I didn't just ping Will Leinweber.  That's what you get for having such a sweet username.

**Comment by ohAitch** [comment]
Basically, I want to be always working off of approximately the code in
master
If maintaining a local master and committing to it is "trollmerges", I will
see if forking off of it to do any discrete thing is all it's jazzed up to
be.

**Comment by juped** [comment]
I'll explain myself here for reference:

The trollmerges that result from that case are, e.g., 373115e, ("A-type") and they come from the confluence of three wrong things, the removal of any one of which would prevent them:

- piling commits directly onto master
- using `git pull` like it was a synchronization primitive
- having `git pull` set to the default behavior
- (using `git pull` at all, honestly...)

The other kind of trollmerge is a backwards, or "C-type" merge (e.g. master into feature) without a good reason (which you then put in your commit message).

Compare this "C-pattern" DAG: https://github.com/juped/with-useless-merges/network
with this "normal pattern" DAG: https://github.com/juped/without-useless-merges/network

and, of course, real situations get much more unreadable much faster.

See also Linus's infamous rare moment of clear explanation: https://lwn.net/Articles/328438/

**Comment by ohAitch** [comment]
Hm, what nondefault behavior should pull be set to? Rebase explicitly
forbidden because clay-incompatible history rewriting.

**Comment by juped** [comment]
Don't use `pull`, and set it to `preserve` (like `rebase` but it doesn't unwind your most recent merge for no reason whatsoever because of a bug that got promoted to feature). The only legitimate use case it has that isn't just a weirdly-syntaxed merge of a remote-tracking branch (to be avoided because of the weird syntax and the inherent weirdness of RTBs) is making your own merges (done in maintainer mode, not contributor mode) pushable to a shared remote like `origin` in case someone else pushed to it in the few minutes. Your options are either: 
- to have information-free commits in the history forever, making your history slightly less useful each time (the "default" if `git` is used naively as CVS-with-distributed),
- to institute a bureaucratic locking procedure where no one is allowed to do a merge on their *own local machine* when someone has "checked out" `master` for merging, in which case I'm pretty sure SourceForge still offers CVS hosting,
- to remove everyone's committing to `origin` powers except one, who is then never allowed on vacation,
- or just to rebase the stupid merge on top of the other guy's merge, because no one reading the history wants to know about this "incident".

Clay is not really relevant for a number of reasons, "history rewriting" not among them. Though you could probably contrive a similar situation by never using scratch desks and setting up odd syncs, &c. I'm sure there's plenty of ways to make clay history unreadable, but right now it's unreadable, period...

**Comment by juped** [comment]
If it makes you feel better, think of it as deleting the merge and merging again. Sometimes this is actually faster, given the interface.

**Comment by juped** [comment]
(tested and merged, sorry @philipcmonk...)

**Comment by ohAitch** [comment]
Um is it actually pushed to zod? The reason this was a pull request and not a direct push is to block on `master` semantics: namely that any hoon in it must be on the network, and vice versa.

**Comment by juped** [comment]
Ah, I thought you were going to do it after comment...

**Comment by ohAitch** [comment]
I'm attempting to establish pull requests as protocol for "*dumps into
@philipcmonk's qeu*" :P

**Comment by juped** [comment]
Sensible!

**Comment by will** [comment]
> I hope I didn't just ping Will Leinweber. That's what you get for having such a sweet username.

:v:

**Comment by juped** [comment]
Bug report: urbit.org not as awesome as Will Leinweber's homepage

**Comment by philipcmonk** [comment]
This is now pushed to ~zod.

**Pull request merged**
