### PR TITLE
Add -new-app thread to build from repo /desk

### PR DESCRIPTION
**Pull request by sigilante**
This should call out to a supplied repo, or sigilante/sunrise if none is supplied.

`-new-app` thread:

Create a new app (desk + agent) from a template GitHub repo:

```
-new-app %dawn /sigilante/sunrise
```

The new desk exists with the supplied name and the contents is a copy of the remote repo.

Steps behind the scenes:
1. Retrieve current version of `%sunrise` from [`sigilante/sunrise`](https://github.com/sigilante/sunrise) or from the supplied repo URL. (`/ted/retrieve-latest-commit`, `/ted/retrieve-github`)
2. Add the `/desk` material into Gall.
3. Rename all of the files and internal matches in `/desk` if empty.
4. Copy the modified `/desk` material into Clay.

### CODE REVIEW

**Comment by sigilante** [comment]
Current status:

1. GitHub retrieval works correctly.
2. Conversion to `soba:clay` in the thread works correctly.
3. Devasing of the returned `soba:clay` fails.  I have tried `;;` and `!<` without success:  `!<` is unhappy that it thinks it's a noun (it's explicitly cast to `soba:clay` several times, while `;;` crashes Spider.

**Comment by sigilante** [comment]
Really frustrating… this sort of thing works:

```
~&  >>>  ;;([path miso:clay] -:q.q.cage)
```

so the individual elements are correct after passing out of the child thread.  But the conversion is crazy slow then crashes Spider.

**Comment by sigilante** [comment]
Got back that with this:

```
=/  sob  ;;((list [path miso:clay]) q.q.cage)
```

Next up, a scry crash:

```
.^((set ^desk) %cd /=//=)
```

**Comment by sigilante** [comment]
`/===` strikes again?

```
.^((set ^desk) %cd /(scot %p our.bowl)//(scot %da now.bowl))
```

**Comment by sigilante** [comment]
```
> -new-app %dawn /sigilante/sunrise
>   "Building desk %dawn from https://github.com/sigilante/sunrise:master."
>   "Retrieving latest commit from https://github.com/sigilante/sunrise."
>>  "Latest commit on branch master is a5ddd2e85b8033419a32bd31a6bfae27a3e258d3."
>   "Retrieving file list in /desk."
>   "Retrieving file URLs in /desk."
>>  'desk/app/sunrise.hoon'
>>  'desk/desk.bill'
>>  'desk/desk.docket-0'
>>  'desk/desk.ship'
>>  'desk/lib/dbug.hoon'
>>  'desk/lib/default-agent.hoon'
>>  'desk/lib/docket.hoon'
>>  'desk/lib/skeleton.hoon'
>>  'desk/lib/sunrise.hoon'
>>  'desk/lib/verb.hoon'
>>  'desk/mar/atom.hoon'
>>  'desk/mar/bill.hoon'
>>  'desk/mar/docket-0.hoon'
>>  'desk/mar/hoon.hoon'
>>  'desk/mar/kelvin.hoon'
>>  'desk/mar/mime.hoon'
>>  'desk/mar/noun.hoon'
>>  'desk/mar/ship.hoon'
>>  'desk/mar/sunrise/action.hoon'
>>  'desk/mar/sunrise/update.hoon'
>>  'desk/mar/txt.hoon'
>>  'desk/sur/docket.hoon'
>>  'desk/sur/sunrise.hoon'
>>  'desk/sur/verb.hoon'
>>  'desk/sys.kelvin'
>   "Successfully retrieved files."
>   "Merging 25 files into new desk %dawn."
>   "Desk %dawn does not exist yet; creating."
```

Then we're crashing because we don't have the directories anymore for some reason.  But mostly there!

**Comment by sigilante** [comment]
OK, in business:

```
> -new-app %dawn /sigilante/sunrise
>   "Building desk %dawn from https://github.com/sigilante/sunrise:master."
>   "Retrieving latest commit from https://github.com/sigilante/sunrise."
>>  "Latest commit on branch master is a5ddd2e85b8033419a32bd31a6bfae27a3e258d3."
>   "Retrieving file list in /desk."
>   "Retrieving file URLs in /desk."
>>  'desk/app/sunrise.hoon'
>>  'desk/desk.bill'
>>  'desk/desk.docket-0'
>>  'desk/desk.ship'
>>  'desk/lib/dbug.hoon'
>>  'desk/lib/default-agent.hoon'
>>  'desk/lib/docket.hoon'
>>  'desk/lib/skeleton.hoon'
>>  'desk/lib/sunrise.hoon'
>>  'desk/lib/verb.hoon'
>>  'desk/mar/atom.hoon'
>>  'desk/mar/bill.hoon'
>>  'desk/mar/docket-0.hoon'
>>  'desk/mar/hoon.hoon'
>>  'desk/mar/kelvin.hoon'
>>  'desk/mar/mime.hoon'
>>  'desk/mar/noun.hoon'
>>  'desk/mar/ship.hoon'
>>  'desk/mar/sunrise/action.hoon'
>>  'desk/mar/sunrise/update.hoon'
>>  'desk/mar/txt.hoon'
>>  'desk/sur/docket.hoon'
>>  'desk/sur/sunrise.hoon'
>>  'desk/sur/verb.hoon'
>>  'desk/sys.kelvin'
>   "Successfully retrieved files."
>   "Merging 25 files into new desk %dawn."
[%clay %d-on-desk-deprecated desk=%$ %use-empty-desk]
>   "Desk %dawn does not exist yet; creating."
: /~zod/dawn/2/desk/bill
: /~zod/dawn/2/sys/kelvin
+ /~zod/dawn/2/desk/ship
+ /~zod/dawn/2/mar/docket-0/hoon
+ /~zod/dawn/2/mar/sunrise/update/hoon
+ /~zod/dawn/2/lib/docket/hoon
+ /~zod/dawn/2/sur/docket/hoon
+ /~zod/dawn/2/sur/sunrise/hoon
+ /~zod/dawn/2/app/sunrise/hoon
+ /~zod/dawn/2/desk/docket-0
+ /~zod/dawn/2/mar/sunrise/action/hoon
+ /~zod/dawn/2/lib/sunrise/hoon
>   "Desk %dawn created."
```

Next:

1. Remove spurious components from the source desk (as `%del` in the list).
2. Rename everything from `%sunrise` to whatever it needs to be.

**Comment by sigilante** [comment]
1. complete

Thinking maybe that 2. should be ignored for this thread? or maybe we have two threads.

The reasoning is that simply `-new-app` installing from a GH repo directly is already pretty convenient.

Is having a basic renamed `%sunrise` copy in your Urbit ship sufficiently helpful in and of itself?  Discuss.

**Comment by sigilante** [comment]
Also, it has a branch to overwrite a current desk from the remote, not sure if we want this functionality or not.

**Comment by sigilante** [comment]
I'd also appreciate input on how to make the child thread return type coercion faster.

**Comment by sigilante** [comment]
This now works correctly by avoiding `soba:clay` entirely.

**Review by pkova — APPROVED** [review]

**Pull request merged**
