### PR TITLE
leap: display chording options

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Screen Shot 2021-06-04 at 12 24 52 pm

### CODE REVIEW

**Comment by tacryt-socryp** [comment]
How does this look / function on mobile? Is it hidden?

**Comment by tacryt-socryp** [comment]
Dope

**Comment by matildepark** [comment]
You gotta fix tsc. I pinged Ed for design look

**Review by matildepark — APPROVED** [review]
This hard restricts us to shift chords, but is a bit more flexible than my idea ("pairing all applicable chords to search categories"). We really need to refactor Leap, but it may just end up being rewritten from scratch whenever we do the next iteration of it — it'll have different product requirements entirely.

**Comment by matildepark** [comment]
Merging because this mock variation was given by Ed OOB, it seems.

**Pull request merged**
