### PR TITLE
Put back =

### PR DESCRIPTION
**Pull request by juped**
Highly trivial changes here.

### CODE REVIEW

**Comment by philipcmonk** [comment]
It was at some point decided by executive decision that `=dir` is
pedagogically preferable to `=%` in tutorials.  Have we revisited this
decision?

**Comment by cgyarvin** [comment]
Don't think so?

I also would slightly prefer not to pollute reserved rune space...

**Comment by juped** [comment]
Reserved rune space, indeed!

I agree that =dir is better in a (non-pedagogical) sense. % and dir do both exist and are not exactly the same thing, and you are setting the latter either way.

**Comment by cgyarvin** [comment]
So it's better in all senses.  Begone, =%, unless anyone complains?...

**Comment by juped** [comment]
This is closed by merging, not closed by closing. GH broke here.

**Comment by ohAitch** [comment]
The original purpose of this was that, similarly to `/-` and `/+`, this is an operation which
- has a different, specialized, parser from direct `=foo`
- is important enough to warrant said irregular syntax

If this has in fact been declared too confusing, should the 
```
=% /~zod/home/~2015.12.7..19.12.27..268a/web
```
confirmation echo also be updated to =dir?

**Comment by juped** [comment]
See above for the reasoning. The =% print should either stay as it is (notifying you that a read-only special has changed as a side effect of what you did) or just go away (the prompt updates).

**Pull request closed without merging**
