### PR TITLE
links: added s3 integration

### PR DESCRIPTION
**Pull request by tylershuster**
Click the button; upload the files.

Also deduped the `<S3Upload />` component.

#3363

### CODE REVIEW

**Comment by tylershuster** [comment]
Oops, this should probably use a different icon...

**Comment by tylershuster** [comment]
Progress bar would be nice too

**Comment by tylershuster** [comment]
@urcades do you have a generic "file upload" icon?

**Comment by matildepark** [comment]
@tylershuster Try picking one from [here](https://github.com/urbit/indigo-react/blob/master/src/Icon/iconIndex.tsx) and using the `<Icon>` indigo-react component (though note that not all of them are in 1.1, which we have in use here. We'll move to 1.2 after some of Liam's PRs are in...)

**Comment by urcades** [comment]
@tylershuster yes, this is an Indigo thing — if you note a lack of icons available, feel free to make a request/suggestion and they can be worked on.

**Comment by tylershuster** [comment]
@urcades As far as I can tell, the existing Image icon isn't in here — and a generic "File" icon would be groovy as well. I can swing it with "ArrowNorth" but expanding the S3 connector beyond images means that it should have some other file types.

Part of the work I'm doing here involves a) deduplicating the S3Upload component and b) adding some new parameters to it to account for context, such as `size` and `accept` and forthcoming `icon`

**Comment by matildepark** [comment]
Interesting. We don't want to remove the image prohibition from Chat yet because we need media previews for what we let you upload. So basically, if a URL is a vid then a nice lil vid preview, etc.

**Comment by matildepark** [comment]
That said I think ArrowNorth is fine for now? But we use that "image" icon for all other instances, even in settings screen PR I think.

**Comment by tylershuster** [comment]
Yeah, I added an `icon` prop but the current problem is that the image icon is an image

**Comment by tylershuster** [comment]
And an `accept` prop

**Comment by urcades** [comment]
cc @g-a-v-i-n : any thoughts on the suggested icon additions mentioned above? I think we had a catch-all file icon here:

Screen Shot 2020-08-25 at 9 24 26 AM

Unsure if you witnessed this in the repo @tylershuster — as a placeholder, the above might work fine (it'd actually be great to get a screenshot of the context you're working in), but I see what you mean re: cooking up some specialized icons for cases like this.

**Comment by tylershuster** [comment]
I didn't see those in the repo. Check this out:
[Video](https://marpem-files.sfo2.digitaloceanspaces.com/Screen%20Recording%202020-08-25%20at%206.31.13%20AM.mov)

**Comment by urcades** [comment]
@tylershuster this reminded me that we had some nascent indigo components that afford for a form/input of this type, at least partially:

Screen Shot 2020-08-25 at 10 44 48 AM

You can imagine how we might conjoin fields to build something akin to what you are updating/improving here. It looks like Gav has specified that we use a text-button in these fields, which seems good. This update still prompts us to have icons for this sort of field/action though.

**Comment by g-a-v-i-n** [comment]
I would punt on the icon and just use <Action /> with descriptive text like 'Upload File'.

**Comment by tylershuster** [comment]
Ok check this out. `S3Upload` now takes `children`. Otherwise defaults to an up arrow.

**Comment by tylershuster** [comment]
For those of you at home:

[video](https://marpem-files.sfo2.digitaloceanspaces.com/Screen%20Recording%202020-08-25%20at%202.10.51%20PM.mov)

**Comment by matildepark** [comment]
... oh it was targeting `settings-screen` for some reason.

**Comment by tylershuster** [comment]
Yeah. I asked @liam-fitzgerald and he agreed because of the s3 changes he had made

**Comment by liam-fitzgerald** [comment]
settings screen is now in release/next-userspace, so it should be able to go in there.

**Comment by matildepark** [comment]
I can't seem to reopen it or change the base branch.

**Pull request closed without merging**
