### PR TITLE
dojo: say how to beat the %dy-edit-busy escape room

### LINKED ISSUE #1462: Clarify %dy-edit-busy
by adding "press backspace to abort" or similar. (Esc or break might make more sense here semantically, actually.)

### PR DESCRIPTION
**Pull request by dnmfarrell**
It's too easy to get trapped in the Dojo %dy-edit-busy escape room. Just
type something like:

    -build-file /=base/gen/ls/hoon

This modifies the dojo output to tell the user how to get out.

Fixes #1462.

### CODE REVIEW

**Comment by dnmfarrell** [comment]
I wonder if this hint should be emitted as an effect, instead of changing the sigpam value?

**Comment by Fang-** [comment]
> I ended up emitting an extra effect with the help text

This is the most real form of output, and as such the best solution. Good call.

> the pattern of using sigpam only to emit %tas.

It's only a pattern in that it's the most common way to easily show debug messages to the user. Of course, we should not be showing debug messages to our users in the first place!

I'd suggest removing the `~&  %dy-edit-busy` entirely, and printing just "dojo: busy (press backspace to abort)" or similar. (As you've done, I just want the "busy" keyword in there also.)

**Comment by dnmfarrell** [comment]
Ahh that's gtk about the sigpam output. Thanks!

**Review by Fang- — APPROVED** [review]
Slick, thank you!

**Pull request merged**
