### PR TITLE
leap: better handling of existing focus

### LINKED ISSUE #3297: Leap Search Interface is overridden by Dojo prompt when summoned in Dojo Module
**Describe the bug**
As mentioned in the issue title, I used the Leap interface to access Dojo, and when invoking it to go elsewhere in Landscape, my cursor was placed into the Dojo's input, even as the Search input was visible.

**To Reproduce**
1. Go to Dojo via any means (I used Leap)
2. Immediately attempt to use the Leap incantation
3. See error: Text insertion point should be in Dojo's prompt, but Leap should be summoned regardless. Attempting to type will result in text being input into the Dojo prompt.

**Expected behavior**
I expect the text insertion point/focus to be placed into the leap interface, rather than the Dojo's

Video:

https://www.dropbox.com/s/9f3f2rf1r6pouh2/dojo.mov?dl=0

### PR DESCRIPTION
**Pull request by tylershuster**
See #3297 and #3323. Provides expected behavior on leap invocation and cancellation, especially within the dojo. Returns the user to previous input when cancelled.

### CODE REVIEW

**Comment by matildepark** [comment]
Shouldn’t all text do this? Or is it that the initial propagation lets Dojo override?

**Comment by tylershuster** [comment]
Oh, I actually forgot about that because I couldn't reproduce it, But I do think that's the case. @urcades what browser are you using?

**Comment by tylershuster** [comment]
As it turns out, this seems to be a Safari-specific problem. I was getting a problem where the `/` of `cmd+/` got entered in dojo, and this does fix that. But Safari doesn't like giving focus if another element is focused.

**Comment by urcades** [comment]
Ooo, this is wonderful! Thank you for addressing this general issue. Lmk if I can provide any other tests.

**Comment by tylershuster** [comment]
Fixes #3323

**Comment by tylershuster** [comment]
As it happens, CodeMirror components handle leap behavior properly. I don't know exactly why. Unless anyone objects, I'm going to reconfigure dojo/input.js to use the same component as chat-editor.js

**Comment by matildepark** [comment]
I assume this PR is waiting on the Dojo change?

**Comment by tylershuster** [comment]
Turns out  that was a red herring. The actual issue was inconsistent handling of "setSelectionRange" which was causing the dojo to always take focus. I think the whole experience is much more fluid and consistent now

**Comment by matildepark** [comment]
Dojo's a scary place.

**Comment by tylershuster** [comment]
Yeah, honestly I noped out of replacing the input with CodeMirror once I started to see what was happening. Turned out for the best.

**Pull request merged**
