### PR TITLE
groups: show tile icon, not full color; alphabetically sort group channels

### PR DESCRIPTION
**Pull request by matildepark**
Upon @galenwp request. Border color is the channel color.

Pasted Graphic

### CODE REVIEW

**Comment by loganallenc** [comment]
What's the fallback if we don't have the image?

**Comment by matildepark** [comment]
How would we programmatically see if we have it? There's no fallback because it splices it directly into the `img src`.

**Comment by loganallenc** [comment]
ah, just maintain an explicit object mapping name to image, and when we don't know anything about the app, should be fine to show a blank square with the colored border (better than a "missing image" placeholder)

**Comment by matildepark** [comment]
The `app` variable defaults to Unknown, thus Unknown.png — maybe we just add an "Unknown" image?

**Comment by matildepark** [comment]
See that.

**Comment by galenwp** [comment]
I love this

**Comment by matildepark** [comment]
This shouldn’t be merged yet. I forgot dark mode. Give me an hour, I’ll eat dinner...

**Comment by matildepark** [comment]
OK, fixed. Added a tinted background too to reflect the colour choice — the border color by itself looked weird with the default black on dark mode.

**Comment by galenwp** [comment]
Is this going in today?

**Comment by ixv** [comment]
Yes

**Comment by galenwp** [comment]
Whew

**Comment by matildepark** [comment]
Ideally … the images are slightly canted left, @urcades is uploading new ones.

--
~haddef-sigwen
https://urbit.org

**Pull request merged**
