### PR TITLE
hark-group-hook: add type checking to vase sent to %hark-store, fix #4217

### LINKED ISSUE #4217: hark-store nest-fail
I've seen this at least twice now.  Not sure what triggered it, but I have also experienced difficulty accepting a DM request recently.  Coincidence?!?
```
poke failed from %hark-group-hook on wire /
nest-fail
- have
[ %add
  ?(
    [%graph group=[entity=@p name=@tas] graph=[entity=@p name=@tas] module=@t description=@t index=it(@)]
    [%group group=[entity=@p name=@tas] description=@t]
  )
  date=@da
  read=?(%.y %.n)
    contents
  ?(
    [ %graph
        list
      it(
        [ author=@p
          index=it(@)
          time-sent=@da
            contents
          it(
            ?(
              [ %code
                expression=@t
                  output
                it(
                  ?(
                    [%leaf p=""]
                    [%palm p=[p="" q="" r="" s=""] q=#6]
                    [ %rose
                      p=[p="" q="" r=""]
                        q
                        ^#6
                      ?(
                        %~
                        [i=?([%leaf p=""] [%palm p=[p="" q="" r="" s=""] q=#6] [%rose p=[p="" q="" r=""] q=#6] @t) t=#6]
                      )
                    ]
                    @t
                  )
                )
              ]
              [%mention ship=@p]
              [%reference uid=[resource=[entity=@p name=@tas] index=it(@)]]
              [%text text=@t]
              [%url url=@t]
            )
          )
          hash=u(@ux)
          signatures=nlr([p=@ux q=@p r=@ud])
        ]
      )
    ]
    [ %group
        list
      it(
        ?(
          ?(
            [%add-members resource=[entity=@p name=@tas] ships=nlr(@p)]
            [%remove-members resource=[entity=@p name=@tas] ships=nlr(@p)]
          )
          ?(
            [ %add
              group-path=/
              resource=[app-name=@tas app-path=/]
              metadata=[title=@t description=@t color=@ux date-created=@da creator=@p module=@tas]
            ]
            [%remove group-path=/ resource=[app-name=@tas app-path=/]]
          )
        )
      )
    ]
  )
]
- need
?(
  [ %add-note
      index
    ?(
      [%graph group=[entity=@p name=@tas] graph=[entity=@p name=@tas] module=@t description=@t index=it(@)]
      [%group group=[entity=@p name=@tas] description=@t]
    )
      notification
    [ date=@da
      read=?(%.y %.n)
        contents
      ?(
        [ %graph
            list
          it(
            [ author=@p
              index=it(@)
              time-sent=@da
                contents
              it(
                ?(
                  [ %code
                    expression=@t
                      output
                    it(
                      ?(
                        [%leaf p=""]
                        [%palm p=[p="" q="" r="" s=""] q=#6]
                        [ %rose
                          p=[p="" q="" r=""]
                            q
                            ^#6
                          ?(
                            %~
                            [ i=?([%leaf p=""] [%palm p=[p="" q="" r="" s=""] q=#6] [%rose p=[p="" q="" r=""] q=#6] @t)
                              t=#6
                            ]
                          )
                        ]
                        @t
                      )
                    )
                  ]
                  [%mention ship=@p]
                  [%reference uid=[resource=[entity=@p name=@tas] index=it(@)]]
                  [%text text=@t]
                  [%url url=@t]
                )
              )
              hash=u(@ux)
              signatures=nlr([p=@ux q=@p r=@ud])
            ]
          )
        ]
        [ %group
            list
          it(
            ?(
              ?(
                [%add-members resource=[entity=@p name=@tas] ships=nlr(@p)]
                [%remove-members resource=[entity=@p name=@tas] ships=nlr(@p)]
              )
              ?(
                [ %add
                  group-path=/
                  resource=[app-name=@tas app-path=/]
                  metadata=[title=@t description=@t color=@ux date-created=@da creator=@p module=@tas]
                ]
                [%remove group-path=/ resource=[app-name=@tas app-path=/]]
              )
            )
          )
        ]
      )
    ]
  ]
  [ %archive
    time=@da
    ?(
      [%graph group=[entity=@p name=@tas] graph=[entity=@p name=@tas] module=@t description=@t index=it(@)]
      [%group group=[entity=@p name=@tas] description=@t]
    )
  ]
  [%read-all %~]
  [%read-count stats-index=?([%graph graph=[entity=@p name=@tas] index=it(@)] [%group group=[entity=@p name=@tas]])]
  [ %read-each
    stats-index=?([%graph graph=[entity=@p name=@tas] index=it(@)] [%group group=[entity=@p name=@tas]])
    ref=it(@)
  ]
  [ %read-note
    time=@da
    ?(
      [%graph group=[entity=@p name=@tas] graph=[entity=@p name=@tas] module=@t description=@t index=it(@)]
      [%group group=[entity=@p name=@tas] description=@t]
    )
  ]
  [%remove-graph resource=[entity=@p name=@tas]]
  [%seen %~]
  [ %seen-index
    time=@da
    stats-index=?([%graph graph=[entity=@p name=@tas] index=it(@)] [%group group=[entity=@p name=@tas]])
  ]
  [%set-dnd dnd=?(%.y %.n)]
  [ %unread-count
    stats-index=?([%graph graph=[entity=@p name=@tas] index=it(@)] [%group group=[entity=@p name=@tas]])
    time=@da
  ]
  [ %unread-each
    stats-index=?([%graph graph=[entity=@p name=@tas] index=it(@)] [%group group=[entity=@p name=@tas]])
    ref=it(@)
    time=@da
  ]
  [ %unread-note
    time=@da
    ?(
      [%graph group=[entity=@p name=@tas] graph=[entity=@p name=@tas] module=@t description=@t index=it(@)]
      [%group group=[entity=@p name=@tas] description=@t]
    )
  ]
)
/app/hark-store/hoon:<[266 37].[266 58]>
/app/hark-store/hoon:<[266 24].[266 59]>
/app/hark-store/hoon:<[265 5].[268 7]>
/app/hark-store/hoon:<[264 3].[269 15]>
/app/hark-store/hoon:<[263 3].[269 15]>
/app/hark-store/hoon:<[262 3].[275 5]>
/app/hark-store/hoon:<[261 3].[275 5]>
/sys/vane/gall/hoon:<[1.375 9].[1.375 37]>
```

### PR DESCRIPTION
**Pull request by tacryt-socryp**
Fixes #4217. Have tested it.

### CODE REVIEW

**Comment by matildepark** [comment]
@Fang- @belisarius222 Are either of you able to confirm this fixes a replication of the issue?

**Review by liam-fitzgerald — APPROVED** [review]

**Comment by matildepark** [comment]
Did you test 👀

**Comment by tacryt-socryp** [comment]
Yup

**Comment by matildepark** [comment]
I mean @liam-fitzgerald

**Comment by liam-fitzgerald** [comment]
tested! works fine

**Comment by tacryt-socryp** [comment]
@matildepark can we get this in as a hotfix soon?

**Comment by matildepark** [comment]
It's going out today with the other hark fixes. When depends on whether the others are stamped and fine to ship.

**Pull request merged**
