### PR TITLE
spa: fix bugs in chat and groups, fix metadata reducer

### PR DESCRIPTION
**Pull request by loganallenc**
All actions in the following have been tested:
- Chat has been tested to work
- Groups have been tested to work

Current State:
- Haven't tested Links
- Publish doesn't work
- Launch works but the weather / clock tile APIs are not hooked up properly

Note: This concludes my JS work on the SPA for a bit. Moving my attention towards fixing the HTTP redirect bug in Eyre and then `linear-store` and `graph-store` afterwards.

### CODE REVIEW

**Comment by matildepark** [comment]
Some weird stuff going on with this PR Logan ... it seems to have a diff commit history than `feat/spa` now that you force pushed `feat/spa`. Many conflicts also

**Comment by loganallenc** [comment]
Will fix, won’t be too hard.

**Comment by matildepark** [comment]
ping @loganallenc

**Comment by matildepark** [comment]
This is blocking two different lines of work, @loganallenc — can you please rebase this PR?

**Comment by loganallenc** [comment]
on it

**Comment by loganallenc** [comment]
It's good to go now. Thanks.

**Comment by matildepark** [comment]
It turns out that the changes in fec5646229d371e11ec648f22d29182bfd7d6836 are why everything is broken. 

The metadata-reducer in every application keys by `app-path` so we can get the metadata for each individual item, and that commit reduces it down to `group-path` and then overwrites the path with the latest `app-path` item's metadata. Thus Chat does not work either. I would revert this PR but it would retain the bugs in question here.

@loganallenc I have to ask you to amend the changes you made to the metadata-reducer to rekey it to `app-path`s; it's broken the entire suite of applications and should not have been pushed.

**Pull request merged**
