### PR TITLE
chat: several design tweaks

### PR DESCRIPTION
**Pull request by matildepark**
- Not the sidebar PR yet, sorry @galenwp.
- Adds blockquotes (#3338). @urcades?

Screen Shot 2020-08-18 at 5 20 37 PM

- Code mode swaps placeholder and text with Source Code Pro.
- Add code messages now use Source Code Pro instead of being reset to Consolas.
- Updated codemirror to 5.55.0 to test my hypothesis from #2828.

### CODE REVIEW

**Comment by urcades** [comment]
Ah, proper quoting is a nice addition!

**Comment by matildepark** [comment]
Threw #3325 into here. 

image

**Review by liam-fitzgerald — APPROVED** [review]
LGTM!

**Comment by tylershuster** [comment]
This is going to make Urbit Dialogues look like this:

quotes

**Comment by urcades** [comment]
whoa ... We'll need another demarcation, huh.

A thought here, Inter natively allows for glyph-formation in a really cool
way: we could transition Dialogue turn-passing with `->`, which turns into
a beautiful arrow.

—
~fabled-faster
https://urbit.org/

**Comment by matildepark** [comment]
Do Urbit Dialogues do `>>` or `> > >`? Why does the markdown renderer process `>>>` as three blockquotes? (Was @Fang- right all along?!)

**Comment by urcades** [comment]
I believe Dialogues uses ">>>", no spaces.

I'll suggest to them we use → , since this is processed by inter in a pleasing manner.

—
~fabled-faster
https://urbit.org/

**Pull request merged**
