### PR TITLE
group-store: remove empty tags

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Fixes urbit/landscape#568

### CODE REVIEW

**Comment by matildepark** [comment]
@tacryt-socryp Able to test this today? Might be good to sneak this out tonight since it's basic functionality (graph permissions) not functioning if you make a room "host only", but then change it to "all group members" later.

**Comment by matildepark** [comment]
Moving this to pre-release/next-userspace, please review tomorrow @tacryt-socryp

**Review by tacryt-socryp — CHANGES_REQUESTED** [review]
This manual list conversion + iteration on a jug seems really bespoke and iffy. Why not just use a map method to get the set directly and dif it?

**Comment by liam-fitzgerald** [comment]
because that would leave an empty set, which is what this is trying to address

——
~hastuc-dibtux

https://urbit.org

**Review by tacryt-socryp — APPROVED** [review]

**Pull request merged**
