### PR TITLE
links: fix unread counts

### LINKED ISSUE #2906: Links unread count in window.title only counts loaded channels
Replication:
1. Go to Links. Note no unread links in `window.title`.
2. Go to a channel. It loads the first page; one link is unread, so `window.title` says "Links - (1)".
3. Go to another channel. It loads its first page, which has four unread links, so `window.title` says "Links - (5)".

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
fixes unread counts on links, and fixes some image scaling issues that were occuring. 

fixes #2906

### CODE REVIEW

**Comment by matildepark** [comment]
1. Target `release/next-userspace`.
2. Could you add the same logic to filter unreads by selected group as demonstrated in Chat / Publish?

**Comment by joemfb** [comment]
I think we probably want to merge `master` into `release/next-userspace` outside of this PR.

/cc @philipcmonk @matildepark

**Comment by matildepark** [comment]
Done, thanks @joemfb

**Comment by loganallenc** [comment]
This still needs a rebase.

**Comment by matildepark** [comment]
ping @liam-fitzgerald, r\*b\*s\* this branch

**Pull request merged**
