### PR TITLE
meta: add landscape development stream information

### PR DESCRIPTION
**Pull request by matildepark**
As of #4198, we auto-deploy release/next-js to opted-in ships on network (I'm getting final word on the specific %desk before announcing this). 

Thus, merging into release/next-js is part of deploying to livenet (and really, merge conflicts should be pretty infrequent, since the `master <-> release/next-js -> release/next-userspace` flow is more or less unidirectional for cross-branch changes).

This includes an advisory to include a merge to next-js as part of deploy. We could sidestep this if GitHub Actions let us auto-merge master into next-js, but unsure about that yet.

### CODE REVIEW

**Comment by philipcmonk** [comment]
This applies to anything that has js changes, and it only copies the js changes to that ship, right?

**Comment by matildepark** [comment]
As far as I'm aware, it globs and deploys like any other — the dev ship becomes your sponsor.

**Comment by philipcmonk** [comment]
> Thus far this only includes `release/next-js`, which can only include livenet-compatible JavaScript changes.

Is this "if there are any js changes, they must be livenet-compatible" or "only js changes are allowed and they must be livenet-compatible"

**Comment by matildepark** [comment]
Ah, okay:

- `release/next-js` is the branch to target when you are making front-end specific changes that do not necessitate an accompanying back-end change
- Full-stack features + changes live on `release/next-userspace` and follow the 6 week sprint pattern for release
- JS hotfixes may still go straight into master, but can target next-js depending on severity, and JS-specific features target next-js

next-js may be released more often, but that's still a matter of discussion for us. I will try to keep merging next-js into next-userspace.

**Review by philipcmonk — APPROVED** [review]
Cool.  Then, as you wrote, the main thing to do is push master changes to release/next-js soon after pushing to master.

**Comment by matildepark** [comment]
@jtobin thinks an auto-merge is an easy action to incorporate so I would stand by before merging ... we can simplify the process here.

**Review by jtobin — APPROVED** [review]
LGTM, and note that #4232 should handle the desired auto-merge.

**Pull request merged**
