### PR TITLE
Validate group names

### PR DESCRIPTION
**Pull request by vvisigoth**
Check if group names conform to @tas

### CODE REVIEW

**Comment by joemfb** [comment]
This doesn't appear to capture the "leading-alpha" constraint of `@tas`. Or ensure that the whole string is match. This should match all valid `@tas` strings:  `/^[a-z][a-z0-9-]*$/`

**Comment by matildepark** [comment]
Oh! God, that's a good catch — thanks. I forgot about the leading alpha. We should port that to Chat's validation check too, @vvisigoth.

**Comment by vvisigoth** [comment]
Oh nice. I'll update this.
—
~poldec-tonteg
http://urbit.org

**Comment by vvisigoth** [comment]
Looks like I was mistaken and this needs to just be a `@ta`

**Comment by joemfb** [comment]
Even easier: `/^[a-z0-9~_.-]*$/`

**Comment by vvisigoth** [comment]
boom
—
~poldec-tonteg
http://urbit.org

**Comment by vvisigoth** [comment]
@matildepark plz look

**Comment by matildepark** [comment]
It’s fine offhand but I think it should be everywhere a group can potentially be created. Chat, Publish.

**Comment by joemfb** [comment]
While I'm nosing around, the `new Regexp()` is superfluous; it's for runtime compilation, but this expression is static. The literal works just fine: `/foo/.test('foo')`.

**Comment by loganallenc** [comment]
@vvisigoth please reflect these changes onto publish and chat, otherwise looks good. thanks!

**Comment by vvisigoth** [comment]
OK I updated chat to use this but the new publish stuff isn't in yet, so I can't update.

**Pull request merged**
