### PR TITLE
vere/unix.c: set _XOPEN_SOURCE

### PR DESCRIPTION
**Pull request by fche**
Above feature macro is needed on glibc 2.17 era, in order to activate ftw* related functions/macros.

### CODE REVIEW

**Comment by ohAitch** [comment]
Is this compatible with the MIT license?

**Comment by fche** [comment]
If "this" means the patch, then sure, I guess.

**Comment by ohAitch** [comment]
I meant like, the "ftw" features we want to link in from `glibc` that are gated behind `OPEN_SOURCE`

**Comment by fche** [comment]
That's not a question about ftw then, but about glibc generally.   (`_XOPEN_SOURCE` is a standards-compliance selector, not a licensing one.  Maybe you're confusing it with the linux kernel's `EXPORT_SYMBOL_GPL` machinery?  glibc doesn't do that kind of thing.)

**Comment by mrdomino** [comment]
On OpenBSD:

```
../vere/unix.c:1100:12: error: use of undeclared identifier 'SIGWINCH'
      case SIGWINCH: u3_term_ef_winc(); break;
           ^
../vere/unix.c:1325:20: error: use of undeclared identifier 'SIGWINCH'
    sig_u->num_i = SIGWINCH;
                   ^
```

So I think sticking it in a U3_OS_linux check somehow or another seems sane. I feel like that's the sort of thing you want defined across more or less a whole project (so portable.h seems like a good place to put it), but I don't know in this case.

**Comment by joemfb** [comment]
Thanks for checking!

@fche, please move the define into `portable.h` and ensure it's only set on Linux.

**Comment by fche** [comment]
> please move the define into portable.h

One problem with that is that `portable.h` is included pretty late in the game.  Feature selection macros ought be set **before** libc headers are included.

**Comment by joemfb** [comment]
Is that a problem in the sense that it's suboptimal, or a problem in that it won't work, or won't work consistently?

If it's the former, it still seems preferable to set it project-wide in `portable.h`. If it's the latter,  the `#include "all.h"` could be moved to the top of `unix.c`. If neither of those are sufficient, I guess it's fine to include directly in `unix.c`, wrapped in a `#ifdef U3_OS_linux`.

**Comment by fche** [comment]
2: It can't work that way (since the decls exposed in `<ftw.h>` are gated by those macros).
Moving `#include "all.h"` to the top would probably work, but is more disruptive, since in principle the same applies to all the C source files.  Can give it a quick try if you like.

**Comment by joemfb** [comment]
Please do, thanks!

**Pull request merged**
