### PR TITLE
Lagoon IEEE 754 floats

### PR DESCRIPTION
**Pull request by sigilante**
Pursuant to draft UIP at https://github.com/urbit/UIPs/blob/sigilante/lagoon-reals/UIPS.

Should be released alongside corresponding Vere code.

### CODE REVIEW

**Comment by mopfel-winrux** [comment]
`++ de-ray` does not work with leading zeros. need to fix before merging

**Comment by sigilante** [comment]
Incidentally, test failure is because I included some older ones that shouldn't be in there.  I'll clean it up later.

**Comment by sigilante** [comment]
`+de-ray` fixed.

Tests fixed.

**Comment by sigilante** [comment]
```
test-urbit> clay: read-at-tako fail [desk=%base care=%a case=[%da p=~2024.5.2..20.40.45..de52] path=/gen/tx/hoon]
test-urbit> [%file-not-found-mist /tests/lib/naive/hoon]
test-urbit> [%error-validating /tests/lib/naive/hoon]
test-urbit> [%error-building /tests/lib/naive/hoon]
test-urbit> [%error-building /gen/tx/hoon]
test-urbit> clay: %a build failed [%base 0v1o.trqdf.gvsr6.07kka.joa89.97t9h.btt65.4a3b2.m0q1g.tgj1n.koh9e /gen/tx/hoon]
test-urbit> FAILED  /gen/tx/hoon
```

AFAICT nothing to do with Lagoon.

**Comment by sigilante** [comment]
Thanks.  Guess things are getting moved around.

```
test-urbit> clay: read-at-tako fail [desk=%base care=%a case=[%da p=~2024.5.3..16.15.42..287f] path=/ted/ph/tend/hoon]
test-urbit> [%file-not-found-mist /tests/app/tend/hoon]
test-urbit> [%error-validating /tests/app/tend/hoon]
test-urbit> [%error-casting-path /tests/app/tend/hoon ~.hoon %hoon]
test-urbit> [%error-building /ted/ph/tend/hoon]
test-urbit> clay: %a build failed [%base 0v1o.trqdf.gvsr6.07kka.joa89.97t9h.btt65.4a3b2.m0q1g.tgj1n.koh9e /ted/ph/tend/hoon]
test-urbit> FAILED  /ted/ph/tend/hoon
test-urbit> %some-threads-failed

test-urbit> clay: read-at-tako fail [desk=%base care=%c case=[%da p=~2024.5.3..16.16.10..f350] path=/noun/mass]
test-urbit> clay: no files match /mar/mass/hoon
test-urbit> [%error-building-cast %noun %mass]
test-urbit> [%error-building-tube %noun %mass]
```

**Comment by sigilante** [comment]
- [ ] add overflow checks to lagoon.c
- [ ] make a file of failed tests
- [ ] run tests against jetted and unjetted

**Comment by sigilante** [comment]
This is ready for review.

**Comment by sigilante** [comment]
When the tests pass here on that last commit, then this is ready to merge. @joemfb @pkova @belisarius222 @jalehman

**Comment by sigilante** [comment]
For posterity, the original PR (prior to refactoring several times) was #3536.

**Comment by sigilante** [comment]
- [ ] fix `^pow`

**Comment by sigilante** [comment]
Looks like the failure has nothing to do with Lagoon tests which all passed.

**Comment by sigilante** [comment]
cc @pkova

Kiitos.

**Pull request merged**
