### PR TITLE
README tweaks

### PR DESCRIPTION
**Pull request by dphiffer**
I rearranged some sections, removed some things that felt incomplete, and pointed new users in the direction the web-based talk UI. I removed a phrase "the best place to read about it 
is in your browser" from the section about the web server because I still haven't discovered where these docs can be found. (Where can they be found?)

### CODE REVIEW

**Comment by cgyarvin** [comment]
Dan, this is a really great patch.  I would say it's unfortunate that we're
about to drop a pile of new documentation including an all-new README, but
that's our fault for poor communication.  I'm going to go through your work
and salvage everything I possibly can :-)

**Comment by dphiffer** [comment]
Not a problem! I just wanted to capture my first impressions somewhere.

**Comment by juped** [comment]
http://sampel-sipnym.urbit.org/home/tree/pub/doc

`~sampel-sipnym` is, of course, just a sample ship name there. Substitute localhost:8080 if you like, or if you aren't a descendant of `~doznec`. (If you got a planet from us, you are.)

**Comment by dphiffer** [comment]
Thanks @juped. Maybe when test branch is commit-able again I'll add a link to that URL. Closing this for now.

**Comment by juped** [comment]
Feel free to keep your branch up for Curtis's benefit, of course.

**Comment by galenwp** [comment]
@dphiffer this is solid. Thanks! Will definitely refer to this when we're re-README-ing.

**Pull request closed without merging**
