### PR TITLE
subscription: clear opened subs before restart

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Fixes subscriptions not restarting properly

### CODE REVIEW

**Review by tacryt-socryp — APPROVED** [review]

**Comment by tacryt-socryp** [comment]
Could this cause us to subscribe twice to the same endpoint? I'm not sure, since I think it would depend on whether Eyre ensures a lack of duplicate subscriptions within a channel object, since this shouldn't switch the channel we're using.

**Comment by liam-fitzgerald** [comment]
When we restart, it's against a totally new channel object. channel.js makes an attempt to cleanup the connection, but it's not always successfully. Even if it's not cleaned up properly, it should get caught by the clog logic. It's more than likely that the old subscriptions have clogged by the time we restart our subscriptions as well.

**Comment by tacryt-socryp** [comment]
Surely we should try to use the same channel in case we didn't clog? Because I'd imagine the majority of subscriptions wouldn't clog (how long does it take to get 50 group-store updates or metadata-store updates, right?)

**Comment by liam-fitzgerald** [comment]
We can't use the same channel until @tylershuster s fetch based event source work lands, see urbit/urbit#4004

**Pull request merged**
