### PR TITLE
updated spec 5 structure description for numbers

### PR DESCRIPTION
**Pull request by nmcb**
**Rationale**

Urbit, which aims to be _the_ personal cloud computing software experience, targets software writers, a.k.a. liaisons or clientele enabling developers, to enthral the majority of all real world beings or called humans.  As such urbit could aim to facilitate these software writers with computing provisionings in the form of more real world language constructs, thus aiming for the availability of real world semantic assets, when they write. As a side note; I do understand that the future software language (or languages) in which these future software writers will compose their work, will probably be much closer in semantics to real world language constructs, far away, but derived from, the current software works that composes urbit; such "future software language" will derive its power from urbit, creating such stuff as dreams are made on. Being also pragmatic; in the real world, numbers and its theory, may provide future software writers with such a future semantic asset. This may be a good point to start, again.

I propose the development of nock native support for all real (world) numbers in hoon and its subsequent depending layers of semantic abstractions above as the one (and only supported) number format.  Though not skilled or educated in CS, I humbly suggest to employ an implementation of [DEC64](http://dec64.com) as a facility to implement this native support in urbits core; the (impressive) nock specification.

### CODE REVIEW

**Comment by galenwp** [comment]
Without commenting on whether this is actually a good idea, makes sense, or should happen — I do appreciate the commentary.

**Comment by nmcb** [comment]
@galenwp Thanks for your comment.  You phrase the questions I had in mind when I felt that urbit could be the place to find the answers. Spot on.

I'm quite sympathetic towards D. Crockford for raising the number issue, pushing the DEC64 spec, but was wondering how actual future language writers would feel about the matter.

**Comment by Hmmm-Max** [comment]
I believe those two lines at the beginning of the spec are deep frozen, and will stay the same for all eternity

**Comment by nmcb** [comment]
@Hmmm-Max Interesting comment, especially the employment of the terms `believe`, `beginning` and `eternity`, but; the spec was liquid in the past, so when did hell freeze over, and more importantly: did it do so recently?  Even if no value can be added tot the spec, is there value in the idea?  Does it make sense? And, do I even dare to hope it might happen? All your thoughts about this are very much appreciated.

**Comment by cgyarvin** [comment]
I would generally agree with Max.  If you extend atoms to include non-integers, all you have is two kinds of atoms - since the DEC64 is obviously a 64-bit atom.  This is already dealt with as a case of the Hoon odor system, which has a (rather imperfect) implementation of IEEE floats.

**Comment by mrdomino** [comment]
I still think the right way to do this is to build up a representation of real numbers as computed values with approximations. On top of Nock. Which only does numbers of the natural sort. Because digital computers are digital.

**Comment by mrdomino** [comment]
Add to that: representation such that IEEE-754 hardware/software can be reused for the common, default case.

**Comment by cgyarvin** [comment]
It's certainly possible to represent fractions, intervals, etc, as nouns.  I don't know enough about fp to know how useful this is.  In any case, I'd say this and IEEE style floats are just different things.

**Comment by nmcb** [comment]
@cgyarvin Was the intent of Hoon's odor to _add_ IEEE's float as a type? Because the intent of Crockford with DEC64 is (as i understand it) to _reify_ the natural number representation in computing with floating point number representation, modeled as the same type, `Number`.  His intent is not so much to add a float number type to an already existing integer natural type, it is to replace all number types by one, implemented in real world base-10, for which he wrote a reference implementation, DEC64. I'm therefore inclined to see my proposal not as a second atom, but as the only atom for number kinds, representing real world, base-10, natural and fractional numbers and not a fractional number type next to an already existing natural number type.

**Comment by cgyarvin** [comment]
There are many, many other abstract concepts we use atoms to implement. For example, a string or even a binary file is generally represented as an atom.  So is a signed integer, with sign bit low.   It's a basic design decision of the system - sort of like unix's insistence that files are just byte streams - to kick the problem out of nock and up to the type system of Hoon.

**Comment by nmcb** [comment]
I guess it's correct to kick problems out of nock and up the type system of Hoon. Clearly strings, files  and other client-programmer defined types have no right to exist in that realm, it's purity being undreamt of before conception.  But I'm not so sure why Hoon programmers would even want to know about this problem, these differences between hardware specific numeric types, between signed and unsigned integers, and with a base-10 representation, even between integers and fractions.

Obviously they know about it, they have been force fed numeric type choices all their programming lives. So much even that the idea to not have separate numeric types (dare I call them numeric primitives) feels unnatural to them. 

We fantom the requirement to be able to define, in Hoon, specific and user defined numeric types, with properties other than basic numeric primitives, use-cases for domain specific numeric types will probably always exist.

That doesn't mean it's automatically a good idea to kick the natural versus fraction type issue towards Hoon, especially since it can be abstracted over so naturally?  I see no penalty in purity, nock's atoms being _just_ natural numbers or _just_ real numbers, both feels just as pure.  I do see a slightly smaller domain of the numeric type when used to constraint values of the integer kind.  But the reification seems worth it.  Abstract freedoms emerge often from the constraints of concrete freedoms, and it feels unnatural to kick a problem up, when we can abstract it away.

**Comment by mrdomino** [comment]
Floating point numbers are incredibly different from real numbers. Leave
aside for now the discussion of whether or not nock should have real
numbers (IMO no), this proposal does not accomplish that. It instead
pollutes nock with a highly weird human made type that is e.g. countable
unlike the reals. Weird human made constructs that can be implemented over
the existing atom structure belong in hoon, or at least not in nock. Come
back with something that can model uncountable sets.

**Comment by cgyarvin** [comment]
Essentially, natural numbers are a good primitive choice because they're
what computers like to think in.  In an analog computer or whatever, this
would obviously different.

If you want to be really purist about it, you can say that nock atoms and
Hoon unsigned integers (@ and @u, in Hoon) are at different conceptual
levels, with the mapping from unsigned integer to atom being trivial
(unlike the mapping from signed integer to atom).  But Hoon is
stylistically a lot like C - it doesn't invest any particular energy in
hiding the inevitable realities of its implementation from the programmer.

**Comment by nmcb** [comment]
My apologies for being offline over the weekend and thanks for the explanations.

Reading back my posts I think I'm to blame for using the phrase real number first which did confuse the matter. I was using it in the the meaning of a "real world" number type, or decimal number type and talking about the semantics of such a reified type as seen from a client-programmers point of view. One number type to rule them all if I'm allowed to exaggerate a bit. This future number type in a future language may very well exist many abstraction layers above nock and Hoon and for complexity sake is probably required to.

I can fully appreciate the number type in nock being natural given the design of its rule structure; and a pure an elegant design it is indeed. I just wouldn't be surprised if somewhere in the future, the implementation of this natural number in nock would limit its natural domain to `0.. 36028797018963967 `, the positive numbers possible in a two-complement, 56 bit encoded coefficient, and to facilitate a decimal number type in urbit's client programer 's language, the future language I speak about in my previous paragraph; a type that reifies the operations on natural and floating point numbers in a decimally consistent way. Such a limitation would be no more arbitrary than the choice to limit it to 64 bit unsigned. (Or paraphrasing Crockford, the choice that client programmers should find it normal that the binary implementation of there floating point number types force an expression of `0.1 + 0.2 == 0.3` to return `false` for that matter.)

I also completely appreciate that such a number type could be implemented in Hoon or above without the proposed solution; that would unfortunately prohibit the underlying implementation of the number type to employ optimisations against the hardware that urbit runs upon. Somewhere between the user and the cloud, the code must interact with hardware.

In the mean time, I have a problem of infinite more importance to solve before I can report back. It is a hard problem, it might take me some time.

Therefore; sorry if my request wasted your time, but many thanks for all comments, discussion and explanations. they were as much appreciated as urbit.

**Comment by philipcmonk** [comment]
The issue is that there are many, many atoms in use that are greater in
size than 56 bits.  For example, the text of hoon.hoon is stored as a
single atom (consecutive ASCII bytes) and is over 2,000,000 bits long.
This is efficiently represented in hardware as an array of characters -- a
string.

Secondly, through the concept of jets, even Hoon-level abstractions can
interact with the appropriate hardware.  For example, we have a (mostly)
working implementation of IEEE floating point in Hoon.  It's jetted so that
it actually all runs on the hardware.  Since the hardware gives the same
results as the Hoon code, we haven't broken our abstraction.

**Comment by galenwp** [comment]
@nmcb just a footnote: this was fun.

**Comment by nmcb** [comment]
@galenwp Thanks, and for me it still is; mrdomino's request to solve accountable sets is challenging, but I'm getting there. I will post my progress as comments here, but in the meantime, with all I've learned thought this about urbit and nock's agnosticism to types I can appreciate my current request being closed. Urbit should use its brain power for real world requests, and I value my funny footnote in history. It has it's own rewards. Once again, thanks for your appreciation, I'll be in touch.

**Pull request closed without merging**
