### PR TITLE
interface: use icon sigils for <16px renders

### PR DESCRIPTION
**Pull request by matildepark**
As per mockups. Tagging designers since the changes are 'passing a prop', but when and where we should use the icons is the question here.

Screenshot 2020-10-16 at 11 51 36 AM

### CODE REVIEW

**Comment by g-a-v-i-n** [comment]
Nice. There should be 2px padding around the glyph, with a 16px width and height. 

Screen Shot 2020-10-19 at 10 33 14 AM

**Comment by matildepark** [comment]
Padded!

image

**Comment by matildepark** [comment]
Should this button have a smaller sigil anyway? 
image

**Comment by urcades** [comment]
the simplified sigils look beautiful in a chat where they are widely customized, like in urbit-community. I think per the indigo spec, we should give them a 1px radius in the chat view.

In the designs created thus far, the top bar sigil is fully 16px square, with no background color — the sigil itself is edge-to-edge 16px, but still iconified. Example/comparison here:

Screen Shot 2020-10-19 at 3 21 07 PM

Screen Shot 2020-10-19 at 3 21 21 PM

**Comment by urcades** [comment]
Another comparison here:

Screen Shot 2020-10-19 at 3 22 49 PM

**Comment by matildepark** [comment]
OK, can change some implementation stuff ... seems that the top bar sigil colour should be a big faded too.

**Comment by urcades** [comment]
it should be using `gray` I believe

**Comment by matildepark** [comment]
OK, addressed the padding and unpadded the statusbar sigil, set it to 16px. The partially transparent colour is a bit beyond me for the moment — unsure how to ensure the sigil render inherits our indigo-react theme instead of, well, css variable `gray`. I think this is ok to merge for a pass.

**Review by urcades — APPROVED** [review]

**Pull request merged**
