### PR TITLE
hark: add %add-note JSON decoder

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Allows notifications to be created from the frontend, and adds api bindings for the same 
cc: @patosullivan

### CODE REVIEW

**Comment by patosullivan** [comment]
Are we good to merge this one, @liam-fitzgerald ?

**Comment by patosullivan** [comment]
Gonna try to cut a release today. Are we good to merge this?

**Comment by liam-fitzgerald** [comment]
Absolutely

**Comment by liam-fitzgerald** [comment]
we are now!

**Pull request merged**
