### PR TITLE
autoprop: automated pill (& other boot prop) building

### PR DESCRIPTION
**Pull request by Fang-**
This is the arvo part of #5470, cherry-picked and updated to account for recent clay changes.

Primary addition here is `/pkg/autoprop`, a utility for automatically building pills and "prop" files, the latter of which will only become useful once the vere side of #5470 lands. (I am not currently looking at backporting that, but could be convinced to give it a quick shot.) In the immediate term, we intend to use that utility to keep the bootstrap pill up to date.

Secondary additions include a `%prep` task for clay to prime its blob storage (for quicker post-boot desk syncing), and a slightly refactored pill library & generators.

Once we get this onto the moon I've set up for this purpose, we can mark #6231 as done.

### CODE REVIEW

**Comment by zalberico** [comment]
Since this isn't a kelvin we should be able to merge this (pending CR and passing tests) and get it in for the next release (currently that will branch after doccords on Jan 31st with a target ship date of Feb 7th).

@belisarius222 and @jalehman for context

**Review by philipcmonk — DISMISSED** [review]
This looks good to me.  CI is failing in a weird place, kind of looks like a transient networking error, so i'll re-run now.

**Comment by Fang-** [comment]
@philipcmonk I noticed I had missed the old-style `%kiln-install` poke sent by dill. iiuc the actual value of the `once` flag doesn't matter here, since it's a purely local install. `&` seems most appropriate regardless though. ptal

**Comment by philipcmonk** [comment]
That change actually got reverted in #6250 because %kiln-install is used in a bunch of places.

**Review by philipcmonk — APPROVED** [review]

**Pull request merged**
