### PR TITLE
chat-fe: add unread and day indicators

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Adds unread and day indicators. Also changes sending of read receipts to occur when the unread indicator passes the halfway mark of the screen.

cc: @urcades 

Demo:
Screen Shot 2020-04-19 at 2 12 53 am

Screen Shot 2020-04-19 at 2 11 43 am
Screen Shot 2020-04-19 at 2 11 20 am

### CODE REVIEW

**Comment by matildepark** [comment]
Might have no impact, but given the incoming Firefox PR, you’ll want to ensure these features PRs work:

- in both colour schemes
- on mobile and desktop
- on most browsers, and then also Firefox

Be careful! We are adding a lot of features that make testing easier to mess up. Though perhaps just wait for the Firefox PR to get a merge ...

(Also, just FYI that we’ll probably stagger these feature releases out one week at a time to catch the bugs individually should they arise.)

**Comment by loganallenc** [comment]
Agreed with this approach Matilde.

**Comment by liam-fitzgerald** [comment]
merged master && tested on FF

**Comment by loganallenc** [comment]
What does it look like on mobile?

**Comment by liam-fitzgerald** [comment]
good catch just pushed a fix
Screen Shot 2020-04-21 at 4 58 21 pm

**Pull request merged**
