### PR TITLE
eyre: add %cache scry to eyre for full cache

### LINKED ISSUE #6830: Eyre needs a scry endpoint to return all cache entries
Currently if you nuke the %blog agent your blog will still be published because it stores the pages in the Eyre cache. Eyre only lets you scry for cached data if you know the exact URL path so, having nuked %blog, there's currently no way to get a list of all cached pages to remove them.

### PR DESCRIPTION
**Pull request by tinnus-napbus**
this adds a %cache scry to Eyre to return the entire cache. It also moves $cache to lull so you can easily return it.

currently, if an app adds a bunch of stuff to the cache and then you nuke it, you have no way to remove the entries unless you know off the top of your head the exact paths. This way, you can grab the whole thing and figure out what you need to remove.

resolves #6830

### CODE REVIEW

**Review by liam-fitzgerald — DISMISSED** [review]
boyscouting is appreciated, totally sensible PR. I see no reason this shouldn't be included.

LGTM!

**Comment by liam-fitzgerald** [comment]
I'm not super familiar with the $gang interface, but @joemfb is, so
I'm gonna punt that to him

**Comment by Fang-** [comment]
Somehow I missed this when I made #6913, but that has since been merged and implements the same scry as this, so heads up on that wrt conflicts.

**Comment by tinnus-napbus** [comment]
closing as the same scry is implemented in #6913

**Pull request closed without merging**
