### PR TITLE
@urbit/http-api: surface mark of updates

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Surfaces the mark of the subscription updates.
For this to not be `json` requires that the ship be running the upcoming kernelspace update. However this upgrade is backwards and forwards compatible, i.e. current `http-api` and these changes are compatible with both current kernel space and upcoming kernel space. How to proceed with versioning changes? Suspect a minor version bump, because type signatures have changed, albeit not very meaningfully.

### CODE REVIEW

**Comment by liam-fitzgerald** [comment]
no, as in for the `mark` argument to the event callback to not be the string `"json"`

**Comment by matildepark** [comment]
How breaking is this for non-Landscape Urbit API consumers? I recall Landscape used to key off that `json`, unsure if others do.

**Comment by liam-fitzgerald** [comment]
This is not breaking whatsoever, we retain full forward and backward compat

**Review by arthyn — APPROVED** [review]
Seems fine to me

**Pull request merged**
