### PR TITLE
Delete outside/cre2 and outside/re2

### PR DESCRIPTION
**Pull request by jfranklin9000**
**Note:** this pull request also contains the changes from:
````
https://github.com/urbit/urbit/pull/741
````

#### Files changed

````
Makefile
jets/tree.c
````

#### Files / directories deleted

````
outside/cre2/
outside/re2/
````

#### Files to be deleted (or do we want to keep them in tree?)

````
jets/e/repg.c
jets/e/rexp.c
````

#### Bonus whitespace changes for consistency in Makefile (tabs to spaces)

````
jets/f/ut_buss.o \
jets/f/ut_find.o \
````

#### Bonus cleanup deletion in Makefile because this doesn't exist

````
-Ioutside/bpt \
````

#### Question

`README.md` says Urbit depends on `re2c`.  Is this true?
It doesn't seem to be needed; I built successfully after uninstalling it.
I'll patch `README.md` if not.

### CODE REVIEW

**Comment by ohAitch** [comment]
It does not: we used to have regex jets, they were deemed to be a poor fit for hoon.hoon, and nobody's found them useful enough to add them back as a userspace library.

**Comment by jfranklin9000** [comment]
OK, final question: should I delete files `jets/e/repg.c` and `jets/e/rexp.c` or leave them in the source tree?  (If I delete those files should I delete the lines referencing `u3we_repg` and `u3we_rexp ` in `jets/tree.c` (which are commented out now)?)

**Comment by cgyarvin** [comment]
Yes, please delete.  Thanks!

**Comment by jfranklin9000** [comment]
Done.  It's squashed into one commit.

**Pull request merged**
