### PR TITLE
btc-wallet: Switch to hooks and functions

### PR DESCRIPTION
**Pull request by finned-palmer**
This should be good to go based on my testing. Would be good to get others to poke around and test it.

For https://github.com/urbit/bitcoin-wallet/issues/34

### CODE REVIEW

**Comment by timlucmiptev** [comment]
OK, I'm probably less qualified than you to review this, so I'll merge it once you tell me it's fully tested.

**Comment by finned-palmer** [comment]
Ok, I think we're good to go. We really need to build out some unit tests eventually.

**Comment by finned-palmer** [comment]
merge conflicts resolved

**Comment by finned-palmer** [comment]
I derived a vpub from my master ticket's xpub, been using that to test. Doesn't look like we can actually sign TXs in bridge that were generated using a vpub, though (in either my branch or master). Tested signing with mainnet though and it works. Everything else is working in testnet, so this branch should be good to go.

**Pull request merged**
