### PR TITLE
all: sets scrollbar colors

### PR DESCRIPTION
**Pull request by tylershuster**
fixes urbit/landscape#87

Also fixes reversed scroll dragging in Chrome...?

### CODE REVIEW

**Comment by matildepark** [comment]
> Also fixes reversed scroll dragging in Chrome...?

*How*?

**Comment by tylershuster** [comment]
The line that specifies the scrollbar width seems to invoke some deep magic at the core of Chromium's implementation that makes it think a bit harder about what it's doing. Remove that line and you don't get any of the fixes.

**Comment by tylershuster** [comment]
FF Light:
image
FF Dark:
image
Chrome Light:
image
Chrome Dark:
image

**Comment by tacryt-socryp** [comment]
Safari?

**Comment by tylershuster** [comment]
Safari is Webkit, so it looks the same as Chrome

**Comment by tylershuster** [comment]
(These are webkit prefixes, which Chrome respects)

**Comment by matildepark** [comment]
Safari works fine with "always show scrollbar" on, as said — 

image

And it indeed does fix the backwards scroll stuff. I do not even begin to get it.

**Review by matildepark — APPROVED** [review]

**Comment by tylershuster** [comment]
Maybe it takes control over an implementation that's normally controlled by the OS

**Comment by matildepark** [comment]
Dark mode much cleaner (livenet on right). 
image

**Pull request merged**
