### PR TITLE
ames: honor -p for non-galaxies

### PR DESCRIPTION
**Pull request by joemfb**
This was never properly wired up in cc-release. Also adds port printfs for all ships.

### CODE REVIEW

**Comment by ohAitch** [comment]
Yeah like, unless you know what you're doing you don't want -p anyway, for
galaxies this should print a loud warning about "the port you _probably_
want is nnnnn" but I think still work?

**Comment by joemfb** [comment]
I can believe it would be slightly more convenient to have that flexibility galaxies. Not sure how much it matters, given the external configuration overhead. @brendanhay, what say you?

**Comment by noops888** [comment]
I would like this option on planets, stars, or even moons so that urbit is not using a random port every time it's run - this makes firewall configuration a lot easier.

**Comment by brendanhay** [comment]
Ideally the `-p` option would be honored for any ship class - but I think loud warnings are in order when used with a Galaxy to ensure the operator does in fact, know what they are doing.

For hosting, having the ability to assign ports using `-p` to any ship is mildly desirable as it removes the need to unobsfucate/fynd the `@p` within internal configuration (say, containers using hardcoded `-p 13337`) - leaving the responsibility of ensuring that `@p + 13337` is exposed externally left up to external configuration (load balancers, firewalls, etc.) or the hosting operator.

**Comment by joemfb** [comment]
The aye's have it. @belisarius222, PTAL.

(Closes #2062)

**Comment by jtobin** [comment]
I'll merge this as I'm judging by @belisarius222's original review here, plus the comment in the linked issue, that he'll find the solution here agreeable.

**Pull request merged**
