### PR TITLE
channel.js: ack every 30 events *even if this.outstandingJSON is empty*

### LINKED ISSUE #4110: landscape: repeated clog on group-store subscription
I'm getting `%e %clogged` printfs relatively frequently. Decided to pop open the debug dashboard and see what specific subscription this is. Took a little bit before I caught it in the act, but:

image

(Note the right-hand "unacked events" column.)

Hitting refresh repeatedly sometimes shows the amount of unacked events for the group-store subscription climb rapidly, sometimes paired with `<<ames>>` flickering on the ship's cli. My best guess it's getting contact data updates or something for people who are (re)joining the groups I'm in, but why those events specifically aren't getting acked, I have no clue.

### PR DESCRIPTION
**Pull request by tacryt-socryp**
Hotfix to channel.js that *should* (currently being tested) vastly reduce `%eyre` clogs. Fixes #4110.

### CODE REVIEW

**Review by liam-fitzgerald — APPROVED** [review]
Looks correct, have you tested it?

**Comment by tacryt-socryp** [comment]
Am currently testing it on `~tacryt` to see if it reduces clogs in the wild.

**Comment by tacryt-socryp** [comment]
Oof, this issue was far worse than expected. We were incorrectly setting the `lastAcknowledgedEventId` and also trying to compare the values of a string and an integer with the `<` operand to determine whether to send the ack. In other words, we never acked under any conditions.

**Comment by matildepark** [comment]
I'm content pushing this tomorrow but with the caveat that we cache bust channel.js to ensure people catch the fix here.

**Comment by matildepark** [comment]
ping @tacryt-socryp ? This seems sooner the better if tacryt is clogged less.

**Comment by tacryt-socryp** [comment]
This definitely made ~tacryt clog less

**Comment by matildepark** [comment]
So can we cache bust it? Looks like one line in file server.

**Review by Fang- — APPROVED** [review]
Pretty wild. I think the two branches of the "have acknowledged last event" check could be merged, the branching moved to the construction of the payload specifically. Might make the flow here a bit more clear. But the logic itself is fine as-is.

**Comment by tacryt-socryp** [comment]
Brief offline chat with @matildepark and we're moving ahead with this as a hotfix as is. not sure about deploy schedule

**Pull request merged**
