### PR TITLE
landscape: add woff2 support, serve Inter & Source Code Pro

### PR DESCRIPTION
**Pull request by tylershuster**
Fixes https://github.com/urbit/landscape/issues/92 except it doesn't. What am I missing?

(does not reference inter.woff2 in CSS yet, just trying to get it to serve woff2 files)

### CODE REVIEW

**Comment by pkova** [comment]
My guess would be `pkg/interface/src/views/css/fonts.css` and `pkg/interface/dbug/src/css/fonts.css`.

**Comment by matildepark** [comment]
Well the first thing I’d do is go directly to ~landscape/fonts/inter.woff2 and see if it’s there.

**Comment by tylershuster** [comment]
Right yeah I went to the URL and got a 404. Haven't added it to css yet

**Comment by pkova** [comment]
This is broken because the url extension parsing in zuse is broken. I made a PR #3603.

**Comment by tylershuster** [comment]
Cheers that puts me back on track

**Comment by matildepark** [comment]
You may want to target next-sys since this depends on the PR in there. (And maybe serve Source Code Pro while you're at it.)

**Comment by tylershuster** [comment]
Good point on the target. I've based off it. I'm adding SCP but I've run into some issues I'm working through with fang

**Comment by tylershuster** [comment]
@Fang- Here's what I'm working with. Hopefully you can reproduce my problem (For spectators, the problem is that trailing zeroes get trimmed off the end when the woff2 is served)

**Comment by tylershuster** [comment]
Should note for posterity that we have an issue where uppercase files don't get served

**Comment by Fang-** [comment]
> the problem is that trailing zeroes get trimmed off the end when the woff2 is served

This probably happens at the point of storage in clay, because we define its canonical type to be an atom. If we care about leading zeroes (trailing zeroes become leading because muh byte ordering) then the type should be octs!

Defining the mark as such, and updating file-server to scry for `octs` instead of `@`, seems to work:

```hoon
|_  dat=octs
++  grow 
  |% 
  ++  mime  [/font/woff2 dat] 
  -- 
++  grab 
  |% 
  ++  mime  |=([=mite =octs] octs) 
  ++  noun  octs
  -- 
++  grad  %mime 
--
```

We should probably consider making file-server filetype agnostic, and just always scrying for `(snoc path.content.u.content %mime)`, instead of manually reconstructing the octs and content-type... but that's outside of scope here.

**Comment by tylershuster** [comment]
So what needs to be changed besides this mark?

**Comment by Fang-** [comment]
> updating file-server to scry for `octs` instead of `@`

So, something slightly tidier than:

```hoon
        ::  etc
        ?.  .^(? %cu scry-path)  [not-found:gen %.n]
        ?:  ?=([~ %woff2] ext.req-line)
          :_  public.u.content
          [[200 [['content-type' '/font/woff2'] ~]] `.^(octs %cx scry-path)]
        =/  file  (as-octs:mimes:html .^(@ %cx scry-path))
        ::  etc
```

**Comment by tylershuster** [comment]
You'll make a hooner of me yet

**Comment by tylershuster** [comment]
If I update `file-server` to the following:
```
        ?.  .^(? %cu scry-path)  [not-found:gen %.n]
        =/  file  (as-octs:mimes:html .^(@ %cx scry-path))
        :_  public.u.content
        ?+  ext.req-line  not-found:gen
            [~ %js]     (js-response:gen file)
            [~ %css]    (css-response:gen file)
            [~ %png]    (png-response:gen file)
            [~ %woff2]  [[200 [['content-type' 'font/woff2'] ~]] `.^(octs %cx scry-path)]
```

I get

```
%nets-failed
%nets-need
[p=@ud q=@]
%nets-have
@
arvo: scry-lost
```

**Comment by matildepark** [comment]
Since the Zuse change is in master this can target userspace again

**Pull request closed without merging**
