### PR TITLE
ford: remove ship and desk from %reef +rain path

### PR DESCRIPTION
**Pull request by belisarius222**
This should allow %reef builds on %base and %home desks to share cache.

### CODE REVIEW

**Comment by ohAitch** [comment]
arguably the desk should be a runtime "biblical" constant; removing it
entirely will cause much confusion looking through hoon or zuse stack
traces when your source is a different version, though to an extent this
already happened with case zeroing

perhaps it's time for clay to grow a `@uv/absolute/file/path/hoon`
interface, keyed off the hash of the file? (keyed off hash of the desk
would be neater in some sense but much less compatible with this sort of
caching; honestly the path could be entirely presentational and ignored,
like blog post or amazon product "readable" url slugs)

**Comment by belisarius222** [comment]
I doubt we'll lose important debugging information from this change.

@liam-fitzgerald's work to put file locations in types suggests we at least want some kind of programmatically readable path in there, so that an editor can jump-to-definition.  I suspect as desks get more self-contained, being reminded which desk something happened in will also become less useful.  Arguably, for kernel code the pair of spur (or maybe even just a $term like %zuse, %arvo, or %hoon) and Kelvin version should be an unambiguous file reference.

**Comment by joemfb** [comment]
@belisarius222, I don't see how this would help with slow boot due to #2322, as I don't think we build anything but %home during boot. It might help with `|mount`'ing desks other than %home.

I think we want the paths in the stack traces. As long as it's possible to run different versions of a piece of code, it's a help to know where the source came from. Even in the kernel, as |autoload or the equivalent could be set on different desks.

We could have remove the path entirely from %spot, and have a separate hint that sets the path for subsequent %spots. Or maybe a biblical would work, I'm not entirely sure.

Adding %spot to type is mostly orthogonal -- it's behind a flag, and probably shouldn't be on in general. And those types won't be available to traces.

**Comment by belisarius222** [comment]
Right, it wouldn't help with boot.  It would help with later %reef builds across desks, though, which currently can't share any caching at all because the desk information is in there.

In over two years of working on Urbit, I'm pretty sure that not once have I made use of the ship or desk in a stack trace for debugging purposes.  Have you?  Maybe @ixv has on live ships.  Also keep in mind this is just for %reef builds.  Builds of other files still have the full beam (with zeroed-out case) as their +rain paths.

Knowing that an error happened on a particular line in hoon vs. zuse is certainly useful, but knowing it happened on this ship (which it always did) or in some particular desk ... doesn't seem anywhere near as useful as being able to share kernel build results across desks.

This "biblical" idea is possibly compelling, although I'm not sure anyone knows how to implement that, so I wouldn't count on it coming into existence anytime soon.

Being able to load kernel source and pit from Arvo itself should fix this issue, so I could just drop it in favor of that.

—
~rovnys-ricfer
https://urbit.org

**Comment by loganallenc** [comment]
Status on this?

**Comment by belisarius222** [comment]
dead in the water

**Pull request closed without merging**
