### PR TITLE
gen: add |new-desk for creating minimal desks

### PR DESCRIPTION
**Pull request by Fang-**
The created desk includes the bare minimum of necessary files, sourced from base (by default), or some desk of the user's choosing.

### CODE REVIEW

**Comment by belisarius222** [comment]
Not all Clay commits are diffs, which might be why the missing codepath isn't always triggered.  I think we do need %txt in there for now, though.

**Comment by rabsef-bicrym** [comment]
I beg of thee, bring this into core.

**Review by philipcmonk — APPROVED** [review]

**Comment by rabsef-bicrym** [comment]
Yay!

**Comment by matildepark** [comment]
Thank you Phil. I've never seen the boy so happy like this.

**Pull request merged**
