### PR TITLE
king: update to ghc 8.10.4

### PR DESCRIPTION
**Pull request by ryjm**
I can't get this to build locally for some reason - lorri keeps trying to build ghc.

### CODE REVIEW

**Comment by ryjm** [comment]
```unpacking 'https://github.com/nixos/nixpkgs/archive/db21819e91aee7d2bc2edb5845bdad65cddb5cee.tar.gz'...
unpacking 'https://github.com/input-output-hk/haskell.nix/archive/a88542003caddbfeff37ef2bd7fc51b4a9e43d1f.tar.gz'...
error: infinite recursion encountered, at /nix/store/hvvl42amkxhzbqi0k5hyshic5kr7wk5b-nixpkgs-src/pkgs/top-level/all-packages.nix:3595:10
(use '--show-trace' to show detailed location information)
Error: Process completed with exit code 1.```

i think this is a bug in nix, investigating.

**Comment by tacryt-socryp** [comment]
is this ready?

**Comment by ryjm** [comment]
Not quite, OSX builds are still failing because of lmdb.

**Comment by pilfer-pandex** [comment]
This looks fine except:
- fix the build
- undo the package.yaml -> cabal change, as discussed in meeting
- see if you can get the latest 9.* instead of 8.10

**Review by pilfer-pandex — CHANGES_REQUESTED** [review]
As per my previous comment.

**Comment by joemfb** [comment]
Closing, as king-haskell is deprecated (and build changes have a short half-life).

**Pull request closed without merging**
