### PR TITLE
clock: render in SVG, show moon phase

### PR DESCRIPTION
**Pull request by tylershuster**
image

### CODE REVIEW

**Comment by urcades** [comment]
I see the utility for dimming the donut hole for readability reasons, but it detracts from the geometric starkness of the interface that I personally find very pleasing..

I think if we really wanted a utility-driven clock, we'd simply stick a numerals-only clock in the menubar area and be done with it — I think the homescreen-based clock is somewhat of a more artistic object that doesn't exactly need to be 'read' more than it needs to be 'perceived'.

**Comment by urcades** [comment]
I'd be okay with retaining the "dimmed and more legible" donut hole if others felt strongly about it. 

I wouldn't die on a hill to make the clock **less** legible, heh. Just expressing the 'keep it an art object' take.

**Comment by matildepark** [comment]
> I see the utility for dimming the donut hole for readability reasons, but it detracts from the geometric starkness of the interface that I personally find very pleasing..

Why not make it always black bg

**Comment by urcades** [comment]
> > I see the utility for dimming the donut hole for readability reasons, but it detracts from the geometric starkness of the interface that I personally find very pleasing..
> 
> Why not make it always black bg

Oh, well to be clear, I'm pro no background at all — literally just a punched-out void that would allow you to see the background, so the "ring" of the clock is the shape that is emphasized. This obviously gets into low-legibility territory depending on the color/image of a user's background.

Basically, if others agree we like the clock for its artistic qualities, I'd say we should vouch for no background. 

If we believe the clock should meet a bar of accessibility/legibility, we should probably leave the background as-is.

**Comment by matildepark** [comment]
> Oh, well to be clear, I'm pro no background at all — literally just a punched-out void that would allow you to see the background, so the "ring" of the clock is the shape that is emphasized. This obviously gets into low-legibility territory depending on the color/image of a user's background.
> Basically, if others agree we like the clock for its artistic qualities, I'd say we should vouch for no background.

Why not remove the time and date if the actual timetelling isn't important

**Comment by urcades** [comment]
While typing the above, I realized if we had a more developed approach to on-hover interactions, the clock could be a pure visual ring, and could display the time on-hover, using a background matched to the light/dark theme.

**Comment by urcades** [comment]
> Why not remove the time and date if the actual timetelling isn't important

Well, that's the primary object of debate here imo, I'm more or less trying to attain a temp check on whether we think this interface is more art/fun or intended to be a utility-based thing, that's all.

**Comment by g-a-v-i-n** [comment]
The svg clock is very cool. Canvas was probably overkill. Could these changes be made?
- make the donut hole white. 
- make the time black. 
- make the date gray60. 

Thanks!

**Comment by urcades** [comment]
> make the donut hole white

and w/e background color we use for dark mode, I presume?

**Comment by g-a-v-i-n** [comment]
yes, but that should happen automatically via the theme

**Comment by tylershuster** [comment]
You would think so. But because this is SVG, indigo colors aren't available automatically. Do you have an example in the `indigo-react` repo that you can point to? I need to set them manually and add a listener for dark mode.

**Comment by matildepark** [comment]
> You would think so. But because this is SVG, indigo colors aren't available automatically. Do you have an example in the indigo-react repo that you can point to? I need to set them manually and add a listener for dark mode.

Just check the two values for `white` in the themes directory and use the listener logic as in the root application. Actually I think the clock has a listener already.

**Comment by g-a-v-i-n** [comment]
You can give an svg element an id or className, and then target that in a styled component wrapper. Up to you.

```jsx

const ApplyDonutBg = styled.div`
   #donut {
       fill: ${p => p.theme.colors.white};
}
`
```
and
```jsx
<ApplyDonutBg>
<svg
        style={{ height: '100%', width: '100%'}}
        viewBox={`0 0 ${VIEWBOX_SIZE} ${VIEWBOX_SIZE}`}
        xmlns="http://www.w3.org/2000/svg"
        xmlnsXlink="http://www.w3.org/1999/xlink"
      >
...
 <circle cx={CY} cy={CY} r={RADIUS} fill={background} id={#donut} />
...
```

**Review by g-a-v-i-n — APPROVED** [review]

**Comment by tylershuster** [comment]
fixing colon and rebasing

**Comment by matildepark** [comment]
Loadin' up Brisbane, Australia time zone and ...

image

**Comment by matildepark** [comment]
Reverting for now ...

**Comment by tylershuster** [comment]
Well that's because they're all upside down over there

**Comment by matildepark** [comment]
No I mean if you set your coordinates to Australia and also your date/time to Australia you'll see this, we just need to enforce a mask on that donut

**Pull request merged**
