### PR TITLE
clay: fix meet-conflict crash

### PR DESCRIPTION
**Pull request by philipcmonk**
When clamming was changed to crash instead of coerce, this idiom broke.  Fortunately, `_` works fine.

fixes urbit/docs#714

### CODE REVIEW

**Comment by ohAitch** [comment]
wait _~ still does coerce? that's confusing

**Comment by joemfb** [comment]
It's not so much that `$_` coerces, it just clams to a constant. So it won't crash regardless of the sample.

**Comment by philipcmonk** [comment]
Ah yes, I forgot we added `+key:by`; will change.

**Comment by ohAitch** [comment]
Right, all other molds no longer clam and now er gauge, while $_ still
clams. The consistent handling of this would be to have $_ coerce to a
constant, and then crash unless the input was that exact constant

(Unless ofc molds are after all a useful syntactic capability that we still
want in the system...)

**Comment by joemfb** [comment]
@ohAitch, "gauge" terminology predates me. But there's an argument that `$_` and `$-` (and the not-yet-parsed core interfaces in `+spec`) should all behave as you say. It seems like the most inconsistent part of the new crash-first story for molds.

**Comment by ohAitch** [comment]
sorry it's not like an Official Term, I just meant the new crash-first story

**Comment by joemfb** [comment]
@philipcmonk, `+key:by` producing a set is obviously correct, but I find myself usually wanting a list, which leads me to `~(tap in ~(key by *(map)))` or `(turn ~(tap by *(map)) head)`, neither of which is particularly satisfying ...

**Comment by joemfb** [comment]
A particular problem with `$_` now is the pattern of using it to change the bunt: `_|` or `_1`, for instance. The right way to write those now would be `$~(| ?)` and `$~(1 @ud)`, but I haven't done that, or seen it anywhere.

**Comment by ohAitch** [comment]
I think you mean one of the other new $ runes and $~ is an iron gate? But
yeah _1 being equivalent to @ moldwise sounds right to me, I guess we don't
want "check equal to sample" and rather "check fits general type of
sample"; mostly it seems bad for _%1 (or in the motivating case _~) to
traditional-sense-mold when ,%1 (resp. ,~) crashes

**Comment by joemfb** [comment]
No, I mean `$~(a b)`, which explicitly sets the bunt of `b` to `a`.

```
> *@ud
0
> (@ud 10)
10
> *$~(1 @ud)
1
> ($~(1 @ud) 10)
10
```

`$-(a b)` is `_|~(a *b)`.

```
> $-(@ @)
<1.ngv {* {our/@p now/@da eny/@uvJ} <21.bal 27.kva 7.ylp 36.uek 92.otg 247.tye 51.mvt 126.xjf 41.mac 1.ane $141>}>
> *$-(@ @)
<1|akq {@ @ @}>
> ($-(@ @) dec)
<1|akq {@ @ @}>
> (($-(@ @) dec) 0)
0
> (($-(@ @) dec) 10)
0

```

`,%1` used to be `_%1`, but now it's built-in:

```
> *%1
%1
> (,%1 1)
%1
> (,%1 0)
ford: %ride failed to execute:
> *_%1
%1
> (_%1 1)
%1
> (_%1 0)
%1
```

Not quite optimal ...

**Comment by ohAitch** [comment]
Ah yup you're right, am I thinking of $-(a b) or sth?

**Comment by philipcmonk** [comment]
Yes, $- is equivalent to both $_  ^|  |=  and $_  |~ and was formerly $+

**Comment by ohAitch** [comment]
So it used to be |+ $+ and is now |~ $- then?

**Comment by philipcmonk** [comment]
Yeah, exactly.

**Pull request merged**
