### PR TITLE
Visual QA: Module-wide header uniformity fixes

### PR DESCRIPTION
**Pull request by urcades**
Basically, this PR includes a collection of edits made to the headers across each of our modules.

I flattened the font sizing, fixed edge margins/padding, and fixed some copy, in the case of the Contacts app.

After creating this PR, I'll include a small guide for testing/viewing the changes made.

Quick note: This PR/branch was derived from my last QA PR, which is the tiny class fix for publish comments module margins. That should be rolled into os1-rc before this PR.

### CODE REVIEW

**Comment by urcades** [comment]
Suggested review steps:

Kapture 2020-02-26 at 21 09 49

1. Checkout this branch
2. Open each module in a separate tab, in a new window (like the above .gif)
3. Check for consistency across each module

**Comment by urcades** [comment]
One pending issue is the header-bar's underline in dark mode chat changing colors: I will fix this momentarily, but I need to run for a bit.

**Comment by matildepark** [comment]
Dojo uses `black` instead of `gray2` for "Home" in its light mode variant. And the ship name is slightly bumped on Dojo, Launch and Publish compared to Chat and Links. But mostly this looks so aligned that you start to see the infrastructural, template feel, which is really cool.

> One pending issue is the header-bar's underline in dark mode chat changing colors: I will fix this momentarily, but I need to run for a bit.

I was struggling to see what you meant by this, but you refer to the top header of the apps themselves as the 'header' — I was just thinking about the OS1 header for this. Yeah, the settings page header in particular needs `b--gray2-d` I think.

**Comment by urcades** [comment]
@matildepark I've addressed all of your feedback — everything is looking wonderful! I'm down to merge this as soon as I get a stamp from you or @jyng

**Comment by matildepark** [comment]
This is looking good, but this looks askew — the sidebar switcher and "Private":

image

**Comment by urcades** [comment]
@matildepark fixed this issue — for future reference, `lh-solid` is a great class for aligning text to buttons/icons

**Comment by matildepark** [comment]
Sorry for so many of these — just one more `lh-solid` to add here and I'll stamp (remove `v-top` I think too)

image

**Comment by urcades** [comment]
@matildepark no thank you — eagle eyes are good for polish, and mine are tired atm, thank you for catching these 🙏

**Comment by urcades** [comment]
I have no idea how to rebase atm, and I am impatient: @jtobin I swear to you I will be better in coming contributions!

**Comment by matildepark** [comment]
> I have no idea how to rebase atm

Impromptu lesson! Sorry!

```
git merge-base <target branch> <this branch>
```

This gives you the commit you branched off from. Then pass that commit to the rebase tool to see the history since then, so you can make changes to your history.

```
git rebase -i <that commit>
```

You'll see a list of commits it's going to replay again in your local repo copy. "Pick" means a regular commit, 'reword' will stop before continuing the replay and let you rewrite the commit title / description, and 'squash' will just put that snapshot into the previous commit.

This always uses vi for me so remember to hit `i` to enter insert mode, `esc` to leave, `dd` and `p` to cut and paste lines to rearrange them...

If all is good and there's no conflicts, `git push -f` to make your branch have this history on the remote repository.

Now, as you're aware, we have a lot of contention around rebase round these parts ... but now you know.

**Comment by urcades** [comment]
@matildepark I believe I've successfully performed my first rebase! It was actually quite fun.

With this completed, am I OK to merge into os1-rc, or should I wait for checks to finish?

**Comment by matildepark** [comment]
You did rebase this successfully, but it's still not [our spec](https://github.com/urbit/urbit/blob/master/CONTRIBUTING.md#hygiene). Sorry to be a hardass, we just might as well figure this out now...

**Comment by urcades** [comment]
Ah, I think I used `pick` on items I had intended to `reword` — also, this is fine, agree this is good to learn properly now.

**Comment by urcades** [comment]
@matildepark wow I did it (i think) — thanks for walking me through the correct way to go about this.

**Comment by matildepark** [comment]
OK — go ahead and merge once CI is complete! I don't know if that's a rule but it seems like a good idea anyway!

**Comment by jyng** [comment]
Is there a specific reason why links doesn't use 'borders' on list-items?
Screen Shot 2020-02-27 at 3 09 21 PM
Screen Shot 2020-02-27 at 3 09 15 PM

**Comment by urcades** [comment]
@jyng no lol, it was probably adapted straight from the mocks, so is my bad — I can add some in to match the chat design

**Comment by urcades** [comment]
@jyng let me know what you think of changes:

Screen Shot 2020-02-27 at 6 59 22 PM
Screen Shot 2020-02-27 at 6 59 19 PM
diff

**Comment by jyng** [comment]
LGTM

**Pull request merged**
