### PR TITLE
clock: ignore cached date for sunrise

### PR DESCRIPTION
**Pull request by tylershuster**
Fixes https://github.com/urbit/landscape/issues/190

### CODE REVIEW

**Comment by matildepark** [comment]
So we were always comparing the time from our last request (every ~3 hours)?

**Comment by tylershuster** [comment]
Right.

**Comment by tylershuster** [comment]
This way won't be accurate to the minute but it doesn't need to be

**Comment by matildepark** [comment]
I can't trigger a reproduction in next userspace to test this, heh.

**Comment by matildepark** [comment]
Ah ok it's when we pass the midnight threshold with a 3 hour cache. Really weird.

**Review by matildepark — APPROVED** [review]
lgtm

**Pull request merged**
