### PR TITLE
[hoon @r] add .0j1 complex float syntax

### PR DESCRIPTION
**Pull request by ohAitch**
Stores real then complex part in the obvious LSB manner: `=(.123j0 .123)`, `=(.3j-4 (cat 5 .3 .-4))`

Parsing feature-flagged as no support has been implemented in the math
cores, which will just ignore/truncate off the complex part.

In dojo,

    =enable-complex-float  &

to try out the syntax. (Or just go nuts with,
```
> ? (div:rs .15 .8)
  @rs
.1.875
> ? .~1
  @rd
.~1
> `@ux`(div:rs .15 .8)
0x3ff0.0000
> `@ux`.~1
0x3ff0.0000.0000.0000
> `@rs`.~1
.0j1.875
```
etc)

Steps to leave draft status:
- [ ] Figure out if we want a `@rsr` `@rdr` etc odor for "real, as in actually real", and implement that in the parser / otherwise resolve the TODO
- [ ] Update all the `ff` library functions and `++r[sdhq]` jet-variants to correctly calculate complex results, or to reject complex inputs per #3673 leaving correct implementations for future work; or at least figure out a more principled way to do the "opt into syntax that breaks all your math" flag.

### CODE REVIEW

**Comment by sigilante** [comment]
(This question presses me because it impinges on how to set up vector types in the matrix library #3536 .)

There are several possible configurations for a complex number type:

1. Complex values have a separate new aura:  `@qd`
2. Complex values are nested inside of floating-point auras:  `@rdc`, etc.
3. Complex values live in the matrix library as a new aura:  `@lcd`
4. Complex values live in the matrix library only as vector/matrix elements:  `@lvcd`

##  Separate New Aura

Complex values are stored as real and imaginary parts inside of a single atom as upper and lower bytes.

An unoccupied aura like `@q` would be used, since the logical choices `@c` and `@i` are already occupied with incompatible types.

Pros:

- Values with the aura has separate handling logic.

Cons:

- Values with the aura don't sit next to similarly-used values such as `@r`.


##  `@r` Nested Aura

Complex values are stored as an extension of the floating-point auras.

Pros:

- Complex-valued logic can live beside the real-valued logic.

Cons:

- Introduces aura complexity relatively close to the language primitives.


##  Matrix Library Aura

In addition to the matrix library types (currently `@lv` for vectors and `@lm` for matrices), we can introduce `@lc` as a container aura for `@lcs`, etc.

Pros:

- Complex values are handled by optimized routines in the matrix library.

Cons:

- Still requires case 4.

##  Matrix Library Value

In this case, complex values are implemented only within the matrix library as entries in a complex-valued vector or matrix.  That is, the primitive complex value is the special case of a 1×1 matrix or a 1× vector, such as `@lvcd` (for vector-complex-double).

Pros:

- Implements complex numbers in the matrix library where they are most likely to be useful.

Cons:

- Requires matrix library to become part of Hoon or Zuse if complex types are going to become Hoon primitives.  (Not necessarily a con, but a design decision.)

---

I personally favor case 3, which is a superset of case 4, but I welcome cases for other configurations.

**Comment by sigilante** [comment]
I should also mention the `@rt` structure that @ohAitch mentioned here:  https://github.com/urbit/urbit/pull/3536#discussion_r505775785

**Comment by ohAitch** [comment]
`@q` is currently occupied by an "unscrambled `@p`" format, though I don't think literally anything ended up using it.

**Comment by sigilante** [comment]
Doh!  Yes, of course.

**Comment by philipcmonk** [comment]
(didn't mean to close this, apparently github deletes PR branches even if other PRs are targeted to them and doesn't retarget the open PRs?)

**Comment by ohAitch** [comment]
I think there's a checkbox for it or sth?

**Comment by philipcmonk** [comment]
normally when you have PR A->B and B->master and then you merge B into master, then the first becomes A->master automatically.  maybe that only applies to the master branch, or maybe it doesn't work when you delete the branch as you're merging

**Comment by joemfb** [comment]
I think you can reopen it if you restore the branch, then retarget elsewhere.

**Pull request closed without merging**
