### PR TITLE
eyre: add instructions to login page

### LINKED ISSUE #1965: Login page should say how to get passcode
Lots of people bounce off this.  It should say that you can get your passcode by typing +code in the dojo or from bridge.

### PR DESCRIPTION
**Pull request by philipcmonk**
A common issue is not knowing where to get your login passcode.  This puts those instructions on the login page.

Not sure who to tag on this one, maybe @jyng or @g-a-v-i-n?  Feel free to improve text or styling.

Screen Shot 2019-12-05 at 12 32 54 PM

Fixes #1965

### CODE REVIEW

**Comment by loganallenc** [comment]
Winning! I love it.

**Comment by matildepark** [comment]
Might be better to put that hint in the placeholder. "enter +code from dojo or bridge"

**Comment by jtobin** [comment]
ping @g-a-v-i-n

**Comment by jtobin** [comment]
I'm going to pull this in as it's a strict improvement.

**Pull request merged**
