### PR TITLE
graph-store, metadata-store lib: skip trip and crip, use rap

### PR DESCRIPTION
**Pull request by tacryt-socryp**
Attempting to remove all uses of `+trip` and `+crip` from the hotpath that Landscape data moves through. These arms make quite a few allocations and can be replaced with `+rap` for better performance.

The change to the `%graph-store` lib is likely to have a larger effect.

### CODE REVIEW

**Review by liam-fitzgerald — APPROVED** [review]
LGTM!

**Comment by tacryt-socryp** [comment]
Confirmed on ~tacryt-socryp on livenet that this does not cause any problems and that the returned strings are the exact same as they were before.

**Comment by matildepark** [comment]
Does this have to hit network or can we just put it in the eventual release?

**Comment by tacryt-socryp** [comment]
Shouldn't matter which it targets, but it will make Landscape load times snappier

**Pull request merged**
