### PR TITLE
+gut:by: value by key, or default

### PR DESCRIPTION
**Pull request by Fang-**
What I _really_ wanted to implement was just `|*  b=*`, and bunting the type as in the map definition. But since we can only access the type of individual map _items_, the bunt of that will just be the map's head node.

Unless there's some magic I'm unaware of that can be used here? I'd love to be wrong about this.

Still, the `(fall (~(get by` pattern is common enough (86 instances!) to warrant a stdlib function. If we're forced to take an argument, might as well take a `noun` instead of a `mold`. Bunting is easy, and makes up only ~half of existing `(fall (~(get by` cases anyway.

One could argue this is too small, but I think `got:by` sets a good precedent. It's just big enough to provide some convenience for a common pattern.  
It may be yet another thing to remember the meaning of, but hoon devs are of strong mind!

(Not sure what the CI failure is about, booting with pill built from e7cc662 works fine locally.)

### CODE REVIEW

**Comment by belisarius222** [comment]
I think auto-bunting should be doable. I wonder what percent of the default cases bunt -- I know I do that pattern in a few places in new Ames.

Does this auto-bunt work?

++ gut |* b=* %+ fall (get b) *_?>(?=(^ a) q.n.a)

—
~rovnys-ricfer
https://urbit.org

**Comment by Fang-** [comment]
> I wonder what percent of the default cases bunt

I counted roughly half of them bunting, see also eb6c8a4.

> Does this auto-bunt work?

```hoon
> =m (~(gas by *(map @ @t)) `(list [@ @t])`~[1^'one'])
> (~(gut by m) 5)
'one'
```

No, that just gets you the bunt of the example of the head node, which is its value. And it crashes in the empty map case, which seems important to support here.

**Comment by joemfb** [comment]
I don't think auto-bunting is possible here without explicitly passing the map key/value molds. Those molds are never bunted anywhere in `+by` -- the assertion magic in @belisarius222's example works only to "recover their type" through forward inference, but that assertion will fail in the presence of any bunted `+map` (which will always be `~`).

**Comment by belisarius222** [comment]
If only maps were moist, we could auto-bunt no problem:

```
++  by
  |*  [key=mold value=mold]
  |%
  ++  gut
    |=  [a=(map key value) k=key]
    ^-  value
    ::
    (fall (get a k) *key)
  ::
  ++  get  ...
  --
```

**Comment by ohAitch** [comment]
*value surely

On Tue, Jul 9, 2019 at 14:05, Ted Blackman <notifications@github.com> wrote:

> If only maps were moist, we could auto-bunt no problem:

++  by
  |*  [key=mold value=mold]
  |%
  ++  gut
    |=  [a=(map key value) k=key]
    ^-  value
    ::
    (fall (get a k) *key)
  ::
  ++  get  ...
  --

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GvitHub
<https://github.com/urbit/urbit/pull/1310?email_source=notifications&email_token=AAOFPBRRAARCCS76O7HGFHLP6T4P7A5CNFSM4H4M53Q2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZRQ5KI#issuecomment-509808297>,
or mute the thread

**Comment by belisarius222** [comment]
Yes, I meant *value

—
~rovnys-ricfer
https://urbit.org

**Comment by belisarius222** [comment]
Just remember that moisture is the essence of wetness

—
~rovnys-ricfer
https://urbit.org

**Comment by joemfb** [comment]
@Fang-, to fix CI here you'll also need to commit your own update to `bin/solid.pill`.

**Comment by Fang-** [comment]
Yeah I tried, and I figured I could just run `sh/update-solid-pill`. Turns out I had to walk through my previous commits and build pills for those prior to building a pill for head of this PR, or face the wrath of misleading error messages.

<details><summary>For the record, errors encountered that got resolved by running `update-solid-pill` more.</summary>
When I first tried running it on 12b8134, I got this:

```
+ cp /nix/store/j0diax0fzdjppzs30dnpapn4dpgkyj55-arvo/lib/pill.hoon ./pier/home/lib/
cp: cannot create regular file './pier/home/lib/': Not a directory
```

Okay, that's weird. Let's just make pills for the commits one-by-one. On e7cc662 this worked fine right away. On eb6c8a4 it failed with this at first:

```
[%user-files 377]
WARNING <module> 402 - unrecognized response
gateway timeout
+ mv solid.pill /nix/store/6y85g561dk2kb6fysncr98xds3sjwpnp-solid
mv: cannot stat 'solid.pill': No such file or directory
```

but succeeded on second run, without really changing anything. Might've been an internet connection hickup?</details>

What's the reason this isn't automated in CI, anyway? Seems to me that it should be easier now than ever before.

Also note that the contributing.md hasn't been updated for nix/monorepo dev ops yet. Probably should be prior to release. cc @jtobin.

**Comment by jtobin** [comment]
On Wed, Jul 10, 2019 at 02:57:47AM -0700, Fang wrote:
> Yeah I tried, and I figured I could just run `sh/update-solid-pill`.
> Turns out I had to walk through my previous commits and build pills
> for those prior to building a pill for head of this PR, or face the
> wrath of misleading error messages.

Strange, I've been using `sh/update-solid-pill` a fair bit lately and
haven't had any trouble with it.

> What's the reason this isn't automated in CI, anyway? Seems to me that
> it should be easier now than ever before.

The pill management strategy isn't 100% baked yet.  @joemfb has some
thoughts on this (copied from an email he'd sent me):

On Tue, Jul 02, 2019 at 11:04:54AM -0700, Joe Bryan wrote:
> Determining the correct pill management strategy is complicated by the
> presence of the filesystem in all the pills but ivory.  In theory, every
> commit that changes arvo should also update brass and solid, and every
> commit that changes sys/ should update all three pills.  In practice,
> that's probably more churn than we want. We will also bloat our LFS
> store pretty quickly doing that, and there's no way to GC those files
> from within git. I have some ideas about what I think the platonic form
> of pill management looks like, but they involve a fair amount of work.

Of note: some back-of-the-envelope math I did suggested that adding
another 15000 commits to arvo, and creating 3x pills for each one, would
only increase the LFS usage by about ~250G.  I don't know anything about
LFS's costs/limitations yet, but that may very well be acceptable, given
the added convenience.

> Also note that the contributing.md hasn't been updated for
> nix/monorepo dev ops yet. Probably should be prior to release. cc
> @jtobin.

+1, have a todo item for it kicking around.

**Comment by Fang-** [comment]
Thanks for the info/update!

Pinging @pilfer-pandex for review, now that CI succeeds. Without moist maps this seems like the best we're gonna get.

**Comment by ohAitch** [comment]
What we probably want actually checked in is a "slim" pill, which has the
hoon.hoon nock blob and some bootstrapping code that unpacks a first event
(list [@tpath @]) into hoon zuse vanes etc. That can then be passed in with
-A during development, or added to the boot events to compose a release
pill: extending a jammed list is almost a binary concatenation.

Short of that, it seems at least good to avoid soliding on every single
commit, which would slow down CI considerably: a checked in full pill
should contain the file tree as of the last commit that touched sys/
(checking that version back out to build it if necessary), in the event of
a full breach being brought up to date by the corresponding ames era bump.

**Pull request merged**
