### PR TITLE
Get HTTPS working in King Haskell.

### PR DESCRIPTION
**Pull request by benjamin-tlon**

### CODE REVIEW

**Comment by benjamin-tlon** [comment]
This change is correct, but HTTPS still not working.

Chromium fails with `NET::ERR_CERT_INVALID`.

```
PEM encoded chain:
-----BEGIN CERTIFICATE-----
[...]
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
[...]
-----END CERTIFICATE-----
```

**Comment by benjamin-tlon** [comment]
Maybe I need to parse this and use this:

```
tlsSettingsChainMemory
  :: ByteString | Certificate bytes
  -> [ByteString] | Chain certificate bytes
  -> ByteString | Key bytes
  -> TLSSettings
```

Instead of this?

```
tlsSettingsMemory
  :: ByteString | Certificate bytes
  -> ByteString | Key bytes
  -> TLSSettings 
```

**Comment by benjamin-tlon** [comment]
C King does seem to parse the cert chain itself:

```

  {
    BIO* bio_u = BIO_new_mem_buf(key_u.base, key_u.len);
    EVP_PKEY* pky_u = PEM_read_bio_PrivateKey(bio_u, 0, 0, 0);
    c3_i sas_i = SSL_CTX_use_PrivateKey(tls_u, pky_u);

    EVP_PKEY_free(pky_u);
    BIO_free(bio_u);

    if( 0 == sas_i ) {
      u3l_log("http: load private key failed:\n");
      ERR_print_errors_fp(u3_term_io_hija());
      u3_term_io_loja(1);

      SSL_CTX_free(tls_u);

      return 0;
    }
  }

  {
    BIO* bio_u = BIO_new_mem_buf(cer_u.base, cer_u.len);
    X509* xer_u = PEM_read_bio_X509_AUX(bio_u, 0, 0, 0);
    c3_i sas_i = SSL_CTX_use_certificate(tls_u, xer_u);

    X509_free(xer_u);

    if( 0 == sas_i ) {
      u3l_log("http: load certificate failed:\n");
      ERR_print_errors_fp(u3_term_io_hija());
      u3_term_io_loja(1);

      BIO_free(bio_u);
      SSL_CTX_free(tls_u);

      return 0;
    }

    // get any additional CA certs, ignoring errors
    while ( 0 != (xer_u = PEM_read_bio_X509(bio_u, 0, 0, 0)) ) {
      // XX require 1.0.2 or newer and use SSL_CTX_add0_chain_cert
      SSL_CTX_add_extra_chain_cert(tls_u, xer_u);
    }

    BIO_free(bio_u);
  }
```

**Comment by benjamin-tlon** [comment]
This last changes works, but not sure if correct. @joemfb ?

**Comment by joemfb** [comment]
This looks right -- the first PEM block is our certificate, any subsequent PEM blocks are intermediate certs in the chain (these are optional). Note that the OpenSSL buffered i/o apis have an internal cursor with stateful reads.

**Comment by benjamin-tlon** [comment]
Thanks @joemfb.

**Comment by benjamin-tlon** [comment]
This seems to work. Can I get this merged? @jtobin @ixv @eglaysher @joemfb

**Pull request merged**
