### PR TITLE
interface: embeds on by default

### PR DESCRIPTION
**Pull request by matildepark**
By @vvisigoth request.

cc @tylershuster: this isn't set anywhere else, is it?

### CODE REVIEW

**Comment by tylershuster** [comment]
No...but...uh...this is almost-arbitrary script injection

WARNED - LORAX

**Comment by vvisigoth** [comment]
TBC this isn't a commentary on the righteousness of opt-out embeds, it's
just going to be interpreted as a regression if something that previously
worked doesn't anymore.
—
~poldec-tonteg
http://urbit.org

**Comment by tylershuster** [comment]
Ok, fair enough. What could be worse than allowing Google in, which is already the case?

**Review by liam-fitzgerald — APPROVED** [review]
LGTM!

**Pull request merged**
