### PR TITLE
Use libent for getentropy

### PR DESCRIPTION
**Pull request by mrdomino**
XX make sure to fork [mrdomino/libent](https://github.com/mrdomino/libent) to the urbit org before merging this.

### CODE REVIEW

**Comment by joemfb** [comment]
Thanks! I forked the repo and kicked CI.

@benjamin-tlon, can you confirm that this works with your nix build?

**Comment by benjamin-tlon** [comment]
This looks sweet! I was thinking about pulling in a library instead of reverting the other commit, but all the libraries I found (after a quick search) were pretty heavy.

**Comment by benjamin-tlon** [comment]
Are you the FreeBSD dude @mrdomino?

I'm about to break the FreeBSD build pretty badly (by using `nix` for builds), and I'd like to talk to you about how I can do that without making life too much worse for you.

**Comment by benjamin-tlon** [comment]
Yes! This works with `nix`.

**Comment by mrdomino** [comment]
I'm the OpenBSD dude, so maybe still relevant? Happy to talk, although my time is limited this week. Feel free to send me an email.

**Comment by benjamin-tlon** [comment]
Reviewed the code in `libent`. LGTM :+1:

**Comment by joemfb** [comment]
@benjamin-tlon, you're good with this superseding #1146?

**Comment by benjamin-tlon** [comment]
Yes @joemfb

**Comment by benjamin-tlon** [comment]
Definitely still relevant @mrdomino

**Pull request merged**
