### PR TITLE
moved :write into hood

### PR DESCRIPTION
**Pull request by ohAitch**

### CODE REVIEW

**Comment by juped** [comment]
I hate that git uses heuristics to track renames that diffs like this break. (It's not your fault, it's entirely git's fault. I'm just complaining for the record.)

**Comment by cgyarvin** [comment]
It wouldn't really sting if there wasn't such a thing as git mv.

That's the ultimate problem with snapshot oriented revision control: it loses information...

**Comment by juped** [comment]
`git mv` is an *actual* example of a false affordance. :)

**Comment by ohAitch** [comment]
*notes that he used |mv, which unlike both unix and git `mv ` creates parent directories as needed*
Clay, of course, doesn't track renames either.

**Comment by cgyarvin** [comment]
I don't believe %clay, unlike git, has heuristics to detect renames.  But I
could be wrong...

**Comment by ohAitch** [comment]
Yes. It doesn't have any way to resolve the "one person moved, other person
edited" conflict case /at all/

**Comment by juped** [comment]
This branch is broken on startup, please test and fix

**Comment by ohAitch** [comment]
Yes sorry, eyre-root-beam `|serve` had leaked in (without supporting code).

**Pull request merged**
