### PR TITLE
Master is broken: syntax error in app/azimuth.hoon

### PR DESCRIPTION
**Pull request by tadad**
couldn't build base on my fake ship

### CODE REVIEW

**Comment by belisarius222** [comment]
I find it disturbing that the master branch had a syntax error here in the azimuth code.  It should prevent anything from working, right?  I think this suggests a bunch of artifacts are stale, like pills -- or they fail to build and nobody's tried them.

Or maybe it's more that the master branch has diverged from a good state in a release branch, and the artifacts accurately reflect the good state from that other branch.

**Comment by zalberico** [comment]
You can tell in the git blame, it's this: https://github.com/urbit/urbit/commit/0e16d82a46ea569e04326ba497b99f93b7ddc751

We should not be merging anything into master outside of a tested release.

**Comment by zalberico** [comment]
@tadad can you amend your commit with a better commit message?

**Comment by zalberico** [comment]
I'll resubmit with a new commit message - @tadad thanks for flagging this for us!

**Pull request closed without merging**
