### PR TITLE
publish: add spinner, transition behaviours

### PR DESCRIPTION
**Pull request by matildepark**
Polish batch:

- new-post.js had `mw7` and the other views use `mw6`, so the views weren't consistent in use. Amended to all use `mw6`.
- Sidebar sorter uses the custom dropdown component. Dropdown component gets an `align` prop to flush itself left or right against its parent.
- Sidebar was too long to see all notebooks if you have a lot of notebooks. This is calc'd against the UI height now.
- header-bar moved back into skeleton a la Chat. Spinner added as an animation on the Home button.
Feb-20-2020 00-17-24
- header-bar sigil is now lined up properly with the ship name, and blends into its background regardless of theme.
- New posts, new notebooks, new comments all have proper button disabling transitions and spinner functionality.
- Adding some fixes for `-m` and `-l` viewports for sidebar and note.js navigation back to notebooks — the latter is using a `w-90-l w-90-m` shim for now...

### CODE REVIEW

**Comment by Fang-** [comment]
This might be the cutest spinner we've ever had.

**Comment by ixv** [comment]
Checked out branch, built solid pill and ran gulp to make sure everything was up to date. Got this:
image

**Comment by matildepark** [comment]
Oh, I think I know the issue — I think I forgot to add a single file to the commit. -_-; Standby!

—
~haddef-sigwen
https://urbit.org

**Comment by matildepark** [comment]
Ok, try now @ixv

**Pull request merged**
