### PR TITLE
Updated styles of chat and build systems for JS

### PR DESCRIPTION
**Pull request by loganallenc**
Updated build systems of JS files to remove unnecessary steps and improve speed

### CODE REVIEW

**Comment by ixv** [comment]
Please update the minified js in pkg/arvo

**Comment by loganallenc** [comment]
I thought we were removing those files... Okay will update them

**Comment by matildepark** [comment]
This LGTM so far, but yes the pkg/arvo needs to be updated to make it to OTA, I'm pretty sure. Curious about these build changes, can you specify them a bit? Are we losing functionality here? I will port it to other repos once this is merged.

**Comment by loganallenc** [comment]
@matildepark No important lost functionality. Just removes the Node builtins integration and the automatic JSON file conversion (neither of which we're using). The builtins integration was slowing down the build considerably and adding size to our JS blobs.

**Comment by Fang-** [comment]
Looks like the `message.js` change here has non-trivial conflicts with #1399. I can try resolving those in there, if this gets merged first.

**Comment by ixv** [comment]
I think we're going to want to test your PR further before merging Mark. I don't think its going to make it into this OTA.

**Pull request merged**
