### PR TITLE
chat: fixes wobble

### PR DESCRIPTION
**Pull request by tylershuster**
Fixes https://github.com/urbit/landscape/issues/317

### CODE REVIEW

**Comment by tylershuster** [comment]
See https://github.com/urbit/landscape/issues/317#issuecomment-767154960

**Comment by matildepark** [comment]
@jamesacklin

**Comment by tylershuster** [comment]
@Fang- says this works for him

**Comment by jamesacklin** [comment]
Can confirm, this fixes the wobble on hover.

**Review by matildepark — APPROVED** [review]
No ill side effects in my own (brief) testing. No animations has a really nice feel, weirdly.

**Pull request merged**
