### PR TITLE
eyre: allow last-event-id as query parameter

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Browsers do not support setting custom headers on EventSources, so we
allow the last-event-id to be sent as a query parameter. See below link
for reference.
https://github.com/whatwg/html/issues/2177#issuecomment-332071504

Fixes: #4004

### CODE REVIEW

**Comment by Fang-** [comment]
Neat.

As per my comment in https://github.com/urbit/urbit/issues/4004#issuecomment-732502980, did you look into making `channel.js` use `fetch` instead? Is that unergonomic, unreliable, or in some other way unreasonable?

**Comment by tylershuster** [comment]
Do you mean for EventSources? `fetch` isn't a solution for processing data from SSEs — a more modern way would probably be to use websockets, because SSE support is a bit lacking as you can see in the WhatWG discussion.

**Comment by ohAitch** [comment]
Is it not? `fetch` exposes a [stream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream), which can polyfill a less restricted EventSource API: https://github.com/Azure/fetch-event-source

Though I haven't evaluated the quality of that particular implementation in detail, so it might not literally be as easy as `npm install @microsoft/fetch-event-source`

**Comment by tylershuster** [comment]
Interesting, this didn't exist when I was doing my research. Seems promising, and a clever use of the exposed stream. Would definitely have made my TS lib easier.

**Comment by liam-fitzgerald** [comment]
hmm, closing in favour of a fetch based stream

**Pull request closed without merging**
