### PR TITLE
launch: fix modal backgrounds

### PR DESCRIPTION
**Pull request by matildepark**
I used `washedGray` and forgot it was an opacity colour — falling back to the hex here.

### CODE REVIEW

**Review by jamesacklin — APPROVED** [review]
image

Looking much better.

**Comment by matildepark** [comment]
Let me see if I can make it match better in dark mode, it sticks out now.

**Comment by matildepark** [comment]
Screenshot 2021-02-24 at 5 11 01 PM

**Comment by urcades** [comment]
The buttons themselves looks beautiful with a background, and are looking good on the 'default' dark background, in isolation. In conjunction with the way we render tiles in dark mode, I do have a lurking feeling that this isn't as visually 'put together' as it could be, mostly due to how we actually render the tiles (not the buttons):

Screen Shot 2021-02-24 at 5 17 13 PM

...The buttons themselves (the subject of this issue) feel fine, but there's something I can't put my finger on with how the surrounding elements are rendered. Maybe it's the extreme contrast of the titles (white) with the very light borders that makes this a little uncomfortable to parse.

**Comment by jamesacklin** [comment]
The buttons themselves look good to me; I can rationalize the tile borders for the time being or resolve seperately.

**Review by urcades — APPROVED** [review]
Stamping for the button change in particular, but feel like we need to render tiles better in dark mode, maybe via a separate PR

**Pull request merged**
