### PR TITLE
groups: enable sigil foreground color customization

### PR DESCRIPTION
**Pull request by pkova**
Bridge had spoiled me on this.

Also fixes a bug where if you type an uppercase letter A-F to the sigil color box you enter an annoying infinite request loop until you refresh.

### CODE REVIEW

**Comment by matildepark** [comment]
Oh my goodness.

**Comment by matildepark** [comment]
We’ll have to adjust every app to make use of this too but just wow.

**Comment by galenwp** [comment]
I feel like the right way to do this is to provide a palette, otherwise these are going to often look quite bad.

**Comment by loganallenc** [comment]
I feel like we should offer maximum customizability to our users, and also provide the ability for a user to turn off display of colors entirely.

**Comment by matildepark** [comment]
I agree that we want maximum customizability. I see no reason to kneecap this out of user distrust ... I believe people can arrive at beauty in ways I couldn’t fathom by leashing them. 

Turning off colours is interesting. I can imagine how to implement but we’d need a settings store, no?

**Comment by reitraced** [comment]
oh wow i could finally do that black on pink ive wanted to do since os1 came out

**Comment by eglaysher** [comment]
I will also speak in favor of this feature, though not being on interface, I have no idea about the implementation.

**Comment by loganallenc** [comment]
So far the code looks quite reasonable and good. I'll do a full review once we finish the OS1 release, as we're trying to pause new features until we're well-pleased that the current functionality / user stories are smooth and work properly.

**Comment by loganallenc** [comment]
Hi, we're going to include automatic logic for making the sigil white when on a dark-colored background and black when on a light-colored background. Closing this, as it complicates the contacts UI.

**Pull request closed without merging**
