### PR TITLE
interface: grabbag of fixes

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Leap: fix double section

Fixes urbit/landscape#504

Participants: kick pending contacts

Fixes urbit/landscape#269

Profile: fix stale headers

Fixes urbit/landscape#419

StatusBar: fix dismiss

Fixes urbit/landscape#476

VirtualScroller: correct lazy loading with small chats

Fixes urbit/landscape#523

Comments: validate on submit only

Fixes urbit/landscape#530

### CODE REVIEW

**Comment by matildepark** [comment]
Regarding 456 — how does this behave if you’re scrolled up and disconnect?

— 
~haddef-sigwen
https://urbit.org

**Comment by liam-fitzgerald** [comment]
you lose the scroll pos, sadly. We can fix this when connection resuming lands in `@urbit/http-api`

**Comment by matildepark** [comment]
I think that's actually worse UX than our "temporarily, silently dropping a message" — it means people with multiple tabs open or the like won't be able to read backlog like, at all. I'd punt the commit out and reapproach after http-api.

**Comment by liam-fitzgerald** [comment]
commit dropped

**Review by matildepark — APPROVED** [review]
Rest of these read sanely.

**Pull request merged**
