### PR TITLE
GraphContent: rendering fixes 

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
- Preserve newlines
- Fix lineheight
- Disable nested blockquotes
- Disable inline html

### CODE REVIEW

**Comment by matildepark** [comment]
Mind making links inline instead of inline blocks?

**Comment by matildepark** [comment]
For future reference, can you start committing lockfiles when you change dependencies? It wreaks a little bit of havoc otherwise.

**Comment by matildepark** [comment]
The line-height was better at 20px I think, now the chat interface doesn't line up.

**Comment by liam-fitzgerald** [comment]
Messages with newlines look a little squashed to me with the old line-height

**Comment by matildepark** [comment]
> Messages with newlines look a little squashed to me with the old line-height

Behold my neurosis! This before/after with the timestamp off with the line-height! @urcades 

Screen Shot 2021-05-10 at 12 02 20 AM

**Review by matildepark — APPROVED** [review]

**Pull request merged**
