### PR TITLE
Refactor /gen and /ted in %base; improve +help

### PR DESCRIPTION
**Pull request by sigilante**
Pursuant to discussion in #7004.

- `/gen` has been refactored into more consistent categories.
- `%story` has been moved to [its own repo](https://github.com/urbit/story).
- `/ted` is planned to be similarly refactored.

### CODE REVIEW

**Comment by sigilante** [comment]
- `/ted` has been refactored to parallel `/gen` conventions.

**Comment by sigilante** [comment]
`+help` now searches `/ted` as well as `/gen`; to wit,

```
> +help %code
+code     ::  Login code for web UI
-code     ::  Login code for web UI
```

We also support agent-directed generator notation:

```
> +helper %spider
:spider|kill        ::  Kill a thread
:spider|poke        ::  Poke a thread
:spider|start       ::  Start a thread
:spider|stop        ::  Stop a thread
+spider/tree        ::  List running threads
```

Now I need it to search for a buried one, and to handle paths.  E.g.,

```
> +help %cp
|cp     ::  Copy a file in Clay

> +help /hood/cp
|cp    ::  Copy a file in Clay
```

**Comment by sigilante** [comment]
```
> +help /hood/gall
|gall/rein/hoon     ::  Adjust the state of agents on a desk.
|gall/sear/hoon     ::  Clear ship from pending queues
|gall/start/hoon    ::  Drum: boot unstarted app
|gall/verb/hoon     ::  Helm: Adjust Gall verbosity
|gall/sift/hoon     ::  Helm: Set Gall Verbosity by Agent
|gall/doff/hoon     ::  Kill old-style subscription.
|gall/goad/hoon     ::  Kiln: force Gall to rebuild agents
|gall/nuke/hoon     :: wipe agent state & subscriptions after confirmation

> +help /test
-test/hoon          <undocumented>

> +help %test
-test/hoon          <undocumented>
```

Looks like I'm missing passing in the file contents now.

**Comment by sigilante** [comment]
```
> +help %code
+code     ::  Login code for web UI
|code     ::  Helm: query or reset login code for web
-code     ::  Login code for web UI

> +help %cp
|cp       ::  Kiln: copy file in clay
|clay/cp            ::  Kiln: copy file in clay

> +help /clay/cp

> +help /hood/clay/cp
|clay/cp            ::  Kiln: copy file in clay

> +help %test
-test     ::  Run tests at paths.

> +help %toot
%toot not found

> +help %hood
|ames/close-flows   ::  Deletes all stale ames flows from failed (re) subscriptions
|commit   ::  Kiln: Commit from mount
* * *
|suspend            ::  Suspend the agents on a desk
|unmount            ::  Kiln: Remove unix mount
```

**Comment by sigilante** [comment]
Oh, remaining desideratum:  parse thread syntax like `-azimuth/load` in Dojo.

**Comment by sigilante** [comment]
OK, got thread parsing with optional `/` supported now:

```hoon
> -azimuth/load
ship: loading azimuth snapshot (137.928 points)
ship: processing azimuth snapshot (137.928 points)

> -azimuth-load
ship: loading azimuth snapshot (137.928 points)
ship: processing azimuth snapshot (137.928 points)

> -base!azimuth/load
ship: loading azimuth snapshot (137.928 points)
ship: processing azimuth snapshot (137.928 points)

> -base!azimuth-load
ship: loading azimuth snapshot (137.928 points)
ship: processing azimuth snapshot (137.928 points)
```

**Comment by sigilante** [comment]
This is ready for review.

**Comment by sigilante** [comment]
This will require some modest changes to documentation since a few things are moved.  Important things are duplicated.

**Review by tinnus-napbus — DISMISSED** [review]
LGTM

**Review by jalehman — APPROVED** [review]

**Comment by sigilante** [comment]
@tamlut-modnys can you queue this for docs as well?  Just need to move some things around, nothing has been added or removed.

`+help` is substantially more useful now.

**Pull request merged**
