### PR TITLE
interface: use production build of react

### PR DESCRIPTION
**Pull request by matildepark**
We were shipping development builds of React in production. Now we're not. Affects Chat, Publish, Soto. (Should be pulled into Contacts and Links branches.)

- Also adds parity for rollup's 'named exports' so that indigo-react can be used seamlessly in future builds of all applications without running into build errors.

Apparently the performance increase can be 3-5x, but I don't really know how to measure that with much accuracy. From just using the "Performance" tab in Chrome, basic actions in a 6s window went from 981ms of scripting to 103ms. We'll see how it actually feels to use.

### CODE REVIEW

**Comment by matildepark** [comment]
I agree, although ... I'm unsure how to perform a partial rollup query and then throw the remainder of the work to another task. What do you suggest? My initial thought is to restructure the gulp pipe work into a common function that each variant calls...

**Comment by jtobin** [comment]
> I'm unsure how to perform a partial rollup query and then throw the remainder of the work to another task.

I went over this tonight and cleaned things up a bit using ⚡️ *functional programming* :zap:.  WIll put finishing touches on it tomorrow and push it out.

**Comment by jtobin** [comment]
> WIll put finishing touches on it tomorrow and push it out.

Please hold, with a bit more work I can solve this together with the long-standing #1664 and #1710..

**Comment by litpub** [comment]
There's an issue related to this @jtobin @matildepark which is that `sucrase` has a production config that is not enabled. See: https://github.com/alangpierce/sucrase/pull/270

On HEAD of os1-rc this results in:

1. ~12kb delta on the chat app
2. Not including the personal filepaths of developers in the production build (if you go look at the production builds you'll see personal filepaths baked in - https://raw.githubusercontent.com/urbit/urbit/b6120ac9fc640c43e9dae8a9ec95fc923cb4f692/pkg/arvo/app/chat/js/index.js ctrl+f for `matilde` here). Basically, the `createElement` in React is designed to accept a `__source` prop for local debugging.

This can be solved by doing 

``` 
gulp.task('jsx-transform', function(cb) {
  return gulp.src('src/**/*.js')
    .pipe(sucrase({
      transforms: ['jsx'],
      production: true
    }))
    .pipe(gulp.dest('dist'));
});
```

But it should be sensitive to only the production build, though. I suspect the use of `         rollupReplace({'process.env.NODE_ENV': JSON.stringify('production')}),` in this PR could be pulled out and made more generally available for reference by other tasks so prod builds always use NODE_ENV = production across any task?

**Comment by matildepark** [comment]
@litpub I believe @jtobin was about to wrap a functional-oriented rewrite of the gulp scripts in the near-term that may address this ...

**Comment by jtobin** [comment]
On Tue, Feb 18, 2020 at 08:14:05PM -0800, matildepark wrote:
> @litpub I believe @jtobin was about to wrap a functional-oriented
> rewrite of the gulp scripts in the near-term that may address this ...

Yeah, this (+ some associated stuff) has been mostly done and sitting
for awhile now.  Will try to wrap it up this week.

**Comment by loganallenc** [comment]
This is a small and pleasant quality of life improvement that decreases the size of our minified JS files. I think this should be merged today, as it has no dependencies on any other work.

**Comment by matildepark** [comment]
Since @jtobin is out and refactoring his Landscape build process I approve of this merged for the time being. It's definitely a performance improvement.

**Comment by ixv** [comment]
Seems fine, conflicts need to be fixed though.

**Comment by matildepark** [comment]
Are one of you able to resolve them, test the build and merge it if all’s well? @loganallenc @ixv They seem straightforward, just a bit occupied atm

—
~haddef-sigwen
https://urbit.org

**Comment by loganallenc** [comment]
fixed

**Comment by loganallenc** [comment]
@ixv ready

**Pull request merged**
