### PR TITLE
vere: fix terminal deadlock conditions

### PR DESCRIPTION
**Pull request by joemfb**
This PR fixes two deadlock scenarios having to do with the terminal: pathological `tcsettr()` retry loops, and thread contention over logging to the terminal. These should further ameliorate #1981 (but I can't be sure they'll completely resolve it).

### CODE REVIEW

**Comment by sibwyl-batrep** [comment]
Hope this helps

**Comment by galenwp** [comment]
I started seeing daily `tcsetattr` crashes again yesterday. Should I try using this?

**Comment by joemfb** [comment]
Yes, please. Here are the binaries for the latest vere hotfix release candidate (including these changes):

- [linux](https://bootstrap.urbit.org/d057208a84a4ec77a5858568f402cd40d716767e-linux64.tgz)
- [macos](https://bootstrap.urbit.org/d057208a84a4ec77a5858568f402cd40d716767e-darwin.tgz)

**Comment by Fang-** [comment]
@joemfb ftr, tried running with that binary, and got into a frozen state (#1981) again shortly after.

**Comment by Fang-** [comment]
@joemfb happened again, got some stack traces out using gbd as requested. (Indeed, lldb refused to attach.) Hope this gives you something to work with!

<details><summary>stack traces</summary>

```
## urbit

Thread 5 (LWP 13340):
#0  0x0000000000758b46 in __syscall ()
#1  0x000000000075aa68 in __timedwait_cp ()
#2  0x0000000000000000 in ?? ()

Thread 4 (LWP 13339):
#0  0x0000000000758b46 in __syscall ()
#1  0x000000000075aa68 in __timedwait_cp ()
#2  0x0000000000000000 in ?? ()

Thread 3 (LWP 13338):
#0  0x0000000000758b46 in __syscall ()
#1  0x000000000075aa68 in __timedwait_cp ()
#2  0x0000000000000000 in ?? ()

Thread 2 (LWP 13337):
#0  0x0000000000758b46 in __syscall ()
#1  0x000000000075aa68 in __timedwait_cp ()
#2  0x0000000000000000 in ?? ()

Thread 1 (LWP 13323):
#0  0x0000000000748b1e in syscall ()
#1  0x000000000000002b in ?? ()
#2  0x00007ffe00000030 in ?? ()
#3  0x00007ffecbb46d10 in ?? ()
#4  0x00007ffecbb46cd0 in ?? ()
#5  0x0000001f00000000 in ?? ()
#6  0x0000000000000006 in ?? ()
#7  0x00007ffecbb46df0 in ?? ()
#8  0x0000000000000400 in ?? ()
#9  0x000000000000f655 in ?? ()
#10 0x00000000000000d0 in ?? ()
#11 0x00007ffecbb46d40 in ?? ()
#12 0x0000000000525665 in uv__epoll_wait (epfd=6, events=0x7ffecbb46df0, nevents=1024, timeout=63061) at src/unix/linux-syscalls.c:321
#13 0x00000000005224a2 in uv__io_poll (loop=0xc26da0 <default_loop_struct>, timeout=63061) at src/unix/linux-core.c:271
#14 0x000000000050f130 in uv_run (loop=0xc26da0 <default_loop_struct>, mode=UV_RUN_DEFAULT) at src/unix/core.c:354
#15 0x0000000000455e57 in u3_daemon_commence () at vere/daemon.c:955
#16 0x0000000000402024 in main (argc=<optimized out>, argv=<optimized out>) at daemon/main.c:764


## urbit-worker

Thread 1 (process 13330):
#0  0x0000000000749829 in syscall ()
#1  0x0000000001845460 in ?? ()
#2  0x0000000000000030 in ?? ()
#3  0x00007fff0a6925c0 in ?? ()
#4  0x00007fff0a692580 in ?? ()
#5  0x0000001f00000000 in ?? ()
#6  0x0000000000000008 in ?? ()
#7  0x00007fff0a6926a0 in ?? ()
#8  0x0000000000000400 in ?? ()
#9  0x00000000ffffffff in ?? ()
#10 0x000000000006d0b0 in ?? ()
#11 0x000000000424c0ba in ?? ()
#12 0x000000000052678d in uv__epoll_wait (epfd=8, events=0x7fff0a6926a0, nevents=1024, timeout=-1) at src/unix/linux-syscalls.c:321
#13 0x00000000005235ca in uv__io_poll (loop=0xbf5440 <default_loop_struct>, timeout=-1) at src/unix/linux-core.c:271
#14 0x0000000000510258 in uv_run (loop=0xbf5440 <default_loop_struct>, mode=UV_RUN_DEFAULT) at src/unix/core.c:354
#15 0x0000000000401d55 in main (argc=<optimized out>, argv=<optimized out>) at worker/main.c:1098
```

</details>

**Comment by Fang-** [comment]
@joemfb built the next-vere locally with debug symbols, looks like this gets us some more information. Here's traces from this morning, will check for differences the next couple times this happens again:

<details><summary>stack traces</summary>

```
## urbit

Thread 5 (Thread 0x7efc4fbbf700 (LWP 6752)):
#0  0x00007f0b52baa592 in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /nix/store/mrfcv8ipiksfdrx3xq7dvcrzgg2jdfsw-glibc-2.27/lib/libpthread.so.0
#1  0x00000000004a99d9 in uv_cond_wait (cond=cond@entry=0x8871e0 <cond>,
    mutex=mutex@entry=0x8871a0 <mutex>) at src/unix/thread.c:443
#2  0x000000000049bbc8 in worker (arg=arg@entry=0x0) at src/threadpool.c:75
#3  0x00000000004a9517 in uv__thread_start (arg=<optimized out>) at src/unix/thread.c:52
#4  0x00007f0b52ba45a7 in start_thread ()
   from /nix/store/mrfcv8ipiksfdrx3xq7dvcrzgg2jdfsw-glibc-2.27/lib/libpthread.so.0
#5  0x00007f0b52eae22f in clone ()
   from /nix/store/mrfcv8ipiksfdrx3xq7dvcrzgg2jdfsw-glibc-2.27/lib/libc.so.6

Thread 4 (Thread 0x7efc503c0700 (LWP 6751)):
#0  0x00007f0b52baa592 in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /nix/store/mrfcv8ipiksfdrx3xq7dvcrzgg2jdfsw-glibc-2.27/lib/libpthread.so.0
#1  0x00000000004a99d9 in uv_cond_wait (cond=cond@entry=0x8871e0 <cond>,
    mutex=mutex@entry=0x8871a0 <mutex>) at src/unix/thread.c:443
#2  0x000000000049bbc8 in worker (arg=arg@entry=0x0) at src/threadpool.c:75
#3  0x00000000004a9517 in uv__thread_start (arg=<optimized out>) at src/unix/thread.c:52
#4  0x00007f0b52ba45a7 in start_thread ()
   from /nix/store/mrfcv8ipiksfdrx3xq7dvcrzgg2jdfsw-glibc-2.27/lib/libpthread.so.0
#5  0x00007f0b52eae22f in clone ()
   from /nix/store/mrfcv8ipiksfdrx3xq7dvcrzgg2jdfsw-glibc-2.27/lib/libc.so.6

Thread 3 (Thread 0x7efc50bc1700 (LWP 6750)):
#0  0x00007f0b52baa592 in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /nix/store/mrfcv8ipiksfdrx3xq7dvcrzgg2jdfsw-glibc-2.27/lib/libpthread.so.0
#1  0x00000000004a99d9 in uv_cond_wait (cond=cond@entry=0x8871e0 <cond>,
    mutex=mutex@entry=0x8871a0 <mutex>) at src/unix/thread.c:443
#2  0x000000000049bbc8 in worker (arg=arg@entry=0x0) at src/threadpool.c:75
#3  0x00000000004a9517 in uv__thread_start (arg=<optimized out>) at src/unix/thread.c:52
#4  0x00007f0b52ba45a7 in start_thread ()
   from /nix/store/mrfcv8ipiksfdrx3xq7dvcrzgg2jdfsw-glibc-2.27/lib/libpthread.so.0
#5  0x00007f0b52eae22f in clone ()
   from /nix/store/mrfcv8ipiksfdrx3xq7dvcrzgg2jdfsw-glibc-2.27/lib/libc.so.6

Thread 2 (Thread 0x7efc513c2700 (LWP 6749)):
#0  0x00007f0b52baa592 in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /nix/store/mrfcv8ipiksfdrx3xq7dvcrzgg2jdfsw-glibc-2.27/lib/libpthread.so.0
#1  0x00000000004a99d9 in uv_cond_wait (cond=cond@entry=0x8871e0 <cond>,
    mutex=mutex@entry=0x8871a0 <mutex>) at src/unix/thread.c:443
#2  0x000000000049bbc8 in worker (arg=arg@entry=0x0) at src/threadpool.c:75
#3  0x00000000004a9517 in uv__thread_start (arg=<optimized out>) at src/unix/thread.c:52
#4  0x00007f0b52ba45a7 in start_thread ()
   from /nix/store/mrfcv8ipiksfdrx3xq7dvcrzgg2jdfsw-glibc-2.27/lib/libpthread.so.0
#5  0x00007f0b52eae22f in clone ()
   from /nix/store/mrfcv8ipiksfdrx3xq7dvcrzgg2jdfsw-glibc-2.27/lib/libc.so.6

Thread 1 (Thread 0x7f0b546217c0 (LWP 6736)):
#0  0x00007f0b52ea9229 in syscall ()
   from /nix/store/mrfcv8ipiksfdrx3xq7dvcrzgg2jdfsw-glibc-2.27/lib/libc.so.6
#1  0x00000000004adf4a in uv__epoll_wait (epfd=<optimized out>,
    events=events@entry=0x7ffecfdee160, nevents=nevents@entry=1024,
    timeout=timeout@entry=65512) at src/unix/linux-syscalls.c:321
#2  0x00000000004ac571 in uv__io_poll (loop=loop@entry=0x887240 <default_loop_struct>,
    timeout=65512) at src/unix/linux-core.c:271
#3  0x000000000049e898 in uv_run (loop=0x887240 <default_loop_struct>,
    mode=mode@entry=UV_RUN_DEFAULT) at src/unix/core.c:354
#4  0x000000000044a084 in u3_daemon_commence () at vere/daemon.c:955
#5  0x0000000000453f62 in main (argc=<optimized out>, argv=<optimized out>)
    at daemon/main.c:764

## urbit-worker

Thread 1 (Thread 0x7fc32aebc7c0 (LWP 6742)):
#0  0x00007fc329744229 in syscall ()
   from /nix/store/mrfcv8ipiksfdrx3xq7dvcrzgg2jdfsw-glibc-2.27/lib/libc.so.6
#1  0x00000000004ae17a in uv__epoll_wait (epfd=<optimized out>,
    events=events@entry=0x7fff96e1db20, nevents=nevents@entry=1024,
    timeout=timeout@entry=-1) at src/unix/linux-syscalls.c:321
#2  0x00000000004ac7a1 in uv__io_poll (loop=loop@entry=0x8557a0 <default_loop_struct>,
    timeout=-1) at src/unix/linux-core.c:271
#3  0x000000000049eac8 in uv_run (loop=loop@entry=0x8557a0 <default_loop_struct>,
    mode=mode@entry=UV_RUN_DEFAULT) at src/unix/core.c:354
#4  0x0000000000454cdd in main (argc=<optimized out>, argv=<optimized out>)
    at worker/main.c:1095
```
</details>

**Pull request merged**
