### PR TITLE
jets: disable equivalence test ice toggle (#5580)

### PR DESCRIPTION
**Pull request by mrdomino**

### CODE REVIEW

**Comment by joemfb** [comment]
The design here (longstanding, I believe) is to allow for outer-level equivalence testing, while still jetting internal recursion or reentrant calls. That obviously doesn't play well with bails, and may require separately virtualizing the nock and jet invocations to be generally useful. Simply disabling this approach to recursion may be too costly ...

/cc @frodwith

**Comment by mrdomino** [comment]
This is a natural use case for something like go’s `defer`. Alas, I don't know of a way to model that easily in C…

**Comment by mrdomino** [comment]
So the practical issue here is that `sosi` (the schnorr signature jet) bails if you call it with wrong-sized arguments, as does the hoon. So equivalence testing for it gets disabled right after the first unit test for bounds checking within it.

If possible, it'd be nice to push this change with the next release (since we don't seem to be doing any equivalence testing aside from the schnorr jets, which don't recurse), and then ship an actual fix later.

**Review by joemfb — COMMENTED** [review]
This change is not practical, as it will redo the equivalence testing for every iteration of a jetted recursive gate. So this equivalence testing regime is not suitable for long-running, livenet usage.

It was my mistake to suggest it as a strategy for #5510. Please back out the testing change from that PR, we can discuss further testing there. This PR is a WONTMERGE.

**Pull request closed without merging**
