### PR TITLE
Align test output display.

### PR DESCRIPTION
**Pull request by sigilante**
Add some spaces so that testing output looks like

```
FAILED  /lib/lm/test-zeros
expected: 0x20000000200000000
actual:   0x20000000100000000
```

instead of the current misaligned

```
FAILED  /lib/lm/test-zeros
expected: 0x20000000200000000
actual: 0x20000000100000000
```

### CODE REVIEW

**Comment by sigilante** [comment]
OK, this was forked from the jetting tutorial branch and that's been reverted here to `urbit:master` standard.

**Review by tacryt-socryp — APPROVED** [review]

**Comment by sigilante** [comment]
Argh, missed a spot.  I don't have time this afternoon to fix but I'll take a look tomorrow.

**Comment by joemfb** [comment]
The commits can also just be squashed on merge.

**Comment by philipcmonk** [comment]
Commits squashed and merged out-of-band

**Pull request closed without merging**
