### PR TITLE
Message type support in Chat

### PR DESCRIPTION
**Pull request by Fang-**
This PR aims to bring Chat's message rendering and sending ability up to par with :talk.

image

- Support rendering `%lin` messages for both `pat` values
- Support rendering `%url` messages
- Make `%url` images clickable (to view in new window)
- Support sending `%lin` "@" messages, URLs, as their appropriate message types
- Turn select Urbit app URLs into "arvo://" URLs prior to sending rather than on-render *
- Style input field depending on detected message type

\* `purl:eyre` doesn't support non-HTTP protocols. @eglaysher new eyre didn't add a type for parsed URLs that has more than just a `?` for the protocol, right? Should `purl:eyre` be updated to support this? Or should hall define its own parsed-URL type?

`/pkg/interface` has no readme, so I followed the one from [the old repo](/urbit/interface). It generates new dist files in `/pkg/arvo/app/chat`. The files that were already there were minimized, but the files that are being 

Remaining work:
- [x] Support rendering `%exp`, `%ire`, `%app`, `%fat`
- [x] Support all message types in the sidebar also
- [x] Correct `arvo://` paths again
- [x] Update dist files in `/pkg/arvo/app/chat`
- [x] Support sending (& more flexible rendering of) `%exp`

### CODE REVIEW

**Comment by matildepark** [comment]
That truncated minified thing you mention might be a bug I introduced into the gulpfile by accident. I can investigate a little later.

**Comment by matildepark** [comment]
Oh nevermind. Looks like the minified process is done with `gulp bundle-prod`.

**Comment by Fang-** [comment]
Alright, it now renders `%exp` and`%app` messages.

image

image

**Comment by Fang-** [comment]
Oh, and there's also very extensive support for attachments now I guess. tldr: inline pastebin and niceties for writing long-form content. (^:

ragedev

Sidebar isn't playing nice with these new message types just yet. That's the extent of my remaining work here, I think.

**Comment by Fang-** [comment]
I want to do better support for `%exp`. Commits soon!

**Comment by Fang-** [comment]
image

**Comment by Fang-** [comment]
@g-a-v-i-n tagged you for PR. If you want to see these things in action, feel free to drop by my desk. (:

**Comment by Fang-** [comment]
Sweet! Should be good to merge now. Next OTA can't come soon enough. (:

**Comment by philipcmonk** [comment]
Am waiting for #1436 status checks to finish and I'm going to merge that, so please don't merge this until then!

**Comment by Fang-** [comment]
@philipcmonk I wouldn't dare merge this myself regardless of other pending PRs! All of this seems pretty fragile/fiddly rn, I'll keep my hands away from master unless explicitly directed.

**Pull request merged**
