### PR TITLE
u3: off-loom global deduplication

### PR DESCRIPTION
**Pull request by joemfb**
The PR adds off-loom global state unification and memory compaction. It works via a hash-consing allocator, backed by malloc. We reallocate and deduplicate the entire persistent state, wipe the loom, and then re-reallocate on the loom.

The new allocator is in a new `ur` module, and has no dependencies on `u3`. It should be an entirely separate library, but is included in the `u3` build for shot-term expedience. As an experiment -- since it's conceptually separate from u3 -- this module is written in a conventional style. (It's an experiment, because it remains to be seen if the cost of context-switching overrides the conventional clarity.) This is effectively a first, rough draft, and all APIs and implementation details are subject to change.

This PR is a basic, minimum viable integration of this new tooling, availably exclusively as an emergency recovery tool in the `urbit-worker` binary:

```
./urbit-worker uniq path/to/pier
```

Reconciling this tooling with the existence of the loom defragmenter (ie, the new `|pack` added in #) and the old `|pack` (ie, current `-n` and `-r` partial replay arguments) remains a top priority. The exact shape of that integration is yet to be determined; the next steps will be to implement jam and cue (universal noun de/serialization) on top of this noun representation.

But even in this minimal state, this tool allows us fully utilize the loom up to its 2GB limit, by maximizing structural sharing and limiting fragmentation. Since it runs off-loom, it can handle arbitrary amounts of data -- up to the limits of the underlying machine.

Relevant history: #1984, #2957, #3099

Obsoletes: #3182

Ameliorates #3190, #3179, #3117, #3116, #3051, #2903, #2896, #2677, #2456, #2283, #2108, #1767, #1629, and likely others. (Full fixes will require further integration, and, in some cases, improvements to related functionality.)

Many thanks to @frodwith, who designed the hash-consing allocator, and guided me in its implementation.

### CODE REVIEW

**Comment by galenwp** [comment]
king

**Comment by joemfb** [comment]
To anyone looking to run this before it's released, the latest static binaries from this branch are here:

- [linux](https://bootstrap.urbit.org/993f4b83f4df7a65f76ce03df93871fbf59f659c-linux64.tgz)
- [macos](https://bootstrap.urbit.org/993f4b83f4df7a65f76ce03df93871fbf59f659c-darwin.tgz)

Just download one of those, unpack the tarball (`tar -xzvf 993f4b83f4df7a65f76ce03df93871fbf59f659c-linux64.tgz`), and run `./993f4b83f4df7a65f76ce03df93871fbf59f659c-linux64/urbit-worker uniq path/to/your/pier`.

**Comment by philipcmonk** [comment]
Read this in some detail, and it looks great!  Agree with @Fang- that a couple comments on the data structures could be useful; for me it all clicked into place when I understood the relation between `_cu_loom` and `_ur_root_t`.

**Comment by joemfb** [comment]
My apologies for the delay -- I'm afraid I let the scope of this effort expand significantly. This PR now includes:

- an off-loom, hash-consing noun representation and allocator
- routines to (destructively) move permanent state off the loom and back
- off-loom jam and cue implementations
- backed by off-loom bitstream read/write modules
- and several hashtables
- use of the above for taking/loading portable snapshots
- additional implementations of jam/cue, with various permutations of loom usage
- use of the same on both sides of the ipc pipe, and in the (c) king's persistence layer
- a new +cue jet
- tests and benchmarks for (portions of) the above

As a result of these features, we can fully utilize the loom up to its 2GB limit (by completely deduplicating the persistent state),
and take/load portable snapshots of a size up to (and, in fact, well beyond) the limitations of the loom.

Additionally, the new jam and cue implementations generally exceed the performance of the old by a factor of 2-10x, depending on a variety of details. In the most extreme cases (a full, highly deduplicated, loom), portable snapshot performance exceeds the old implementation by many hundreds of times (due to guaranteed, preemptive unification, as opposed to exponential re-comparison of duplicate, equal subtrees in the worst case).

Incredibly unscientific results follow:

The (incredibly basic) jam/cue microbenchmarks (`make bench`) simply jam or cue a representative %ames effect (in an ipc message wrapper) with different implementations, 20K times in a loop, timing with `gettimeofday()`. Representative output from a run on my machine (2017 macbook pro):

```
jam microbenchmark:
  jam og: 48 ms
  jam xeno: 27 ms
  jam cons: 24 ms
  jam cons unsafe: 11 ms

cue microbenchmark:
  cue og: 270 ms
  cue atom: 63 ms
  cue xeno: 32 ms
  cue xeno unsafe: 26 ms
  cue test: 21 ms
  cue test unsafe: 15 ms
  cue cons: 59 ms
  cue re-cons: 90 ms

cue virtual microbenchmark:
  cue virtual og: 280 ms
  cue virtual atom: 38 ms
```

Here's the result of some simple trace profiling of the changes to the ipc layer. These numbers are taken from local usage of a fake ship,
wherein I mashed on the keyboard in dojo, sent myself a few small messages in webchat dm, and refreshed the page a few times. The jam/cue timing was logged in the `chrome://tracing` format, and averaged in the ui. Note, again, that personal results may vary -- past performance is no indicator of future success:

- serf jam (effects and logging output) improved 15-22x
- serf cue (input events) improved ~3.5x
- king jam (input events) improved ~1.5x
- king jam (input events, persistence) improved ~1.5x
- king cue (input events, replay) improved ~1.8x
- king cue (effects and logging output) improved ~12x
- king process startup (ivory pill cue) improved ~4x.

----------------------------

The new portable snapshots have been wired into the -n/-r replay arguments (and `urbit-worker` commands: `cram` and `queu`). Global deduplication with jamming a portable snapshot is now available via `urbit-worker meld` (since `uniq` is not a verb), and will be available via `|meld` -- the arvo-side implementation will be in a separate PR. (The relevant changes -- fairly small -- will also need to be ported to king-haskell.)

There are two more pieces of integration that should be done.

The new %ames stateless-forwarding implementation in vere should make special use of the new jam/cue implementations (most notably the non-allocating `ur_cue_test()` for packet validation) -- that's simple, and can be PR'd after these changes are merged.

The global deduplicator (meld) should be automatically deployed via memory pressure heuristics. At the same time, various currently-fatal error conditions (`bail:meme`) should become non-fatal. This will require memory pressure notifications to flow back from the serf to the king, and the i/o driver event error-handlers to be integrated with overall memory-pressure tracking and mediation.

As this is a large PR, I've requested multiple reviewers, with the following breakdown in mind:

- @Fang-: changes to the c king (predominantly in `vere/`)
- @philipcmonk: changes to the u3 library (`noun/`) and serf implementation (`worker/`)
- @brendanhay: new off-loom modules (`include/ur`, `ur/`, `tests/ur_tests.c`)

@brendanhay, note that the new modules in the `ur_` namespace are effectively a separate library, with no dependencies except murmur3. I bundled them in `pkg/urbit` for development convenience, but I'd be happy to split them into a separate library now if you have any strong opinions about how that should be built. I expect them to eventually become a separate library in any case.

**Review by Fang- — COMMENTED** [review]
> I let the scope of this effort expand significantly.

Nobody is surprised. (; Amazing work, regardless!

> routines to (destructively) move permanent state off the loom and back

To be clear, "destructively" here just means temporarily wiping the loom, right? It's not like you're losing any data.

I gave the king-related code a look. The changes mostly make sense to me. The only issue I found is in a printf. I could complain about alignment inconsistencies in variable declaration, but it's really not that bad.

There's a couple new `XX`s that you added. I'm assuming we're fine punting on all of those. You could consider writing some of them up as contributor-friendly issues, maybe someone will pick them up. (Thinking specifically of the "check if dictionary can be shrunk" ones, which seem fairly self-contained. Perhaps there's others.)

**Comment by galenwp** [comment]
Exciting

**Comment by brendanhay** [comment]
I'd leave `ur` as-is for now ( - will `urcrypt` subsume a direct `murmur3` dependency at all? Either way we can look at how to build/split `ur` proper separately from this PR.

**Comment by frodwith** [comment]
I wasn't planning on including murmur in urcrypt, as it's not a
cryptographic hash, but I could be convinced otherwise.

**Comment by Fang-** [comment]
For the record, just rescued ~palfun-foslup from `bail: meme` using this! Good stuff.

 `urbit-worked meld` wasn't blazing-fast by any means, still took 10-15 minutes, but it got the job done. If those are anomalous numbers (for a standard-ish DO droplet), let me know. I have a backup of the pre-meld `chk` files in case they're interesting.

**Review by brendanhay — APPROVED** [review]
I've looked through the off-loom modules - other than the shock of being confronted with 'normal' C code in the urbit repository, it looks good to me.

**Comment by joemfb** [comment]
For anyone needing to run this, the latest static binaries from this branch are now:

- [linux](https://bootstrap.urbit.org/a6a7b557a95cd246430ce68809d8188d40ae28f4-linux64.tgz)
- [macos](https://bootstrap.urbit.org/a6a7b557a95cd246430ce68809d8188d40ae28f4-darwin.tgz)

Just download one of those, unpack the tarball (`tar -xzvf a6a7b557a95cd246430ce68809d8188d40ae28f4-linux64.tgz`), and run `./a6a7b557a95cd246430ce68809d8188d40ae28f4-linux64/urbit-worker meld path/to/your/pier`.

**Review by philipcmonk — APPROVED** [review]
There's a lot here, but I think it all makes sense.  With occasional `|meld` (which will be automatic in trim eventually), this essentially gets us to the point where all memory leaks are "true" leaks in the kernel/app code (or a few hashtables), which is a great milestone.  I remember when we finally got to zero C memory leaks on the loom (around when we wrote `|mass`), and that made a huge difference.  This is the next level!

I reviewed noun/ and worker/ and they look good to me.

**Pull request merged**
