### PR TITLE
fix ++lore and ++role

### LINKED ISSUE #241: fix ++lore/++role
`++lore` is meant to convert a cord into a list of cords, broken on line break.  Thus, `(lore 'hi\0ahey')` should give `~['hi' 'hey']` and `(lore ~['hi\0ahey\0a'])` should give `~['hi' 'hey' '']` and `(lore 'hi\0ahey\0a\0a')` should give `~['hi' 'hey' '' '']`.  `++role` should invert this.  This isn't quite the case at the moment, which is the source of a small variety of bugs.

These are both defined in hoon.hoon, which means to test you need to run :reset.  Additionally, `++lore` at least is jetted, so it'd also be good to fix the c jet (j/5/lore.c), if possible (although even just a hoon solution would be welcome).

### PR DESCRIPTION
**Pull request by chc4**
Fixes both the ++lore jet and both arms in hoon.hoon. I'd like someone to verify that I didn't do something terribly wrong with the jet, since it's my first one commited.

(Does this pull request have a pill attached? I solided one and added it to the commit, but it's not showing the github UI...)

Fixes #241

### CODE REVIEW

**Comment by chc4** [comment]
Nevermind, I copied fake_zod/.urb/urbit.pill instead of fake_zod/.urb/put/urbit.pill

**Comment by chc4** [comment]
@philipcmonk brought up that current Markdown files are stored as a list of lines, and pad/trim '\0a' to have it work. This commit probably would have to be breached in (or have a mark adapter written? Is that a thing?) with that fixed as well.

**Comment by philipcmonk** [comment]
Since the padding is both added and removed, I think it shouldn't cause a
problem.  I'm too jetlagged to actually be able to say so authoritatively.

**Comment by juped** [comment]
I don't understand - %txt just uses lore/role.

**Comment by chc4** [comment]
mar/txt.hoon just uses lore/role, but md.hoon and a few others (%hoon, %hood, %markdown, and the hard-coded %hood and %hood diffing in %ford) weld '\0a' and cut during conversions.

**Comment by juped** [comment]
At first glance it looks like that stuff is handling newlines-at-end-of-file. That's the bug you're fixing in the first place, isn't it? In that case, the fixed marks should go in with this, yeah. Philip would be the last word on whether it's breaching, but I don't believe it is, since the right behavior is what's being hacked in on the mark side right now.

**Comment by philipcmonk** [comment]
From inspection, I'm going to say that as long as the new kernel (hoon.hoon and ford), jet, and mark definitions go in at the same time there won't be a problem.  The jet hint should probably be named something slightly different so that we don't ever use a jet with incorrect code.

I haven't inspected the jet code for correctness, though if it works with the given test cases, then it should be fine.

**Comment by cgyarvin** [comment]
Unfortunately, this is a pretty abstract set of criteria, because we really
don't have any way other than a continuity breach of doing all these
updates simultaneously.  It would certainly be nice to have a "pull,
rebuild and rerun" event we could send to unix.

My recommendation would be to use exclusively new names for everything.
It's fine to have duplicate code for the moment.  We separate out the
problem of deleting the old from the problem of adding and using the new.

**Comment by cgyarvin** [comment]
By "everything" I mean not just the hint, but also the arms.

**Comment by philipcmonk** [comment]
It's actually not necessary for the new jet to come in at the same time.  As long as the jet is hinted differently, it's okay to just use the native hoon code here.  The performance difference shouldn't be all that bad.

It may not even be important for the kernel and mark changes to happen at the same time, but it would make me feel better.

**Comment by juped** [comment]
If they don't, we'll have/expect double newlines in Unix, won't we?

**Comment by philipcmonk** [comment]
Since the padding is added in ++txt:grow and removed in ++txt:grab, it shouldn't even be necessary to change the marks at all, though it should obviously be done for cleanliness.  The only issue that I could see coming up would be if a diff depended on he existence of the extra newline, but I doubt that would happen.  Still, it would be worth testing the case where you have some md files, make changes to them (resulting in a diff being stored in memory), then update the kernel+marks, and make some more changes/look at previous versions of the md files.

**Comment by cgyarvin** [comment]
I'm comfortable with however Philip wants to do this, since it seems like
we've thought it through adequately.

**Comment by philipcmonk** [comment]
We should make the ford/mark chages, change the jet hint (i.e. keep both jets in the system), then do the above test.  If all goes well, we push out the kernel and mark changes over clay and the jet over github.

**Comment by juped** [comment]
@chc4 may be on that, but if he's not I will be

**Comment by chc4** [comment]
That seems a bit involved, and I'm not sure I understand the process all that much. I'd be OK with @juped doing it. I can't push changes to ~zod regardless.

**Comment by chc4** [comment]
Hey, just some bumping. What's the plan for this? Just bring it in after the next breach, since we don't have a method of versioning jets and hints? Or are we still going with the duplicating of the arms at first then removing and renaming the old.

**Comment by juped** [comment]
Non-breaching it in as a rehinted jet, I think.

**Comment by philipcmonk** [comment]
que pasó?

**Comment by juped** [comment]
I have no idea.why it's closed. Github did it itself, and I can't reopen it. `chc4/fixlore` is still going in.

**Comment by juped** [comment]
Just busy with other stuff. Haven't forgotten.
Yours,
r

**Pull request closed without merging**
