### PR TITLE
clay: replace ream with nouns and !, zapcom

### PR DESCRIPTION
**Pull request by Fang-**
Motivation for the change is performance improvements on the un-`^~`d uses of
`+ream`. Parsing turns out to be slow, making `+ream` slow in turn. So we construct
the hoon ast manually instead.

`!,` is arguably better style than ream, since it doesn't necessitate a `^~` for static
input, and lets syntax highlighting function properly.

For the investigated case, in `+get-cast`'s +grow flow, improves performance by
over 80%.

### CODE REVIEW

**Comment by ohAitch** [comment]
It's certainly clearer.

If !, is showing up in vanes we should probably add a biblical for ++hoon,
so you can just say !,(tw(i g)) - probably the OTA-able version of this is
to just modify the parser to stag it onto a one-child syntax(and an
optional wide two-child form to cover the one existing use in also clay),
though that's certainly less clean than the way !> / !; work

**Comment by ohAitch** [comment]
Oh actually the ! namespace is much less crowded than I remembered, given
?!(@) ?!(^) etc are pretty nonsensical - let me amend that to propose !~
for a one-arity rune that expands to biblical !,(*hoon a), by analogy to |~
/ $- being gates which are kind of like unevaluated code ;)

Idk enough bible for a four-letter name invoking the concept of risk of
overabstraction by operating on language, something tower of babel themed
perhaps? <s> @philipcmonk help </s>

**Review by belisarius222 — APPROVED** [review]
LGTM

**Review by joemfb — COMMENTED** [review]
It's a small thing, but `[%limb a]` is probably preferable to [%wing ~[a]]` throughout.

**Comment by Fang-** [comment]
Good catch @joemfb, I was matching the `!,`-generated AST a bit too closely.

**Review by philipcmonk — APPROVED** [review]

**Pull request merged**
