### PR TITLE
Make navbar always show, add urbit.org link

### PR DESCRIPTION
**Pull request by galenwp**

### CODE REVIEW

**Comment by juped** [comment]
RIP master

**Comment by galenwp** [comment]
Did I do something wrong here?

**Comment by galenwp** [comment]
(After some discussion, I think I actually get it now)

**Comment by juped** [comment]
Yeah, but it's too late to do anything about it now, it's on master.

**Comment by juped** [comment]
(the initial comment was advice on how to restore a better state, but pr was merged in the middle of typing - it has now been moved to the book)

**Pull request merged**
