### PR TITLE
Add keyword parser to Hoon.

### PR DESCRIPTION
**Pull request by sigilante**
In the original Urbit whitepaper, two versions of Hoon were presented.

This is a modification to `/sys/hoon` which enables keyword Hoon.

Keyword Hoon keywords are prefixed with `#` hax.  The resulting code AST is a regular Hoon AST, and the only modification made to `++tall:vast` is the addition of a new `++keyword` parser after `++expression`.

Not every rune has (or should have) a keyword, but only common constructions.  Regular Hoon runes can be used in a file alongside keyword Hoon.

```hoon
:: Sieve of Eratosthenes in keyword syntax.
:gate  thru/atom
:cast  (list atom)
:var   field/(set atom)  (silt (gulf 2 thru))
:rap   abet:main
:core
++  abet
  (sort (~(tap in field) ~) lth)
::
++  main
  :var   factor/atom  2
  :loop  :like  ..main
  :if    (gth (mul factor factor) thru)
    ..main
  :moar(factor +(factor), ..main (reap factor))
::
++  reap
  :gate  factor/atom
  :var   count/atom  (mul 2 factor)
  :loop  :like  ..reap
  :if    (gth count thru)
    ..reap
  :moar
    count  (add count factor)
    field  (~(del in field) count)
  ==
--
```

```hoon
|=  top/@
^-  (list @)
=+  fed=(silt (gulf 2 top))
=<  abet:main
|%
++  abet  (sort (~(tap in fed)) lth)
++  main
  =+  fac=2
  |-  ^+  ..main
  ?:  (gth (mul fac fac) top)
    ..main
  $(fac +(fac), ..main (reap fac))
::
++  reap
  |=  fac/atom
  =+  cot=(mul 2 fac)
  |-  ^+  ..reap
  ?:  (gth cot top)
    ..reap
  $(cot (add cot fac), fed (~(del in fed) cot))
--
```

Principles:

1. AST compatible with normal Hoon.
2. Not every rune has a keyword.
3. Just a new parser from `cord` → `hoon` (AST).
4. Prefix every keyword with `#` hax.

```hoon
> =hooner -build-file /===/hoon/hoon

> (make:hooner '#if(%.y 2 3)')
[%1 p=2]

> (make:hooner '#gate(a=@ a)')
[%8 p=[%1 p=0] q=[p=[%1 p=[0 6]] q=[%0 p=1]]]

> (ream:hooner '#gate(a=@ a)')
[%brts p=[%bcts p=term=%a q=[%base p=[%atom p=~.]]] q=[%wing p=~[%a]]]
```

---

##  Planned Keywords

- #assert - `?>` `%wtgr expb`
- #bind - `;<` `%mcgl expz`
- #cast - `^-` `%kthp exqc`
- #cell - `:-` `%clhp expb`
- #door - `|_` `%brcb exqr`
- #gate - `|=` `%brts exqc`
- #if - `?:` `%wtcl expc`
- #like - `^+` `%ktls expb`
- #loop - `|-` `%brhp expa`
- #moar - '%=` `%cnts exph`
- #mold - `;;` `%mcmc exqc`
- #pipe - `;~` `%mcsg expi`
- #print - `~&` `%sgpm hinf`
- #scry - `.^` `%dtkt exqn`
- #switch - `?-` `wthp`
- #switch-default - `?+` `%wtls`
- #tuple - `:*` `%cltr`
- #typeof - `!>` `%zpgr`
- #unless - `?.` `%wtdt`
- #var - `=/` `%tsfs`
- #wrap - `=<` `%tsgl`

### CODE REVIEW

**Comment by sigilante** [comment]
As of this commit, we have `#if` and `#gate` working.  The implementation syntax is a bit painful, so we'll wait a bit to implement the rest.

**Comment by ohAitch** [comment]
[last time](https://github.com/urbit/urbit/commit/b0fd655914d3804c05ce7fb862581f5438403128) they were on `:` :P
(and looks like the AST tags had gotten refactored to use words instead of acronyms, though by the time they got [removed again](https://github.com/urbit/urbit/commit/1c561965b2099029f747068c967e5c8b5c37c78a) they were in the modern `%wtcl` form in lieu of anyone having used the keyword syntax)

**Comment by sigilante** [comment]
Not really strong opinion on `#` vs. `:` vs. something else, but I was avoiding collision with the Dojo `#` help syntax.

**Comment by drbeefsupreme** [comment]
FYI I only picked `#` for the dojo help syntax since I was told `#` has been used just to mean "placeholder" in the past.

**Comment by jalehman** [comment]
My two cents as a Clojure guy:

* `moar` -> `recur` because `loop/recur` pairs well
* `unless` -> `if-not` because it pairs with `if` well

**Comment by sigilante** [comment]
was tempted by `#lest`

**Comment by sigilante** [comment]
- `#assert` - `?>` `%wtgr expb`
- `#assert-not` - `?<` `%wtgl expb`
- `#bind` - `;<` `%mcgl expz`
- `#cast` - `^-` `%kthp exqc`
- `#cell` - `:-` `%clhp expb`
- `#define` - `=/` `%tsfs expo`
- `#door` - `|_` `%brcb exqr`
- `#gate` - `|=` `%brts exqc`
- `#if` - `?:` `%wtcl expc`
- `#if-not` - `?.` `%wtdt expc`
- `#like` - `^+` `%ktls expb`
- `#loop` - `|-` `%brhp expa`
- `#mold` - `;;` `%mcmc exqc`
- `#pipe` - `;~` `%mcsg expi`
- `#print` - `~&` `%sgpm hinf`
- `#recur` - '%=` `%cnts exph`
- `#scry` - `.^` `%dtkt exqn`
- `#switch` - `?-` `wthp ;~(pfix hep (toad txhp))`
- `#switch-default` - `?+` `%wtls ;~(pfix lus (toad txls))`
- `#tuple` - `:*` `%cltr exps`
- `#typeof` - `!>` `%zpgr expa`
- `#wrap` - `=<` `%tsgl expb`

**Comment by sigilante** [comment]
```
#aint - ?< %wtgl expb
#assert - ?> %wtgr expb
#bind - ;< %mcgl expz
#cast - ^- %kthp exqc
#cell - :- %clhp expb
#crash - !! %zpzp (cold ~ ;~(plug zap zap))
#default - ?+ %wtls ;~(pfix lus (toad txls))
#define - =/ %tsfs expo
#door - |_ %brcb exqr
#gate - |= %brts exqc
#if - ?: %wtcl expc
#lest - ?. %wtdt expc
#like - ^+ %ktls expb
#loop - |- %brhp expa
#mold - ;; %mcmc exqc
#pipe - ;~ %mcsg expi
#print - ~& %sgpm hinf
#recur - '%= %cnts exph`
#scry - .^ %dtkt exqn
#switch - ?- wthp ;~(pfix hep (toad txhp))
#tuple - :* %cltr exps
#typeof - !> %zpgr expa
#wrap - =< %tsgl expb
```

The parser is slow as molasses on its way to church, so we definitely need a better option there.

The current set of keywords is limited by the fact that I don't have a good parser to optionally continue a match (e.g. from `if` to `if-not`).  We could/should write one but I'm not doing it right now because I want to hiatus this project with a working good-enough solution.

**Comment by sigilante** [comment]
Current status:

- No `#crash` because doesn't parse `%zpzp` now
- No `#default` or `#switch` because the `toad` in the rule fails on `toad` calling it
- Nesting issue of resulting core with `++keyword` parser enabled (due to doccords?)

**Comment by sigilante** [comment]
After consulting with @Fang-, those issues have been resolved.  To simplify the parser reasoning, I adopted a similar form to the removed keyword parser.  This is ready for consideration.

The keywords have been revised slightly:

`%assert-not` → `%wtgl`
`%assert` → `%wtgr`
`%bind` → `%mcgl`
`%cast` → `%kthp`
`%cell` → `%clhp`
`%compose` → `%tsgr`
`%crash` → `%zpzp`
`%default` → `%wtls`
`%door` → `%brcb`
`%function` → `%brts`
`%if` → `%wtcl`
`%let` → `%tsfs`
`%like` → `%ktls`
`%loop` → `%brhp`
`%mold` → `%mcmc`
`%pipe` → `%mcsg`
`%print` → `%sgpm`
`%recur` → `%cnts`
`%scry` → `%dtkt`
`%switch` → `%wthp`
`%tuple` → `%cltr`
`%typeof` → `%zpgr`
`%unless` → `%wtdt`
`%wrap` → `%tsgl`

**Comment by sigilante** [comment]
@belisarius222 @jalehman I guess we're just deep-sixing this one for now, I forgot about it.

**Pull request closed without merging**
