### PR TITLE
link: improve page load performance

### PR DESCRIPTION
**Pull request by Fang-**
By doing more or less the same thing that chat does, where it doesn't load in big backlog on page-load, but instead only does so when you actually go to view the resource.

Also does some smaller refactoring things. Cleans up the pagination logic in link-view a little bit, and refactors "message display" as used for the link fe landing page and "loading" messages into its own component.

### CODE REVIEW

**Comment by vvisigoth** [comment]
king
—
~poldec-tonteg
http://urbit.org

**Comment by Fang-** [comment]
(Numbers observed here differ per the amount of collections you have, but my test case with eight collections went from ~10 seconds to <1 second in `+give-initial-submissions` for the intitial-pageload subscription result.)

**Comment by matildepark** [comment]
This looks good to me but haven't tested yet.

**Comment by ixv** [comment]
When I create a collection and invite invite someone, and accept that invite on the other ship, the collection doesn't then show up in that ships sidebar.

**Comment by matildepark** [comment]
I can reproduce what @ixv is reporting — it's added to `associations`, but not `listening`.

**Comment by Fang-** [comment]
Hmm, get the feeling this might be an unintended side-effect from #2708. We should still auto-opt-in to unmanaged groups I guess? Will take a deeper look and push a fix.

**Comment by Fang-** [comment]
Kinda outside of PR scope, but went and pushed a fix here. Please take a look.

**Comment by matildepark** [comment]
ping @loganallenc

**Pull request merged**
