### PR TITLE
+vats options

### PR DESCRIPTION
**Pull request by hoclun-rigsep**
With a hat tip to #6390, this pr also implements #6297.

Not quite ready to merge; in certain cases I don't understand, the formatting of the resulting tank gets messed up. Also I need to start getting my updates from ~binnec-dozzod-marzod. Will report back asap.

### CODE REVIEW

**Comment by hoclun-rigsep** [comment]
Here is my bug; you see the section of the output for %base is messed up.

```
> +vats, =verb |
%groups
  /sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415]
  app status:       running
  publishing ship:  [~ ~sogryp-dister-dozzod-dozzod]
  pending updates:  ~
::
%base/sys/kelvin:      [%zuse 415]app status:       runningpublishing ship:  ~pending updates:  ~::
%landscape
  /sys/kelvin:      [%zuse 416] [%zuse 415]
  app status:       running
  publishing ship:  [~ ~lander-dister-dozzod-dozzod]
  pending updates:  ~
::
```

**Comment by pkova** [comment]
Looks like the build fail is caused by the type changes from https://github.com/urbit/urbit/pull/6332.

**Comment by belisarius222** [comment]
@elizasviel and @hoclun-rigsep: this architecture is cleaner than the other PR, so both of you, please focus your efforts on this one.  Please also write some docs in the top of the generator to describe how to pass in the arguments.

**Comment by belisarius222** [comment]
You probably need to make some small changes to the Clay types to get it to compile, due to the PR that @pkova mentioned.

**Comment by hoclun-rigsep** [comment]
> You probably need to make some small changes to the Clay types to get it to compile, due to the PR that @pkova mentioned.

I get the compile error before I introduce any of my changes:

1. fakezod with or without developer pill
2. mount %base
3. check out e17cb3e801a7403d67c6e4a926b80733056a8535
4. `rsync -aL arvo/{app,mar,sur,gen,lib,ted}  ../../zod/base/`
5. `|commit %base`
6.  `nest-fail` at /sur/hood/hoon::[76 14].[76 38] 

I assume your CI builds everything before it gets merged, so what is going on here?

**Comment by pkova** [comment]
I fail to reproduce your issue. Here are the exact commands I ran:
```
git fetch --all
git checkout e17cb3e801a7403d67c6e4a926b80733056a8535
urbit -F zod -B bin/solid.pill
|mount %base
rsync -aL pkg/arvo/ zod/base/
|commit %base
```
Note that you need to be on `vere` edge to run this `|commit` since the branch `develop` is now on `[%zuse 414]`. Still, no matter what `vere` version you're on it shouldn't `nest-fail` there unless you're somehow missing this change:

 https://github.com/urbit/urbit/commit/0286ca7b5b648f8a14e4a00b31dd0b34c5e3a752#diff-d2279d1657ac67537f222ce9b819365ba27aca4741becdce9d2f3f38e7f79f8cL76-R76

**Comment by hoclun-rigsep** [comment]
@pkova thanks for checking that out. I am now on bleeding `vere` and included pill and back on track. I would feel better if I knew how I was able to produce the `nest-fail` on a release pier but I can come back to that.

@belisarius222 looking more closely at this file there seems to be a ton of repeated code/unnecessary scries; I've basically refactored it.

**Review by belisarius222 — DISMISSED** [review]

**Comment by belisarius222** [comment]
from the CI:

```
clay: read-at-aeon fail [desk=%base care=%a case=[%da p=~2023.3.23..15.33.40..ef7c] path=/gen/vat/hoon]
-find.report-vat
/gen/vat/hoon::[6 11].[6 21]>
/gen/vat/hoon::[6 10].[6 61]>
/gen/vat/hoon::[6 8].[6 62]>
/gen/vat/hoon::[6 1].[6 63]>
/gen/vat/hoon::[3 1].[6 63]>
/gen/vat/hoon::[2 1].[6 63]>
[%error-building /gen/vat/hoon]
clay: %a build failed [%base 1 /gen/vat/hoon]
```

**Comment by belisarius222** [comment]
`+report-vat` is now inside another core, which the call site in `/gen/vat/hoon` needs to instantiate.  Should be a quick fix.

**Comment by hoclun-rigsep** [comment]
Might be more going on here—the following scry works on a release comet but hangs as if in a loop on a dev ship:

```
.^(cone:clay %cx /=//=/domes) 
:: also hangs:
.^(noun %cx /=//=/domes) 
```

I assume this has to do with the aforementioned #6332 and I am investigating.
I can't explain why my `+report-vats` works despite scrying thus but then breaks when I try to test `+vats-info` in isolation.

**Comment by hoclun-rigsep** [comment]
I think this will pass now but maybe hold off, there's still something wrong with my terse output.

**Comment by belisarius222** [comment]
@hoclun-rigsep I saw you posted a commit after saying to hold off.  Should I still hold off, or is this ready for review?

**Comment by hoclun-rigsep** [comment]
@belisarius222 Hold off please; I might as well get the `=verb |` output right before merge. This is fun

**Comment by hoclun-rigsep** [comment]
This can be reviewed. Issue: if the terminal is wide enough, information about the desk prints out on one line, which is probably not what we want. If someone can explain idiomatic use of the tank/tang system I can conform to it.

**Comment by belisarius222** [comment]
@hoclun-rigsep I just learned from @joemfb that removing the top-level `%rose` and instead have the `$tang` be a list of lines (with each line as a `$tank`) should get it to print the way you want.  Do it in a new PR, though.  I'm merging this, because it's already a lot better than what we have now.

Thank you for your hard work on this, @hoclun-rigsep.

**Comment by jfranklin9000** [comment]
`+vats` doesn't handles the `%kids` presentation well:
```
+vats
<snip>
::
 %kids %kids %cz hash:     0v14.4jub3.fe4i1.5pfa6.do69s.fqkh7.tf6o9.g7b68.pgdeu.jjec8.u8517::
```
```
+vat %kids
%kids %cz hash:     0v14.4jub3.fe4i1.5pfa6.do69s.fqkh7.tf6o9.g7b68.pgdeu.jjec8.u8517
```
Also, I noticed that `%suspended` more corresponds to uninstalled.  I had `%escape` installed and then uninstalled it from the UI and I see it in the `+vats %suspended` output.  I have `%bitcoin` installed, but suspended, and I see it in the UI, but not in the `+vats %suspended` output.

**Comment by jalehman** [comment]
> `+vats` doesn't handles the `%kids` presentation well:
> 
> ```
> +vats
> <snip>
> ::
>  %kids %kids %cz hash:     0v14.4jub3.fe4i1.5pfa6.do69s.fqkh7.tf6o9.g7b68.pgdeu.jjec8.u8517::
> ```
> 
> ```
> +vat %kids
> %kids %cz hash:     0v14.4jub3.fe4i1.5pfa6.do69s.fqkh7.tf6o9.g7b68.pgdeu.jjec8.u8517
> ```

@tinnus-napbus would you mind working this into the Manual? Alternatively, would love if @hoclun-rigsep could help out with this.

**Comment by jalehman** [comment]
> It’d be helpful if the details in the pr or release notes explained the options/showed basic usage and examples

@tinnus-napbus would you mind working this into the Manual? Alternatively, would love if @hoclun-rigsep could help out with this.

**Comment by tinnus-napbus** [comment]
> > It’d be helpful if the details in the pr or release notes explained the options/showed basic usage and examples
> 
> @tinnus-napbus would you mind working this into the Manual? Alternatively, would love if @hoclun-rigsep could help out with this.

yeah I'll PR an update to the +vats entry in dojo tools in operators shortly

**Comment by hoclun-rigsep** [comment]
> yeah I'll PR an update to the +vats entry in dojo tools in operators shortly

Thank you @tinnus-napbus; also happy to take this task if you wish.

**Pull request merged**
