### PR TITLE
Group Feed: unread counts

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Keeps track of an unread count for group feeds, and displays the link as blue if the group feed has unreads. In lieu of better specified behaviour the unread count is reset upon navigation to the page.

### CODE REVIEW

**Review by tacryt-socryp — APPROVED** [review]
Really straightforward. What say you @urcades ?

**Comment by urcades** [comment]
Very big +1

In a prior design of the sidebar, prior to jimmy's work, I had made the suggestion that "unread counts" for the feed could live in the following location:

Screen Shot 2021-04-07 at 3 09 30 AM

I'm pro- this update broadly, but could one of you provide some visual context as to how this is being implemented? I scanned the "files changed" in github and it looks like this is being based in a pretty similar manner.

**Comment by liam-fitzgerald** [comment]
Screen Shot 2021-04-08 at 4 38 33 pm

**Comment by urcades** [comment]
Perf, spiritual stamp

**Comment by tacryt-socryp** [comment]
@liamfitzgerald this is good to go

**Comment by liam-fitzgerald** [comment]
Absolutely, but there's backend changes here. They don't affect the networking layer, so maybe they could go out in release/next-js ?

**Comment by matildepark** [comment]
I have declared "that's ok"

**Pull request merged**
