### PR TITLE
tutorial: reenable

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
- Needs a new release of indigo-react for the lifesaver icon, currently stubbed as NullIcon
- Addresses issue where the profile would lag for tutorial popover
- Dynamically resizes tutorial modal
- Fixes joining graphs
- Changes 'Updates' to 'Notifications' in the notifications screen (nb: Updates doesn't appear anywhere else in our copy)
-  Updates the location of the beginner island group for mainnet. 

cc: @jyng @urcades

### CODE REVIEW

**Comment by jyng** [comment]
Clicking 'Yes' seems to infinitely hang?
image

**Comment by jyng** [comment]
Spacing between title, paragraph, and buttons are still space 2 (8px) and not space 4 (16px)
image

**Comment by matildepark** [comment]
> Clicking 'Yes' seems to infinitely hang?
> image

I no longer have it infinitely hang, but i resolved some merge conflicts and we might've had something mixed up with that. Pushed, if you wanna try it. Functionally seems to work fine.

**Review by matildepark — COMMENTED** [review]
Even mobile looks pretty nice. I like this a lot. Stamp from me, just needs that prerequisite indigo-react version and design stamp.

**Comment by jyng** [comment]
Hmmm, still hangs for me.

**Comment by jyng** [comment]
## Welcome Modal
1) Let's give the welcome modal the same treatment of space 3 padding, just like the other modals
2) When you press skip, it should prompt the 'End Tutorial Now' screen. 

image


#Tutorial in Leap
**Let's not include tutorial as a top level item in Leap. It should only appear when you search for it.**

image

**Comment by jyng** [comment]
End Tutorial Spacing
- Lets give this modal the same space `3` spacing as the other modals.

**Comment by jyng** [comment]
## End Tutorial
- The step here should be **10 of 10** not 10 of 11.
image

**Comment by matildepark** [comment]
@liam-fitzgerald 1.2.18 is released and has the new icon; you can just resolve the conflict here and bump indigo-react for merge

**Comment by matildepark** [comment]
Or — wait maybe not, we still need the timer.

**Comment by liam-fitzgerald** [comment]
I'm deploying the timer now

**Comment by matildepark** [comment]
Still needs time remaining in the tile.

**Comment by jyng** [comment]
@liam-fitzgerald I left the group and then joined the group again and my 'days remaining' results in an error.
image

**Comment by matildepark** [comment]
Presumably if you join the group straight up (or if we don't have anything in our settings-store) we just shouldnt show the line at all

**Comment by jyng** [comment]
If you join the group straight up, you still only get a 2 week membership. So, shouldn't we still show that?

**Comment by matildepark** [comment]
Oh true. So perhaps we should just have an ongoing conditional for the group join in this case.

**Comment by jyng** [comment]
@liam-fitzgerald The design/styling here is done. All that's remaining is the timer bug here.

**Comment by matildepark** [comment]
Can we get commit hygiene on @jyng's commits? Either one of you should reword and force push.

**Review by matildepark — APPROVED** [review]

**Pull request merged**
