### PR TITLE
metadata-store: actually fix it, strongly type the action sent to %pull-hook to prevent moronic errors

### PR DESCRIPTION
**Pull request by tacryt-socryp**
I should have cast the action I passed into the !> in #4748. Apologies, I messed up.

### CODE REVIEW

**Comment by joemfb** [comment]
Is there anything useful that the metadata-hook could've been with the negative poke-ack it was getting here?

**Comment by tacryt-socryp** [comment]
@joemfb I was just irresponsible with translating the work I had done in `+poke-noun` into `+on-load`. This was a deterministic failure, not really something that we would want to meaningfully recover from or use the poke nack on.

**Comment by tacryt-socryp** [comment]
@matildepark I've tested this on ~littel-wolfur's fiance's livenet ship and the updated version does indeed fix all group feeds.

**Review by liam-fitzgerald — APPROVED** [review]
LGTM!

**Comment by liam-fitzgerald** [comment]
This illustrates a pressing need to abstract the creation of different cages in a typesafe and concise manner.
```hoon
::  lib/pull-hook.hoon
|%
++  cg
  |%
  ++  action
     |=  =update:store
     :-  %pull-hook-action
     !>(update)
  --
--
::  at callsite
(poke-our:pass %metadata-pull-hook (action:cg:pull-hook %add [entity .]:rid))
```
Something like this pattern, where we have a `cg` core in the helper lib that exposes cage-creation functions as its arms would go a long way towards preventing these kinds of silly mistakes, and also help reduce churn due to new mark versions

**Comment by matildepark** [comment]
@liam-fitzgerald tested this last night on a -L and also confirmed it sends the adds. Still, I'm gonna opt to hold for Monday since this is an edge case, not a universal issue.

**Comment by tacryt-socryp** [comment]
can we push this out today?

**Comment by matildepark** [comment]
I intend to slate it, yes.

—
~haddef-sigwen
https://urbit.org

**Pull request merged**
