### PR TITLE
contact-push-hook: speed up asymptotics by only doing a fixed number …

### PR DESCRIPTION
**Pull request by tacryt-socryp**
…of scries

### CODE REVIEW

**Review by ixv — APPROVED** [review]
LGTM

**Comment by matildepark** [comment]
Mind holding a second to put this out with a batch of JS fixes I have? Let me know when you intend to deploy and I'll get my omnibus PR.

**Comment by ixv** [comment]
Wanna just take care of the deploy yourself, since you have a machine that can glob?

**Comment by matildepark** [comment]
No, you can do the deploy. PR is in #4435.

**Comment by matildepark** [comment]
Right, machine that can glob. OK, fine, *this time*.

**Pull request merged**
