### PR TITLE
eyre closes arvo requests when their source connections die, kills longstanding dormant sessions

### PR DESCRIPTION
**Pull request by ohAitch**

### CODE REVIEW

**Comment by juped** [comment]
Looks like this can't be updated in place. It type-fails in `++mo-pass`. Can this be solved with a type adapter or should it be put off?

**Comment by juped** [comment]
(Or... do I need to update ford before gall? That looks like it might be it.)

**Comment by ohAitch** [comment]
You need to update use before gall, at any rate, yes.

**Comment by ohAitch** [comment]
zuse*

**Comment by ohAitch** [comment]
The specific change is that %wasp now contains a loobean as to whether it
is a subscription or unsubscription request. The same could perhaps be done
with a separate card, but it's how %exec works(approximately);
pinging @cgyarvin re: is this proper card architecture?

**Comment by juped** [comment]
Merged, sans empty commit 8^)

**Comment by ohAitch** [comment]
Metadata!

**Comment by juped** [comment]
ae14e14

**Comment by ohAitch** [comment]
?

**Comment by juped** [comment]
wrong HEAD, edited
the metadata is still there, is the point

**Comment by ohAitch** [comment]
Yup, I noticed the issue was closed
I suppose the correct thing to do would have been to put it in the or
title?

**Comment by ohAitch** [comment]
(And as a matter of tone, I meant that as a "waves hands
faux-enthusiastically" exclamation point and not a "but wait this is
important" one, apologies if that was unclear)

**Comment by juped** [comment]
I put issue numbers into merge commits when I see them there, yeah. It is indeed not that important in the eyes of 天.

**Comment by ohAitch** [comment]
May or may not have just brought down doznec.

**Comment by juped** [comment]
Why would this sort of error not fail to typecheck?

**Comment by ohAitch** [comment]
- +< etc. are unsafe P:

**Comment by philipcmonk** [comment]
There's a lesson here:  if you're going to use direct tree addresses,
you're doing it because you're explicitly trying to get around the type
system.  Be absolutely sure that you're right before using it.  Also, test.

**Comment by ohAitch** [comment]
- taken to its logical conclusion, this requires every clause of a `$%` to start with `h=%foo` or somesuch. Possibly worthwhile, but a nontrivial refactoring.
- Solid test protocols would be helpful yes. I had tested that proxying worked when I had been editing that part of the code, but did not think to rerun that after apparently clobbering the relevant wire in the session-expiration change.

**Comment by juped** [comment]
`+>.$`

**Comment by juped** [comment]
(It's more of an @cgyarvin question - why does your typechecker suck at basic things like "atom or cell"? :) Given that it is what it is, though, I would not have designed that type like that - I would have added a `%$` case to the beginning of the `$%`...)

**Comment by ohAitch** [comment]
Quite. There you are safe in the knowledge that $ is a door, and therefore
is a [^ * *] while you're in it despite the compiler only recognizing it as
a *; likewise, I was safe in the knowledge that whir was a $%, that
knowledge just happened to be false.
Perhaps the lesson to take away there is that $|(~ $%(...)) is just a bad
type to use, by its offensiveness to proper hoonish intuition.

**Comment by ohAitch** [comment]
I think there it's a completeness problem: axis syntax unsafety exists
precisely because there are cases where the type checker can't prove
atom/cell, and you want to crashingly pull out the contents of a unit/
second element of a list/ etc. anyway

**Comment by philipcmonk** [comment]
Quite.  I definitely don't advocate the logical conclusion -- caution
should be sufficient.

**Comment by ohAitch** [comment]
> `path`[%$ ~]
    /
Maybe not *precisely* a `%$` case.

**Comment by juped** [comment]
Or even just use `(unit whir)` instead of whir. There are many things that can be done. :)

**Comment by ohAitch** [comment]
The whole point of ++whir is that it is transparently castable to ++wire,
and more importantly back via ++soft. This is also why span:ship etc.

**Comment by ohAitch** [comment]
(Specifically, the rough meaning of "span:ship" is "@ta-obtained-by-scot-p")

**Comment by juped** [comment]
> `path`~
    /
idgi dude

**Comment by ohAitch** [comment]
> `path`(some /foo)
type-fail

**Comment by juped** [comment]
That's in reference to using `[%$ ~]`, not using a unit.

**Comment by ohAitch** [comment]
Yes, my concern is that [%$ ~] -> / -> ~
Granted they should never be /parsed/, but this still causes me to have an
intuition that "a path is a list of nonempty spans".

**Comment by ohAitch** [comment]
But %$ could just as easily be %fin, really this is bikeshedding.

**Comment by juped** [comment]
It's all your call.

**Comment by cgyarvin** [comment]
It is quite intentional that axis syntax is "unsafe" - not in the sense of
"can create mis-typed nouns," but in the sense of "can crash."  $|(~
$%(...))) is fine, so long as you use actual pattern-matching to decode it
rather than just going straight in with tree geometry.

None of this should cause a core dump, however...

**Comment by juped** [comment]
I think @ohAitch just likes golfing too much. I would have used `?~`.

**Comment by ohAitch** [comment]
Imo pattern-matching is far clearer than golfing; but the issue here was
not having the ~ possibility in mind. Probably exacerbated by having a
bunch of ?+ -.tee !! in surrounding code, in which case there /isn't/ a
problem with the unsafe access.

**Comment by philipcmonk** [comment]
`?+  -.tee  !!` isn't formally bad because it'll crash in either case, but it's downright misleading.  If I see a `-.tee`, then I expect `tee` to be a cell, and I probably won't even check the definition.

**Pull request closed without merging**
