### PR TITLE
Remove unused components

### LINKED ISSUE #6216: Remove unused components from urbit/urbit
As part of the ongoing migration from the monorepo, let's clean up some unused bits:

- Remove bitcoin: set up a new repo, and time willing, deploy this to its own desk. This is being removed from the default pill (#6204), so it should still be accessible on the network.
- Remove vere: since it's now got its own repo
- Investigate removal of npm packages — might be too onerous for this

### PR DESCRIPTION
**Pull request by tinnus-napbus**
Fixes #6216

We moved Vere out of the urbit repo. As part of this clean up we're also removing a few other unused items and removing bitcoin from the code (and from the default pill: https://github.com/urbit/urbit/issues/6204)

- bitcoin: removed
- garden: new location https://github.com/tloncorp/landscape
- hs: removed
- urbit (vere), docker-image, ent, urcrypt: new repo https://github.com/urbit/vere

### CODE REVIEW

**Review by philipcmonk — APPROVED** [review]
Very satisfying!

**Comment by istathar** [comment]
This is terrific.

**Comment by felzix** [comment]
FYI `garden-dev` is still mentioned here: https://developers.urbit.org/guides/additional/software-distribution

What should I do in lieu of `[user@host pkg]$ ./symbolic-merge.sh garden-dev hello` ?

**Comment by zalberico** [comment]
It still exists: https://github.com/urbit/urbit/blob/develop/pkg/symbolic-merge.sh

**Comment by zalberico** [comment]
It lives here now: https://github.com/tloncorp/landscape/tree/master/desk-dev

**Pull request merged**
