### PR TITLE
soto: ignores backspace at position 0

### PR DESCRIPTION
**Pull request by matildepark**
@ixv caught this. The keypress handler would check if backspace was past position 0
before deleting one character at that position. If you were at position
0, then it would drop down to the 'else' and send the key value as a
string, throwing off the state between front and back end. This commit
fixes the issue, ignoring Backspace at position 0.

### CODE REVIEW

**Comment by ixv** [comment]
LGTM

**Comment by joemfb** [comment]
@matildepark, @jtobin, I just got `:soto` in the recent OTA, and this bug still present. It looks like this commit went into the update, so I'm not sure what went wrong ...

**Comment by matildepark** [comment]
@joemfb Since there were multiple commits with built JS (but not each other's changes), presumably #1973 took precedence and the two commits weren't rebuilt for the OTA. Depends what @jtobin's build process is like these days (I recall he built the JS himself before deploying? It was a while ago, and we've changed a lot since then).

**Comment by joemfb** [comment]
That makes sense. I also appear to be missing the tab completion.

**Comment by matildepark** [comment]
That wasn't patched in, but it could point to me being wrong about the build thing (and the keycodes operating differently wherever you're on?). What's the browser and OS? I'll try and replicate this.

**Comment by joemfb** [comment]
Chrome 77 on MacOS 10.14.

**Comment by matildepark** [comment]
I can replicate … I’ll look into what’s going on and patch shortly. The rebuilt JS will help too — running from master only has the backspace commit’s built JS, not both.

— 
~haddef-sigwen
http://urbit.org

**Comment by jtobin** [comment]
> Since there were multiple commits with built JS (but not each other's changes), presumably #1973 took precedence and the two commits together in a built JS format weren't pushed for the OTA. Depends what @jtobin's build process is like these days (I recall he built the JS himself before deploying? It was a while ago, and we've changed a lot since then).

Indeed, I recompile the JS before every release, so this *should* contain all the committed :soto changes.  I do remember running `make interface` a few times, but I had to tweak the release candidate a couple of times to drop some commits, so it's possible the updated compiled JS fell out.

(The release process is still an overly manual affair -- I am steadily automating things as I get the opportunity, but much remains to be automated.)

**Comment by jtobin** [comment]
If it *is* missing I can hotfix it today.

**Comment by jtobin** [comment]
If it helps diagnose the issue one way or the other, this is appearing in the compiled JS:

```
{if("Backspace"===e.key&&this.props.cursor>0)return qs.doEdit({del:this.props.cursor-1}),qs.setState({cursor:this.props.cursor-1}
```

**Comment by matildepark** [comment]
@jtobin That code fragment wasn't what was patched here in #1980 — this PR adds "Backspace" as an ignored key so that if cursor is *at* 0, it gets caught and ignored instead of sent as a string.

I think this patch wasn't incorporated in the OTA, just #1973's changes. #1988 rebuilds everything and fixes the issue @joemfb brings up here.

**Comment by jtobin** [comment]
@matildepark Aha.  I've figured this out. 

I just checked, and `make interface` on `v0.9` doesn't produce any different compiled JS for me.  So I did (attempt to) update it accordingly.  But, per #1664, `make interface` is really only half a build; it assumes that one has already `npm install`'d a bunch of stuff before running it.  I hadn't done that since `:soto` landed, so the relevant JS wasn't being compiled at all, and no errors were thrown.

I'll patch this up and hotfix things lickety-split.

**Comment by jtobin** [comment]
(`:soto` also hadn't been added to `sh/build-interface`.  That'd also do it. 😄)

**Pull request merged**
