### PR TITLE
reclaim memory from persistent caches on restart and kernel reset

### PR DESCRIPTION
**Pull request by joemfb**
/cc @frodwith

### CODE REVIEW

**Comment by frodwith** [comment]
Looks good.

**Comment by frodwith** [comment]
We might want something similar that trims those u3hs to some nice predefined bounded size. We could call it, for example, after pokes.

**Comment by joemfb** [comment]
@frodwith, we have `u3h_trim_to()` which trims a hashtable to a specified number of entries, but I don't think we have anything that works by memory footprint. Something like that would ideally run every *n* events, imo.

@philipcmonk, it's an incomplete gesture in that direction. It's not before *any* allocations (note the `%wack` entropy injection event immediately prior), but before most of them. The biggest remaining problem is still home-road fragmentation; the overall free space of the loom only grows on deallocation if the block in question is adjacent to that free space. So the big improvement of this PR is just in clearing these caches more regularly.

**Comment by joemfb** [comment]
Having revived `|mass` in #1171, I rebased these changes on top to check them for correctness. Lo and behold, they leaked. I've plugged the leaks, and added some clarifying comments and details.

Now that I can measure, I'm somewhat surprised that this doesn't seem to be reclaiming all of these caches -- but maybe they just populate that quickly on restart and the first few events. I'll do some more testing.

**Comment by joemfb** [comment]
I booted a fake-zod, immediately ran `|mass`, exited, restarted, and ran `|mass` again. Some memory is clearly reclaimed, but a lot less than I expected. At least it doesn't leak!

```
wish cache: 
  boot:    B/932
  restart: KB/1.328

memoization cache:
  boot:    KB/28.580
  restart: KB/8.424

battery hash cache:
  boot:    B/288 
  restart: B/288

hank cache: 
  boot:    KB/1.676
  restart: KB/1.256

bytecode programs:
  boot:    MB/2.506.404
  restart: MB/1.227.780

bytecode cache:
  boot:    KB/262.040
  restart: KB/116.784
```

**Pull request merged**
