### PR TITLE
graph lib: make subset interface work the same as old one did

### PR DESCRIPTION
**Pull request by tacryt-socryp**
Should fix weird notification bug.

### CODE REVIEW

**Comment by tacryt-socryp** [comment]
This needs to be pushed out as a hotfix to prevent excessive network traffic @liam-fitzgerald

**Comment by liam-fitzgerald** [comment]
Has it been tested?

**Review by liam-fitzgerald — APPROVED** [review]
LGTM, if tested

**Comment by tacryt-socryp** [comment]
Yes, tested

**Pull request merged**
