### PR TITLE
more typescript cleanup

### PR DESCRIPTION
**Pull request by tylershuster**
Another TS cleanup, pushing this for further commits

### CODE REVIEW

**Comment by matildepark** [comment]
Flatten into one commit?

**Review by matildepark — CHANGES_REQUESTED** [review]
This doesn't actually compile — PostItem.tsx crashes. Can you try building and doing a runthrough and tag me again if you have reasonable confidence?

**Comment by tylershuster** [comment]
Yep, I'm sure I know why it crashed before and am confident it won't again.

**Review by matildepark — APPROVED** [review]
Human selenium'd through each route and corrected one prop that really should be a string.

**Comment by matildepark** [comment]
123 errors remaining.

**Pull request merged**
