### PR TITLE
Vector Library (Jets)

### PR DESCRIPTION
**Pull request by sigilante**
This PR reflects a subset of the changes in #3536, which has become rather unwieldy. This includes the jets for #4455, the vector library components.

I have some refactoring to do in this branch, I will ping you when ready.

### CODE REVIEW

**Comment by sigilante** [comment]
Question about jetting transmission.  Suppose I have a pass-through gate `++addv`.  From what I can tell, this gate's hint (my `printf`s do nothing) is ignored and `++funv` is invoked directly.  To avoid that happening do I need to remove the `++funv` call or do I need to implement `++funv` as a gate?

```
|%
++  lvs
  ^|
  ~%  %lvs  ..part  ~
  |_  r=$?(%n %u %d %z)   :: round nearest, round up, round down, round to zero
  ::    Turn on a gate of two variables.
  ++  turn2  :: I guess not in hoon.hoon
    |=  [[a=(list @rs) b=(list @rs)] f=$-([@rs @rs] @rs)]
    ^-  (list @rs)
    ?+  +<-  ~|(%turn2-length !!)
      [~ ~]  ~
      [^ ^]  [(f i.a i.b) $(a t.a, b t.b)]
    ==
  ::
  ::    Apply a two-variable function across a vector input.
  ++  funv
    ~/  %funv
    |=  f=$-([@rs @rs] @rs)
    |=  [u=@lvs v=@lvs]  ^-  @lvs
    ~_  leaf+"lagoon-fail"
    (make (turn2 [(unmake u) (unmake v)] f))
  ::
  ::    Vector addition
  ++  addv  ~/  %addv  (funv add:rs)
```

**Comment by ohAitch** [comment]
Hah, can jet hints even match closed-over arguments, or just the formula?

**Comment by sigilante** [comment]
I'm currently permuting to see if I can slice this nicely...  at minimum I should be able to jet `++turn2` although that's simple enough that it may not be worth it for performance.

**Comment by ohAitch** [comment]
I think at worst you should be able to
```
++  addv  ~/  %addv  |=([@lvs @lvs] %.(+< (funv add:rs)))
```
to generate the unique gates

**Comment by sigilante** [comment]
I'm circling around:  I wrote simpler `++addv` etc. and got the jets working for those, then I'm going to reintroduce the more sophisticated approach.

**Comment by sigilante** [comment]
Current jetting status:

- [ ] `%addv`
- [ ] `%subv`
- [ ] `%mulv`
- [ ] `%divv`
- [ ] `%inner`
- [ ] `%invert`

I'm going to have a hard time beating bitwise native performance on these:

- [ ] `%get`
- [ ] `%set`
- [ ] `%funv`
- [ ] `%zeros` etc.

**Comment by sigilante** [comment]
OK, I'll write up a fast inner product for both then this will be ready for review.  There's some room for discussion about which other gates to jet---I've actually written a zillion jets for this but I've only included a few of them here because I don't think it's likely to beat performance for the simple bitwise ops.

**Comment by sigilante** [comment]
Locally everything compiles and works correctly.  In the CI, I get the following warning about jet hints:

```
fund: in in, parent 24d618b9 not found at 7
fund: in apt, parent 5b3c43a7 not found at 7
fund: in in, parent 24d618b9 not found at 7
fund: in apt, parent 5b3c43a7 not found at 7
fund: in in, parent 24d618b9 not found at 7
fund: in apt, parent 5b3c43a7 not found at 7
```

Since I don't see these locally (`gcc`), I'm not sure what's going on.  Any idea what's going on?  _Otherwise_ this is ready to go unless there's a hue and cry for moar jets.

**Comment by sigilante** [comment]
OK, officially tagging this one as ready for review, and moving on to the `@lm` jets.

**Pull request closed without merging**
