### PR TITLE
graph-store: fix signatures & marks

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Fix signing nodes with graph-store

### CODE REVIEW

**Comment by liam-fitzgerald** [comment]
ping: @tacryt-socryp

**Comment by tacryt-socryp** [comment]
What was the issue before?

**Comment by liam-fitzgerald** [comment]
a) `/=app=` syntax doesn't work on ford fusion
b) the mold for the foreign deed scry is incorrect it's a `[life pass (unit @ux)]` not a unit of the same
c) said deed scry crashes if we don't have the users key, necessitating scrying for their lyfe (unitized life) to check whether we have their key

**Comment by tacryt-socryp** [comment]
Sounds good. I had only tested it for local deeds.

**Review by tacryt-socryp — APPROVED** [review]

**Pull request merged**
