### PR TITLE
chat + contacts: finished integration for managed groups

### PR DESCRIPTION
**Pull request by loganallenc**
Specifically, this commit removes the add action from the contact-view
and replaces it with a listener within contact-hook for additions
to groups. This means that when a ship is added to a group that the
contact-hook is watching, the ship is automatically sent an invite to
join that "managed group" from the contacts application. This also
includes the UI integration work on the management screen and settings
screen for working with the new group / permission structure.

### CODE REVIEW

**Comment by vvisigoth** [comment]
plz morge

**Comment by loganallenc** [comment]
:( i wanted isaac to review. this is fine tho

**Comment by matildepark** [comment]
I expected to wait for him too — but when AA demands, I follow ...

**Comment by ixv** [comment]
I'll read it anyway

**Pull request merged**
