### PR TITLE
interface: global audio player for collections

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Adds a landscape-wide music player, and integrates it with collections.
### Behaviour
The audioplayer component now fetches playing status etc. from the music player state. 
### Design notes:
- Missing a pause & music icon (LargeBullet and Bitcoin have been substituted respectively)[
Screen Shot 2021-06-28 at 10 46 08 am
Screen Shot 2021-06-28 at 10 46 17 am
Screen Shot 2021-06-28 at 10 50 19 am
Screen Shot 2021-06-28 at 10 50 45 am

### CODE REVIEW

**Comment by matildepark** [comment]
Very cool. Design — are you cool with this feature? And can we get indigo-react icons for this? @g-a-v-i-n @urcades

**Comment by tylershuster** [comment]
https://github.com/urbit/landscape/issues/192

**Comment by tacryt-socryp** [comment]
Wow, this is truly insane. Glad to have it, but wow

**Comment by matildepark** [comment]
This is unblocked as of indigo-react 1.2.25.

**Comment by arthyn** [comment]
won't ship with this version of groups, but we should do it for the next

**Pull request closed without merging**
