### PR TITLE
Updated nix install instructions

### PR DESCRIPTION
**Pull request by tylershuster**
I don't know this is just what nixos.org says and one worked for me and the other didn't

### CODE REVIEW

**Comment by tylershuster** [comment]
I didn't mean to add other commits on top of this. but the contrib guidelines should be changed

**Comment by tylershuster** [comment]
Oh God how did this get here I am not good with computer

**Comment by botter-nidnul** [comment]
This needs to be corrected, I've seen a person on the discord run into this problem - the nix install just fails silently without the -L.  Do you want to try again @tylershuster with a new branch with just the one commit, or I can redo it?

**Comment by matildepark** [comment]
I actually ran into this as well — feel free to just tag me in the following PR.

**Comment by tylershuster** [comment]
Done

**Pull request closed without merging**
