### PR TITLE
interface: more visual fixes, QA

### PR DESCRIPTION
**Pull request by tacryt-socryp**
- https://github.com/urbit/landscape/issues/359
- https://github.com/urbit/landscape/issues/351

### CODE REVIEW

**Comment by matildepark** [comment]
You missed half of urbit/landscape#351 — it always says "0 channels".

**Comment by tacryt-socryp** [comment]
Oh, didn't even see that part. kk, will fix

**Comment by matildepark** [comment]
That's not what I mean. Here's an example:

image

**Comment by matildepark** [comment]
The issue is L200 in GroupsPane.tsx, we just stub it out with "0" instead of passing in the channels count.

**Review by matildepark — APPROVED** [review]

**Pull request merged**
