### PR TITLE
Add state machine vane.

### PR DESCRIPTION
**Pull request by sigilante**
Simplest possible state machine in Hoon:

```hoon
=|  n=@ud
|=  ~
.(n +(n))
```

next step up is to add read arm and write arm to make more usable

```hoon
=|  n=@ud
|%
  ++  on-read  n
  ++  on-write
    |=  ~
    .(n +(n))
--
```

start simplest:

```hoon
++  scamp
  |%
  +$  bowl
    $:  our=ship     ::  identity of ship
        eny=@uvJ     ::  entropy
        now=@da      ::  timestamp
    ==
  ++  form
    $_  ^|
    |_  bowl
    ++  on-write
      |~  [mark noun]
      *[(list card) _^|(..on-write)]
    ::
    ++  on-read
      |~  path
      *(unit (unit page))
    --
  --
```

our simple example made to conform by THE MAN
```hoon
!:
=|  n=@ud
|_  [our=@p eny=@uvJ now=@da]
  +*  this  .
  ++  on-read
    |=  =path
    ^-  (unit (unit cage))
    ``[%noun !>(n)]
  ++  on-write
    |=  [=mark =noun]
    ^-  [(list move) _this]
    `this(n +(n))
--
```

### CODE REVIEW

**Comment by sigilante** [comment]
Faye is named after Morgana le Fay (various spellings of her sobriquet being attested).  In particular, I have in mind the “Fata Morgana”, the optical mirage leading to tales of lost islands and ghost ships in the sky.  Since Faye was nominally motivated as part of the Layer Zero blockchain endeavor, such a reference to slippery treasures and hidden ways seems apt.

**Comment by tacryt-socryp** [comment]
this should replace gall, not joking

**Comment by tiller-tolbus** [comment]
> this should replace gall, not joking

The purpose of this research is to have a userspace primitive more amenable to consensus algorithms. See also: https://gist.github.com/tiller-tolbus/5cd62b4c1c6988fda1e269fc2aa34494

**Comment by sigilante** [comment]
Superseded by Aegean etc.

**Pull request closed without merging**
