### PR TITLE
chat: restore message-to-json virtualisation

### PR DESCRIPTION
**Pull request by liam-fitzgerald**

### CODE REVIEW

**Comment by matildepark** [comment]
@ixv merge at your leisure before ota

**Comment by joemfb** [comment]
Seems like #2887 is a better option here. But if not, it should be specifically superseded by this PR.

**Comment by liam-fitzgerald** [comment]
#2887 is still waiting on approval from @loganallenc but if it's good to go in then happy to change this PR

**Comment by matildepark** [comment]
@joemfb This PR is meant to restore parity between `release/next-userspace` and `master` after I merged the chat namespacing PR a touch early, thinking it was ready to go. It seems best to leave #2887 to merge after this one and resolve its conflicts after being reviewed.

**Comment by loganallenc** [comment]
I prefer the solution in #2887

**Comment by matildepark** [comment]
Alright — it doesn't target `release/next-userspace`, so I guess we would close this one, merge `release/next-userspace` and then merge #2887 since I think @Fang- is asleep and OTA is due tonight.

**Comment by matildepark** [comment]
Nevermind, I had a brainfart and changed the base on #2887. Alright, please see #2887 for approval and merge.

**Pull request closed without merging**
