### PR TITLE
apps: remove %hall and %talk

### PR DESCRIPTION
**Pull request by loganallenc**
These applications are now deprecated, so if there are no objections I'd like to remove them. I'll leave the sur/hall.hoon file so that the %dns and %acme apps don't need the intensive state adapter updates that Joe mentioned in #1894.

### CODE REVIEW

**Comment by Fang-** [comment]
_pours one out_
It was fun while it lasted. ):

**Comment by galenwp** [comment]
We appreciate all your hard work, @Fang-

**Comment by joemfb** [comment]
The presence of :hall's log/save/load files in this diff leads me to ask: does any of that functionality needs to be implemented in the new chat apps? In the same vein, do these apps support herb's import/export?

**Comment by loganallenc** [comment]
The new %chat-store and %chat-hook should certainly have their own import/export written. Will this to my to-do.

**Comment by matildepark** [comment]
Chat apps, like languages, evolve. This human, this good. When we have applications that aren’t chat apps on Urbit, then, only then, will we will have transcended ourselves.

**Pull request merged**
