### PR TITLE
hoon: bscl to bccl, etc

### PR DESCRIPTION
**Pull request by jfranklin9000**
### Issues

- I'm not sure how to create a bootable pill with these changes.

- `pkg/arvo/lib/pprint.hoon` may have a bug.
See these lines (403 and 406):
`XX %tsld to %tsgl, but should be %tsgr? (to match =>)`
`XX %tsbn to %tsgr, but should be %tsgl? (to match =<)`

### CODE REVIEW

**Comment by joemfb** [comment]
`sh/update-solid-pill` should be able to handle these kinds of changes. If there are issues with the script, I'd do something similar manually:

```
> |merge %stage our %home
> |mount /=stage=
... copy hoon.hoon into $pier/stage/sys
> |commit %stage
> .latest/pill +solid /=stage=/sys, =dub &
```

Which will put the pill at `$pier/.urb/put/latest.pill`.

As for `lib/pprint`, I would worry about it beyond the comment you added -- it's practically unused right now.

**Comment by philipcmonk** [comment]
FYI the `|merge` and `|mount` can be replaced by simply `-work`, which is a utility to set up such a scratch desk called `%work`.

**Comment by jfranklin9000** [comment]
I ran `sh/update-solid-pill`.  The output is noisy (see https://pastebin.com/2iQQ6U1p), but `solid.pill` was updated.

Then I booted from the new pill:
```
$ urbit -B bin/solid.pill -F zod
~
urbit 0.10.8
boot: home is /xxx/urbit-release-next-sys/zod
loom: mapped 2048MB
lite: arvo formula 50147a8a
lite: core 590c9d56
lite: final state 590c9d56
boot: loading pill bin/solid.pill
loom: mapped 2048MB
boot: protected loom
live: logical boot
boot: installed 268 jets
---------------- playback starting ----------------
pier: replaying events 1-7
arvo: assembly
arvo: assembled
arvo: formal event
arvo: formal event
arvo: metamorphosis
gall: direct morphogenesis
arvo: metamorphosed
arvo: formal event
arvo: formal event
gall: loading %hood
gall: not running %chat-cli yet, got %watch
gall: not running %dojo yet, got %watch
gall: loading %chat-store
gall: loading %contact-store
gall: loading %group-store
gall: loading %invite-store
gall: loading %link-store
gall: loading %metadata-store
gall: loading %permission-store
gall: loading %chat-hook
gall: loading %file-server
gall: loading %acme
gall: loading %azimuth-tracker
gall: not running %eth-watcher yet, got %watch
gall: loading %chat-cli
gall: loading %chat-view
gall: loading %clock
gall: loading %contact-hook
gall: loading %contact-view
gall: loading %dojo
gall: loading %eth-watcher
gall: loading %glob
gall: loading %goad
gall: loading %graph-pull-hook
gall: loading %graph-push-hook
gall: not running %graph-store yet, got %watch
gall: loading %graph-store
gall: loading %group-pull-hook
gall: loading %group-push-hook
gall: loading %invite-hook
gall: loading %launch
gall: loading %lens
gall: loading %link-listen-hook
gall: loading %link-proxy-hook
gall: loading %link-view
gall: loading %metadata-hook
gall: loading %permission-group-hook
gall: loading %permission-hook
gall: loading %ping
gall: loading %publish
gall: loading %s3-store
gall: loading %soto
gall: loading %spider
gall: loading %weather
pier: (7): play: done
---------------- playback complete ----------------
ames: live on 31337 (localhost only)
http: web interface live on http://localhost:8080
http: loopback live on http://localhost:12321
pier (14): live
ames: larva: drain
ames: metamorphosis
> |mount /=home=
>=
~zod:dojo>
^d
```
Looks clean, check the files:
```
$ diff -ruq pkg/arvo zod/home
Only in pkg/arvo/: .gitattributes
Only in pkg/arvo/: .ignore
Only in pkg/arvo/: LICENSE.txt
Only in pkg/arvo/: README.md
Only in pkg/arvo/: TESTING.udon
Only in pkg/arvo/: ren
```
All looks good.  Should I add `solid.pill` to the PR?

**Comment by philipcmonk** [comment]
Did you verify that when booting with the new pill, you have the changes loaded?  For example, try casting a new hoon to `+hoon`.

The errors in that output are in lib/xray, which made the dojo not start I think because it was using new files with the old kernel?  If the new pill works correctly, that's all that matters though.

**Comment by jfranklin9000** [comment]
Yes, the `diff -ruq pkg/arvo zod/home` was minimal.  The changes in this PR made it into the new pill.  I also checked for `bscl` (and all the others) in `zod/home/*` (after booting from the new pill) and they are gone.

**Comment by joemfb** [comment]
FYI @jfranklin9000, you'll save time if you use `-l` ("lite boot", loading only the necessary apps) when booting fake -zods.

**Comment by philipcmonk** [comment]
This looks good to me.  @jfranklin9000 Yes, push that pill to this PR.

@joemfb what's the right branch for this to target the next breach?

**Comment by jfranklin9000** [comment]
I committed and pushed and see:
### This branch has conflicts that must be resolved
### Conflicting files
`bin/solid.pill`

Not sure what to do.

**Comment by joemfb** [comment]
You'll need pills for each intermediate state, but they don't need to be committed. We will need an updated pill once all the changes are made, but we could merge this PR and add it. In general, the pill management (git lfs) is a longstanding clustercuss -- there's no way to merge binary assets like that, so you need to be all the way up-to-date before you commit it (and any intervening merges cause you to be out-of-date again).

The right branch will be `na-release/next-vere`, but it's not ready quite yet. I think the simplest thing will be for you to stage your changes here, building pills locally but not committing them. Once the changes are you complete, you merge the target branch back into yours and add a pill, or we can merge your changes and add the pill ourselves.

**Comment by joemfb** [comment]
I should be more explicit: you're welcome to commit pills or not, as you see fit. You don't need to worry about the conflicts, they are almost guaranteed to eventually arise regardless of what you do. Since you're already setup to work off this branch, I think you should continue here. I'll be happy to handle any necessary merges.

**Comment by jfranklin9000** [comment]
OK.  All the changes required for this task are in this PR.  Commit 11f8ba23d783a751722f3ff87e5a002c113cbf3b has just the hoon changes.  Commit 2cd4c29613e314a54aef24fa9c7fa4a7a9defbe4 has the changes plus the pill.  I haven't tried to resolve the conflict.  If you want to merge from 11f8ba23d783a751722f3ff87e5a002c113cbf3b and build/commit the pill I'm fine with that.  It might be the best for this PR.

**Comment by joemfb** [comment]
Oh, I hadn't looked at the diff yet .... That's awesome, thanks!

**Review by joemfb — APPROVED** [review]
Thanks again, @jfranklin9000!

I'm gonna merge this onto an integration branch. Per CI, there might still be some issues with lib/xray -- or it might have been a transient failure. I can fix those up if they're real.

Everything else LGTM.

**Pull request merged**
