### PR TITLE
landscape: bring placeholder group joins to parity

### PR DESCRIPTION
**Pull request by matildepark**
cc @urcades 

image

Fixes urbit/landscape#478

### CODE REVIEW

**Comment by urcades** [comment]
Looking wonderful — two very minor requests: 

1. Let us be sure to apply the "small" border radius style to the group tiles (this is marked in figma as 4pt/px, but if there is a variable that represents this, let's use that of course.
2. Rather than use the language of "Unknown members", I'd prefer if we pointed to the fact that the number was awaiting an async update — something like, "Member/peer count pending" or "Fetching peer count" would be preferable — anything that communicates the "live"ness of the state would be good here.

**Comment by matildepark** [comment]
image

**Comment by urcades** [comment]
beautiful — spiritual stamp

—
~fabled-faster
https://urbit.org/

**Review by jamesacklin — APPROVED** [review]
Looks wonderful.

**Pull request merged**
