### PR TITLE
clay: add requests permission checks

### LINKED ISSUE #6401: clay: default desk is public
# Issue Description:
New Desks, as created by `|new-desk %desk-name`, are "public" and can be merged despite `%treaty`'s settings.

## Steps to Reproduce:
1. `|new-desk %test`
2. from another ship, `|merge %test ~their %test`
3. enjoy

## Expected Behavior:
Not that.

### PR DESCRIPTION
**Pull request by MarcusMiguel**
Resolves #6401

### CODE REVIEW

**Review by joemfb — COMMENTED** [review]
This looks right to me.

It seems like the `?(%next %mult)` case in `+try-fill-sub` also needs a permission check -- I'm not sure if these cases had just been missed, or if there's some obstacle.

@MarcusMiguel have you tried this on a livenet ship?

/cc @Fang- @philipcmonk

**Comment by MarcusMiguel** [comment]
While testing this i discovered what appears to be an issue with `Ames`. I'm digging into that before resuming the tests.

**Comment by belisarius222** [comment]
@MarcusMiguel any luck with the Ames issue?

**Comment by MarcusMiguel** [comment]
Changed the return to `[~ ~]` when the permission is denied for `%many`, which means that we will not store the request to try to fill later (this is the current behaviour in the `%sing` handler).

This PR looks good, I don't think it will break anything.

 I'm going to continue debugging some weird behavior I'm noticing in `Ames`.

**Comment by jalehman** [comment]
@philipcmonk when you get a sec, mind giving this a look?

**Review by philipcmonk — APPROVED** [review]
This looks correct to me.

**Pull request merged**
