### PR TITLE
Extras changes.

### PR DESCRIPTION
**Pull request by KeatonDunsford**
Touch up the Extras dir for dev-friendliness. :)

### CODE REVIEW

**Comment by galenwp** [comment]
This looks fine to me.  @juped ?

**Comment by juped** [comment]
Oh, I thought I had commented already - sorry! I'm strongly against having an `extras` directory in here.

**Comment by galenwp** [comment]
Better to be a separate repo?

**Comment by juped** [comment]
hoon.vim and hoon-mode.el are already separate repos that we have. The third thing added here should be one too.

**Comment by galenwp** [comment]
Oh, ok.  This can move, then we can get rid of `extras/`?

**Comment by KeatonDunsford** [comment]
Agreed that this should be separate repo.

**Comment by juped** [comment]
Please put it up at urbit/hoon-LT

**Pull request closed without merging**
