### PR TITLE
groups: resize group summary

### PR DESCRIPTION
**Pull request by jamesacklin**
Adds a manual but indigo-appropriate (indigo "8" x 3 = 288px) max-width to the group message such that it wraps nicely and is centered in the main pane.

image

fixes urbit/landscape#728

### CODE REVIEW

**Review by liam-fitzgerald — APPROVED** [review]
Looks good, wondering if the groupsummary should always have this max-width cc: @urcades

**Comment by urcades** [comment]
@liam-fitzgerald this seems like a reasonable size to maintain for all viewports besides mobile ones — we can probably opt for a `width: 100%` (or something)  pending proper padding being applied to the left and right edges of the element.

**Review by liam-fitzgerald — CHANGES_REQUESTED** [review]
Please apply max-width inside the groupsummary component

**Review by tacryt-socryp — APPROVED** [review]

**Comment by jamesacklin** [comment]
Totally makes sense to do -- just wondering how to handle this in the downstream case of the group-join modal? Happy to set a max-width on this modal container for large viewports, but this affects a host of other things as well.

image

**Review by liam-fitzgerald — APPROVED** [review]

**Pull request merged**
