### PR TITLE
chat: restore 'copied' notice on copying names

### PR DESCRIPTION
**Pull request by matildepark**
See #3326. Now in a nice, stateless flavour.

### CODE REVIEW

**Comment by matildepark** [comment]
ping @tacryt-socryp

**Comment by tacryt-socryp** [comment]
Must check if ref is null before changing innerText both in the initial closure and in the setTimeout closure.

**Comment by matildepark** [comment]
> Also must set unique key on message in this div so that we don't have the potential for extraneous Copied messages.

Wait, where am I setting `key={props.key}`? The message component itself has a key passed to it from chat-message.

**Comment by matildepark** [comment]
ping @tacryt-socryp

**Comment by tacryt-socryp** [comment]
More explicitly: check if nameSpan is null in the closure and this will be good to go

**Comment by matildepark** [comment]
Aight I think I did. It functions normally.

**Comment by matildepark** [comment]
can I get a stamp here? @tacryt-socryp @liam-fitzgerald

**Review by liam-fitzgerald — APPROVED** [review]
LGTM!

**Pull request merged**
