### PR TITLE
Fix ++peek:ut jet semi-discrepancy

### PR DESCRIPTION
**Pull request by dhaffey**
ut_peek.c contains a check involving an obsolete ++park:ut arm still present in the jet. It manifests as a peek-park crash when reading directly from "opaque" core payloads:

```
> +6:=+(42 |?(~))
-find.+6
```

The Hoon version doesn't have this failure mode, which can be demonstrated by copying ++ut and ++slap into lib/ut2.hoon, loading it, and comparing:

```
> q:(slap !>(**) (ream '+6:=+(42 |?(~))'))
-find.+6
-axis.6
> /+  ut2
> q:(slap:ut2 !>(**) (ream '+6:=+(42 |?(~))'))
42
```

### CODE REVIEW

**Comment by juped** [comment]
Only @cgyarvin can definitively answer, but isn't the error on the Hoon side here? Or are direct axis references supposed to bypass the opacity of the payload?

**Comment by cgyarvin** [comment]
I believe they should be typeless, given an opaque payload?  It's not that
we can't read the data, it's just because we don't know what the right span
is.  Otherwise you could actually break type safety.

Yes, ++park is obsolete.

**Comment by dhaffey** [comment]
Yeah, you *could* make `+:|?(~)` an error, but there's really no point since you can just write ```+:`*`|?(~)``` to get around it. The only unreadable nouns are the ones not present in your subject.

**Comment by juped** [comment]
So, what then - readable but %void (or %noun depending on variance)? That would help to explain certain errors...

On August 3, 2016 3:39:08 PM PDT, Dan Haffey <notifications@github.com> wrote:
>Yeah, you *could* make `+:|?(~)` an error, but there's really no point
>since you can just write ```+:`*`|?(~)``` to get around it. The only
>unreadable nouns are the ones not present in your subject.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/urbit/urbit/pull/765#issuecomment-237397188

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dhaffey** [comment]
Should be %noun in all cases (unless of course the payload isn't opaque to begin with). If you ever end up with a %void span for a terminating computation, something's gone very wrong.

**Comment by juped** [comment]
Every core is gold to its own arms, of course. "Opaque" doesn't mean some kind of security mechanism to me, just a type-safety mechanism where you can't accidentally look at a payload and refine its type by doing so.

**Comment by cgyarvin** [comment]
I love seeing you guys do core language work.  There really is no little
man behind the curtain.

The real dream I got halfway through was to (a) eliminate the duplication
of ++mint, ++play, +mull with the fabulous power of higher-order
programmings; and (b) eliminate the dependency on out-of-band caching for
non-exponential performance on ++ut's pruning-list algorithms, by simply
using an in-band cache.

I simply didn't know how exactly to do a monadic cache in the subject when
I wrote ++ut.  Note that you don't see =^ used in this code at all.  I also
was a much stronger believer in out-of-band caching ~+ style, except that
~+ per se cannot work in ++ut because the subject cache becomes polluted
with the worklist.  You have to actually depend semantically in the jets
that the worklist is a clearable cache.  In practice this means the vaunted
self-compiling Hoon compiler can't actually compile itself without the
assistance of C.  Which is lame.

I can't justify working on this myself as a *business* decision.  But as a
mere language designer I wish someone would finish it.  Caution, the
higher-orderness in modern ++ut is quite strong.  I didn't solve the
unification of mint, play and mull in general, but I did for the hardest
rune, %=.  Honestly I feel cut-and-paste might be better software
engineering in this case -- I half just wanted to see if Hoon could be used
as Haskell here.  The answer is "yes, but I'm not sure we want to."  In any
case, the current ++ut is half fish and half bird.

The ++ut jets are the oldest code in Urbit and have evolved, of course,
from the original bootstrap code in C.  I definitely wouldn't mind shooting
them in the head.  But Tlon is not at present so rich that it can spend
money shooting them in the head, even though they need to be shot in the
head.

**Pull request merged**
