### PR TITLE
chat: set initialisation time to 100ms

### PR DESCRIPTION
**Pull request by matildepark**
Eliminates the friction quite a bit! See urbit/landscape#332.

cc @tylershuster

### CODE REVIEW

**Comment by tacryt-socryp** [comment]
What does the initialization time constant *do*?

**Comment by tylershuster** [comment]
￼Gives the renderer time to calculate the size of the chat items￼. Includes loading images. ￼

**Comment by matildepark** [comment]
Right now each time you click a chat you wait 1.5s with the placeholder. But we don’t really need it. And the 1.5s itself adds up...

**Review by liam-fitzgerald — APPROVED** [review]
Looks good, plays ok on livenet

**Comment by matildepark** [comment]
We'll see how next-js reacts and adjust if need be.

**Pull request merged**
