### PR TITLE
Commented out zod in osxpackage and debbuild

### PR DESCRIPTION
**Pull request by revprez**
… as per [this bit of advice](https://twitter.com/urbit_/status/739273155512958976) from [@urbit_](https://www.twitter.com/urbit_):

### CODE REVIEW

**Comment by galenwp** [comment]
Curious to hear @juped weigh in here.

**Comment by revprez** [comment]
Would also love to hear from @yebyen.  I think this is in his wheelhouse, though it doesn't seem the target `debinstall` actually prepares a package.

**Comment by juped** [comment]
I object only on style grounds, to wit:

- one shouldn't comment out something to delete it
- I oppose personal clutter in .gitignore

**Comment by galenwp** [comment]
Well, the `.gitignore` changes are for anyone using Vagrant.  They're not exactly personal.  I'm not exactly sure why `fintud-macrep/` is in there though.

Just delete the other lines then?

**Comment by revprez** [comment]
I'll close this and resubmit, then

**Comment by juped** [comment]
No need. It's tracked by branch name, and I don't care about the tracker anyway.

**Comment by revprez** [comment]
Ah, so it is. 

No matter then, removed the .gitignore stuff and deleted the lines.

**Comment by revprez** [comment]
Just following up. @juped, I removed the commented out lines and did away with my .gitignore changes.

**Comment by juped** [comment]
I saw. (Just waiting for my next trip to a wifi-enabled cafe.)

**Pull request merged**
