### PR TITLE
Jael recursion fix

### PR DESCRIPTION
**Pull request by belisarius222**
Fixes the Jael bug @philipcmonk was talking about in his issue comment here, where the +vent-pass function was missing the recursion: https://github.com/urbit/arvo/issues/1032#issuecomment-506441123

Kale (future Jael) had a similar recursion issue in its equivalent +vent-give arm, which this also fixes.

### CODE REVIEW

**Comment by belisarius222** [comment]
@joemfb Added the pill. PTAL

**Comment by belisarius222** [comment]
Why are people merging their own PRs? I recall being present at a meeting during which @jtobin assumed that responsibility.

@jtobin is the potentate of pull, the czar of the PR, the merge demiurge.

I'll merge the release candidate back in and try again, but the rhymes will continue until this question is resolved.

**Comment by vvisigoth** [comment]
> the merge demiurge

plz stop
—
~poldec-tonteg
http://urbit.org

**Comment by belisarius222** [comment]
Oh, I'll stop, but I want to know who merges PRs around here. The rhymes are only gonna get worse until then. This pill is taking a while, too...

@jtobin is the ace of rebase, the president of the indent, the prefect of the defect. He compiles in style, with code à la mode.

**Comment by belisarius222** [comment]
Merged and pushed the new pill. @joemfb PTAL

**Comment by joemfb** [comment]
In the state of nature, it's every committer for himself.

**Comment by belisarius222** [comment]
Is it ethical to merge before the CI finishes?

@jtobin's purview is review, he's got the authority of the reposit'ry. You've gotta be in the groove to get approved. You've gotta do it right to get on the site. You've gotta ...

come on man, these are getting rough

**Comment by jtobin** [comment]
@belisarius222 doesn't lie,
but my merge skills were awry
whilst in the grips of transit,
thumbs a-twiddling in the sky.

**Comment by jtobin** [comment]
(With reference to the emergent merge free-for-all, pill business, etc., I'll send out an email about all this post 0.8.0 release.)

**Pull request merged**
