### PR TITLE
contributing.md: Added a new section outlining how to develop urbit's frontend

### PR DESCRIPTION
**Pull request by urcades**
We have had a document floating around in gdocs for a while outlining how to actually contribute to urbit's frontend design/dev, but I figured this would actually be really good info to surface up in our Contributing guideline.

I've minified the original doc to somewhat match the tone of this guide, but it could use an editorial pass (and accuracy check) from @jtobin , @loganallenc , @matildepark, @g-a-v-i-n , and @jyng  . Please email Interface for a link to the original document, if you'd like to compare.

Crucial information this should be communicating:
- how to get the frontend dev environment set up, in a *foolproof* manner
- steps that outline in-sequence the steps necessary to edit code, sync to ship, preview changes, and commit to a branch of the project
- how to correctly sync and view the changes made by others (this is the .sh/build-interface step outlined at the end of my edit)

I've gotten tripped up numerous times on basic aspects of doing the above work, and I've had to ask @matildepark for basics on contributing far too often — it's time to get this encoded into the project.

### CODE REVIEW

**Comment by urcades** [comment]
Also, I'm not expecting everyone listed to review this PR, just making sure folks see this, and check it out if interested.

**Comment by matildepark** [comment]
The start of CONTRIBUTING refers people to read pkg/interface/CONTRIBUTING for interface development. These changes should be applied to that file.

**Comment by urcades** [comment]
@matildepark Yeah, I had absolutely no idea that file existed, ha..

Do you feel strongly about nestling the interface contributing doc two directories deep? I checked out the other directories in /pkg and while they all have READMEs, which is a basic affordance, none have CONTRIBUTING.md files to speak of.

I feel quite strongly that we should surface this information at as high a level as possible, and this type of info doesn't seem too alien/weird/unique to omit from the root of the project.

**Comment by urcades** [comment]
All this said, the existing doc is really good and would have saved me some time bothering people about basic dev stuff — would be happy to incorporate it wholesale and fuse the two together somehow, regardless of where the file ends up.

**Comment by matildepark** [comment]
This is a question for the project maintainers — @jtobin, @joemfb et al.

— 
~haddef-sigwen
https://urbit.org

**Comment by loganallenc** [comment]
I prefer interface CONTRIBUTING being either merged or the link between the two being even more boldly presented as well.

**Comment by loganallenc** [comment]
@urcades What's the status on this PR?

**Comment by urcades** [comment]
@loganallenc I made an additional edit today taking the previous feedback into consideration — basically this text has been extracted from the root CONTRIBUTING doc, and moved over to the `pkg/interface` context, and merged into the existing directions. 

A note regarding your earlier question @jtobin , and @loganallenc 's comment, is that I think a nice solution to minifying and generalizing the root document would be to extract the "Kernel development" and "Pill development" sections and accordingly nest them into their appropriate directories, and reference them in a list at the end of the root doc between `# Code style` and `# Issues`, as such:

Screen Shot 2020-04-03 at 3 46 55 PM

**Comment by urcades** [comment]
I decided not to actually edit the root CONTRIBUTING doc due to me having no context as to where each section should be placed. If the actual interface development instructions are solid, I'm happy to merge this in as an update to that doc alone.

**Comment by urcades** [comment]
@jtobin Regarding #2349 , I'm all in favor of massively simplifying our development process, and would edit this doc accordingly, if that change was pushed.

**Comment by loganallenc** [comment]
Ping.

**Pull request merged**
